---
permalink: try/task_use_demonode.html 
sidebar: sidebar 
keywords: element demo node, virtual machine, element software, element api, vmware deployment 
summary: Element Demo Node は、Element ソフトウェアの VMware 仮想マシン バージョンであり、 NetApp HCIおよびSolidFire製品の主要なストレージ機能の多くを簡単にデモンストレーションできます。 
---
= Element Demo Node を使用してストレージ機能を試す
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://mysupport.netapp.com/site/tools/tool-eula/element-demonode/download["要素デモノード"^]は、Element ソフトウェアの VMware 仮想マシン (VM) バージョンであり、 NetApp HCIおよびSolidFire製品の主要なストレージ機能の多くを簡単にデモンストレーションできます。デモ ノードを使用すると、開発者は物理的なハードウェアを必要とせずに Element API に対してコードを記述できます。  VMware の導入を容易にするために、OVA ファイルとしてパッケージ化されています。



== サポートされている機能:

Element Demo Node は、デモンストレーションおよび開発ツールとしてのみ使用することを目的としています。デモノードを使用する前に、次の機能制限に注意してください。

* 要素デモノードはクラスタリングをサポートしていません。単一ノード クラスターとしてのみ機能します。
* 要素のアップグレードはサポートされていません。新しいバージョンの Element をデモするには、新しいデモ ノード VM をインストールする必要があります。
* ストレージのパフォーマンスを示すことを目的としたものではありません。デモ ノードで観測されたパフォーマンスは、決して物理クラスター上のパフォーマンスを示すものではありません。
* NetApp HCIまたはSolidFireクラスターにデモ ノードを追加することはできません。
* VRF VLAN はサポートされていません (標準のタグ付き VLAN はサポートされています)。
* マルチドライブ スライス サービス (MDSS) はサポートされていません。
* 要素デモ ノードは VMFS データストアでのみサポートされます。  VVol はサポートされていません。
* ハードウェアベースの構成および監視機能は、デモ ノードでは動作しません。
* ボリュームごとに最大 10 個のスナップショットをサポートします。
* ノード/クラスターごとに最大 20 個のアカウントをサポートします。
* アカウントごとに最大 100 ボリュームをサポートします。
* アカウントごとに最大 200 個のvVols をサポートします。
* 最大ボリュームサイズ 100 GiB をサポートします。
* 持続的なクラスター制限として 3000 IOPS をサポートします。



NOTE: その他のすべての Element ソフトウェアの制限が適用されます。詳細については、最新の Element ソフトウェア リリース ノートを参照してください。



== VMの要件

* 合計容量 240 GB (VM の仮想ディスクのサイズと数は変更できません。ハイパーバイザー経由で提供される追加のストレージは、ゲスト OS によって無視されます。
* 60 GB ルートディスク
* シック プロビジョニング/Eager Zeroed (30 GB メタデータ ドライブ 1 台または 50 GB ブロック ドライブ 3 台) またはシン プロビジョニング/Eager Zeroed (*推奨*) (30 GB メタデータ ドライブ 1 台または 50 GB ブロック ドライブ 3 台)
* 2 つの vCPU（完全に予約済み）
* 16 GB RAM（完全予約済み）
* すべてのディスクに単一のHBA、LSIロジックパラレル
* 2 つの vNIC、両方とも vmxnet3 (1 つは管理、もう 1 つはストレージ)




== ホストの要件

* Element Demo Node 11.7 VM 用の ESXi 6.0 または 6.5
* Element Demo Node 12.0 および 12.2 VM 用の ESXi 6.5
* Element Demo Node 12.3 および 12.5 VM 用の ESXi 6.7 および 7.0
* マルチコア 64 ビット Intel® アーキテクチャ




== Element Demo Nodeをダウンロード

Element Demo Node ソフトウェアは、.ova ファイルにパッケージ化された VMware ファイルのセットです。



== VMware ESXiにElementデモノードをインストールする

VMware ESXi に Element Demo Node をインストールするには、次のタスクが必要です。

* <<ネットワークインターフェースを構成する>>
* <<ESXiサーバーにデモノードを登録する>>
* <<ESXiサーバー上でデモノードを起動する>>




=== ネットワークインターフェースを構成する

Element デモ ノードには 2 つの個別の仮想マシン ネットワークが必要です。 1 つはストレージ トラフィック用で、もう 1 つは管理トラフィック用です。ジャンボ フレームをサポートするようにストレージ ネットワークを構成する必要があります。



=== ESXiサーバーにデモノードを登録する

Element Demo Node を ESXi サーバーに登録するには、vSphere Client を使用してデモ ノードの .ova ファイルを展開する必要があります。

.手順
. vSphere Client にログインし、インベントリ パネルから ESXi ホストを選択します。
. *ファイル* > *OVF テンプレートのデプロイ* を選択します。
+
OVF テンプレートのデプロイ ウィザードが起動します。

. *テンプレートの選択*ページで、ダウンロードした OVA ファイルを参照し、*開く*を選択します。
. *次へ*を選択します。
. *名前と場所*ページで、デプロイされたテンプレートの名前と場所を指定し、*次へ*を選択します。
. *リソースの選択*ページで、テンプレートを実行する場所を参照し、*次へ*を選択します。
. 詳細を確認し、[次へ] を選択します。
. [ストレージの選択] ページで、仮想マシン ファイルを保存する場所を選択し、[次へ] を選択します。
. *ネットワークの選択*ページで、OVA ファイルで使用されるネットワークをインベントリ内の 2 つの個別の仮想マシン ネットワークにマッピングし、*次へ*を選択します。
. *完了準備完了*ページで、作成する仮想マシンの詳細を確認し、*完了*を選択します。



NOTE: デモ ノードのデプロイメントが完了するまでに数分かかる場合があります。



=== ESXiサーバー上でデモノードを起動する

VMware ESXi コンソールを介して Element にアクセスするには、デモ ノード VM を起動する必要があります。

.手順
. vSphere Client で、作成したデモ ノード VM を選択します。
. この VM の詳細を表示するには、[*概要*] タブを選択します。
. VM を起動するには、[電源オン] を選択します。
. *Web コンソールの起動* を選択します。
. TUI を使用してデモ ノードを構成します。詳細については、 link:../setup/concept_setup_configure_a_storage_node.html["ストレージノードを構成する"^]。




== サポートを受ける方法

Element Demo Node は、ベストエフォートのボランティアによって提供されています。サポートが必要な場合は、 https://community.netapp.com/t5/Simulator-Discussions/bd-p/simulator-discussions["要素デモノードフォーラム"^] 。



== 詳細情報の参照

https://mysupport.netapp.com/site/tools/tool-eula/element-demonode/download["Element Demo Node のダウンロードページ（ログインが必要です）"^]
