---
sidebar: sidebar 
permalink: upgrade/task_hcc_update_management_services.html 
summary: NetApp SolidFireストレージ システムのアップグレードの一環として、管理サービスを更新する必要があります。 
keywords: netapp, solidfire, cluster, management services, hcc, update management services 
---
= 更新管理サービス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
管理ノード 11.3 以降をインストールした後、管理サービスを最新のバンドル バージョンに更新できます。

Element 11.3 管理ノード リリース以降、管理ノードの設計は、個別のサービスを提供する新しいモジュール アーキテクチャに基づいて変更されました。これらのモジュラー サービスは、 SolidFireオールフラッシュ ストレージ システムの集中管理機能と拡張管理機能を提供します。管理サービスには、システム テレメトリ、ログ記録、更新サービス、vCenter Server の Element プラグインの QoSSIOC サービス、 NetApp Hybrid Cloud Control などが含まれます。

.タスク概要
管理サービス 2.27 バンドルには、管理ノード 12.8 とのみ互換性のある vCenter Server 5.5 用の Element プラグインが含まれています。管理サービス 2.27 に更新する場合は、管理ノードと管理サービス間の互換性を確保するために、アップグレード シーケンスを変更し、Element 12.8 にアップグレードした後に管理サービス バンドルを更新する必要があります。

管理サービス 2.21.61 から 2.26.40 に更新する場合は、Element 12.8 にアップグレードする前に、管理サービス バンドルを更新する必要があります。

[NOTE]
====
* 管理サービス 2.22.7 には、vCenter Server 5.0 用の Element プラグインが含まれており、これにはリモートプラグインが含まれています。Element プラグインをご利用の場合は、ローカルプラグインのサポートを削除する VMware の指示に従うため、管理サービス 2.22.7 以降にアップグレードする必要があります。 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere-sdks-tools/8-0/developing-local-plug-ins-client-sdk/about-this-book-local/deprecation-of-local-plug-in-architecture.html["詳細情報"^]。
* 各サービスバンドルの主要なサービス、新機能、バグ修正、回避策を説明した最新の管理サービスリリースノートについては、以下を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理サービスのリリースノート"^]


====
.要件
管理サービス 2.20.69 以降では、 NetApp Hybrid Cloud Control UI または API を使用して管理サービスをアップグレードする前に、エンド ユーザー ライセンス契約 (EULA) に同意して保存する必要があります。

. Web ブラウザで管理ノードの IP アドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
. ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. インターフェースの右上近くにある*アップグレード*を選択します。
. EULA がポップアップ表示されます。下にスクロールして、「*現在および今後のすべての更新に同意します*」を選択し、「*保存*」を選択します。


.更新オプション
NetApp Hybrid Cloud Control UI または管理ノード REST API を使用して管理サービスを更新できます。

* <<ハイブリッドクラウドコントロールを使用した更新管理サービス>>（推奨方法）
* <<管理ノード API を使用して管理サービスを更新する>>




== ハイブリッドクラウドコントロールを使用した更新管理サービス

NetApp Hybrid Cloud Control を使用してNetApp管理サービスを更新できます。

管理サービス バンドルは、メジャー リリース以外でインストールに対して強化された機能と修正を提供します。

.開始する前に
* 管理ノード 11.3 以降を実行しています。
* 管理サービスをバージョン 2.16 以降に更新し、管理ノード 11.3 ～ 11.8 を実行している場合は、管理サービスを更新する前に、管理ノード VM の RAM を増やす必要があります。
+
.. 管理ノード VM の電源をオフにします。
.. 管理ノード VM の RAM を 12 GB から 24 GB RAM に変更します。
.. 管理ノード VM の電源をオンにします。


* クラスタ バージョンでは、 NetApp Elementソフトウェア 11.3 以降が実行されています。
* 管理サービスをバージョン 2.1.326 以上にアップグレードしました。  NetApp Hybrid Cloud Control のアップグレードは、以前のサービス バンドルでは利用できません。



NOTE: 各サービスバンドルバージョンで利用可能なサービスのリストについては、 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理サービスリリースノート"^] 。

.手順
. Web ブラウザで管理ノードの IP アドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
. ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. インターフェースの右上近くにある*アップグレード*を選択します。
. [アップグレード] ページで、[管理サービス] タブを選択します。
. ページの指示に従って、管理サービスのアップグレード パッケージをダウンロードし、コンピューターに保存します。
. *参照*を選択して、保存したパッケージを見つけてアップロードします。
+
パッケージをアップロードすると、アップグレードが自動的に開始されます。

+
アップグレードが開始されると、このページでアップグレードのステータスを確認できます。アップグレード中に、 NetApp Hybrid Cloud Control との接続が失われ、アップグレードの結果を確認するために再度ログインする必要がある場合があります。





== 管理ノード API を使用して管理サービスを更新する

理想的には、ユーザーはNetApp Hybrid Cloud Control から管理サービスの更新を実行する必要があります。ただし、REST API を使用して、管理サービスのサービス バンドル更新を管理ノードに手動でアップロード、抽出、および展開することはできます。管理ノードの REST API UI から各コマンドを実行できます。

.開始する前に
* NetApp Elementソフトウェア管理ノード 11.3 以降を導入しました。
* 管理サービスをバージョン 2.16 以降に更新し、管理ノード 11.3 ～ 11.8 を実行している場合は、管理サービスを更新する前に、管理ノード VM の RAM を増やす必要があります。
+
.. 管理ノード VM の電源をオフにします。
.. 管理ノード VM の RAM を 12 GB から 24 GB RAM に変更します。
.. 管理ノード VM の電源をオンにします。


* クラスタ バージョンでは、 NetApp Elementソフトウェア 11.3 以降が実行されています。
* 管理サービスをバージョン 2.1.326 以上にアップグレードしました。  NetApp Hybrid Cloud Control のアップグレードは、以前のサービス バンドルでは利用できません。
+

NOTE: 各サービスバンドルバージョンで利用可能なサービスのリストについては、 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理サービスリリースノート"^] 。



.手順
. 管理ノードで REST API UI を開きます。 `https://<ManagementNodeIP>/mnode`
. *承認*を選択し、以下を完了します。
+
.. クラスターのユーザー名とパスワードを入力します。
.. クライアントIDを入力してください `mnode-client`値がまだ入力されていない場合。
.. セッションを開始するには、[承認] を選択します。
.. ウィンドウを閉じます。


. 次のコマンドを使用して、管理ノードにサービス バンドルをアップロードして抽出します。 `PUT /services/upload`
. 管理ノードに管理サービスをデプロイします。 `PUT /services/deploy`
. 更新のステータスを監視します。 `GET /services/update/status`
+
更新が成功すると、次の例のような結果が返されます。

+
[listing]
----
{
"current_version": "2.10.29",
"details": "Updated to version 2.17.52",
"status": "success"
}
----


[discrete]
== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

