---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_storage_firmware.html 
summary: NetApp SolidFireシステムのアップグレードの一環として、ストレージ ノードに関連付けられているファームウェアをアップグレードします。 
keywords: netapp, element, hcc, firmware, storage firmware 
---
= ストレージファームウェアのアップグレード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Element 12.0 および管理サービス バージョン 2.14 以降では、 NetApp Hybrid Cloud Control UI と REST API を使用して、ストレージ ノードでファームウェアのみのアップグレードを実行できます。この手順では、Element ソフトウェアはアップグレードされませんが、Element のメジャー リリース以外でストレージ ファームウェアをアップグレードできます。

.要件
* *管理者権限*: アップグレードを実行するためのストレージ クラスター管理者権限があります。
* *システム時間の同期*: すべてのノードのシステム時間が同期され、ストレージ クラスターとノードに対して NTP が正しく構成されていることを確認しました。各ノードは、ノードごとのWeb UIでDNSネームサーバーを設定する必要があります。(`https://[IP address]:442` ) 時間のずれに関連する未解決のクラスター障害はありません。
* *システム ポート*: アップグレードにNetApp Hybrid Cloud Control を使用している場合は、必要なポートが開いていることを確認します。見るlink:../storage/reference_prereq_network_port_requirements.html["ネットワーク ポート"]詳細についてはこちらをご覧ください。
* *管理ノード*: NetApp Hybrid Cloud Control UI および API の場合、環境内の管理ノードはバージョン 11.3 を実行しています。
* *管理サービス*: 管理サービス バンドルを最新バージョンに更新しました。



IMPORTANT: Element ソフトウェア バージョン 12.0 を実行している H610S ストレージ ノードの場合、ストレージ ファームウェア バンドル 2.27 にアップグレードする前に、D パッチ SUST-909 を適用する必要があります。アップグレードする前に、 NetAppサポートに連絡して D パッチを入手してください。見るlink:http://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.27.html["ストレージファームウェアバンドル 2.27 リリースノート"^]。


IMPORTANT: ストレージ ノードのファームウェアをアップグレードする前に、最新の管理サービス バンドルにアップグレードする必要があります。  Element ソフトウェアをバージョン 12.2 以降に更新する場合、続行するには管理サービス 2.14.60 以降が必要です。

* *クラスターのヘルス*: ヘルスチェックを実行しました。見るlink:task_hcc_upgrade_element_prechecks.html["ストレージをアップグレードする前に、Element ストレージのヘルスチェックを実行します。"]。
* *H610S ノードのベースボード管理コントローラー (BMC) が更新されました*: H610S ノードのBMCバージョンがアップグレードされました。見るlink:https://docs.netapp.com/us-en/hci/docs/rn_H610S_BMC_3.84.07.html["リリースノートとアップグレード手順"^]。



NOTE: お使いのハードウェアのファームウェアとドライバファームウェアの完全なマトリックスについては、以下を参照してください。link:../hardware/fw_storage_nodes.html["SolidFireストレージノードでサポートされているストレージファームウェアバージョン"] 。

[[storage-firmware-upgrade]]
* *アップグレード プロセスの時間*: アップグレードを実行するために十分な時間をスケジュールしました。  Element ソフトウェア 12.5 以降にアップグレードする場合、アップグレード プロセスの時間は、現在の Element ソフトウェア バージョンとファームウェアの更新によって異なります。
+
[cols="20,20,20,20,20"]
|===
| ストレージ ノード | 現在のElementソフトウェアバージョン | ノードあたりのソフトウェアおよびファームウェアのインストール時間の概算^1^ | ノードあたりのおおよそのデータ同期時間^2^ | ノードあたりのアップグレード時間の概算 


| 最新のファームウェアを搭載したすべてのSolidFireおよびNetApp H シリーズ ノード^3^ | 12.x | 15分 | 10～15分 | 20～30分 


| H610SとH410S | 12.x および 11.8 | 60分 | 30～60分 | 90～120分 


| H610S | 11.7以前 | 90分 | 40～70分 | 130～160分 また、 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["完全なノードシャットダウンと電源切断を実行する"^]各H610Sノードに対して。 
|===
+
^1^ハードウェアのファームウェアとドライバファームウェアの完全なマトリックスについては、link:../hardware/fw_storage_nodes.html["SolidFireストレージノードでサポートされているストレージファームウェアバージョン"] 。

+
^2^書き込み IOPS 負荷が大きいクラスターとファームウェア更新時間の長いクラスターを組み合わせると、データ同期時間が長くなります。

+
^3^ 次のノードはサポートされていません。これらのノードのいずれかをサポートされていない Element バージョンにアップグレードしようとすると、ノードが Element 12.x でサポートされていないことを示すエラーが表示されます。

+
** Element 12.8、SF4805、SF9605、SF19210、および SF38410 ストレージ ノード以降。
** エレメント 12.7 以降、SF2405 および SF9608 ストレージ ノードと FC0025 および SF-FCN-01 FC ノード。


* *エンド ユーザー ライセンス契約 (EULA)*: 管理サービス 2.20.69 以降では、 NetApp Hybrid Cloud Control UI または API を使用してストレージ ファームウェアをアップグレードする前に、EULA に同意して保存する必要があります。
+
.. Web ブラウザで管理ノードの IP アドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
.. ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
.. インターフェースの右上近くにある*アップグレード*を選択します。
.. EULA がポップアップ表示されます。下にスクロールして、「*現在および今後のすべての更新に同意します*」を選択し、「*保存*」を選択します。




.アップグレードオプション
次のストレージ ファームウェア アップグレード オプションのいずれかを選択します。

* <<NetApp Hybrid Cloud Control UI を使用してストレージ ファームウェアをアップグレードする>>
* <<NetApp Hybrid Cloud Control API を使用してストレージ ファームウェアをアップグレードする>>




== NetApp Hybrid Cloud Control UI を使用してストレージ ファームウェアをアップグレードする

NetApp Hybrid Cloud Control UI を使用して、クラスター内のストレージ ノードのファームウェアをアップグレードできます。

.要件
* 管理ノードがインターネットに接続されていない場合は、 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["ストレージファームウェアバンドルをダウンロードしました"^] 。



CAUTION: NetApp Hybrid Cloud Controlを使用してストレージクラスタをアップグレードする際に発生する可能性のある問題とその回避策については、 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["技術情報"^] 。


TIP: アップグレード プロセスには、ストレージ ノードごとに約 30 分かかります。  Element ストレージ クラスターをバージョン 2.76 より新しいストレージ ファームウェアにアップグレードする場合、新しいファームウェアがノードに書き込まれた場合にのみ、個々のストレージ ノードはアップグレード中に再起動します。

.手順
. Web ブラウザで管理ノードの IP アドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
. ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. インターフェースの右上近くにある*アップグレード*を選択します。
. *アップグレード*ページで、*ストレージ*を選択します。
+
[NOTE]
====
*ストレージ* タブには、インストールに含まれるストレージ クラスターが一覧表示されます。クラスターがNetApp Hybrid Cloud Control からアクセスできない場合は、*アップグレード* ページに表示されません。 Element 12.0 以降を実行しているクラスターがある場合は、これらのクラスターの現在のファームウェア バンドルのバージョンが表示されます。単一クラスター内のノードに異なるファームウェア バージョンがある場合、またはアップグレードが進行中の場合は、[*現在のファームウェア バンドル バージョン*] 列に [*複数*] と表示されます。 *複数* を選択すると、*ノード* ページに移動してファームウェア バージョンを比較できます。すべてのクラスターが 12.0 より前のバージョンの Element を実行している場合、ファームウェア バンドルのバージョン番号に関する情報は表示されません。

クラスターが最新であるか、アップグレード パッケージが利用できない場合は、*要素* タブと *ファームウェアのみ* タブは表示されません。アップグレードの進行中は、これらのタブも表示されません。  *要素* タブは表示されているが、*ファームウェアのみ* タブが表示されていない場合は、使用できるファームウェア パッケージがありません。

====
. アップグレードするクラスターの横にあるドロップダウン矢印を選択します。
. *参照* を選択して、ダウンロードしたアップグレード パッケージをアップロードします。
. アップロードが完了するまでお待ちください。進行状況バーにアップロードのステータスが表示されます。
+

CAUTION: ブラウザ ウィンドウから移動すると、ファイルのアップロードは失われます。

+
ファイルが正常にアップロードされ、検証されると、画面にメッセージが表示されます。検証には数分かかる場合があります。この段階でブラウザ ウィンドウから移動しても、ファイルのアップロードは保持されます。

. *ファームウェアのみ*を選択し、利用可能なアップグレード バージョンから選択します。
. *アップグレードの開始*を選択します。
+

TIP: *アップグレード ステータス* は、アップグレード中にプロセスのステータスを反映して変化します。また、アップグレードを一時停止したり、アップグレードでエラーが返されたりした場合など、実行したアクションに応じても変更されます。見る<<アップグレードステータスの変更>>。

+

NOTE: アップグレードの進行中は、ページを離れて後で戻って、引き続き進行状況を監視できます。クラスター行が折りたたまれている場合、ページのステータスと現在のバージョンは動的に更新されません。テーブルを更新するには、クラスター行を展開するか、ページを更新する必要があります。



アップグレードが完了したら、ログをダウンロードできます。



=== アップグレードステータスの変更

アップグレード プロセスの前、最中、および後に UI の *アップグレード ステータス* 列に表示されるさまざまな状態は次のとおりです。

[cols="2*"]
|===
| アップグレード状態 | 説明 


| 最新 | クラスターは利用可能な最新の Element バージョンにアップグレードされたか、ファームウェアが最新バージョンにアップグレードされました。 


| 検出できません | このステータスは、ストレージ サービス API が、可能なアップグレード ステータスの列挙リストに含まれていないアップグレード ステータスを返した場合に表示されます。 


| 使用可能なバージョンあり | Element および/またはストレージ ファームウェアの新しいバージョンをアップグレードできます。 


| 実行中 | アップグレードが進行中です。進行状況バーにアップグレードのステータスが表示されます。画面上のメッセージには、ノード レベルの障害も表示され、アップグレードの進行中にクラスター内の各ノードのノード ID も表示されます。  Element UI または vCenter Server UI 用のNetApp Elementプラグインを使用して、各ノードのステータスを監視できます。 


| アップグレードを一時停止中 | アップグレードを一時停止することもできます。アップグレード プロセスの状態に応じて、一時停止操作は成功または失敗する可能性があります。一時停止操作の確認を求める UI プロンプトが表示されます。アップグレードを一時停止する前にクラスターが安全な場所にあることを確認するために、アップグレード操作が完全に一時停止されるまでに最大 2 時間かかる場合があります。アップグレードを再開するには、[再開] を選択します。 


| 一時停止 | アップグレードを一時停止しました。プロセスを再開するには、[*再開*] を選択します。 


| エラー | アップグレード中にエラーが発生しました。エラー ログをダウンロードしてNetAppサポートに送信できます。エラーを解決したら、ページに戻って「*再開*」を選択できます。アップグレードを再開すると、システムがヘルスチェックを実行し、アップグレードの現在の状態をチェックする間、進行状況バーは数分間逆戻りします。 
|===


== NetApp Hybrid Cloud Control を使用したアップグレードが失敗した場合はどうなるでしょうか?

アップグレード中にドライブまたはノードに障害が発生した場合、Element UI にクラスター障害が表示されます。アップグレード プロセスは次のノードに進まず、クラスターの障害が解決されるまで待機します。 UI の進行状況バーには、アップグレードがクラスター障害の解決を待機中であることが示されます。この段階では、アップグレードはクラスターが正常になるまで待機するため、UI で *一時停止* を選択しても機能しません。障害の調査を支援するためにNetAppサポートに問い合わせる必要があります。

NetApp Hybrid Cloud Control には 3 時間の待機期間が事前に設定されており、その間に次のいずれかのシナリオが発生する可能性があります。

* クラスターの障害は 3 時間以内に解決され、アップグレードが再開されます。このシナリオでは、何らかのアクションを実行する必要はありません。
* 問題は 3 時間経過しても解決せず、アップグレード ステータスに赤いバナーとともに *エラー* が表示されます。問題が解決したら、[*再開*] を選択してアップグレードを再開できます。
* NetAppサポートは、3 時間の期限が切れる前に修正措置を講じるためにアップグレードを一時的に中止する必要があると判断しました。サポートは API を使用してアップグレードを中止します。



CAUTION: ノードの更新中にクラスターのアップグレードを中止すると、ドライブがノードから不用意に削除される可能性があります。ドライブが不適切に取り外された場合、アップグレード中にドライブを再度追加するには、 NetAppサポートによる手動介入が必要になります。ノードでは、ファームウェアの更新や更新後の同期アクティビティに時間がかかる可能性があります。アップグレードの進行が停止していると思われる場合は、 NetAppサポートにお問い合わせください。



== NetApp Hybrid Cloud Control API を使用してストレージ ファームウェアをアップグレードする

API を使用して、クラスター内のストレージ ノードを最新の Element ソフトウェア バージョンにアップグレードできます。任意の自動化ツールを使用して API を実行できます。ここで説明する API ワークフローでは、管理ノードで使用可能な REST API UI を例として使用します。

.手順
. 管理ノードからアクセス可能なデバイスにストレージファームウェアアップグレードパッケージをダウンロードします。Elementソフトウェアにアクセスしてください。 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["ダウンロードページ"^]最新のストレージ ファームウェア イメージをダウンロードします。
. ストレージ ファームウェア アップグレード パッケージを管理ノードにアップロードします。
+
.. 管理ノードで管理ノード REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. *承認*を選択し、以下を完了します。
+
... クラスターのユーザー名とパスワードを入力します。
... クライアントIDを入力してください `mnode-client`。
... セッションを開始するには、[承認] を選択します。
... 認証ウィンドウを閉じます。


.. REST API UI から、*POST /packages* を選択します。
.. *試してみる*を選択します。
.. *参照*を選択し、アップグレード パッケージを選択します。
.. アップロードを開始するには、[実行] を選択します。
.. レスポンスからパッケージIDをコピーして保存します(`"id"`) を後のステップで使用します。


. アップロードのステータスを確認します。
+
.. REST API UI から、*GET​ /packages​/{id}​/status* を選択します。
.. *試してみる*を選択します。
.. *id* に、前の手順でコピーしたファームウェア パッケージ ID を入力します。
.. ステータス要求を開始するには、[実行] を選択します。
+
回答は `state`として `SUCCESS`完了したら。



. インストール資産 ID を見つけます。
+
.. 管理ノードで管理ノード REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. *承認*を選択し、以下を完了します。
+
... クラスターのユーザー名とパスワードを入力します。
... クライアントIDを入力してください `mnode-client`。
... セッションを開始するには、[承認] を選択します。
... 認証ウィンドウを閉じます。


.. REST API UI から、*GET /installations* を選択します。
.. *試してみる*を選択します。
.. *実行*を選択します。
.. レスポンスからインストールアセットIDをコピーします(`id`）。
+
[listing, subs="+quotes"]
----
*"id": "abcd01e2-xx00-4ccf-11ee-11f111xx9a0b",*
"management": {
  "errors": [],
  "inventory": {
    "authoritativeClusterMvip": "10.111.111.111",
    "bundleVersion": "2.14.19",
    "managementIp": "10.111.111.111",
    "version": "1.4.12"
----
.. REST API UI から、*GET /installations/{id}* を選択します。
.. *試してみる*を選択します。
.. インストール アセット ID を *id* フィールドに貼り付けます。
.. *実行*を選択します。
.. レスポンスからストレージクラスタIDをコピーして保存します(`"id"`後の手順で使用するために、アップグレードする予定のクラスターの .dmg ファイル ( ) を保存します。
+
[listing, subs="+quotes"]
----
"storage": {
  "errors": [],
  "inventory": {
    "clusters": [
      {
        "clusterUuid": "a1bd1111-4f1e-46zz-ab6f-0a1111b1111x",
        *"id": "a1bd1111-4f1e-46zz-ab6f-a1a1a111b012",*
----


. ストレージ ファームウェアのアップグレードを実行します。
+
.. 管理ノードでストレージ REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. *承認*を選択し、以下を完了します。
+
... クラスターのユーザー名とパスワードを入力します。
... クライアントIDを入力してください `mnode-client`。
... セッションを開始するには、[承認] を選択します。
... ウィンドウを閉じます。


.. *POST /upgrades*を選択します。
.. *試してみる*を選択します。
.. パラメータ フィールドにアップグレード パッケージ ID を入力します。
.. パラメータ フィールドにストレージ クラスター ID を入力します。
.. アップグレードを開始するには、[実行] を選択します。
+
応答は次のように状態を示す必要があります `initializing`:

+
[listing, subs="+quotes"]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  *"state": "initializing",*
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. アップグレードIDをコピーする(`"upgradeId"`) は応答の一部です。


. アップグレードの進行状況と結果を確認します。
+
.. *GET ​/upgrades/{upgradeId}* を選択します。
.. *試してみる*を選択します。
.. *upgradeId* に前の手順のアップグレード ID を入力します。
.. *実行*を選択します。
.. アップグレード中に問題や特別な要件が発生した場合は、次のいずれかを実行します。
+
[cols="2*"]
|===
| オプション | 手順 


| クラスタの健全性の問題を修正する必要があるのは、 `failedHealthChecks`レスポンス本文のメッセージ。  a| 
... 各問題について記載されている特定の KB 記事に移動する、または指定された解決策を実行します。
... KB が指定されている場合は、関連する KB 記事に記載されているプロセスを完了します。
... クラスターの問題を解決したら、必要に応じて再認証し、*PUT ​/upgrades/{upgradeId}* を選択します。
... *試してみる*を選択します。
... *upgradeId* に前の手順のアップグレード ID を入力します。
... 入力 `"action":"resume"`リクエスト本文に。
+
[listing]
----
{
  "action": "resume"
}
----
... *実行*を選択します。




| メンテナンス期間が終了するか、またはその他の理由により、アップグレードを一時停止する必要があります。  a| 
... 必要に応じて再認証し、*PUT ​/upgrades/{upgradeId}* を選択します。
... *試してみる*を選択します。
... *upgradeId* に前の手順のアップグレード ID を入力します。
... 入力 `"action":"pause"`リクエスト本文に。
+
[listing]
----
{
  "action": "pause"
}
----
... *実行*を選択します。


|===
.. プロセスが完了するまで、必要に応じて *GET ​/upgrades/{upgradeId}* API を複数回実行します。
+
アップグレード中、 `status`示す `running`エラーが発生しなかった場合。各ノードがアップグレードされるにつれて、 `step`値が変更される `NodeFinished`。

+
アップグレードが正常に完了すると、 `percent`価値は `100`そして `state`示す `finished`。





[discrete]
== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

