---
sidebar: sidebar 
permalink: mnode/task_mnode_install.html 
summary: NetApp Elementソフトウェアを実行しているクラスターの管理ノードをインストールできます。 
keywords: netapp, element, management node, mnode, storage, install 
---
= 管理ノードをインストールする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
構成に適したイメージを使用して、 NetApp Elementソフトウェアを実行しているクラスターの管理ノードを手動でインストールできます。

この手動プロセスは、管理ノードのインストールにNetApp Deployment Engine を使用していないSolidFireオールフラッシュ ストレージ管理者を対象としています。

.開始する前に
* クラスタ バージョンでは、 NetApp Elementソフトウェア 11.3 以降が実行されています。
* インストールでは IPv4 を使用します。管理ノード 11.3 は IPv6 をサポートしていません。
+

NOTE: IPv6 サポートが必要な場合は、管理ノード 11.1 を使用できます。

* NetAppサポート サイトからソフトウェアをダウンロードする権限があります。
* プラットフォームに適した管理ノード イメージ タイプを特定しました。
+
[cols="30,30"]
|===
| プラットフォーム | インストールイメージの種類 


| Microsoft Hyper-V | .iso 


| KVM | .iso 


| VMware vSphere | .iso、.ova 


| Citrix XenServer | .iso 


| OpenStack | .iso 
|===
* (プロキシ サーバーを備えた管理ノード 12.0 以降) プロキシ サーバーを構成する前に、 NetApp Hybrid Cloud Control を管理サービス バージョン 2.16 に更新しておきます。


.タスク概要
Element 12.2 管理ノードはオプションのアップグレードです。既存の展開では必要ありません。

この手順を実行する前に、以下の点を理解しておく必要があります。link:../concepts/concept_solidfire_concepts_volumes.html#persistent-volumes["永続ボリューム"]そして、それらを使用するかどうかを決定します。永続ボリュームはオプションですが、仮想マシン (VM) が失われた場合に管理ノード構成データの回復を行うために推奨されます。



== ステップ1: ISOまたはOVAをダウンロードしてVMを展開する

NetAppサポート サイトから適切な ISO または OVA をダウンロードし、VM をインストールします。

.手順
. インストール用のOVAまたはISOを以下からダウンロードします。link:https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["エレメントソフトウェア"^] NetAppサポート サイトのページ。
+
.. *最新リリースをダウンロード*を選択し、EULA に同意します。
.. ダウンロードする管理ノード イメージを選択します。


. OVA をダウンロードした場合は、次の手順に従ってください。
+
.. OVA をデプロイします。
.. ストレージ クラスターが管理ノード (eth0) とは別のサブネット上にあり、永続ボリュームを使用する場合は、ストレージ サブネット (eth1 など) 上の VM に 2 番目のネットワーク インターフェイス コントローラー (NIC) を追加するか、管理ネットワークがストレージ ネットワークにルーティングできることを確認します。


. ISO をダウンロードした場合は、次の手順に従ってください。
+
.. 次の構成でハイパーバイザーから新しい 64 ビット VM を作成します。
+
*** 6つの仮想CPU
*** 24GBのRAM
*** ストレージアダプタタイプがLSI Logic Parallelに設定されている
+

IMPORTANT: 管理ノードのデフォルトは LSI Logic SAS である可能性があります。 *新しい仮想マシン* ウィンドウで、*ハードウェアのカスタマイズ* > *仮想ハードウェア* を選択して、ストレージ アダプタの構成を確認します。必要に応じて、LSI Logic SAS を *LSI Logic Parallel* に変更します。

*** 400GBの仮想ディスク、シンプロビジョニング
*** インターネット アクセスとストレージ MVIP へのアクセスを備えた 1 つの仮想ネットワーク インターフェイス。
*** (オプション) ストレージ クラスターへの管理ネットワーク アクセスを備えた 1 つの仮想ネットワーク インターフェイス。ストレージ クラスターが管理ノード (eth0) とは別のサブネット上にあり、永続ボリュームを使用する場合は、ストレージ サブネット (eth1) 上の VM に 2 番目のネットワーク インターフェイス コントローラー (NIC) を追加するか、管理ネットワークがストレージ ネットワークにルーティングできることを確認します。
+

IMPORTANT: この手順の後半で VM の電源をオンにするように指示されるステップの前に、VM の電源をオンにしないでください。



.. ISO を VM に接続し、.iso インストール イメージを起動します。
+

NOTE: イメージを使用して管理ノードをインストールすると、スプラッシュ スクリーンが表示されるまでに 30 秒の遅延が発生する可能性があります。



. インストールが完了したら、管理ノードの VM の電源をオンにします。




== ステップ2: 管理ノード管理者を作成し、ネットワークを構成する

VM のインストールが完了したら、管理ノードの管理者ユーザーを作成し、管理ノード ネットワークを構成します。

.手順
. ターミナル ユーザー インターフェイス (TUI) を使用して、管理ノードの管理者ユーザーを作成します。
+

TIP: メニュー オプション間を移動するには、上矢印キーまたは下矢印キーを押します。ボタン間を移動するには、Tab キーを押します。ボタンからフィールドに移動するには、Tab キーを押します。フィールド間を移動するには、上矢印キーまたは下矢印キーを押します。

. ネットワーク上に、最大転送単位 (MTU) が 1500 バイト未満の IP を割り当てる動的ホスト構成プロトコル (DHCP) サーバーが存在する場合は、次の手順を実行する必要があります。
+
.. 管理ノードを、iSCSI などの DHCP のない vSphere ネットワークに一時的に配置します。
.. VM を再起動するか、VM ネットワークを再起動します。
.. TUI を使用して、管理ネットワーク上で 1500 バイト以上の MTU を持つ正しい IP を設定します。
.. 正しい VM ネットワークを VM に再割り当てします。


+

NOTE: 1500 バイト未満の MTU で IP を割り当てる DHCP では、管理ノード ネットワークの構成や管理ノード UI の使用ができなくなる可能性があります。

. 管理ノードネットワーク (eth0) を構成します。
+

NOTE: ストレージ トラフィックを分離するために追加の NIC が必要な場合は、別の NIC を構成する手順を参照してください。link:task_mnode_install_add_storage_NIC.html["ストレージ ネットワーク インターフェイス コントローラ (NIC) を構成する"] 。





== ステップ3: 時刻同期を設定する

管理ノードをセットアップする前に、管理ノードとストレージ クラスター間の時刻を同期します。

.手順
. NTP を使用して管理ノードとストレージ クラスター間で時刻が同期されていることを確認します。



NOTE: 要素12.3.1以降、サブステップ(a)～(e)は自動的に実行されます。管理ノード12.3.1の場合は、<<substep_f_install_config_time_sync,サブステップ（f）>>時刻同期の構成を完了します。

. SSH またはハイパーバイザーが提供するコンソールを使用して管理ノードにログインします。
. NTPDを停止します。
+
[listing]
----
sudo service ntpd stop
----
. NTP設定ファイルを編集する `/etc/ntp.conf`:
+
.. デフォルトサーバーをコメントアウトする(`server 0.gentoo.pool.ntp.org`）を追加することで `#`それぞれの前に。
.. 追加したいデフォルトのタイムサーバーごとに新しい行を追加します。デフォルトのタイムサーバーは、ストレージクラスターで使用するNTPサーバーと同じである必要があります。 <<set-up-the-management-node,後のステップ>>。
+
[listing]
----
vi /etc/ntp.conf

#server 0.gentoo.pool.ntp.org
#server 1.gentoo.pool.ntp.org
#server 2.gentoo.pool.ntp.org
#server 3.gentoo.pool.ntp.org
server <insert the hostname or IP address of the default time server>
----
.. 完了したら設定ファイルを保存します。


. 新しく追加されたサーバーとの NTP 同期を強制します。
+
[listing]
----
sudo ntpd -gq
----
. NTPD を再起動します。
+
[listing]
----
sudo service ntpd start
----
. [[substep_f_install_config_time_sync]]ハイパーバイザー経由でホストとの時刻同期を無効にします (以下は VMware の例です)。
+

NOTE: Openstack 環境の .iso イメージなど、VMware 以外のハイパーバイザー環境に mNode を展開する場合は、同等のコマンドについてはハイパーバイザーのドキュメントを参照してください。

+
.. 定期的な時刻同期を無効にする:
+
[listing]
----
vmware-toolbox-cmd timesync disable
----
.. サービスの現在のステータスを表示して確認します。
+
[listing]
----
vmware-toolbox-cmd timesync status
----
.. vSphereで、 `Synchronize guest time with host` VM オプションのボックスがオフになっています。
+

NOTE: 今後 VM に変更を加える場合は、このオプションを有効にしないでください。






NOTE: 時刻同期の設定が完了したら、NTPを編集しないでください。これは、実行時にNTPに影響します。 <<set-up-the-management-node,セットアップコマンド>> 管理ノード上。



== ステップ4: 管理ノードを設定する

管理ノードを構成するには、 `setup-mnode`指示。

.手順
. 管理ノードのセットアップ コマンドを構成して実行します。
+

NOTE: 安全なプロンプトでパスワードを入力するよう求められます。クラスターがプロキシ サーバーの背後にある場合は、パブリック ネットワークにアクセスできるようにプロキシ設定を構成する必要があります。

+
[listing]
----
sudo /sf/packages/mnode/setup-mnode --mnode_admin_user [username] --storage_mvip [mvip] --storage_username [username] --telemetry_active [true]
----
+
.. 次の必須パラメータごとに、[ ] 括弧内の値（括弧を含む）を置き換えます。
+

NOTE: コマンド名の省略形は括弧 ( ) で囲まれており、完全な名前の代わりに使用できます。

+
*** *--mnode_admin_user (-mu) [username]*: 管理ノード管理者アカウントのユーザー名。これは、管理ノードにログインするために使用したユーザー アカウントのユーザー名である可能性があります。
*** *--storage_mvip (-sm) [MVIP アドレス]*: Element ソフトウェアを実行しているストレージ クラスターの管理仮想 IP アドレス (MVIP)。管理ノードを、インストール時に使用したのと同じストレージクラスターで構成します。 <<configure-time-sync,NTPサーバーの構成>>。
*** *--storage_username (-su) [username]*: 指定されたクラスタのストレージクラスタ管理者のユーザー名。 `--storage_mvip`パラメータ。
*** *--telemetry_active (-t) [true]*: Active IQによる分析用のデータ収集を有効にする値 true を保持します。


.. (オプション): コマンドにActive IQエンドポイント パラメータを追加します。
+
*** *--remote_host (-rh) [AIQ_endpoint]*: Active IQテレメトリ データが処理のために送信されるエンドポイント。パラメータが含まれていない場合は、デフォルトのエンドポイントが使用されます。


.. (推奨): 次の永続ボリューム パラメータを追加します。永続ボリューム機能用に作成されたアカウントおよびボリュームを変更または削除しないでください。そうしないと、管理機能が失われます。
+
*** *--use_persistent_volumes (-pv) [true/false、デフォルト: false]*: 永続ボリュームを有効または無効にします。永続ボリューム機能を有効にするには、値 true を入力します。
*** *--persistent_volumes_account (-pva) [アカウント名]*: `--use_persistent_volumes` true に設定されている場合、このパラメータを使用して、永続ボリュームに使用するストレージ アカウント名を入力します。
+

NOTE: 永続ボリュームには、クラスター上の既存のアカウント名とは異なる一意のアカウント名を使用します。永続ボリュームのアカウントを環境の残りの部分から分離しておくことが非常に重要です。

*** *--persistent_volumes_mvip (-pvm) [mvip]*: 永続ボリュームで使用される、Element ソフトウェアを実行しているストレージ クラスターの管理仮想 IP アドレス (MVIP) を入力します。これは、管理ノードによって複数のストレージ クラスターが管理される場合にのみ必要です。複数のクラスターが管理されていない場合は、デフォルトのクラスター MVIP が使用されます。


.. プロキシ サーバーを構成します。
+
*** *--use_proxy (-up) [true/false、デフォルト: false]*: プロキシの使用を有効または無効にします。プロキシ サーバーを構成するにはこのパラメーターが必要です。
*** *--proxy_hostname_or_ip (-pi) [host]*: プロキシのホスト名または IP。プロキシを使用する場合はこれが必要です。これを指定すると、入力を求められます `--proxy_port`。
*** *--proxy_username (-pu) [username]*: プロキシのユーザー名。このパラメータは省略可能です。
*** *--proxy_password (-pp) [password]*: プロキシパスワード。このパラメータは省略可能です。
*** *--proxy_port (-pq) [ポート、デフォルト: 0]*: プロキシ ポート。これを指定すると、プロキシホスト名またはIPアドレスを入力するように求められます。(`--proxy_hostname_or_ip` ）。
*** *--proxy_ssh_port (-ps) [ポート、デフォルト: 443]*: SSH プロキシ ポート。デフォルトではポート 443 になります。


.. (オプション) 各パラメータに関する追加情報が必要な場合は、パラメータヘルプを使用します。
+
*** *--help (-h)*: 各パラメータに関する情報を返します。パラメータは、初期展開に基づいて必須またはオプションとして定義されます。アップグレードおよび再デプロイメントのパラメータ要件は異なる場合があります。


.. 実行 `setup-mnode`指示。






== ステップ5: コントローラーアセットを構成する

インストール ID を見つけて、vCenter コントローラ アセットを追加します。

.手順
. インストール ID を見つけます。
+
.. ブラウザから管理ノードの REST API UI にログインします。
.. ストレージ MVIP に移動してログインします。このアクションにより、次の手順で証明書が受け入れられます。
.. 管理ノードでインベントリ サービス REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. *承認*を選択し、以下を完了します。
+
... クラスターのユーザー名とパスワードを入力します。
... クライアントIDを入力してください `mnode-client`。
... セッションを開始するには、[承認] を選択します。


.. REST API UI から、*GET ​/installations* を選択します。
.. *試してみる*を選択します。
.. *実行*を選択します。
.. コード200のレスポンス本文から、 `id`後のステップで使用するためにインストールします。
+
インストールには、インストールまたはアップグレード中に作成された基本アセット構成があります。



. NetApp Hybrid Cloud Control の vCenter コントローラ アセットを管理ノードの既知のアセットに追加します。
+
.. 管理ノードのIPアドレスに続けて入力して、管理ノードのmnodeサービスAPI UIにアクセスします。 `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. *承認*または任意のロックアイコンを選択し、次の手順に従います。
+
... クラスターのユーザー名とパスワードを入力します。
... クライアントIDを入力してください `mnode-client`。
... セッションを開始するには、[承認] を選択します。
... ウィンドウを閉じます。


.. コントローラー サブアセットを追加するには、*POST /assets/{asset_id}/controllers* を選択します。
+

NOTE: コントローラ サブアセットを追加するには、vCenter で新しいNetApp HCC ロールを作成する必要があります。この新しいNetApp HCC ロールは、管理ノード サービス ビューをNetAppのみの資産に制限します。見るlink:task_mnode_create_netapp_hcc_role_vcenter.html["vCenterでNetApp HCCロールを作成する"]。

.. *試してみる*を選択します。
.. *asset_id* フィールドに、クリップボードにコピーした親ベースアセット ID を入力します。
.. 必要なペイロード値をタイプで入力してください `vCenter`および vCenter 資格情報。
.. *実行*を選択します。






== 詳細情報はこちら

* link:../concepts/concept_solidfire_concepts_volumes.html#persistent-volumes["永続ボリューム"]
* link:task_mnode_add_assets.html["管理ノードにコントローラアセットを追加する"]
* link:task_mnode_install_add_storage_NIC.html["ストレージNICを構成する"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]

