---
sidebar: sidebar 
permalink: mnode/task_mnode_api_get_authorizationtouse.html 
summary: REST API UI で管理サービス用の API を使用する前に、承認する必要があります。 
keywords: netapp, Element, management node, mnode, api, token 
---
= REST APIを使用するための承認を取得する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST API UI で管理サービス用の API を使用する前に、承認する必要があります。これはアクセス トークンを取得することによって行います。

トークンを取得するには、クラスター管理者の資格情報とクライアント ID を提供します。各トークンの有効期限は約 10 分です。トークンの有効期限が切れた後は、新しいアクセス トークンを再度承認できます。

承認機能は、管理ノードのインストールおよびデプロイメント中に自動的に設定されます。トークン サービスは、セットアップ時に定義したストレージ クラスターに基づいています。

.開始する前に
* クラスター バージョンでは、 NetApp Elementソフトウェア 11.3 以降が実行されている必要があります。
* バージョン 11.3 以降を実行している管理ノードをデプロイしておく必要があります。


.APIコマンド
[listing]
----
TOKEN=`curl -k -X POST https://MVIP/auth/connect/token -F client_id=mnode-client -F grant_type=password -F username=CLUSTER_ADMIN -F password=CLUSTER_PASSWORD|awk -F':' '{print $2}'|awk -F',' '{print $1}'|sed s/\"//g`
----
.REST API UI の手順
. 管理ノードのIPアドレスに続けてサービス名を入力して、サービスのREST API UIにアクセスします。例: `/mnode/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. *承認*を選択します。
+

NOTE: あるいは、任意のサービス API の横にあるロック アイコンを選択することもできます。

. 以下の項目を完了してください。
+
.. クラスターのユーザー名とパスワードを入力します。
.. クライアントIDを入力してください `mnode-client`。
.. クライアント シークレットの値を入力しないでください。
.. セッションを開始するには、[承認] を選択します。


. *利用可能な承認*ダイアログボックスを閉じます。
+

NOTE: トークンの有効期限が切れた後にコマンドを実行しようとすると、 `401 Error: UNAUTHORIZED`メッセージが表示されます。これが表示された場合は、再度承認してください。



[discrete]
== 詳細情報の参照

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]

