---
sidebar: sidebar 
permalink: mnode/task_mnode_run_system_utilities.html 
summary: クラスター サポート バンドルを作成または削除したり、ノード構成設定をリセットしたり、ネットワークを再起動したりすることができます。 
keywords: netapp, Element, management node ui, mnode ui, system utilities 
---
= 管理ノードからシステムユーティリティを実行する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
管理ノードのノードごとの UI を使用して、クラスター サポート バンドルを作成または削除したり、ノード構成設定をリセットしたり、ネットワークを再起動したりすることができます。

.手順
. 管理ノード管理者の資格情報を使用して、ノードごとの管理ノード UI を開きます。
. *システムユーティリティ*を選択します。
. 実行するユーティリティのボタンを選択します。
+
.. *電源制御*: ノードを再起動、電源サイクル、またはシャットダウンします。次のいずれかのオプションを指定します。
+

IMPORTANT: この操作により、ネットワーク接続が一時的に失われます。

+
*** *アクション*: オプションには以下が含まれます `Restart`そして `Halt`（電源オフ）。
*** *ウェイクアップ遅延*: ノードがオンラインに戻るまでの追加時間。


.. *クラスタ サポート バンドルの作成*: クラスタ内の 1 つ以上のノードに対するNetAppサポート診断評価を支援するために、クラスタ サポート バンドルを作成します。次のオプションを指定します。
+
*** *バンドル名*: 作成された各サポート バンドルの一意の名前。名前が指定されていない場合は、「supportbundle」とノード名がファイル名として使用されます。
*** *Mvip*: クラスターの MVIP。バンドルはクラスター内のすべてのノードから収集されます。  Nodes パラメータが指定されていない場合は、このパラメータは必須です。
*** *ノード*: バンドルを収集するノードの IP アドレス。バンドルを収集するノードを指定するには、Nodes または Mvip のいずれかを使用します (両方は使用できません)。  Mvip が指定されていない場合、このパラメータは必須です。
*** *ユーザー名*: クラスター管理者のユーザー名。
*** *パスワード*: クラスター管理者のパスワード。
*** *不完全を許可*: 1 つ以上のノードからバンドルを収集できない場合でも、スクリプトの実行を続行できます。
*** *追加引数*: このパラメータは `sf_make_support_bundle`スクリプト。このパラメータは、NetAppサポートから指示された場合にのみ使用します。


.. *すべてのサポート バンドルを削除*: 管理ノード上の現在のサポート バンドルをすべて削除します。
.. *ノードのリセット*: 管理ノードを新しいインストール イメージにリセットします。これにより、ネットワーク構成を除くすべての設定がデフォルト状態に変更されます。次のオプションを指定します。
+
*** *ビルド*: ノードがリセットされるリモート Element ソフトウェア イメージへの URL。
*** *オプション*: リセット操作を実行するための仕様。詳細が必要な場合は、NetAppサポートにお問い合わせください。
+

IMPORTANT: この操作により、ネットワーク接続が一時的に失われます。



.. *ネットワークの再起動*: 管理ノード上のすべてのネットワーク サービスを再起動します。
+

IMPORTANT: この操作により、ネットワーク接続が一時的に失われます。





[discrete]
== 詳細情報はこちら

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]

