= 
:allow-uri-read: 


.開始する前に
* Active IQの一部の機能 (サービス品質 (QoS) など) が正しく動作するには、Element 11.3 以降が必要です。すべてのActive IQ機能を使用できることを確認するために、 NetApp次のことを推奨します。
+
** ストレージ クラスターはNetApp Elementソフトウェア 11.3 以降を実行しています。
** バージョン 11.3 以降を実行している管理ノードをデプロイしました。


* インターネットにアクセスできます。  Active IQコレクター サービスは、外部接続のないダーク サイトからは使用できません。


.手順
. インストールの基本アセット ID を取得します。
+
.. 管理ノードでインベントリ サービス REST API UI を開きます。
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. *承認*を選択し、以下を完了します。
+
... クラスターのユーザー名とパスワードを入力します。
... クライアントIDを入力してください `mnode-client`。
... セッションを開始するには、[承認] を選択します。
... ウィンドウを閉じます。


.. REST API UI から、*GET ​/installations* を選択します。
.. *試してみる*を選択します。
.. *実行*を選択します。
.. コード200のレスポンス本文から、 `id`インストール用。
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: インストールには、インストールまたはアップグレード中に作成された基本アセット構成があります。



. テレメトリを有効にする:
+
.. 管理ノードのIPアドレスに続けて入力して、管理ノードのmnodeサービスAPI UIにアクセスします。 `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. *承認*または任意のロックアイコンを選択し、次の手順に従います。
+
... クラスターのユーザー名とパスワードを入力します。
... クライアントIDを入力してください `mnode-client`。
... セッションを開始するには、[承認] を選択します。
... ウィンドウを閉じます。


.. 基本アセットを構成します。
+
... *PUT /assets/{asset_id}*を選択します。
... *試してみる*を選択します。
... JSON ペイロードに以下を入力します。
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... *asset_ID* に前の手順のベース ID を入力します。
... *実行*を選択します。
+
資産が変更されるたびに、 Active IQサービスが自動的に再起動されます。アセットを変更すると、設定が適用されるまで少し時間がかかります。






