---
sidebar: sidebar 
permalink: hccstorage/task-hcc-qos-policies.html 
summary: ストレージ クラスター内のボリュームに適用する QoS ポリシーを設定および変更できます。 
keywords: netapp, qos policy, quality of service, qos policies, volumes, element 
---
= ボリュームQoSポリシーの作成と管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
QoS (Quality of Service) ポリシーを使用すると、多くのボリュームに適用できる標準化された QoS 設定を作成して保存できます。  QoS ポリシーを使用するには、選択したクラスターが Element 10.0 以降である必要があります。それ以外の場合、QoS ポリシー機能は使用できません。


NOTE: SolidFireオールフラッシュストレージのコンセプトコンテンツで使用方法の詳細をご覧ください。link:../concepts/concept_data_manage_volumes_solidfire_quality_of_service.html#qos-policies["QoSポリシー"]個々のボリュームの代わりにlink:../concepts/concept_data_manage_volumes_solidfire_quality_of_service.html["QoS"]。

NetApp Hybrid Cloud Control を使用すると、次のタスクを完了して QoS ポリシーを作成および管理できます。

* <<QoSポリシーを作成する>>
* <<ボリュームにQoSポリシーを適用する>>
* <<ボリュームのQoSポリシーの割り当てを変更する>>
* <<QoSポリシーを編集する>>
* <<QoSポリシーを削除する>>




== QoSポリシーを作成する

QoS ポリシーを作成し、同等のパフォーマンスを持つボリュームに適用できます。


NOTE: QoS ポリシーを使用している場合は、ボリューム上でカスタム QoS を使用しないでください。カスタム QoS は、ボリューム QoS 設定の QoS ポリシー値を上書きして調整します。

.手順
. Element ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. ダッシュボードから、ストレージ クラスターのメニューを展開します。
. *ストレージ > ボリューム*を選択します。
. *QoS ポリシー* タブを選択します。
. *ポリシーの作成*を選択します。
. *ポリシー名*を入力します。
+

TIP: 説明的な命名のベストプラクティスを使用します。これは、環境内で複数のクラスタまたは vCenter Server が使用されている場合に特に重要です。

. 最小 IOPS、最大 IOPS、バースト IOPS の値を入力します。
. *QoS ポリシーの作成*を選択します。
+
ポリシーのシステム ID が生成され、割り当てられた QoS 値とともにポリシーが QoS ポリシー ページに表示されます。





== ボリュームにQoSポリシーを適用する

NetApp Hybrid Cloud Control を使用して、既存の QoS ポリシーをボリュームに割り当てることができます。

.要件
割り当てたいQoSポリシーは<<QoSポリシーを作成する,作成済み>>。

.タスク概要
このタスクでは、設定を変更して個々のボリュームに QoS ポリシーを割り当てる方法について説明します。 NetApp Hybrid Cloud Control の最新バージョンには、複数のボリュームを一括割り当てするオプションはありません。将来のリリースで一括割り当て機能が提供されるまでは、Element Web UI または vCenter プラグイン UI を使用して QoS ポリシーを一括割り当てできます。

.手順
. Element ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. ダッシュボードから、ストレージ クラスターのメニューを展開します。
. *ストレージ > ボリューム*を選択します。
. 変更するボリュームの横にある*アクション*メニューを選択します。
. 表示されたメニューで、[*編集*] を選択します。
. ダイアログボックスで、「QoS ポリシーの割り当て」を有効にし、ドロップダウン リストから選択したボリュームに適用する QoS ポリシーを選択します。
+

NOTE: QoS を割り当てると、以前に適用された個々のボリューム QoS 値が上書きされます。

. *保存*を選択します。




== ボリュームのQoSポリシーの割り当てを変更する

ボリュームから QoS ポリシーの割り当てを削除したり、別の QoS ポリシーまたはカスタム QoS を選択したりできます。

.要件
変更したいボリュームは<<ボリュームにQoSポリシーを適用する,割り当てられた>>QoS ポリシー。

.手順
. Element ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. ダッシュボードから、ストレージ クラスターのメニューを展開します。
. *ストレージ > ボリューム*を選択します。
. 変更するボリュームの横にある*アクション*メニューを選択します。
. 表示されたメニューで、[*編集*] を選択します。
. ダイアログ ボックスで、次のいずれかを実行します。
+
** *QoS ポリシーの割り当て* を無効にし、個々のボリューム QoS の *最小 IOPS*、*最大 IOPS*、および *バースト IOPS* の値を変更します。
+

NOTE: QoS ポリシーが無効になっている場合、特に変更しない限り、ボリュームはデフォルトの QoS IOPS 値を使用します。

** 選択したボリュームに適用する別の QoS ポリシーをドロップダウン リストから選択します。


. *保存*を選択します。




== QoSポリシーを編集する

既存の QoS ポリシーの名前を変更したり、ポリシーに関連付けられている値を編集したりできます。  QoS ポリシーのパフォーマンス値を変更すると、ポリシーに関連付けられているすべてのボリュームの QoS に影響します。

.手順
. Element ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. ダッシュボードから、ストレージ クラスターのメニューを展開します。
. *ストレージ > ボリューム*を選択します。
. *QoS ポリシー* タブを選択します。
. 変更する QoS ポリシーの横にある *アクション* メニューを選択します。
. *編集*を選択します。
. *QoS ポリシーの編集* ダイアログ ボックスで、次の 1 つ以上の項目を変更します。
+
** *名前*: QoS ポリシーのユーザー定義名。
** *最小 IOPS*: ボリュームに保証される IOPS の最小数。デフォルト = 50。
** *最大 IOPS*: ボリュームに許可される IOPS の最大数。デフォルト = 15,000。
** *バースト IOPS*: ボリュームに対して短時間に許可される IOPS の最大数。デフォルト = 15,000。


. *保存*を選択します。
+

TIP: ポリシーの「アクティブ ボリューム」列のリンクを選択すると、そのポリシーに割り当てられているボリュームのフィルターされたリストが表示されます。





== QoSポリシーを削除する

不要になった QoS ポリシーは削除できます。 QoS ポリシーを削除すると、そのポリシーが割り当てられたすべてのボリュームでは、以前にポリシーで定義された QoS 値が個々のボリュームの QoS として維持されます。削除された QoS ポリシーとの関連付けはすべて削除されます。

.手順
. Element ストレージ クラスタ管理者の資格情報を入力して、 NetApp Hybrid Cloud Control にログインします。
. ダッシュボードから、ストレージ クラスターのメニューを展開します。
. *ストレージ > ボリューム*を選択します。
. *QoS ポリシー* タブを選択します。
. 変更する QoS ポリシーの横にある *アクション* メニューを選択します。
. *削除*を選択します。
. 操作を確定します。


[discrete]
== 詳細情報の参照

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"^]

