---
permalink: concepts/concept_solidfire_concepts_nodes.html 
sidebar: sidebar 
keywords: what is, node, management node, storage node, fibre channel, state, pending, active 
summary: ノードは、ブロック ストレージまたはコンピューティング リソースとしてアクセスできるようにクラスターにグループ化されたハードウェアです。 
---
= ノード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードは、ブロック ストレージとコンピューティング機能を提供するためにクラスターにグループ化されたハードウェアまたは仮想リソースです。

NetApp Elementソフトウェアは、クラスターのさまざまなノード ロールを定義します。ノード ロールの種類は次のとおりです。

* <<管理ノード>>
* <<ストレージ ノード>>
* <<ファイバーチャネルノード>>


<<ノードの動作状態,ノードの状態>>クラスターの関連付けによって異なります。



== 管理ノード

管理ノードは、監視やテレメトリなどのシステム サービスのアップグレードと提供、クラスタ アセットと設定の管理、システム テストとユーティリティの実行、トラブルシューティングのためのNetAppサポート アクセスの有効化などに使用される仮想マシンです。link:../concepts/concept_intro_management_node.html["詳細情報"]



== ストレージ ノード

SolidFireストレージ ノードは、Bond10G ネットワーク インターフェイスを介して相互に通信するドライブのコレクションを含むサーバーです。ノード内のドライブには、データの保存とデータ管理のためのブロックとメタデータのスペースが含まれています。各ノードには、 NetApp Elementソフトウェアの工場出荷時のイメージが含まれています。

ストレージ ノードには次の特性があります。

* 各ノードには一意の名前があります。管理者がノード名を指定しない場合は、デフォルトで SF-XXXX に設定されます。ここで、XXXX はシステムによって生成される 4 つのランダムな文字です。
* 各ノードには独自の高性能な不揮発性ランダム アクセス メモリ (NVRAM) 書き込みキャッシュがあり、システム全体のパフォーマンスを向上させ、書き込みの待ち時間を短縮します。
* 各ノードは、ストレージと管理の 2 つのネットワークに接続され、それぞれ冗長性とパフォーマンスのために 2 つの独立したリンクを備えています。各ノードには、各ネットワーク上の IP アドレスが必要です。
* 新しいストレージ ノードを使用してクラスターを作成したり、既存のクラスターにストレージ ノードを追加してストレージ容量とパフォーマンスを向上させることができます。
* サービスを中断することなく、いつでもクラスターにノードを追加したり削除したりできます。




== ファイバーチャネルノード

SolidFireファイバー チャネル ノードはファイバー チャネル スイッチへの接続を提供し、ファイバー チャネル クライアントに接続できます。ファイバー チャネル ノードは、ファイバー チャネル プロトコルと iSCSI プロトコル間のプロトコル コンバータとして機能します。これにより、新規または既存のSolidFireクラスターにファイバー チャネル接続を追加できます。

ファイバー チャネル ノードには次の特性があります。

* ファイバー チャネル スイッチはファブリックの状態を管理し、最適化された相互接続を提供します。
* 2 つのポート間のトラフィックはスイッチのみを通過し、他のポートには送信されません。
* ポートの障害は分離されており、他のポートの動作に影響を与えません。
* ファブリック内で複数のポートのペアが同時に通信できます。




== ノードの動作状態

ノードは、構成のレベルに応じて、いくつかの状態のいずれかになります。

* *利用可能*
+
ノードには関連付けられたクラスター名がなく、まだクラスターの一部ではありません。

* *保留中*
+
ノードが設定され、指定されたクラスターに追加できます。

+
ノードにアクセスするために認証は必要ありません。

* *アクティブ保留中*
+
システムは、ノードに互換性のある Element ソフトウェアをインストール中です。完了すると、ノードはアクティブ状態に移行します。

* *アクティブ*
+
ノードはクラスターに参加しています。

+
ノードを変更するには認証が必要です。



これらの各状態では、一部のフィールドは読み取り専用になります。



== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

