---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: クラスターはSolidFireストレージ システムのハブであり、ノードの集合で構成されます。 SolidFire のストレージ効率を実現するには、クラスター内に少なくとも 4 つのノードが必要です。クラスターは単一の論理グループとしてネットワーク上に表示され、ブロック ストレージとしてアクセスできるようになります。 
---
= クラスタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスターはSolidFireストレージ システムのハブであり、ノードの集合で構成されます。 SolidFire のストレージ効率を実現するには、クラスター内に少なくとも 4 つのノードが必要です。クラスターは単一の論理グループとしてネットワーク上に表示され、ブロック ストレージとしてアクセスできるようになります。

新しいクラスターを作成すると、ノードがクラスターの通信所有者として初期化され、クラスター内の各ノードのネットワーク通信が確立されます。このプロセスは、新しいクラスターごとに 1 回だけ実行されます。  Element UI または API を使用してクラスターを作成できます。

追加のノードを追加することでクラスターをスケールアウトできます。新しいノードを追加しても、サービスは中断されず、クラスターは新しいノードのパフォーマンスと容量を自動的に使用します。

管理者とホストは仮想 IP アドレスを使用してクラスターにアクセスできます。クラスター内の任意のノードが仮想 IP アドレスをホストできます。管理仮想 IP (MVIP) は 1GbE 接続を介してクラスター管理を可能にし、ストレージ仮想 IP (SVIP) は 10GbE 接続を介してストレージへのホスト アクセスを可能にします。これらの仮想 IP アドレスにより、 SolidFireクラスターのサイズや構成に関係なく、一貫した接続が可能になります。仮想 IP アドレスをホストしているノードに障害が発生した場合、クラスター内の別のノードが仮想 IP アドレスのホスティングを開始します。


NOTE: Element バージョン 11.0 以降では、管理ネットワークのノードに IPv4、IPv6、またはその両方のアドレスを構成できます。これは、IPv6 をサポートしない管理ノード 11.3 以降を除き、ストレージ ノードと管理ノードの両方に適用されます。クラスターを作成する場合、MVIP には単一の IPv4 または IPv6 アドレスのみを使用でき、対応するアドレス タイプをすべてのノードで構成する必要があります。

.クラスターの詳細
* <<権威あるストレージクラスター>>
* <<三分割法>>
* <<取り残された容量>>
* <<ストレージ効率>>
* <<ストレージクラスタークォーラム>>




== 権威あるストレージクラスター

権限のあるストレージ クラスターは、 NetApp Hybrid Cloud Control がユーザーを認証するために使用するストレージ クラスターです。

管理ノードにストレージ クラスターが 1 つしかない場合は、それが権限のあるクラスターになります。管理ノードに 2 つ以上のストレージ クラスタがある場合、それらのクラスタの 1 つが権限のあるクラスタとして割り当てられ、そのクラスタのユーザーのみがNetApp Hybrid Cloud Control にログインできるようになります。どのクラスターが権威あるクラスターであるかを調べるには、 `GET /mnode/about` API。応答では、 `token_url`フィールドは、権限のあるストレージ クラスターの管理仮想 IP アドレス (MVIP) です。権限のあるクラスタにいないユーザーとしてNetApp Hybrid Cloud Control にログインしようとすると、ログイン試行は失敗します。

NetApp Hybrid Cloud Control の多くの機能は複数のストレージ クラスターで動作するように設計されていますが、認証と承認には制限があります。認証と承認に関する制限は、権限のあるクラスターのユーザーは、他のストレージ クラスターのユーザーでなくても、 NetApp Hybrid Cloud Control に関連付けられた他のクラスターでアクションを実行できることです。

複数のストレージ クラスターの管理に進む前に、権限のあるクラスターで定義されているユーザーが、他のすべてのストレージ クラスターでも同じ権限で定義されていることを確認する必要があります。ユーザーの管理は、link:../storage/concept_system_manage_manage_cluster_administrator_users.html["Elementソフトウェアのユーザーインターフェース"] 。

見るlink:../mnode/task_mnode_manage_storage_cluster_assets.html["ストレージクラスター資産の作成と管理"]管理ノード ストレージ クラスター アセットの操作の詳細については、こちらをご覧ください。



== 三分割法

NetApp SolidFireストレージ クラスター内でストレージ ノード タイプを混在させる場合、単一のストレージ ノードにストレージ クラスターの合計容量の 33% を超える容量を含めることはできません。



== 取り残された容量

新しく追加されたノードがクラスターの総容量の 50% 以上を占める場合、このノードの容量の一部は使用不可 (「取り残される」) になり、容量ルールに準拠します。ストレージ容量が追加されるまで、この状況は続きます。容量ルールにも従わない非常に大きなノードが追加された場合、以前に取り残されていたノードは取り残されなくなりますが、新しく追加されたノードは取り残されます。このような事態を回避するには、容量を常にペアで追加する必要があります。ノードが孤立すると、適切なクラスター障害がスローされます。



== ストレージ効率

Netapp SolidFireストレージ クラスターは、重複排除、圧縮、シン プロビジョニングを利用して、ボリュームの保存に必要な物理ストレージの量を削減します。

* *圧縮*
+
圧縮では、データ ブロックを圧縮グループにまとめ、各ブロックを 1 つのブロックとして保存することで、ボリュームに必要な物理ストレージの量を削減します。

* *重複排除*
+
重複排除は、重複したデータ ブロックを破棄することで、ボリュームに必要な物理ストレージの量を削減します。

* *シンプロビジョニング*
+
シンプロビジョニングされたボリュームまたは LUN は、ストレージが事前に予約されていないボリュームまたは LUN です。代わりに、ストレージは必要に応じて動的に割り当てられます。ボリュームまたはLUN内のデータが削除されると、空き領域がストレージシステムに解放されます。





== ストレージクラスタークォーラム

Element ソフトウェアは、選択されたノードからストレージ クラスターを作成し、クラスター構成の複製されたデータベースを維持します。クラスターの回復力を確保するためにクォーラムを維持するには、少なくとも 3 つのノードがクラスター アンサンブルに参加する必要があります。
