---
permalink: concepts/concept_solidfire_concepts_data_protection.html 
sidebar: sidebar 
keywords: what is, element, solidfire, replication, clone, snapshot, protection domain, double helix 
summary: データ保護機能には、リモート レプリケーション、ボリューム スナップショット、ボリューム クローン、保護ドメイン、Double Helix テクノロジによる高可用性が含まれます。 
---
= データ保護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護機能には、リモート レプリケーション、ボリューム スナップショット、ボリューム クローン、保護ドメイン、Double Helix テクノロジによる高可用性が含まれます。

要素ストレージのデータ保護には、次の概念が含まれます。

* <<リモートレプリケーションの種類>>
* <<データ保護のためのボリュームスナップショット>>
* <<ボリューム クローン>>
* <<Elementストレージのバックアップと復元プロセスの概要>>
* <<保護ドメイン>>
* <<custom_pd,カスタム保護ドメイン>>
* <<Double Helixの高可用性>>




== リモートレプリケーションの種類

データのリモート レプリケーションには次の形式があります。

* <<クラスター間の同期および非同期レプリケーション>>
* <<スナップショットのみのレプリケーション>>
* <<SnapMirrorを使用したElementとONTAPクラスタ間のレプリケーション>>


詳細については、 https://www.netapp.com/pdf.html?item=/media/10607-tr4741pdf.pdf["TR-4741: NetApp Elementソフトウェア リモート レプリケーション"^] 。



=== クラスター間の同期および非同期レプリケーション

NetApp Elementソフトウェアを実行しているクラスターでは、リアルタイム レプリケーションにより、ボリューム データのリモート コピーをすばやく作成できます。

ストレージ クラスターを最大 4 つの他のストレージ クラスターとペアリングできます。フェイルオーバーおよびフェイルバックのシナリオでは、クラスター ペアのいずれかのクラスターからボリューム データを同期的または非同期的に複製できます。



==== 同期レプリケーション

同期レプリケーションは、ソース クラスターからターゲット クラスターにデータを継続的に複製し、遅延、パケット損失、ジッター、帯域幅の影響を受けます。

同期レプリケーションは次のような状況に適しています。

* 短距離での複数システムの複製
* 発生源から地理的に近い災害復旧サイト
* 時間依存のアプリケーションとデータベースの保護
* プライマリサイトがダウンしたときにセカンダリサイトがプライマリサイトとして機能することを必要とするビジネス継続性アプリケーション




==== 非同期レプリケーション

非同期レプリケーションは、ターゲット クラスターからの確認応答を待たずに、ソース クラスターからターゲット クラスターにデータを継続的に複製します。非同期レプリケーション中、書き込みはソース クラスターでコミットされた後にクライアント (アプリケーション) に確認応答されます。

非同期レプリケーションは次のような状況に適しています。

* 災害復旧サイトはソースから遠く離れており、アプリケーションはネットワークによって発生する遅延を許容しません。
* ソース クラスターとターゲット クラスターを接続するネットワークには帯域幅の制限があります。




=== スナップショットのみのレプリケーション

スナップショットのみのデータ保護では、特定の時点で変更されたデータをリモート クラスターに複製します。ソース クラスターで作成されたスナップショットのみが複製されます。ソースボリュームからのアクティブな書き込みは行われません。

スナップショットのレプリケーションの頻度を設定できます。

スナップショット レプリケーションは、非同期レプリケーションまたは同期レプリケーションには影響しません。



=== SnapMirrorを使用したElementとONTAPクラスタ間のレプリケーション

NetApp SnapMirrorテクノロジーを使用すると、災害復旧の目的で、 NetApp Elementソフトウェアを使用して作成されたスナップショットをONTAPに複製できます。  SnapMirror関係では、Element が一方のエンドポイントであり、 ONTAP がもう一方のエンドポイントです。

SnapMirrorは、災害復旧を容易にするNetAppスナップショット レプリケーション テクノロジであり、地理的に離れたサイトのプライマリ ストレージからセカンダリ ストレージへのフェイルオーバー用に設計されています。SnapMirrorテクノロジは本番データの複製（ミラー）をセカンダリ ストレージに作成し、プライマリ サイトで災害が発生した場合に、セカンダリ ストレージから引き続きデータを提供できるようにします。データのミラーリングはボリューム単位で行われます。

プライマリ ストレージのソース ボリュームとセカンダリ ストレージの宛先ボリューム間の関係は、データ保護関係と呼ばれます。クラスターはボリュームが存在するエンドポイントと呼ばれ、複製されたデータを含むボリュームはピアリングされる必要があります。ピア関係にあることで、クラスタとボリュームの間でデータをセキュアにやり取りできます。

SnapMirror はNetApp ONTAPコントローラ上でネイティブに実行され、 NetApp HCIおよびSolidFireクラスタ上で実行される Element に統合されています。 SnapMirror を制御するロジックはONTAPソフトウェア内に存在するため、すべてのSnapMirror関係には、調整作業を実行するために少なくとも 1 つのONTAPシステムが関与する必要があります。ユーザーは主に Element UI を通じて Element とONTAPクラスタ間の関係を管理しますが、一部の管理タスクはNetApp ONTAP System Manager に存在します。ユーザーは、 ONTAPと Element で利用可能な CLI と API を通じてSnapMirror を管理することもできます。

見る https://fieldportal.netapp.com/content/616239["TR-4651: NetApp SolidFire SnapMirror のアーキテクチャと構成"^]（ログインが必要です）

Element ソフトウェアを使用して、クラスタ レベルでSnapMirror機能を手動で有効にする必要があります。  SnapMirror機能はデフォルトで無効になっており、新規インストールまたはアップグレードの一部として自動的に有効になることはありません。

SnapMirror を有効にすると、Element ソフトウェアの [データ保護] タブからSnapMirror関係を作成できます。

NetApp Elementソフトウェア 10.1 以降は、 ONTAPシステムでスナップショットをコピーおよび復元するためのSnapMirror機能をサポートしています。

Element 10.1 以降を実行しているシステムには、9.3 以降を実行しているONTAPシステム上のSnapMirrorと直接通信できるコードが含まれています。 Element API は、クラスター、ボリューム、スナップショットでSnapMirror機能を有効にするメソッドを提供します。さらに、Element UI には、Element ソフトウェアとONTAPシステム間のSnapMirror関係を管理する機能も含まれています。

Element 10.3 およびONTAP 9.4 システム以降では、機能が制限された特定のユースケースで、 ONTAP で生成されたボリュームを Element ボリュームに複製できます。

詳細については、 link:../storage/element-replication-index.html["NetApp ElementソフトウェアとONTAP間のレプリケーション (ONTAP CLI)"]。



== データ保護のためのボリュームスナップショット

ボリューム スナップショットは、ボリュームの特定の時点のコピーであり、後でボリュームをその特定の時点に復元するために使用できます。

スナップショットはボリューム クローンと似ていますが、スナップショットは単にボリューム メタデータのレプリカであるため、マウントしたり書き込んだりすることはできません。ボリューム スナップショットの作成には少量のシステム リソースとスペースしか必要ないため、クローン作成よりもスナップショットの作成が高速になります。

スナップショットをリモート クラスターに複製し、ボリュームのバックアップ コピーとして使用できます。これにより、複製されたスナップショットを使用してボリュームを特定の時点にロールバックできるようになります。また、複製されたスナップショットからボリュームのクローンを作成することもできます。

Element クラスターのスナップショットを外部オブジェクト ストアまたは別の Element クラスターにバックアップできます。スナップショットを外部オブジェクト ストアにバックアップする場合は、読み取り/書き込み操作を許可するオブジェクト ストアへの接続が必要です。

データ保護のために、個々のボリュームまたは複数のボリュームのスナップショットを作成できます。



== ボリューム クローン

単一ボリュームまたは複数ボリュームのクローンとは、データの特定時点のコピーです。ボリュームのクローンを作成すると、システムはボリュームのスナップショットを作成し、スナップショットによって参照されるデータのコピーを作成します。

これは非同期プロセスであり、プロセスに必要な時間は、複製するボリュームのサイズと現在のクラスターの負荷によって異なります。

クラスターは、ボリュームごとに一度に最大 2 つの実行中のクローン要求と、一度に最大 8 つのアクティブなボリューム クローン操作をサポートします。これらの制限を超えるリクエストは、後で処理するためにキューに入れられます。



== Elementストレージのバックアップと復元プロセスの概要

ボリュームを他のSolidFireストレージや、Amazon S3 または OpenStack Swift と互換性のあるセカンダリ オブジェクト ストアにバックアップおよび復元できます。

ボリュームを次の場所にバックアップできます。

* SolidFireストレージクラスター
* Amazon S3 オブジェクトストア
* OpenStack Swift オブジェクトストア


OpenStack Swift または Amazon S3 からボリュームを復元する場合は、元のバックアップ プロセスのマニフェスト情報が必要です。  SolidFireストレージ システムにバックアップされたボリュームを復元する場合、マニフェスト情報は必要ありません。



== 保護ドメイン

保護ドメインとは、データの可用性を維持しながら、その一部または全部に障害が発生しても問題がないようにグループ化されたノードまたはノード セットです。保護ドメインにより、ストレージ クラスターはシャーシ (シャーシ アフィニティ) またはドメイン全体 (シャーシのグループ) の損失から自動的に修復できるようになります。

vCenter Server 用のNetApp ElementプラグインのNetApp Element構成拡張ポイントを使用して、保護ドメインの監視を手動で有効にすることができます。ノードまたはシャーシ ドメインに基づいて保護ドメインしきい値を選択できます。  Element API または Web UI を使用して保護ドメインの監視を有効にすることもできます。

保護ドメイン レイアウトでは、各ノードを特定の保護ドメインに割り当てます。

保護ドメイン レベルと呼ばれる 2 つの異なる保護ドメイン レイアウトがサポートされています。

* ノード レベルでは、各ノードは独自の保護ドメインに属します。
* シャーシ レベルでは、シャーシを共有するノードのみが同じ保護ドメインに存在します。
+
** ノードがクラスターに追加されると、シャーシ レベルのレイアウトはハードウェアから自動的に決定されます。
** 各ノードが別々のシャーシ内にあるクラスターでは、これら 2 つのレベルは機能的に同一です。




新しいクラスターを作成するときに、共有シャーシ内にあるストレージ ノードを使用している場合は、保護ドメイン機能を使用してシャーシ レベルの障害保護を設計することを検討してください。



== [[custom_pd]]カスタム保護ドメイン

特定のシャーシとノードのレイアウトに一致するカスタム保護ドメイン レイアウトを定義し、各ノードを 1 つのカスタム保護ドメインにのみ関連付けることができます。デフォルトでは、各ノードは同じデフォルトのカスタム保護ドメインに割り当てられます。

カスタム保護ドメインが割り当てられていない場合:

* クラスタの動作には影響ありません。
* カスタム レベルは、寛容性も回復力もありません。


クラスターのカスタム保護ドメインを構成する場合、Element Web UI ダッシュボードから確認できる 3 つの保護レベルがあります。

* 保護されていません: ストレージ クラスターは、カスタム保護ドメインの 1 つで発生した障害から保護されていません。これを修正するには、クラスターにストレージ容量を追加するか、クラスターのカスタム保護ドメインを再構成して、クラスターをデータ損失から保護します。
* フォールト トレラント: ストレージ クラスターには、カスタム保護ドメインの 1 つに障害が発生してもデータの損失を防ぐのに十分な空き容量があります。
* 障害耐性: ストレージ クラスターには、カスタム保護ドメインの 1 つに障害が発生した後でも自己修復できる十分な空き容量があります。修復プロセスが完了すると、追加のドメインに障害が発生した場合でも、クラスターはデータ損失から保護されます。


複数のカスタム保護ドメインが割り当てられている場合、各サブシステムは重複したドメインを個別のカスタム保護ドメインに割り当てます。これが不可能な場合は、重複を別々のノードに割り当てることになります。各サブシステム (ビン、スライス、プロトコル エンドポイント プロバイダー、アンサンブルなど) はこれを独立して実行します。

Element UIを使用すると、link:../storage/task_data_protection_configure_custom_protection_domains.html["カスタム保護ドメインを構成する"]または、次の API メソッドを使用することもできます。

* link:../api/reference_element_api_getprotectiondomainlayout.html["保護ドメインレイアウトの取得"]- 各ノードがどのシャーシとどのカスタム保護ドメインに属しているかを表示します。
* link:../api/reference_element_api_setprotectiondomainlayout.html["保護ドメインレイアウトの設定"]- 各ノードにカスタム保護ドメインを割り当てることができます。




== Double Helixの高可用性

Double Helix データ保護は、システム内のすべてのドライブに少なくとも 2 つの冗長データ コピーを分散するレプリケーション方法です。  「RAID レス」アプローチにより、システムはストレージ システムのすべてのレベルにわたって複数の同時障害を吸収し、迅速に修復できるようになります。
