---
permalink: concepts/concept_solidfire_concepts_accounts_and_permissions.html 
sidebar: sidebar 
keywords: solidfire, element, cluster admin, storage, account, authoritative cluster 
summary: システム上のストレージ リソースを管理し、アクセスを提供するには、システム リソースのアカウントを設定する必要があります。 
---
= アカウントと権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システム上のストレージ リソースを管理し、アクセスを提供するには、システム リソースのアカウントを設定する必要があります。

Element ストレージを使用すると、次の種類のアカウントを作成および管理できます。

* <<ストレージ クラスター管理者アカウント,ストレージクラスターの管理者ユーザーアカウント>>
* <<ユーザ アカウント,ストレージボリュームアクセス用のユーザーアカウント>>
* <<権限のあるクラスターユーザーアカウント,NetApp Hybrid Cloud Control の権限のあるクラスタ ユーザー アカウント>>




== ストレージ クラスター管理者アカウント

NetApp Elementソフトウェアを実行しているストレージ クラスターには、次の 2 種類の管理者アカウントが存在できます。

* *プライマリ クラスター管理者アカウント*: この管理者アカウントは、クラスターの作成時に作成されます。このアカウントは、クラスターへの最高レベルのアクセス権を持つプライマリ管理アカウントです。このアカウントは、Linux システムの root ユーザーに類似しています。この管理者アカウントのパスワードを変更できます。
* *クラスター管理者アカウント*: クラスター管理者アカウントに、クラスター内で特定のタスクを実行するための限定された範囲の管理アクセス権を付与できます。各クラスター管理者アカウントに割り当てられた資格情報は、ストレージ システム内の API および Element UI 要求を認証するために使用されます。



NOTE: ノードごとの UI を介してクラスター内のアクティブなノードにアクセスするには、ローカル (LDAP 以外の) クラスター管理者アカウントが必要です。まだクラスターの一部ではないノードにアクセスするには、アカウント資格情報は必要ありません。

あなたはできるlink:../storage/concept_system_manage_manage_cluster_administrator_users.html["クラスタ管理者アカウントを管理する"]クラスタ管理者アカウントを作成、削除、編集し、クラスタ管理者パスワードを変更し、LDAP 設定を構成してユーザーのシステム アクセスを管理します。



== ユーザ アカウント

ユーザー アカウントは、 NetApp Elementソフトウェア ベース ネットワーク上のストレージ リソースへのアクセスを制御するために使用されます。ボリュームを作成するには、少なくとも 1 つのユーザー アカウントが必要です。

ボリュームを作成すると、アカウントに割り当てられます。仮想ボリュームを作成した場合、アカウントはストレージ コンテナーになります。

追加の考慮事項を次に示します。

* アカウントには、割り当てられたボリュームにアクセスするために必要な CHAP 認証が含まれています。
* 1 つのアカウントには最大 2000 個のボリュームを割り当てることができますが、1 つのボリュームは 1 つのアカウントにのみ属することができます。
* ユーザー アカウントは、 NetApp Element Management 拡張ポイントから管理できます。




== 権限のあるクラスターユーザーアカウント

権限のあるクラスタ ユーザー アカウントは、ノードおよびクラスタのNetApp Hybrid Cloud Control インスタンスに関連付けられた任意のストレージ アセットに対して認証できます。このアカウントを使用すると、すべてのクラスターにわたってボリューム、アカウント、アクセス グループなどを管理できます。

権限のあるユーザー アカウントは、 NetApp Hybrid Cloud Control の右上メニューの [ユーザー管理] オプションから管理されます。

そのlink:../concepts/concept_intro_clusters.html#authoritative-storage-clusters["権威ストレージクラスター"]NetApp Hybrid Cloud Control がユーザーを認証するために使用するストレージ クラスターです。

権限のあるストレージ クラスター上に作成されたすべてのユーザーは、 NetApp Hybrid Cloud Control にログインできます。他のストレージ クラスターで作成されたユーザーは、Hybrid Cloud Control にログインできません。

* 管理ノードにストレージ クラスターが 1 つしかない場合は、それが権限のあるクラスターになります。
* 管理ノードに 2 つ以上のストレージ クラスタがある場合、それらのクラスタの 1 つが権限のあるクラスタとして割り当てられ、そのクラスタのユーザーのみがNetApp Hybrid Cloud Control にログインできるようになります。


多くのNetApp Hybrid Cloud Control 機能は複数のストレージ クラスターで動作しますが、認証と承認には必要な制限があります。認証と承認に関する制限は、権限のあるクラスターのユーザーは、他のストレージ クラスターのユーザーでなくても、 NetApp Hybrid Cloud Control に関連付けられた他のクラスターでアクションを実行できることです。複数のストレージ クラスターの管理に進む前に、権限のあるクラスターで定義されているユーザーが、他のすべてのストレージ クラスターでも同じ権限で定義されていることを確認する必要があります。  NetApp Hybrid Cloud Control からユーザーを管理できます。



== ボリュームアカウント

ボリューム固有のアカウントは、作成されたストレージ クラスターにのみ固有です。これらのアカウントを使用すると、ネットワーク全体の特定のボリュームに対する権限を設定できますが、それらのボリューム外部には影響がありません。

ボリューム アカウントは、 NetApp Hybrid Cloud Control Volumes テーブル内で管理されます。
