---
permalink: concepts/concept_solidfire_concepts_volumes.html 
sidebar: sidebar 
keywords: what is, element, volume, storage volume, persistent volume 
summary: NetApp SolidFireストレージ システムは、ボリュームを使用してストレージをプロビジョニングします。ボリュームは、iSCSI またはファイバー チャネル クライアントによってネットワーク経由でアクセスされるブロック デバイスです。 
---
= ボリューム
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Elementストレージ システムは、ボリュームを使用してストレージをプロビジョニングします。ボリュームは、iSCSI またはファイバー チャネル クライアントによってネットワーク経由でアクセスされるブロック デバイスです。

エレメント ストレージを使用すると、ユーザー アカウントのボリュームを作成、表示、編集、削除、複製、バックアップ、または復元できます。クラスター上の各ボリュームを管理したり、ボリューム アクセス グループ内のボリュームを追加または削除したりすることもできます。



== 永続ボリューム

永続ボリュームを使用すると、管理ノードの構成データを VM のローカルではなく、指定されたストレージ クラスターに保存できるため、管理ノードが失われたり削除されたりした場合でもデータを保持できます。永続ボリュームはオプションですが、推奨される管理ノード構成です。

永続ボリュームを有効にするオプションは、インストールおよびアップグレードスクリプトに含まれています。link:../mnode/task_mnode_install.html["新しい管理ノードを展開する"] 。永続ボリュームは、VM の寿命を超えて存続するホスト管理ノード VM の管理ノード構成情報を含む、Element ソフトウェアベースのストレージ クラスター上のボリュームです。管理ノードが失われた場合、代替の管理ノード VM が失われた VM に再接続し、構成データを回復できます。

インストールまたはアップグレード中に永続ボリューム機能を有効にすると、複数のボリュームが自動的に作成されます。これらのボリュームは、他の Element ソフトウェア ベースのボリュームと同様に、設定とインストールに応じて、Element ソフトウェア Web UI、vCenter Server 用のNetApp Elementプラグイン、または API を使用して表示できます。リカバリに使用できる現在の構成データを維持するには、管理ノードへの iSCSI 接続を使用して永続ボリュームが稼働している必要があります。


NOTE: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード中に作成され、新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、ボリュームやそれに関連付けられたアカウントを変更または削除しないでください。
