---
permalink: storage/concept_system_manage_cluster_terms_manage_the_terms_of_use_banner.html 
sidebar: sidebar 
keywords: element, terms of use, banner, config, edit, terms of use, disable, enable 
summary: ユーザーへのメッセージを含むバナーを有効化、編集、または構成できます。 
---
= 利用規約バナーを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ユーザーへのメッセージを含むバナーを有効化、編集、または構成できます。

.オプション
<<利用規約バナーを有効にする>> <<利用規約バナーを編集する>> <<利用規約バナーを無効にする>>



== 利用規約バナーを有効にする

ユーザーが Element UI にログインしたときに表示される利用規約バナーを有効にすることができます。ユーザーがバナーをクリックすると、クラスターに設定したメッセージを含むテキスト ダイアログ ボックスが表示されます。バナーはいつでも閉じることができます。

利用規約機能を有効にするには、クラスター管理者の権限が必要です。

. *ユーザー* > *利用規約*をクリックします。
. *利用規約* フォームに、利用規約ダイアログ ボックスに表示されるテキストを入力します。
+

NOTE: 4096文字を超えないでください。

. *有効*をクリックします。




== 利用規約バナーを編集する

ユーザーが利用規約のログインバナーを選択したときに表示されるテキストを編集できます。

.要件
* 利用規約を構成するには、クラスター管理者の権限が必要です。
* 利用規約機能が有効になっていることを確認します。


.手順
. *ユーザー* > *利用規約*をクリックします。
. *利用規約* ダイアログボックスで、表示するテキストを編集します。
+

NOTE: 4096文字を超えないでください。

. *変更を保存*をクリックします。




== 利用規約バナーを無効にする

利用規約バナーを無効にすることができます。バナーを無効にすると、Element UI を使用するときにユーザーは利用規約に同意する必要がなくなります。

.要件
* 利用規約を構成するには、クラスター管理者の権限が必要です。
* 利用規約が有効になっていることを確認してください。


.手順
. *ユーザー* > *利用規約*をクリックします。
. *無効*をクリックします。

