---
permalink: storage/concept_remove_nodes_from_cluster.html 
sidebar: sidebar 
keywords: troubleshoot, nodes removing 
summary: メンテナンスや交換のためにクラスターからノードを削除できます。ノードをオフラインにする前に、 NetApp Element UI または API を使用してノードを削除する必要があります。 
---
= クラスターからノードを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メンテナンスや交換のためにクラスターからノードを削除できます。ノードをオフラインにする前に、 NetApp Element UI または API を使用してノードを削除する必要があります。

ストレージ ノードを削除する手順の概要は次のとおりです。

* ノード上のデータのコピーを作成するためにクラスター内に十分な容量があることを確認します。
* UI または RemoveDrives API メソッドを使用して、クラスターからドライブを削除します。
+
その結果、システムはノードのドライブからクラスター内の他のドライブにデータを移行します。このプロセスにかかる時間は、移行する必要があるデータの量によって異なります。

* クラスタからノードを削除します。


ノードの電源を切るか入れる前に、次の点に留意してください。

* ノードとクラスターの電源をオフにすることは、適切に実行されなければリスクを伴います。
+
ノードの電源オフは、NetAppサポートの指示の下で行う必要があります。

* いかなる種類のシャットダウン状態でもノードが 5.5 分以上ダウンしている場合、Double Helix データ保護は、単一の複製ブロックを別のノードに書き込んでデータを複製するタスクを開始します。この場合は、NetAppサポートに連絡して障害ノードの分析を依頼してください。
* ノードを安全に再起動または電源を切るには、Shutdown API コマンドを使用できます。
* ノードが停止またはオフになったら、オンラインに戻す前にNetAppサポートに連絡する必要があります。
* ノードがオンラインに戻った後、サービスが停止していた期間に応じて、ドライブをクラスターに再度追加する必要があります。




== 詳細情報

https://library.netapp.com/ecm/ecm_download_file/ECMLP2844772["故障したSolidFireシャーシの交換"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2846861["故障したH600Sシリーズノードの交換"]
