---
permalink: storage/concept_intro_persistent_volumes.html 
sidebar: sidebar 
keywords: persistent volumes, what are persistent volumes 
summary: 永続ボリュームを使用すると、管理ノードの構成データを VM のローカルではなく、指定されたストレージ クラスターに保存できるため、管理ノードが失われたり削除されたりした場合でもデータを保持できます。永続ボリュームはオプションですが、推奨される管理ノード構成です。 
---
= 永続ボリューム
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
永続ボリュームを使用すると、管理ノードの構成データを VM のローカルではなく、指定されたストレージ クラスターに保存できるため、管理ノードが失われたり削除されたりした場合でもデータを保持できます。永続ボリュームはオプションですが、推奨される管理ノード構成です。

新しい管理ノードを展開するときに、永続ボリュームを有効にするオプションがインストール スクリプトとアップグレード スクリプトに含まれます。永続ボリュームは、VM の寿命を超えて存続するホスト管理ノード VM の管理ノード構成情報を含む、Element ソフトウェアベースのストレージ クラスター上のボリュームです。管理ノードが失われた場合、代替の管理ノード VM が失われた VM に再接続し、構成データを回復できます。

永続ボリューム機能は、インストールまたはアップグレード中に有効にすると、割り当てられたクラスターの名前の先頭にNetApp-HCI- が付加された複数のボリュームを自動的に作成します。これらのボリュームは、他の Element ソフトウェア ベースのボリュームと同様に、設定とインストールに応じて、Element ソフトウェア Web UI、vCenter Server 用のNetApp Elementプラグイン、または API を使用して表示できます。リカバリに使用できる現在の構成データを維持するには、管理ノードへの iSCSI 接続を使用して永続ボリュームが稼働している必要があります。


IMPORTANT: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード中に作成され、新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、ボリュームまたはそれに関連付けられたアカウントを変更または削除しないでください。
