---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: SolidFireストレージ システムのクラスター管理者アカウントを管理できます。利用可能なクラスタ管理者管理機能には、クラスタ管理者アカウントの作成、削除、編集、クラスタ管理者パスワードの変更、ユーザーのシステム アクセスを管理するための LDAP 設定の構成などがあります。 
---
= クラスタ管理者のユーザーアカウントを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ管理者アカウントを作成、削除、編集し、クラスタ管理者パスワードを変更し、LDAP 設定を構成してユーザーのシステム アクセスを管理することで、 SolidFireストレージ システムのクラスタ管理者アカウントを管理できます。



== ストレージクラスタ管理者アカウントの種類

NetApp Elementソフトウェアを実行しているストレージ クラスタには、プライマリ クラスタ管理者アカウントとクラスタ管理者アカウントの 2 種類の管理者アカウントが存在します。

* *プライマリクラスタ管理者アカウント*
+
この管理者アカウントは、クラスターの作成時に作成されます。このアカウントは、クラスターへの最高レベルのアクセス権を持つプライマリ管理アカウントです。このアカウントは、Linux システムの root ユーザーに類似しています。この管理者アカウントのパスワードを変更できます。

* *クラスター管理者アカウント*
+
クラスター管理者アカウントに、クラスター内で特定のタスクを実行するための限定された範囲の管理アクセス権を付与できます。各クラスター管理者アカウントに割り当てられた資格情報は、ストレージ システム内の API および Element UI 要求を認証するために使用されます。




NOTE: ノードごとの UI を介してクラスター内のアクティブなノードにアクセスするには、ローカル (LDAP 以外の) クラスター管理者アカウントが必要です。まだクラスターの一部ではないノードにアクセスするには、アカウント資格情報は必要ありません。



== クラスター管理者の詳細を表示する

. クラスター全体 (LDAP 以外) のクラスター管理者アカウントを作成するには、次の操作を実行します。
+
.. *ユーザー* > *クラスター管理者*をクリックします。


. [ユーザー] タブの [クラスター管理者] ページで、次の情報を表示できます。
+
** *ID*: クラスター管理者アカウントに割り当てられた連番。
** *ユーザー名*: クラスター管理者アカウントの作成時に指定された名前。
** *アクセス*: ユーザー アカウントに割り当てられたユーザー権限。有効な値は次のとおりです。
+
*** 読む
*** 報告
*** ノード
*** ドライブ
*** ボリューム
*** アカウント
*** クラスター管理者
*** administrator
*** サポート管理者




+
[NOTE]
====
管理者アクセス タイプではすべての権限が利用可能です。

Element UI では利用できない、API 経由で利用できるアクセス タイプがあります。

====
+
** *タイプ*: クラスター管理者のタイプ。有効な値は次のとおりです。
+
*** クラスタ
*** LDAP


** *属性*: クラスター管理者アカウントが Element API を使用して作成された場合、この列にはその方法を使用して設定された名前と値のペアが表示されます。
+
見るlink:../api/concept_element_api_about_the_api.html["NetApp Elementソフトウェア API リファレンス"]。







== クラスタ管理者アカウントを作成する

ストレージ システムの特定の領域へのアクセスを許可または制限する権限を持つ新しいクラスター管理者アカウントを作成できます。クラスタ管理者アカウントの権限を設定すると、クラスタ管理者に割り当てられていない権限に対しては読み取り専用権限が付与されます。

LDAP クラスター管理者アカウントを作成する場合は、開始する前にクラスター上で LDAP が構成されていることを確認してください。

link:concept_system_manage_manage_ldap.html["ElementユーザーインターフェースでLDAP認証を有効にする"]

後で、レポート、ノード、ドライブ、ボリューム、アカウント、およびクラスター レベルのアクセスに関するクラスター管理者アカウントの権限を変更できます。権限を有効にすると、システムによってそのレベルの書き込みアクセス権が割り当てられます。選択していないレベルについては、システムは管理者ユーザーに読み取り専用アクセス権を付与します。

システム管理者によって作成されたクラスター管理者ユーザー アカウントを後で削除することもできます。クラスターの作成時に作成されたプライマリ クラスター管理者アカウントを削除することはできません。

. クラスター全体 (LDAP 以外) のクラスター管理者アカウントを作成するには、次の操作を実行します。
+
.. *ユーザー* > *クラスター管理者*をクリックします。
.. *クラスター管理者の作成*をクリックします。
.. *クラスター* ユーザー タイプを選択します。
.. アカウントのユーザー名とパスワードを入力し、パスワードを確認します。
.. アカウントに適用するユーザー権限を選択します。
.. エンド ユーザー ライセンス契約に同意するには、チェック ボックスをオンにします。
.. *クラスター管理者の作成*をクリックします。


. LDAP ディレクトリにクラスタ管理者アカウントを作成するには、次の操作を実行します。
+
.. *クラスター* > *LDAP* をクリックします。
.. LDAP認証が有効になっていることを確認します。
.. *ユーザー認証のテスト* をクリックし、ユーザーまたはユーザーが所属するグループの 1 つに表示される識別名をコピーして、後で貼り付けられるようにします。
.. *ユーザー* > *クラスター管理者*をクリックします。
.. *クラスター管理者の作成*をクリックします。
.. LDAP ユーザー タイプを選択します。
.. [識別名] フィールドで、テキスト ボックスの例に従って、ユーザーまたはグループの完全な識別名を入力します。または、先ほどコピーした識別名を貼り付けます。
+
識別名がグループの一部である場合、LDAP サーバー上のそのグループのメンバーであるすべてのユーザーにこの管理者アカウントの権限が与えられます。

+
LDAP クラスタ管理者のユーザーまたはグループを追加する場合、ユーザー名の一般的な形式は「`LDAP:<Full Distinguished Name>`」です。

.. アカウントに適用するユーザー権限を選択します。
.. エンド ユーザー ライセンス契約に同意するには、チェック ボックスをオンにします。
.. *クラスター管理者の作成*をクリックします。






== クラスタ管理者の権限を編集する

レポート、ノード、ドライブ、ボリューム、アカウント、およびクラスター レベルのアクセスに関するクラスター管理者アカウントの権限を変更できます。権限を有効にすると、システムによってそのレベルの書き込みアクセス権が割り当てられます。選択していないレベルについては、システムは管理者ユーザーに読み取り専用アクセス権を付与します。

. *ユーザー* > *クラスター管理者*をクリックします。
. 編集するクラスター管理者の [アクション] アイコンをクリックします。
. *編集*をクリックします。
. アカウントに適用するユーザー権限を選択します。
. *変更を保存*をクリックします。




== クラスタ管理者アカウントのパスワードを変更する

Element UI を使用して、クラスター管理者のパスワードを変更できます。

. *ユーザー* > *クラスター管理者*をクリックします。
. 編集するクラスター管理者の [アクション] アイコンをクリックします。
. *編集*をクリックします。
. 「パスワードの変更」フィールドに新しいパスワードを入力して確認します。
. *変更を保存*をクリックします。


.関連情報
* link:../api/reference_element_api_app_b_access_control.html["Element API で利用可能なアクセス タイプについて学習します"]
* link:concept_system_manage_manage_ldap.html["ElementユーザーインターフェースでLDAP認証を有効にする"]
* link:concept_system_manage_manage_ldap.html["LDAPを無効にする"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

