---
permalink: storage/concept_system_manage_nodes_node_versioning_and_compatibility.html 
sidebar: sidebar 
keywords: compatibility, node version, clusters, software version, compatible versions, major, minor, micro 
summary: ノードの互換性は、ノードにインストールされている Element ソフトウェアのバージョンに基づいています。  Element ソフトウェア ベースのストレージ クラスターは、ノードとクラスターのバージョンに互換性がない場合、自動的にノードをクラスター上の Element ソフトウェア バージョンにイメージ化します。 
---
= ノードのバージョン管理と互換性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードの互換性は、ノードにインストールされている Element ソフトウェアのバージョンに基づいています。  Element ソフトウェア ベースのストレージ クラスターは、ノードとクラスターのバージョンに互換性がない場合、自動的にノードをクラスター上の Element ソフトウェア バージョンにイメージ化します。

次のリストは、Element ソフトウェア バージョン番号を構成するソフトウェア リリースの重要度レベルを示しています。

* *選考科目*
+
最初の数字はソフトウェアのリリースを示します。あるメジャー番号のノードを、メジャー番号が異なるノードを含むクラスタに追加することはできません。また、メジャー バージョンが異なるノードが混在したクラスタを作成することはできません。

* *マイナー*
+
2 番目の番号は、メジャー リリースに追加された小さなソフトウェア機能または既存のソフトウェア機能の拡張機能を指定します。このコンポーネントはメジャー バージョン コンポーネント内で増分され、この増分リリースが、異なるマイナー コンポーネントを持つ他の Element ソフトウェア増分リリースと互換性がないことを示します。たとえば、11.0 は 11.1 と互換性がなく、11.1 は 11.2 と互換性がありません。

* *マイクロ*
+
3 番目の数字は、major.minor コンポーネントによって表される Element ソフトウェア バージョンに対する互換性のあるパッチ (増分リリース) を指定します。たとえば、11.0.1 は 11.0.2 と互換性があり、11.0.2 は 11.0.3 と互換性があります。



互換性を保つには、メジャー バージョン番号とマイナー バージョン番号が一致している必要があります。マイクロ番号は互換性のために一致する必要はありません。
