---
permalink: storage/concept_data_manage_vvol_protocol_endpoints.html 
sidebar: sidebar 
keywords: protocol endpoint, access, cluster, storage node, iscsi supported 
summary: プロトコル エンドポイントは、 NetApp Elementソフトウェアを実行しているクラスター上のストレージをアドレス指定するためにホストが使用するアクセス ポイントです。プロトコル エンドポイントは、ユーザーによって削除または変更することはできず、アカウントに関連付けられておらず、ボリューム アクセス グループに追加することもできません。 
---
= プロトコルエンドポイントについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
プロトコル エンドポイントは、 NetApp Elementソフトウェアを実行しているクラスター上のストレージをアドレス指定するためにホストが使用するアクセス ポイントです。プロトコル エンドポイントは、ユーザーによって削除または変更することはできず、アカウントに関連付けられておらず、ボリューム アクセス グループに追加することもできません。

Element ソフトウェアを実行するクラスターは、クラスター内のストレージ ノードごとに 1 つのプロトコル エンドポイントを自動的に作成します。たとえば、6 ノードのストレージ クラスターには、各 ESXi ホストにマップされる 6 つのプロトコル エンドポイントがあります。プロトコル エンドポイントは Element ソフトウェアによって動的に管理され、介入なしに必要に応じて作成、移動、または削除されます。プロトコル エンドポイントはマルチパスのターゲットであり、補助 LUN の I/O プロキシとして機能します。各プロトコル エンドポイントは、標準の iSCSI ターゲットと同様に、使用可能な SCSI アドレスを消費します。プロトコル エンドポイントは、vSphere クライアントでは単一ブロック (512 バイト) のストレージ デバイスとして表示されますが、このストレージ デバイスはフォーマットしたり、ストレージとして使用したりすることはできません。

サポートされているプロトコルは iSCSI のみです。ファイバー チャネル プロトコルはサポートされていません。
