---
permalink: storage/concept_data_manage_data_management.html 
sidebar: sidebar 
keywords: virtual volumes, volumes, manage 
summary: 'Element UI の [管理] タブから、Element ソフトウェアを実行しているクラスター内のデータを管理できます。利用可能なクラスター管理機能には、データ ボリューム、ユーザー アカウント、ボリューム アクセス グループ、イニシエーター、およびサービス品質 (QoS) ポリシーの作成と管理が含まれます。' 
---
= ボリュームと仮想ボリュームの管理について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element UI の [管理] タブから、Element ソフトウェアを実行しているクラスター内のデータを管理できます。利用可能なクラスター管理機能には、データ ボリューム、ボリューム アクセス グループ、イニシエーター、およびサービス品質 (QoS) ポリシーの作成と管理が含まれます。



== ボリュームの操作

SolidFireシステムはボリュームを使用してストレージをプロビジョニングします。ボリュームは、iSCSI またはファイバー チャネル クライアントによってネットワーク経由でアクセスされるブロック デバイスです。 [管理] タブの [ボリューム] ページから、ノード上のボリュームを作成、変更、複製、および削除できます。ボリューム帯域幅と I/O 使用量に関する統計も表示できます。

link:../storage/concept_data_manage_volumes_quality_of_service_policies.html["ボリュームの操作について学ぶ"]



== 仮想ボリュームの操作

Element UI を使用して、仮想ボリュームとそれに関連付けられたストレージ コンテナー、プロトコル エンドポイント、バインディング、ホストの情報を表示し、タスクを実行できます。

NetApp Elementソフトウェア ストレージ システムは、仮想ボリューム (VVol) 機能が無効の状態で出荷されます。  Element UI を使用して vSphere VVol 機能を手動で有効にする 1 回限りのタスクを実行する必要があります。

VVol 機能を有効にすると、VVol 関連の監視と制限された管理オプションを提供する VVol タブがユーザー インターフェイスに表示されます。さらに、VASA プロバイダーと呼ばれるストレージ側のソフトウェア コンポーネントは、vSphere のストレージ認識サービスとして機能します。 VVol の作成、クローン作成、編集などのほとんどの VVol コマンドは、vCenter Server または ESXi ホストによって開始され、VASA プロバイダーによって Element ソフトウェア ストレージ システムの Element API に変換されます。ストレージ コンテナーを作成、削除、管理し、仮想ボリュームを削除するコマンドは、Element UI を使用して開始できます。

Element ソフトウェア ストレージ システムで仮想ボリューム機能を使用するために必要な構成の大部分は、vSphere で行われます。  VASA プロバイダーを vCenter に登録し、VVol データストアを作成および管理し、ポリシーに基づいてストレージを管理するには、『VMware vSphere Virtual Volumes for SolidFireストレージ構成ガイド』を参照してください。


NOTE: Element 12.5 以前の場合、1 つの vCenter インスタンスに複数のNetApp Element VASA プロバイダーを登録しないでください。  2 番目のNetApp Element VASA プロバイダーが追加されると、すべての VVOL データストアにアクセスできなくなります。


NOTE: VASA プロバイダーを vCenter にすでに登録している場合は、複数の vCenter に対する VASA サポートをアップグレード パッチとして利用できます。インストールするには、VASA39 .tar.gzファイルを https://mysupport.netapp.com/products/element_software/VASA39/index.html["NetAppソフトウェア ダウンロード"]サイトにアクセスし、マニフェストの指示に従ってください。 NetApp Element VASA プロバイダーはNetApp証明書を使用します。このパッチにより、証明書は vCenter によって変更されずに使用され、VASA および VVols の使用のために複数の vCenter がサポートされるようになります。証明書を変更しないでください。カスタム SSL 証明書は VASA ではサポートされていません。

link:../storage/task_data_manage_vvol_enable_virtual_volumes.html["仮想ボリュームの操作について学ぶ"]



== ボリューム アクセス グループとイニシエーターの操作

iSCSI イニシエーターまたはファイバー チャネル イニシエーターを使用して、ボリューム アクセス グループ内で定義されたボリュームにアクセスできます。

ボリュームのコレクション内の iSCSI イニシエーター IQN またはファイバー チャネル WWPN をマッピングすることにより、アクセス グループを作成できます。アクセス グループに追加した各 IQN は、CHAP 認証を必要とせずにグループ内の各ボリュームにアクセスできます。

CHAP 認証方法には 2 種類あります。

* アカウント レベルの CHAP 認証: アカウントに CHAP 認証を割り当てることができます。
* イニシエーター レベルの CHAP 認証: 単一のアカウント全体で単一の CHAP にバインドされることなく、特定のイニシエーターに一意の CHAP ターゲットとシークレットを割り当てることができます。このイニシエーター レベルの CHAP 認証は、アカウント レベルの資格情報を置き換えます。


オプションで、イニシエータごとの CHAP を使用すると、イニシエータの承認とイニシエータごとの CHAP 認証を強制できます。これらのオプションはイニシエータごとに定義でき、アクセス グループには異なるオプションを持つイニシエータが混在できます。

アクセス グループに追加する各 WWPN により、アクセス グループ内のボリュームへのファイバー チャネル ネットワーク アクセスが可能になります。


NOTE: ボリューム アクセス グループには次の制限があります。

* アクセス グループでは最大 64 個の IQN または WWPN が許可されます。
* アクセス グループは最大 2000 個のボリュームで構成できます。
* 1つのIQNまたはWWPNが属することのできるアクセス グループは1つだけです。
* 1つのボリュームが最大4つのアクセス グループに属することができます。


link:../storage/task_data_manage_vol_access_group_create_a_volume_access_group.html["ボリューム アクセス グループとイニシエーターの操作について学習します"]



== 詳細情報

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

