---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: '外部キー管理 (EKM) は、クラスター外の外部キー サーバー (EKS) と連携して、安全な認証キー (AK) 管理を提供します。  AK は、クラスターで保存時の暗号化が有効になっている場合に、自己暗号化ドライブ (SED) をロックおよびロック解除するために使用されます。' 
---
= 外部キー管理を始める
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部キー管理 (EKM) は、クラスター外の外部キー サーバー (EKS) と連携して、安全な認証キー (AK) 管理を提供します。  AKは自己暗号化ドライブ（SED）のロックとロック解除に使用されます。link:../concepts/concept_solidfire_concepts_security.html["保存時の暗号化"]クラスターで有効になっています。 EKS は、AK の安全な生成と保存を提供します。クラスターは、OASIS が定義した標準プロトコルであるキー管理相互運用性プロトコル (KMIP) を使用して EKS と通信します。

* link:task_system_manage_key_set_up_external_key_management.html["外部管理を設定する"]
* link:task_system_manage_rekey_software_ear_master_key.html["保存時のソフトウェア暗号化マスターキーの再キー化"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["アクセスできない、または無効な認証キーを回復する"]
* link:concept_system_manage_key_external_key_management_api_commands.html["外部キー管理APIコマンド"]


[discrete]
== 詳細情報の参照

* link:../api/reference_element_api_createcluster.html["保存時のソフトウェア暗号化を有効にするために使用できる CreateCluster API"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFireおよび Element 製品の以前のバージョンのドキュメント"^]

