---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: 'メタデータ ドライブの 1 つまたは両方に障害が発生した場合、メタデータ ドライブ (またはスライス ドライブ) をクラスターに再度追加することで、メタデータ ドライブを回復できます。ノードで MDSS 機能がすでに有効になっている場合は、 NetApp Element UI でリカバリ操作を実行できます。' 
---
= MDSSドライブの基本的なトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メタデータ ドライブの 1 つまたは両方に障害が発生した場合、メタデータ (またはスライス) ドライブをクラスターに再度追加することで、メタデータ ドライブを回復できます。ノードで MDSS 機能がすでに有効になっている場合は、 NetApp Element UI でリカバリ操作を実行できます。

ノード内のメタデータ ドライブのいずれかまたは両方に障害が発生した場合、スライス サービスはシャットダウンされ、両方のドライブのデータがノード内の別のドライブにバックアップされます。

次のシナリオでは、起こりうる障害のシナリオの概要を示し、問題を修正するための基本的な推奨事項を示します。



== システムスライスドライブの故障

* このシナリオでは、スロット 2 が検証され、使用可能な状態に戻されます。
* スライス サービスをオンラインに戻す前に、システム スライス ドライブを再設定する必要があります。
* システム スライス ドライブを交換し、システム スライス ドライブが使用可能になったら、ドライブとスロット 2 ドライブを同時に追加する必要があります。



NOTE: スロット 2 のドライブをメタデータ ドライブとして単独で追加することはできません。両方のドライブを同時にノードに追加し直す必要があります。



== スロット2が故障

* このシナリオでは、システム スライス ドライブが検証され、使用可能な状態に戻されます。
* スロット 2 をスペアに交換し、スロット 2 が使用可能になったら、システム スライス ドライブとスロット 2 ドライブを同時に追加する必要があります。




== システムスライスドライブとスロット2に障害が発生しました

* システム スライス ドライブとスロット 2 の両方をスペア ドライブに交換する必要があります。両方のドライブが使用可能になったら、システム スライス ドライブとスロット 2 ドライブを同時に追加します。




== 演算順序

* 故障したハードウェア ドライブをスペア ドライブと交換します (両方のドライブに故障がある場合は、両方のドライブを交換します)。
* ドライブが再配置され、使用可能な状態になったら、ドライブをクラスターに戻します。




== 操作の検証

* スロット 0 (または内部) およびスロット 2 のドライブが、アクティブ ドライブ リストでメタデータ ドライブとして識別されていることを確認します。
* すべてのスライスのバランス調整が完了したことを確認します (少なくとも 30 分間、イベント ログにスライスの移動メッセージが残っていないこと)。




== 詳細情報

xref:task_troubleshoot_add_mdss_drives.adoc[MDSSドライブを追加する]
