---
permalink: storage/concept_intro_drives.html 
sidebar: sidebar 
keywords: drives, physical drives, cluster data, storage node, volume metadata, block drives, clusters 
summary: ストレージ ノードには、クラスターのデータの一部を保存するために使用される 1 つ以上の物理ドライブが含まれています。ドライブがクラスターに正常に追加された後、クラスターはドライブの容量とパフォーマンスを活用します。 
---
= システムの
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードには、クラスターのデータの一部を保存するために使用される 1 つ以上の物理ドライブが含まれています。ドライブがクラスターに正常に追加された後、クラスターはドライブの容量とパフォーマンスを活用します。

ストレージ ノードには 2 種類のドライブが含まれます。

* *ボリュームメタデータドライブ*
+
これらのドライブには、クラスター内の各ボリューム、クローン、またはスナップショットを定義する圧縮された情報が保存されます。システム内のメタデータ ドライブの合計容量によって、ボリュームとしてプロビジョニングできるストレージの最大量が決まります。プロビジョニングできるストレージの最大量は、クラスターのブロック ドライブに実際に保存されるデータの量とは無関係です。ボリューム メタデータ ドライブは、Double Helix データ保護を使用してクラスター全体にデータを冗長的に保存します。

+

NOTE: 一部のシステム イベント ログおよびエラー メッセージでは、ボリューム メタデータ ドライブがスライス ドライブとして参照されます。

* *ブロックドライブ*
+
これらのドライブには、サーバー アプリケーション ボリュームの圧縮され重複が排除されたデータ ブロックが保存されます。ブロック ドライブは、システムのストレージ容量の大部分を占めます。 SolidFireクラスターにすでに保存されているデータの読み取り要求とデータの書き込み要求の大部分は、ブロック ドライブで発生します。システム内のブロック ドライブの合計容量によって、圧縮、シン プロビジョニング、重複排除の影響を考慮して、保存できるデータの最大量が決まります。


