---
permalink: storage/concept_intro_clusters.html 
sidebar: sidebar 
keywords: clusters, about clusters, collection of nodes, nodes in a cluster, block storage, logical group, add nodes, access cluster 
summary: クラスターはSolidFireストレージ システムのハブであり、ノードの集合で構成されます。 SolidFire のストレージ効率を実現するには、クラスター内に少なくとも 4 つのノードが必要です。クラスターは単一の論理グループとしてネットワーク上に表示され、ブロック ストレージとしてアクセスできるようになります。 
---
= クラスタ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスターはSolidFireストレージ システムのハブであり、ノードの集合で構成されます。 SolidFire のストレージ効率を実現するには、クラスター内に少なくとも 4 つのノードが必要です。クラスターは単一の論理グループとしてネットワーク上に表示され、ブロック ストレージとしてアクセスできるようになります。

新しいクラスターを作成すると、ノードがクラスターの通信所有者として初期化され、クラスター内の各ノードのネットワーク通信が確立されます。このプロセスは、新しいクラスターごとに 1 回だけ実行されます。  Element UI または API を使用してクラスターを作成できます。

追加のノードを追加することでクラスターをスケールアウトできます。新しいノードを追加しても、サービスは中断されず、クラスターは新しいノードのパフォーマンスと容量を自動的に使用します。

管理者とホストは仮想 IP アドレスを使用してクラスターにアクセスできます。クラスター内の任意のノードが仮想 IP アドレスをホストできます。管理仮想 IP (MVIP) は 1GbE 接続を介してクラスター管理を可能にし、ストレージ仮想 IP (SVIP) は 10GbE 接続を介してストレージへのホスト アクセスを可能にします。これらの仮想 IP アドレスにより、 SolidFireクラスターのサイズや構成に関係なく、一貫した接続が可能になります。仮想 IP アドレスをホストしているノードに障害が発生した場合、クラスター内の別のノードが仮想 IP アドレスのホスティングを開始します。


NOTE: Element バージョン 11.0 以降では、管理ネットワークのノードに IPv4、IPv6、またはその両方のアドレスを構成できます。これは、IPv6 をサポートしない管理ノード 11.3 以降を除き、ストレージ ノードと管理ノードの両方に適用されます。クラスターを作成する場合、MVIP には単一の IPv4 または IPv6 アドレスのみを使用でき、対応するアドレス タイプをすべてのノードで構成する必要があります。
