---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: Element ソフトウェアを実行しているクラスターは、クラスターの容量が不足すると、クラスター障害を生成してストレージ管理者に警告します。クラスターの満杯度には 3 つのレベル（警告、エラー、重大）があり、それらはすべてNetApp Element UI に表示されます。 
---
= クラスターの満杯度レベルを理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element ソフトウェアを実行しているクラスターは、クラスターの容量が不足すると、クラスター障害を生成してストレージ管理者に警告します。クラスターの満杯度には 3 つのレベル（警告、エラー、重大）があり、それらはすべてNetApp Element UI に表示されます。

システムは、BlockClusterFull エラー コードを使用して、クラスター ブロック ストレージの空き容量がないことを警告します。  Element UI の [アラート] タブから、クラスターの満杯度の重大度レベルを表示できます。

次のリストには、BlockClusterFull の重大度レベルに関する情報が含まれています。

* *警告*
+
これは、クラスターのブロック容量がエラーの重大度レベルに近づいているときに表示される、顧客が構成可能な警告です。デフォルトでは、このレベルはエラー レベルの 3% 下に設定されており、Element UI および API を介して調整できます。できるだけ早く容量を追加するか、容量を解放する必要があります。

* *エラー*
+
クラスターがこの状態にある場合、ノードが失われると、クラスター内に Double Helix データ保護を再構築するのに十分な容量がなくなります。クラスタがこの状態にある間は、ボリュームの新規作成、クローンおよびSnapshotの処理はすべてブロックされます。これは、どのクラスターにとっても安全または推奨される状態ではありません。容量を追加するか、すぐに容量を解放する必要があります。

* *致命的*
+
この重大なエラーは、クラスターが 100% 使用されているために発生しました。読み取り専用状態であり、クラスターへの新しい iSCSI 接続を確立することはできません。この段階に達したら、すぐに容量を解放するか、容量を追加する必要があります。



システムは、MetadataClusterFull エラー コードを使用して、クラスター メタデータ ストレージがいっぱいになっていることを警告します。  Element UI の [レポート] タブの [概要] ページの [クラスター容量] セクションから、クラスター メタデータ ストレージの空き容量を確認できます。

次のリストには、MetadataClusterFull の重大度レベルに関する情報が含まれています。

* *警告*
+
これは、クラスターのメタデータ容量がエラーの重大度レベルに近づいているときに表示される、顧客が構成可能な警告です。デフォルトでは、このレベルはエラー レベルの 3% 下に設定されており、Element API を介して調整できます。できるだけ早く容量を追加するか、容量を解放する必要があります。

* *エラー*
+
クラスターがこの状態にある場合、ノードが失われると、クラスター内に Double Helix データ保護を再構築するのに十分な容量がなくなります。クラスタがこの状態にある間は、ボリュームの新規作成、クローンおよびSnapshotの処理はすべてブロックされます。これは、どのクラスターにとっても安全または推奨される状態ではありません。容量を追加するか、すぐに容量を解放する必要があります。

* *致命的*
+
この重大なエラーは、クラスターが 100% 使用されているために発生しました。読み取り専用状態であり、クラスターへの新しい iSCSI 接続を確立することはできません。この段階に達したら、すぐに容量を解放するか、容量を追加する必要があります。




NOTE: 2 ノード クラスターのしきい値には次の内容が適用されます。

* メタデータ完全性エラーは、クリティカルより 20% 低いです。
* ブロック満杯エラーは、クリティカルな容量より 1 ブロック ドライブ (孤立した容量を含む) 少ないです。つまり、クリティカルな容量より 2 ブロック ドライブ分の容量が少ないということです。

