---
permalink: storage/concept_data_manage_vvol_manage_storage_containers.html 
sidebar: sidebar 
keywords: storage container, storage containers, about storage containers, cluster, vvols, create, view details, chap, edit, delete 
summary: ストレージ コンテナは、Element ソフトウェアを実行するクラスタ上に作成される vSphere データストアの表現です。 
---
= ストレージコンテナの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ コンテナは、Element ソフトウェアを実行するクラスタ上に作成される vSphere データストアの表現です。

ストレージ コンテナが作成され、 NetApp Elementアカウントに関連付けられます。 Element ストレージ上に作成されたストレージ コンテナーは、vCenter および ESXi では vSphere データストアとして表示されます。ストレージ コンテナーは、要素ストレージにスペースを割り当てません。これらは、仮想ボリュームを論理的に関連付けるために使用されます。

クラスターごとに最大 4 つのストレージ コンテナーがサポートされます。  VVols 機能を有効にするには、少なくとも 1 つのストレージ コンテナーが必要です。



== ストレージコンテナを作成する

Element UI でストレージ コンテナーを作成し、vCenter で検出することができます。VVolを使用する仮想マシンのプロビジョニングを開始するためには、少なくとも1つのストレージ コンテナを作成する必要があります。

開始する前に、クラスターの Element UI で VVol 機能を有効にします。

.手順
. *VVols* > *ストレージ コンテナー* を選択します。
. *ストレージ コンテナーの作成* ボタンをクリックします。
. *新しいストレージ コンテナーの作成* ダイアログ ボックスにストレージ コンテナーの情報を入力します。
+
.. ストレージ コンテナーの名前を入力します。
.. CHAP のイニシエーターとターゲットのシークレットを構成します。
+

TIP: シークレットを自動的に生成するには、CHAP 設定フィールドを空白のままにします。

.. *ストレージ コンテナーの作成* ボタンをクリックします。


. 新しいストレージ コンテナーが *ストレージ コンテナー* サブタブのリストに表示されていることを確認します。
+

NOTE: NetApp Elementアカウント ID は自動的に作成され、ストレージ コンテナーに割り当てられるため、手動でアカウントを作成する必要はありません。





== ストレージコンテナの詳細を表示

VVol タブのストレージ コンテナー ページでは、クラスター上のすべてのアクティブなストレージ コンテナーの情報を表示できます。

* *アカウント ID*: ストレージ コンテナーに関連付けられているNetApp Elementアカウントの ID。
* *名前*: ストレージ コンテナーの名前。
* *ステータス*: ストレージ コンテナーのステータス。有効な値は次のとおりです。
+
** アクティブ: ストレージ コンテナーは使用中です。
** ロック済み: 保管コンテナはロックされています。


* *PE タイプ*: プロトコルのエンドポイント タイプ (Element ソフトウェアで使用できるプロトコルは SCSI のみです)。
* *ストレージ コンテナー ID*: 仮想ボリューム ストレージ コンテナーの UUID。
* *アクティブな仮想ボリューム*: ストレージ コンテナーに関連付けられているアクティブな仮想ボリュームの数。




== 個々のストレージコンテナの詳細を表示する

VVol タブのストレージ コンテナー ページから個々のストレージ コンテナーを選択すると、そのストレージ コンテナーの情報を表示できます。

* *アカウント ID*: ストレージ コンテナーに関連付けられているNetApp Elementアカウントの ID。
* *名前*: ストレージ コンテナーの名前。
* *ステータス*: ストレージ コンテナーのステータス。有効な値は次のとおりです。
+
** アクティブ: ストレージ コンテナーは使用中です。
** ロック済み: 保管コンテナはロックされています。


* *CHAP イニシエーター シークレット*: イニシエーターの一意の CHAP シークレット。
* *CHAP ターゲット シークレット*: ターゲットの一意の CHAP シークレット。
* *ストレージ コンテナー ID*: 仮想ボリューム ストレージ コンテナーの UUID。
* *プロトコル エンドポイント タイプ*: プロトコル エンドポイント タイプを示します (使用可能なプロトコルは SCSI のみです)。




== ストレージコンテナを編集する

Element UI でストレージ コンテナーの CHAP 認証を変更できます。

. *VVols* > *ストレージ コンテナー* を選択します。
. 編集するストレージ コンテナーの *アクション* アイコンをクリックします。
. 表示されたメニューで、[*編集*] を選択します。
. 「CHAP 設定」で、認証に使用するイニシエーター シークレットとターゲット シークレットの資格情報を編集します。
+

TIP: CHAP 設定の資格情報を変更しない場合は、同じままになります。資格情報フィールドを空白にすると、システムは自動的に新しいシークレットを生成します。

. *変更を保存*をクリックします。




== ストレージコンテナを削除する

Element UI からストレージ コンテナーを削除できます。

.要件
すべての仮想マシンが VVol データストアから削除されていることを確認します。

.手順
. *VVols* > *ストレージ コンテナー* を選択します。
. 削除するストレージ コンテナーの *アクション* アイコンをクリックします。
. 表示されるメニューで、[削除] を選択します。
. 操作を確定します。
. *ストレージ コンテナー* サブタブでストレージ コンテナーのリストを更新し、ストレージ コンテナーが削除されたことを確認します。

