---
permalink: storage/reference_monitor_volume_performance_details.html 
sidebar: sidebar 
keywords: volume performance 
summary: 'Element UI の [レポート] タブの [ボリューム パフォーマンス] ページから、ボリュームのパフォーマンス統計を表示できます。' 
---
= ボリュームパフォーマンスの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element UI の [レポート] タブの [ボリューム パフォーマンス] ページから、ボリュームのパフォーマンス統計を表示できます。

利用可能な詳細情報を次のリストに示します。

* *ID*
+
ボリュームのシステム生成 ID。

* *名前*
+
ボリュームの作成時に付けられた名前。

* *アカウント*
+
ボリュームに割り当てられたアカウントの名前。

* *アクセスグループ*
+
ボリュームが属するボリューム アクセス グループの名前。

* *ボリューム使用率*
+
クライアントがボリュームをどれだけ使用しているかを示すパーセンテージ値。

+
有効な値は次のとおりです。

+
** 0 = クライアントはボリュームを使用していません
** 100 = クライアントは最大限使用しています
** >100 = クライアントがバーストを使用しています


* *合計IOPS*
+
ボリュームに対して現在実行されている IOPS (読み取りと書き込み) の合計数。

* *読み取りIOPS*
+
ボリュームに対して現在実行されている読み取り IOPS の合計数。

* *書き込みIOPS*
+
ボリュームに対して現在実行されている書き込み IOPS の合計数。

* *総スループット*
+
ボリュームに対して現在実行されているスループット (読み取りと書き込み) の合計量。

* *読み取りスループット*
+
ボリュームに対して現在実行されている読み取りスループットの合計量。

* *書き込みスループット*
+
ボリュームに対して現在実行されている書き込みスループットの合計量。

* *合計レイテンシ*
+
ボリュームへの読み取りおよび書き込み操作を完了するまでの平均時間 (マイクロ秒単位)。

* *読み取り遅延*
+
過去 500 ミリ秒間にボリュームへの読み取り操作を完了するのにかかった平均時間 (マイクロ秒単位)。

* *書き込みレイテンシ*
+
過去 500 ミリ秒間にボリュームへの書き込み操作を完了するのにかかった平均時間 (マイクロ秒単位)。

* *キューの深さ*
+
ボリュームに対する未処理の読み取りおよび書き込み操作の数。

* *平均IOサイズ*
+
過去 500 ミリ秒間のボリュームへの最近の I/O の平均サイズ (バイト単位)。


