---
permalink: storage/reference_copyright.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 著作権
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 2021 NetApp, Inc. All rights reserved.米国で印刷

このドキュメントは著作権によって保護されています。著作権所有者の書面による事前承諾がある場合を除き、画像媒体、電子媒体、および写真複写、記録媒体、テープ媒体、電子検索システムへの組み込みを含む機械媒体など、いかなる形式および方法による複製も禁止します。

NetAppの著作物から派生したソフトウェアは、次に示す使用許諾条項および免責条項の対象となります。

このソフトウェアは、NetAppによって「現状のまま」提供されています。NetAppは明示的な保証、または商品性および特定目的に対する適合性の暗示的保証を含み、かつこれに限定されないいかなる暗示的な保証も行いません。NetAppは、代替品または代替サービスの調達、使用不能、データ損失、利益損失、業務中断を含み、かつこれに限定されない、このソフトウェアの使用により生じたすべての直接的損害、間接的損害、偶発的損害、特別損害、懲罰的損害、必然的損害の発生に対して、損失の発生の可能性が通知されていたとしても、その発生理由、根拠とする責任論、契約の有無、厳格責任、不法行為（過失またはそうでない場合を含む）にかかわらず、一切の責任を負いません。

NetAppは、ここに記載されているすべての製品に対する変更を随時、予告なく行う権利を保有します。NetAppによる明示的な書面による合意がある場合を除き、ここに記載されている製品の使用により生じる責任および義務に対して、NetAppは責任を負いません。この製品の使用または購入は、NetAppの特許権、商標権、または他の知的所有権に基づくライセンスの供与とはみなされません。

このマニュアルに記載されている製品は、1つ以上の米国特許、その他の国の特許、および出願中の特許によって保護されている場合があります。

本書に含まれるデータは市販品（FAR 2.101の定義に基づく）に関係し、データの所有権はNetApp, Inc.にあります。米国政府は本データに対し、非独占的かつ移転およびサブライセンス不可で、全世界を対象とする取り消し不能の制限付き使用権を有し、本データの提供の根拠となった米国政府契約に関連し、当該契約の裏付けとする場合にのみ本データを使用できます。ここに記載されている場合を除き、書面によるNetAppの事前の許可なく、「データ」を使用、開示、複製、変更、実行、または表示することは禁止されています。米国国防総省のライセンス権限は、DFARS 252.227-7015（b）項に規定されている権限に制限されます。
