---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: SSL 暗号は、ホストが安全な通信を確立するために使用する暗号化アルゴリズムです。  Element ソフトウェアがサポートする暗号には、標準の暗号と、FIPS 140-2 モードが有効な場合にサポートされる非標準の暗号があります。 
---
= SSL暗号
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL 暗号は、ホストが安全な通信を確立するために使用する暗号化アルゴリズムです。  Element ソフトウェアがサポートする暗号には、標準の暗号と、FIPS 140-2 モードが有効な場合にサポートされる非標準の暗号があります。

次のリストは、Element ソフトウェアでサポートされている標準の Secure Socket Layer (SSL) 暗号と、FIPS 140-2 モードが有効な場合にサポートされる SSL 暗号を示しています。

* *FIPS 140-2 無効*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_IDEA_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_RC4_128_MD5 (RSA 2048) - C

+
TLS_RSA_WITH_RC4_128_SHA (RSA 2048) - C

+
TLS_RSA_WITH_SEED_CBC_SHA (RSA 2048) - A

* *FIPS 140-2対応*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (sect571r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A





== 詳細情報の参照

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[クラスターでHTTPSにFIPS 140-2を有効にする]
