---
permalink: storage/reference_per_node_network_settings_details.html 
sidebar: sidebar 
keywords: network settings, per-node UI, storage node, ui 
summary: ストレージ ノードのネットワーク設定を変更して、ノードに新しいネットワーク属性のセットを与えることができます。 
---
= ノードごとのUIからのネットワーク設定の詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードのネットワーク設定を変更して、ノードに新しいネットワーク属性のセットを与えることができます。

ストレージノードのネットワーク設定は、ノードにログインすると*ネットワーク設定*ページで確認できます。 (`https://<node_IP>:442/hcc/node/network-settings`）。*Bond1G* (管理) または *Bond10G* (ストレージ) のいずれかの設定を選択できます。次のリストは、ストレージ ノードが使用可能、保留中、またはアクティブな状態のときに変更できる設定を示しています。

* *方法*
+
インターフェイスを構成するために使用される方法。可能な方法:

+
** loopback: IPv4 ループバック インターフェイスを定義するために使用されます。
** manual: デフォルトでは構成が行われないインターフェースを定義するために使用されます。
** dhcp: DHCP 経由で IP アドレスを取得するために使用されます。
** static: 静的に割り当てられた IPv4 アドレスを持つイーサネット インターフェイスを定義するために使用されます。


* *リンク速度*
+
仮想 NIC によってネゴシエートされた速度。

* *IPv4アドレス*
+
eth0 ネットワークの IPv4 アドレス。

* *IPv4サブネットマスク*
+
IPv4 ネットワークのアドレスの細分。

* *IPv4ゲートウェイアドレス*
+
ローカル ネットワークからパケットを送信するためのルーターのネットワーク アドレス。

* *IPv6アドレス*
+
eth0 ネットワークの IPv6 アドレス。

* *IPv6ゲートウェイアドレス*
+
ローカル ネットワークからパケットを送信するためのルーターのネットワーク アドレス。

* *MTU*
+
ネットワーク プロトコルが送信できる最大パケット サイズ。  1500 以上である必要があります。  2 番目のストレージ NIC を追加する場合、値は 9000 にする必要があります。

* *DNSサーバー*
+
クラスター通信に使用されるネットワーク インターフェイス。

* *ドメインを検索*
+
システムで使用可能な追加の MAC アドレスを検索します。

* *絆モード*
+
次のいずれかのモードになります。

+
** アクティブパッシブ（デフォルト）
** ALB
** LACP


* *状態*
+
有効な値は次のとおりです。

+
** アップアンドランニング
** 下
** 稼働


* *仮想ネットワークタグ*
+
仮想ネットワークの作成時に割り当てられたタグ。

* *ルート*
+
ルートが使用するように設定されている関連インターフェースを介した特定のホストまたはネットワークへの静的ルート。


