---
permalink: storage/reference_post_deploy_change_default_ssl_certificate.html 
sidebar: sidebar 
keywords: ssl certificate, SSL, private key, self-signed, cluster, nodes, user-defined certificate, API, change default certificate, certificate, Element API 
summary: NetApp Element API を使用して、クラスター内のストレージ ノードのデフォルトの SSL 証明書と秘密キーを変更できます。 
---
= ElementソフトウェアのデフォルトのSSL証明書を変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element API を使用して、クラスター内のストレージ ノードのデフォルトの SSL 証明書と秘密キーを変更できます。

NetApp Elementソフトウェア クラスタが作成されると、クラスタは、Element UI、ノードごとの UI、または API 経由のすべての HTTPS 通信に使用される一意の自己署名 Secure Sockets Layer (SSL) 証明書と秘密キーを作成します。  Element ソフトウェアは、自己署名証明書だけでなく、信頼できる証明機関 (CA) によって発行および検証された証明書もサポートします。

次の API メソッドを使用して、デフォルトの SSL 証明書に関する詳細情報を取得し、変更を加えることができます。

* *SSL証明書を取得*
+
使用することができますlink:../api/reference_element_api_getsslcertificate.html["GetSSLCertificateメソッド"]すべての証明書の詳細を含む、現在インストールされている SSL 証明書に関する情報を取得します。

* *SSL証明書の設定*
+
使用することができますlink:../api/reference_element_api_setsslcertificate.html["SetSSLCertificateメソッド"]クラスターおよびノードごとの SSL 証明書を、指定した証明書と秘密キーに設定します。システムは、無効な証明書が適用されないように、証明書と秘密キーを検証します。

* *SSL証明書を削除*
+
そのlink:../api/reference_element_api_removesslcertificate.html["RemoveSSLCertificate メソッド"]現在インストールされている SSL 証明書と秘密キーを削除します。次に、クラスターは新しい自己署名証明書と秘密キーを生成します。




NOTE: クラスター SSL 証明書は、クラスターに追加されたすべての新しいノードに自動的に適用されます。クラスターから削除されたノードは自己署名証明書に戻り、ユーザー定義の証明書とキー情報はすべてノードから削除されます。



== 詳細情報の参照

* link:../mnode/reference_change_mnode_default_ssl_certificate.html["管理ノードのデフォルトのSSL証明書を変更する"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["Element Software でカスタム SSL 証明書を設定する場合の要件は何ですか?"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

