---
permalink: storage/reference_replication_volume_pairing_warnings.html 
sidebar: sidebar 
keywords: volume warnings, messages, replication, data protection 
summary: 'ボリュームをペアリングした後、[データ保護] タブの [ボリューム ペア] ページに次のメッセージが表示されます。これらのメッセージは、（特に指定がない限り）レプリケーションボリュームのリストビューで、ペアのソース側とターゲット側の両方の端に表示されます。' 
---
= ボリュームペアリングの警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームをペアにした後、[データ保護] タブの [ボリューム ペア] ページに次のメッセージが表示されます。これらのメッセージは、レプリケーション ボリューム リスト ビューのペアのソース側とターゲット側の両端に表示されます (特に指定がない限り)。

* *一時停止中のクラスターがいっぱい*
+
ターゲット クラスターがいっぱいのため、ソース レプリケーションと一括データ転送を続行できません。メッセージはペアのソース側のみに表示されます。

* *一時停止、最大スナップショット数を超えました*
+
ターゲット ボリュームにはすでに最大数のスナップショットが存在するため、追加のスナップショットを複製することはできません。

* *一時停止マニュアル*
+
ローカルボリュームは手動で一時停止されました。レプリケーションを再開する前に一時停止を解除する必要があります。

* *一時停止手動リモート*
+
リモートボリュームは手動一時停止モードになっています。レプリケーションを再開する前に、リモート ボリュームの一時停止を解除するための手動介入が必要です。

* *一時停止中 設定ミス*
+
アクティブなソースとターゲットを待機しています。レプリケーションを再開するには手動による介入が必要です。

* *一時停止されたQoS*
+
ターゲット QoS は着信 IO を維持できませんでした。レプリケーションは自動的に再開されます。メッセージはペアのソース側のみに表示されます。

* *一時停止された低速リンク*
+
遅いリンクが検出され、レプリケーションが停止されました。レプリケーションは自動的に再開されます。メッセージはペアのソース側のみに表示されます。

* *一時停止中のボリュームサイズの不一致*
+
ターゲット ボリュームのサイズがソース ボリュームのサイズと同じではありません。

* *一時停止Xコピー*
+
ソース ボリュームに対して SCSI XCOPY コマンドが発行されています。レプリケーションを再開するには、コマンドを完了する必要があります。メッセージはペアのソース側のみに表示されます。

* *停止しました。設定ミスです。*
+
永続的な構成エラーが検出されました。リモート ボリュームは削除されたか、ペアリングが解除されました。修正アクションは不可能なので、新しいペアリングを確立する必要があります。


