---
permalink: storage/reference_snapmirror_relationship_actions.html 
sidebar: sidebar 
keywords: element, ui, relationships, snapmirror, actions, configure 
summary: 「データ保護」タブの「SnapMirror関係」ページから関係を設定できます。ここでは、「アクション」アイコンのオプションについて説明します。 
---
= SnapMirror関係アクション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「データ保護」タブの「SnapMirror関係」ページから関係を設定できます。ここでは、「アクション」アイコンのオプションについて説明します。

* *編集*: 関係に使用されるポリシーまたはスケジュールを編集します。
* *削除*: SnapMirror関係を削除します。この機能は宛先ボリュームを削除しません。
* *初期化*: 新しい関係を確立するために、データの最初の初期ベースライン転送を実行します。
* *更新*: 関係のオンデマンド更新を実行し、最後の更新以降に含まれた新しいデータとスナップショット コピーを宛先に複製します。
* *静止*: 関係のそれ以上の更新を防止します。
* *再開*: 休止中の関係を再開します。
* *Break*: 宛先ボリュームを読み取り/書き込み可能にし、現在および将来の転送をすべて停止します。逆再同期操作によって元のソース ボリュームが読み取り専用になるため、クライアントが元のソース ボリュームを使用していないことを確認します。
* *再同期*: 切断された関係を、切断が発生する前と同じ方向に再確立します。
* *逆再同期*: 反対方向の新しい関係を作成して初期化するために必要な手順を自動化します。これは、既存の関係が壊れた状態にある場合にのみ実行できます。この操作では現在の関係は削除されません。元のソース ボリュームは最新の共通スナップショット コピーに戻り、宛先と再同期されます。最後に成功したSnapMirror更新以降に元のソース ボリュームに加えられた変更はすべて失われます。現在の宛先ボリュームに加えられた変更や、現在の宛先ボリュームに書き込まれた新しいデータは、元のソース ボリュームに送り返されます。
* *中止*: 進行中の転送をキャンセルします。中止された関係に対してSnapMirror更新が発行された場合、関係は中止が発生する前に作成された最後の再開チェックポイントからの最後の転送から続行されます。

