---
permalink: storage/reference_per_node_cluster_settings_details.html 
sidebar: sidebar 
keywords: nodes, changing cluster settings, per-node UI 
summary: クラスタ構成後にストレージ ノードのクラスタ設定を確認し、ノードのホスト名を変更できます。 
---
= ノードごとのUIからのクラスタ設定の詳細
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタ構成後にストレージ ノードのクラスタ設定を確認し、ノードのホスト名を変更できます。

次のリストは、ノードごとのUIの*クラスタ設定*ページから示されるストレージノードのクラスタ設定について説明しています。 (`https://<node_IP>:442/hcc/node/cluster-settings`）。

* *役割*
+
クラスター内でのノードの役割。有効な値は次のとおりです。

+
** ストレージ: ストレージまたはファイバー チャネル ノード。
** 管理: ノードは管理ノードです。


* *ホスト名*
+
ノードの名前。

* *クラスタ*
+
クラスタの名前。

* *クラスターメンバーシップ*
+
ノードの状態。有効な値は次のとおりです。

+
** 使用可能: ノードには関連付けられたクラスター名がなく、まだクラスターの一部ではありません。
** 保留中: ノードは構成されており、指定されたクラスターに追加できます。ノードにアクセスするために認証は必要ありません。
** PendingActive: システムはノードに互換性のあるソフトウェアをインストール中です。完了すると、ノードはアクティブ状態に移行します。
** アクティブ: ノードはクラスターに参加しています。ノードを変更するには認証が必要です。


* *バージョン*
+
ノード上で実行されている Element ソフトウェアのバージョン。

* *アンサンブル*
+
データベース アンサンブルの一部であるノード。

* *ノードID*
+
ノードがクラスターに追加されるときに割り当てられる ID。

* *クラスターインターフェース*
+
クラスター通信に使用されるネットワーク インターフェイス。

* *管理インターフェース*
+
管理ネットワーク インターフェイス。デフォルトでは Bond1G になりますが、Bond10G も使用できます。

* *ストレージインターフェース*
+
Bond10G を使用したストレージ ネットワーク インターフェイス。

* *暗号化対応*
+
ノードがドライブ暗号化をサポートしているかどうかを示します。


