---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: システムは複数の種類のイベントを報告します。各イベントはシステムが完了した操作です。イベントには、日常的なイベント、通常のイベント、または管理者の注意を必要とするイベントが含まれます。  「イベント ログ」ページの「イベント タイプ」列には、システムのどの部分でイベントが発生したかが示されます。 
---
= イベントの種類
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムは複数の種類のイベントを報告します。各イベントはシステムが完了した操作です。イベントには、日常的なイベント、通常のイベント、または管理者の注意を必要とするイベントが含まれます。  「イベント ログ」ページの「イベント タイプ」列には、システムのどの部分でイベントが発生したかが示されます。


NOTE: システムは、読み取り専用 API コマンドをイベント ログに記録しません。

次のリストは、イベント ログに表示されるイベントの種類を示しています。

* *apiイベント*
+
設定を変更する、API または Web UI を通じてユーザーによって開始されたイベント。

* *binAssignmentsEvent*
+
データ ビンの割り当てに関連するイベント。ビンは基本的にデータを保持し、クラスター全体にマップされるコンテナーです。

* *binSyncイベント*
+
ブロック サービス間でのデータの再割り当てに関連するシステム イベント。

* *bsチェックイベント*
+
ブロック サービス チェックに関連するシステム イベント。

* *bsキルイベント*
+
ブロック サービスの終了に関連するシステム イベント。

* *バルクオペレーションイベント*
+
バックアップ、復元、スナップショット、クローンなど、ボリューム全体に対して実行された操作に関連するイベント。

* *クローンイベント*
+
ボリュームのクローン作成に関連するイベント。

* *クラスターマスターイベント*
+
クラスターの初期化時、またはノードの追加や削除など、クラスターの構成変更時に表示されるイベント。

* [[csum_event]]*cSumEvent*
+
エンドツーエンドのチェックサム検証中にチェックサムの不一致が検出されたことに関係するイベント。

+
チェックサムの不一致を検出したサービスは自動的に停止され、このイベントの生成後に再起動されません。

* *データイベント*
+
データの読み取りと書き込みに関連するイベント。

* *dbイベント*
+
クラスター内のアンサンブル ノードによって維持されるグローバル データベースに関連するイベント。

* *ドライブイベント*
+
ドライブ操作に関連するイベント。

* *保存時の暗号化イベント*
+
クラスター上の暗号化プロセスに関連するイベント。

* *アンサンブルイベント*
+
アンサンブル内のノードの数の増加または減少に関連するイベント。

* *ファイバーチャネルイベント*
+
ノードの構成と接続に関連するイベント。

* *gcイベント*
+
プロセスに関連するイベントは、ブロック ドライブ上のストレージを再利用するために 60 分ごとに実行されます。このプロセスはガベージコレクションとも呼ばれます。

* *ieイベント*
+
内部システムエラーです。

* *インストールイベント*
+
自動ソフトウェアインストールイベント。保留中のノードにソフトウェアが自動的にインストールされています。

* *iSCSIイベント*
+
システム内の iSCSI の問題に関連するイベント。

* *制限イベント*
+
アカウント内またはクラスター内のボリュームまたは仮想ボリュームの数が許可された最大値に近づいていることに関連するイベント。

* *メンテナンスモードイベント*
+
ノードの無効化など、ノードメンテナンスモードに関連するイベント。

* [[ネットワークイベント]]*ネットワークイベント*
+
各物理ネットワーク インターフェイス カード (NIC) インターフェイスのネットワーク エラー レポートに関連するイベント。

+
これらのイベントは、10 分間の監視間隔中にインターフェイスのエラー数がデフォルトのしきい値 1000 を超えたときにトリガーされます。これらのイベントは、受信ミス、巡回冗長検査 (CRC) エラー、長さエラー、オーバーラン エラー、フレーム エラーなどのネットワーク エラーに適用されます。

* *プラットフォームハードウェアイベント*
+
ハードウェア デバイスで検出された問題に関連するイベント。

* *リモートクラスタイベント*
+
リモート クラスターのペアリングに関連するイベント。

* *スケジューライベント*
+
スケジュールされたスナップショットに関連するイベント。

* *サービスイベント*
+
システム サービスのステータスに関連するイベント。

* *スライスイベント*
+
メタデータ ドライブまたはボリュームの削除など、スライス サーバーに関連するイベント。

+
スライスの再割り当てイベントには 3 つの種類があり、ボリュームが割り当てられているサービスに関する情報が含まれます。

+
** フリップ：プライマリサービスを新しいプライマリサービスに変更する
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 移動: セカンダリ サービスを新しいセカンダリ サービスに変更する
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** プルーニング: サービスセットからボリュームを削除する
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* *snmpトラップイベント*
+
SNMP トラップに関連するイベント。

* *統計イベント*
+
システム統計に関連するイベント。

* *tsイベント*
+
システム トランスポート サービスに関連するイベント。

* *予期しない例外*
+
予期しないシステム例外に関連するイベント。

* *ureEvent*
+
ストレージ デバイスからの読み取り中に発生する回復不可能な読み取りエラーに関連するイベント。

* *vasaプロバイダーイベント*
+
VASA (vSphere APIs for Storage Awareness) プロバイダーに関連するイベント。


