---
permalink: storage/task_data_protection_edit_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, edit, modify 
summary: 既存のスナップショット スケジュールを変更できます。変更後、次にスケジュールを実行するときには更新された属性が使用されます。元のスケジュールで作成されたスナップショットはストレージ システムに残ります。 
---
= スナップショットスケジュールを編集する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のスナップショット スケジュールを変更できます。変更後、次にスケジュールを実行するときには更新された属性が使用されます。元のスケジュールで作成されたスナップショットはストレージ システムに残ります。

.手順
. *データ保護* > *スケジュール*をクリックします。
. 変更したいスケジュールの*アクション*アイコンをクリックします。
. 表示されたメニューで、[*編集*] をクリックします。
. *ボリューム ID CSV* フィールドで、スナップショット操作に現在含まれている単一のボリューム ID またはボリューム ID のコンマ区切りリストを変更します。
. スケジュールを一時停止または再開するには、次のオプションから選択します。
+
** アクティブなスケジュールを一時停止するには、[*手動でスケジュールを一時停止*] リストから [*はい*] を選択します。
** 一時停止したスケジュールを再開するには、[*手動でスケジュールを一時停止*] リストから [*いいえ*] を選択します。


. 必要に応じて、「*新しいスケジュール名*」フィールドにスケジュールの別の名前を入力します。
. 週または月の異なる曜日に実行するようにスケジュールを変更するには、「*スケジュール タイプ*」を選択し、表示されるオプションからスケジュールを変更します。
. *オプション:* スナップショット スケジュールを無期限に繰り返すには、*定期的なスケジュール* を選択します。
. *オプション:* [新しいスナップショット名] フィールドに新しいスナップショットの名前を入力または変更します。
+
フィールドを空白のままにすると、スナップショットの作成日時が名前として使用されます。

. *オプション:* 親ボリュームがペアリングされているときにスナップショットがレプリケーションでキャプチャされるようにするには、[ペアリング時にスナップショットをレプリケーションに含める] チェックボックスをオンにします。
. 保持設定を変更するには、次のオプションから選択します。
+
** スナップショットをシステムに無期限に保持するには、[永久に保存] をクリックします。
** *[保存期間の設定]* をクリックし、日付スピン ボックスを使用して、システムがスナップショットを保持する期間を選択します。


. *変更を保存*をクリックします。

