---
permalink: storage/task_system_manage_nodes_view_individual_node_details.html 
sidebar: sidebar 
keywords: nodes, view, details, vlan, mip, cip, sip, virtual id 
summary: 'サービス タグ、ドライブの詳細、使用率とドライブの統計のグラフなど、個々のノードの詳細を表示できます。  [クラスター] タブの [ノード] ページには、各ノードのソフトウェア バージョンを表示できる [バージョン] 列があります。' 
---
= ノードの詳細を表示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービス タグ、ドライブの詳細、使用率とドライブの統計のグラフなど、個々のノードの詳細を表示できます。  [クラスター] タブの [ノード] ページには、各ノードのソフトウェア バージョンを表示できる [バージョン] 列があります。

.手順
. *クラスター* > *ノード*をクリックします。
. 特定のノードの詳細を表示するには、ノードの *アクション* アイコンをクリックします。
. *詳細を表示*をクリックします。
. ノードの詳細を確認します。
+
** *ノード ID*: ノードのシステム生成 ID。
** *ノード名*: ノードのホスト名。
** *ノード ロール*: クラスター内でのノードの役割。有効な値は次のとおりです。
+
*** クラスター マスター: クラスター全体の管理タスクを実行し、MVIP と SVIP を含むノード。
*** アンサンブル ノード: クラスターに参加するノード。クラスターのサイズに応じて、3 つまたは 5 つのアンサンブル ノードが存在します。
*** ファイバー チャネル: クラスター内のノード。


** *ノード タイプ*: ノードのモデル タイプ。
** *アクティブ ドライブ*: ノード内のアクティブ ドライブの数。
** *ノード使用率*: nodeHeat に基づくノード使用率のパーセンテージ。表示される値は、centrethPrimaryTotalHeat のパーセンテージです。  Element 12.8 以降で使用可能です。
** *管理 IP*: 1GbE または 10GbE ネットワーク管理タスク用にノードに割り当てられた管理 IP (MIP) アドレス。
** *クラスター IP*: 同じクラスター内のノード間の通信に使用される、ノードに割り当てられたクラスター IP (CIP) アドレス。
** *ストレージ IP*: iSCSI ネットワーク検出およびすべてのデータ ネットワーク トラフィックに使用されるノードに割り当てられたストレージ IP (SIP) アドレス。
** *管理 VLAN ID*: 管理ローカル エリア ネットワークの仮想 ID。
** *ストレージ VLAN ID*: ストレージ ローカル エリア ネットワークの仮想 ID。
** *バージョン*: 各ノードで実行されているソフトウェアのバージョン。
** *レプリケーション ポート*: リモート レプリケーション用のノードで使用されるポート。
** *サービス タグ*: ノードに割り当てられた一意のサービス タグ番号。
** *カスタム保護ドメイン*: ノードに割り当てられたカスタム保護ドメイン。



