---
permalink: storage/task_data_protection_create_a_group_snapshot.html 
sidebar: sidebar 
keywords: group snapshot, create, volumes, schedule, automate group snapshots 
summary: ボリュームのグループのスナップショットを作成できるほか、グループ スナップショットを自動化するグループ スナップショット スケジュールを作成することもできます。  1 つのグループ スナップショットでは、最大 32 個のボリュームを一度に一貫してスナップショットできます。 
---
= グループスナップショットの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームのグループのスナップショットを作成できるほか、グループ スナップショットを自動化するグループ スナップショット スケジュールを作成することもできます。  1 つのグループ スナップショットでは、最大 32 個のボリュームを一度に一貫してスナップショットできます。

.手順
. *管理* > *ボリューム*をクリックします。
. チェックボックスを使用して、ボリュームのグループに対して複数のボリュームを選択します。
. *一括操作*をクリックします。
. *グループスナップショット*をクリックします。
. [ボリュームのグループ スナップショットの作成] ダイアログ ボックスに新しいグループ スナップショット名を入力します。
. *オプション:* 親ボリュームがペアリングされているときに各スナップショットがレプリケーションでキャプチャされるようにするには、[ペアリング時に各グループ スナップショット メンバーをレプリケーションに含める] チェック ボックスをオンにします。
. グループ スナップショットの保持オプションを選択します。
+
** スナップショットをシステムに無期限に保持するには、[永久に保存] をクリックします。
** *[保存期間の設定]* をクリックし、日付スピン ボックスを使用して、システムがスナップショットを保持する期間を選択します。


. 単一の即時スナップショットを取得するには、次の手順を実行します。
+
.. *今すぐグループスナップショットを取得*をクリックします。
.. *グループスナップショットの作成*をクリックします。


. スナップショットを将来実行するようにスケジュールするには、次の手順を実行します。
+
.. *グループスナップショットスケジュールの作成*をクリックします。
.. *新しいスケジュール名*を入力します。
.. リストから*スケジュール タイプ*を選択します。
.. *オプション:* スケジュールされたスナップショットを定期的に繰り返すには、[定期的なスケジュール] チェックボックスをオンにします。
.. *スケジュールの作成*をクリックします。



