---
permalink: storage/task_data_protection_back_up_volume_to_solidfire.html 
sidebar: sidebar 
keywords: volume backup, solidfire storage cluster 
summary: Element ソフトウェアを実行しているストレージ クラスターの場合、クラスター上に存在するボリュームをリモート クラスターにバックアップできます。 
---
= SolidFireストレージクラスターにボリュームをバックアップする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element ソフトウェアを実行しているストレージ クラスターの場合、クラスター上に存在するボリュームをリモート クラスターにバックアップできます。

ソース クラスターとターゲット クラスターがペアになっていることを確認します。

見るlink:task_replication_pair_clusters.html["レプリケーション用のクラスタをペアリングする"]。

あるクラスターから別のクラスターにバックアップまたは復元する場合、システムはクラスター間の認証として使用されるキーを生成します。この一括ボリューム書き込みキーにより、ソース クラスターは宛先クラスターに対して認証を行うことができ、宛先ボリュームへの書き込み時に一定レベルのセキュリティが提供されます。バックアップまたは復元プロセスの一環として、操作を開始する前に、宛先ボリュームから一括ボリューム書き込みキーを生成する必要があります。

. 宛先クラスターで、*管理* > *ボリューム*。
. 宛先ボリュームのアクション アイコンをクリックします。
. 表示されるメニューで、[復元元] をクリックします。
. *統合復元*ダイアログボックスの*復元元*で* SolidFire*を選択します。
. *データ形式*のオプションを選択します。
+
** *ネイティブ*: SolidFireストレージ システムでのみ読み取り可能な圧縮形式。
** *非圧縮*: 他のシステムと互換性のある非圧縮形式。


. *キーの生成*をクリックします。
. *一括ボリューム書き込みキー* ボックスからキーをクリップボードにコピーします。
. ソース クラスターで、[*管理*] > [*ボリューム*] に移動します。
. バックアップするボリュームのアクション アイコンをクリックします。
. 表示されるメニューで、[バックアップ先] をクリックします。
. *統合バックアップ* ダイアログボックスの *バックアップ先* で、 * SolidFire* を選択します。
. *データ形式*フィールドで先ほど選択したのと同じオプションを選択します。
. *リモート クラスター MVIP* フィールドに、宛先ボリュームのクラスターの管理仮想 IP アドレスを入力します。
. *リモート クラスター ユーザー名* フィールドにリモート クラスター ユーザー名を入力します。
. *リモート クラスター パスワード* フィールドにリモート クラスター パスワードを入力します。
. *一括ボリューム書き込みキー* フィールドに、先ほど宛先クラスターで生成したキーを貼り付けます。
. *読み取りを開始*をクリックします。

