---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: ネットワーク設定の変更は、ネットワーク構成にコミットした後にテストできます。テストを実行して、ストレージ ノードが安定しており、問題なくオンラインにできることを確認できます。 
---
= ノードごとのUIを使用してシステムテストを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワーク設定の変更は、ネットワーク構成にコミットした後にテストできます。テストを実行して、ストレージ ノードが安定しており、問題なくオンラインにできることを確認できます。

ストレージ ノードのノードごとの UI にログインしました。

. *システムテスト*をクリックします。
. 実行するテストの横にある *テストを実行* をクリックするか、 *すべてのテストを実行* を選択します。
+

NOTE: すべてのテスト操作を実行すると時間がかかる可能性があるため、 NetAppサポートの指示に従ってのみ実行する必要があります。

+
** *接続されたアンサンブルのテスト*
+
データベース アンサンブルへの接続をテストおよび検証します。デフォルトでは、テストではノードが関連付けられているクラスターのアンサンブルが使用されます。あるいは、接続性をテストするために別のアンサンブルを提供することもできます。

** *テストコネクトMvip*
+
指定された管理仮想 IP (MVIP) アドレスを ping し、MVIP への簡単な API 呼び出しを実行して接続を確認します。デフォルトでは、テストではノードが関連付けられているクラスターの MVIP が使用されます。

** *テスト接続Svip*
+
ネットワーク アダプタに設定された最大転送単位 (MTU) サイズに一致するインターネット制御メッセージ プロトコル (ICMP) パケットを使用して、指定されたストレージ仮想 IP (SVIP) アドレスを ping します。次に、iSCSI イニシエーターとして SVIP に接続します。デフォルトでは、テストではノードが関連付けられているクラスターの SVIP が使用されます。

** *ハードウェア構成のテスト*
+
すべてのハードウェア構成が正しいことをテストし、ファームウェア バージョンが正しいことを検証し、すべてのドライブが適切にインストールされ、動作していることを確認します。これは工場でのテストと同じです。

+

NOTE: このテストはリソースを大量に消費するため、 NetAppサポートから要求された場合にのみ実行する必要があります。

** *ローカル接続のテスト*
+
各ノードのクラスター IP (CIP) を ping して、クラスター内の他のすべてのノードへの接続をテストします。このテストは、ノードがアクティブなクラスターの一部である場合にのみノード上に表示されます。

** *クラスターの位置特定テスト*
+
ノードがクラスター構成で指定されたクラスターを見つけられることを検証します。

** *ネットワーク構成のテスト*
+
構成されたネットワーク設定がシステムで使用されているネットワーク設定と一致していることを確認します。このテストは、ノードがクラスターにアクティブに参加しているときにハードウェア障害を検出することを目的としたものではありません。

** *テストPing*
+
指定されたホストのリストに ping を実行します。または、何も指定されていない場合は、クラスター内のすべての登録済みノードのリストを動的に構築し、各ノードに ping を実行して単純な接続を確立します。

** *リモート接続のテスト*
+
各ノードのクラスター IP (CIP) を ping して、リモートでペアリングされたクラスター内のすべてのノードへの接続をテストします。このテストは、ノードがアクティブなクラスターの一部である場合にのみノード上に表示されます。




