---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: ストレージ ノードのノードごとの UI を使用して、サポート バンドルを作成または削除したり、ドライブの構成設定をリセットしたり、ネットワーク サービスまたはクラスター サービスを再起動したりすることができます。 
---
= ノードごとのUIを使用してシステムユーティリティを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ ノードのノードごとの UI を使用して、サポート バンドルを作成または削除したり、ドライブの構成設定をリセットしたり、ネットワーク サービスまたはクラスター サービスを再起動したりすることができます。

ストレージ ノードのノードごとの UI にログインしました。

. *システムユーティリティ*をクリックします。
. 実行するシステム ユーティリティのボタンをクリックします。
+
** *コントロールパワー*
+
ノードを再起動、電源サイクル、またはシャットダウンします。

+

IMPORTANT: この操作により、ネットワーク接続が一時的に失われます。

+
次のパラメータを指定します。

+
*** アクション: オプションには、再起動と停止 (電源オフ) が含まれます。
*** ウェイクアップ遅延: ノードがオンラインに戻るまでの追加時間。


** *ノードログを収集する*
+
ノードの /tmp/bundles ディレクトリの下にサポート バンドルを作成します。

+
次のパラメータを指定します。

+
*** バンドル名: 作成された各サポート バンドルの一意の名前。名前が指定されていない場合は、「supportbundle」とノード名がファイル名として使用されます。
*** 追加引数: このパラメーターは sf_make_support_bundle スクリプトに渡されます。このパラメータは、NetAppサポートから指示された場合にのみ使用します。
*** タイムアウト秒数: 個々の ping 応答を待機する秒数を指定します。


** *ノードログを削除*
+
*Create Cluster Support Bundle* または CreateSupportBundle API メソッドを使用して作成された、ノード上の現在のサポート バンドルを削除します。

** *ドライブをリセット*
+
ドライブを初期化し、現在ドライブ上にあるすべてのデータを削除します。既存のノードまたはアップグレードされたノードでドライブを再利用できます。

+
次のパラメータを指定します。

+
*** ドライブ: リセットするデバイス名 (ドライブ ID ではありません) のリスト。


** *ネットワーク設定をリセット*
+
個々のノードのネットワーク構成の問題を解決し、個々のノードのネットワーク構成を工場出荷時のデフォルト設定にリセットします。

** *ノードをリセット*
+
ノードを工場出荷時の設定にリセットします。この操作中、すべてのデータは削除されますが、ノードのネットワーク設定は保持されます。ノードは、クラスターに割り当てられておらず、使用可能な状態にある場合にのみリセットできます。

+

IMPORTANT: このオプションを使用すると、すべてのデータ、パッケージ (ソフトウェア アップグレード)、構成、およびログ ファイルがノードから削除されます。

** *ネットワークを再起動*
+
ノード上のすべてのネットワーク サービスを再起動します。

+

IMPORTANT: この操作により、ネットワーク接続が一時的に失われる可能性があります。

** *サービスを再起動*
+
ノード上の Element ソフトウェア サービスを再起動します。

+

IMPORTANT: この操作により、一時的なノード サービスの中断が発生する可能性があります。この処理は、NetAppサポートから指示があった場合にのみ実行してください。

+
次のパラメータを指定します。

+
*** サービス: 再起動するサービス名。
*** アクション: サービスで実行するアクション。オプションには、開始、停止、再起動が含まれます。





