---
permalink: storage/task_monitor_system_alerts.html 
sidebar: sidebar 
keywords: system alerts, view, cluster faults, system errors 
summary: クラスターの障害やシステム内のエラーに関する情報のアラートを表示できます。アラートは情報、警告、またはエラーであり、クラスターの実行状況を示す優れた指標となります。ほとんどのエラーは自動的に解決されます。 
---
= システムアラートを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスターの障害やシステム内のエラーに関する情報のアラートを表示できます。アラートは情報、警告、またはエラーであり、クラスターの実行状況を示す優れた指標となります。ほとんどのエラーは自動的に解決されます。

ListClusterFaults API メソッドを使用して、アラート監視を自動化できます。これにより、発生したすべてのアラートについて通知を受けることができます。

. Element UI で、*レポート* > *アラート* を選択します。
+
システムはページ上のアラートを 30 秒ごとに更新します。

+
イベントごとに次の情報が表示されます。

+
|===


| 項目 | 説明 


 a| 
ID
 a| 
クラスターアラートに関連付けられた一意の ID。



 a| 
重大度
 a| 
アラートの重要度。有効な値は次のとおりです。

** 警告: すぐに対処が必要になる可能性のある軽微な問題です。システムのアップグレードは引き続き許可されます。
** エラー: パフォーマンスの低下や高可用性 (HA) の損失を引き起こす可能性がある障害。通常、エラーはそれ以外の場合にはサービスに影響を与えません。
** 重大: サービスに影響する重大な障害。システムは API またはクライアント I/O 要求を処理できません。この状態で操作すると、データが失われる可能性があります。
** bestPractice: 推奨されるシステム構成のベストプラクティスが使用されていません。




 a| 
タイプ
 a| 
障害が影響を与えるコンポーネント。ノード、ドライブ、クラスター、サービス、またはボリュームになります。



 a| 
ノード
 a| 
この障害が参照するノードのノード ID。ノードおよびドライブの障害の場合は含まれ、それ以外の場合は - (ダッシュ) に設定されます。



 a| 
ドライブ ID
 a| 
この障害が関係するドライブのドライブ ID。ドライブ障害の場合は含まれ、それ以外の場合は - (ダッシュ) に設定されます。



 a| 
エラー コード
 a| 
障害の原因を示す説明コード。



 a| 
詳細
 a| 
追加の詳細を含む障害の説明。



 a| 
日付
 a| 
障害が記録された日時。

|===
. 個々のアラートの「詳細を表示」をクリックすると、そのアラートに関する情報が表示されます。
. ページ上のすべてのアラートの詳細を表示するには、[詳細] 列をクリックします。
+
システムがアラートを解決すると、解決日を含むアラートに関するすべての情報が「解決済み」領域に移動されます。





== 詳細情報の参照

* xref:reference_monitor_cluster_fault_codes.adoc[クラスター障害コード]
* link:../api/concept_element_api_about_the_api.html["Element APIでストレージを管理する"]

