---
permalink: storage/task_data_manage_vol_access_group_create_an_initiator.html 
sidebar: sidebar 
keywords: initiator, create, fc, iscsi, aliases, chap 
summary: iSCSI またはファイバー チャネル イニシエーターを作成し、オプションでエイリアスを割り当てることができます。 
---
= イニシエーターを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI またはファイバー チャネル イニシエーターを作成し、オプションでエイリアスを割り当てることができます。

API 呼び出しを使用して、イニシエータベースの CHAP 属性を割り当てることもできます。イニシエーターごとにCHAPアカウント名と資格情報を追加するには、 `CreateInitiator` CHAP アクセスと属性を削除および追加するための API 呼び出し。イニシエータのアクセスは、1つ以上の仮想ネットワークIDを1つ以上指定することで、1つ以上のVLANに制限できます。 `CreateInitiators`そして `ModifyInitiators`API 呼び出し。仮想ネットワークが指定されていない場合、イニシエーターはすべてのネットワークにアクセスできます。

詳細については、API リファレンス情報を参照してください。 link:../api/concept_element_api_about_the_api.html["Element APIでストレージを管理する"]

.手順
. *管理* > *イニシエーター*をクリックします。
. *イニシエーターの作成*をクリックします。
. 単一のイニシエーターまたは複数のイニシエーターを作成するには、次の手順を実行します。
+
[cols="25,75"]
|===
| オプション | 手順 


 a| 
単一のイニシエーターを作成する
 a| 
.. *単一イニシエーターの作成*をクリックします。
.. *IQN/WWPN* フィールドにイニシエーターの IQN または WWPN を入力します。
.. *エイリアス* フィールドにイニシエーターのフレンドリ名を入力します。
.. *イニシエーターの作成*をクリックします。




 a| 
複数のイニシエーターを作成する
 a| 
.. *イニシエーターの一括作成*をクリックします。
.. テキスト ボックスに IQN または WWPN のリストを入力します。
.. *イニシエーターの追加*をクリックします。
.. 表示されたリストからイニシエーターを選択し、*エイリアス*列の対応する追加アイコンをクリックして、イニシエーターのエイリアスを追加します。
.. 新しいエイリアスを確認するには、チェックマークをクリックします。
.. *イニシエーターの作成*をクリックします。


|===

