---
permalink: storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html 
sidebar: sidebar 
keywords: volume pairings, paired volumes, replication source, assign 
summary: ボリュームをペアリングした後、ソース ボリュームとそのレプリケーション ターゲット ボリュームを割り当てる必要があります。レプリケーションのソースまたはターゲットは、ボリューム ペアのいずれかのボリュームにすることができます。また、この手順を使用して、ソース ボリュームが使用できなくなった場合に、ソース ボリュームに送信されたデータをリモート ターゲット ボリュームにリダイレクトすることもできます。 
---
= ペアボリュームにレプリケーションソースとターゲットを割り当てる
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームをペアリングした後、ソース ボリュームとそのレプリケーション ターゲット ボリュームを割り当てる必要があります。レプリケーションのソースまたはターゲットは、ボリューム ペアのいずれかのボリュームにすることができます。また、この手順を使用して、ソース ボリュームが使用できなくなった場合に、ソース ボリュームに送信されたデータをリモート ターゲット ボリュームにリダイレクトすることもできます。

.要件
ソース ボリュームとターゲット ボリュームを含むクラスターにアクセスできます。

.手順
. ソースボリュームを準備します。
+
.. ソースとして割り当てるボリュームを含むクラスターから、*管理* > *ボリューム* を選択します。
.. ソースとして割り当てるボリュームの*アクション*アイコンをクリックし、*編集*をクリックします。
.. *アクセス*ドロップダウンリストで、*読み取り/書き込み*を選択します。
+

IMPORTANT: ソースとターゲットの割り当てを元に戻す場合、このアクションにより、新しいレプリケーション ターゲットが割り当てられるまで、ボリューム ペアに次のメッセージが表示されます。 `PausedMisconfigured`

+
アクセスを変更すると、ボリュームのレプリケーションが一時停止され、データの転送が停止します。両方のサイトでこれらの変更が調整されていることを確認してください。

.. *変更を保存*をクリックします。


. ターゲットボリュームを準備します。
+
.. ターゲットとして割り当てるボリュームを含むクラスターから、*管理* > *ボリューム* を選択します。
.. ターゲットとして割り当てるボリュームのアクション アイコンをクリックし、*編集* をクリックします。
.. *アクセス* ドロップダウン リストで、*レプリケーション ターゲット* を選択します。
+

IMPORTANT: 既存のボリュームをレプリケーション ターゲットとして割り当てると、そのボリューム上のデータは上書きされます。データが含まれず、サイズ、512e 設定、QoS 構成など、ソース ボリュームとまったく同じ特性を持つ新しいターゲット ボリュームを使用する必要があります。ターゲット ボリュームのサイズはソース ボリュームと同等かそれ以上にすることができますが、それより小さくすることはできません。

.. *変更を保存*をクリックします。






== 詳細情報の参照

* xref:task_replication_pair_volumes_using_a_volume_id.adoc[ボリュームIDを使用してボリュームをペアリングする]
* xref:task_replication_pair_volumes_using_a_pairing_key.adoc[ペアリングキーを使用してボリュームをペアリングする]

