---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 安全なアクセスのために、イニシエーターをボリュームのコレクションにマッピングすることで、ボリューム アクセス グループを作成できます。その後、アカウントの CHAP イニシエーター シークレットとターゲット シークレットを使用して、グループ内のボリュームへのアクセスを許可できます。 
---
= ボリュームアクセスグループを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安全なアクセスのために、イニシエーターをボリュームのコレクションにマッピングすることで、ボリューム アクセス グループを作成できます。その後、アカウントの CHAP イニシエーター シークレットとターゲット シークレットを使用して、グループ内のボリュームへのアクセスを許可できます。

イニシエーターベースの CHAP を使用する場合は、ボリューム アクセス グループ内の単一のイニシエーターに対して CHAP 資格情報を追加して、セキュリティを強化できます。これにより、既存のボリューム アクセス グループにこのオプションを適用できるようになります。

.手順
. *管理* > *アクセス グループ*をクリックします。
. *アクセス グループの作成*をクリックします。
. *名前* フィールドにボリューム アクセス グループの名前を入力します。
. 次のいずれかの方法で、イニシエーターをボリューム アクセス グループに追加します。
+
[cols="25,75"]
|===
| オプション | 説明 


 a| 
ファイバーチャネルイニシエーターの追加
 a| 
.. [イニシエーターの追加] の下で、[バインドされていないファイバー チャネル イニシエーター] リストから既存のファイバー チャネル イニシエーターを選択します。
.. *FCイニシエーターの追加*をクリックします。
+

NOTE: この手順中に、*イニシエーターの作成*リンクをクリックし、イニシエーター名を入力して*作成*をクリックすると、イニシエーターを作成できます。イニシエーターを作成すると、システムによって自動的にイニシエーター リストに追加されます。



形式のサンプルは次のとおりです。

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
iSCSIイニシエーターの追加
 a| 
[イニシエーターの追加] で、[イニシエーター] リストから既存のイニシエーターを選択します。 *注:* [イニシエーターの作成] リンクをクリックし、イニシエーター名を入力して [作成] をクリックすると、この手順中にイニシエーターを作成できます。イニシエーターを作成すると、システムによってそのイニシエーターがイニシエーター リストに自動的に追加されます。

形式のサンプルは次のとおりです。

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: 各ボリュームのイニシエーター IQN は、[管理] > [ボリューム] > [アクティブ] リストのボリュームの [アクション] メニューで [詳細の表示] を選択すると見つかります。

イニシエーターを変更するときに、requiredCHAP 属性を True に切り替えることで、ターゲット イニシエーター シークレットを設定できるようになります。詳細については、ModifyInitiator API メソッドに関する API 情報を参照してください。

link:../api/concept_element_api_about_the_api.html["Element APIでストレージを管理する"]

|===
. *オプション:* 必要に応じてイニシエーターを追加します。
. [ボリュームの追加] で、[ボリューム] リストからボリュームを選択します。
+
ボリュームは「*接続されたボリューム*」リストに表示されます。

. *オプション:* 必要に応じてボリュームを追加します。
. *アクセス グループの作成*をクリックします。




== 詳細情報の参照

xref:task_data_manage_vol_access_group_add_volumes.adoc[アクセスグループにボリュームを追加する]
