---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: 追加のストレージが必要になったとき、またはクラスターの作成後に、クラスターにノードを追加できます。ノードは、初めて電源を入れるときに初期構成が必要です。ノードが設定されると、保留中のノードのリストに表示され、クラスターに追加できるようになります。 
---
= クラスターにノードを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
追加のストレージが必要になったとき、またはクラスターの作成後に、クラスターにノードを追加できます。ノードは、初めて電源を入れるときに初期構成が必要です。ノードが設定されると、保留中のノードのリストに表示され、クラスターに追加できるようになります。

クラスター内の各ノードのソフトウェア バージョンは互換性がある必要があります。クラスタにノードを追加すると、クラスタは必要に応じて新しいノードにNetApp Elementソフトウェアのクラスタ バージョンをインストールします。

既存のクラスターに、より小さい容量またはより大きい容量のノードを追加できます。容量の拡張を可能にするために、クラスターにさらに大きなノード容量を追加できます。小さなノードが含まれるクラスターに、大きなノードを追加する場合は、ペアで追加する必要があります。これにより、大規模なノードの 1 つに障害が発生した場合でも、Double Helix がデータを移動するのに十分なスペースが確保されます。パフォーマンスを向上させるために、より大きなノード クラスターに小さなノード容量を追加できます。


NOTE: 新しく追加されたノードがクラスターの総容量の 50% 以上を占める場合、このノードの容量の一部は使用不可 (「取り残される」) になり、容量ルールに準拠します。ストレージが追加されるまで、この状態は続きます。容量ルールにも従わない非常に大きなノードが追加された場合、以前に取り残されていたノードは取り残されなくなりますが、新しく追加されたノードは取り残されます。このような事態を回避するには、容量を常にペアで追加する必要があります。ノードが孤立すると、strandedCapacity クラスター障害がスローされます。

https://www.youtube.com/embed/2smVHWkikXY?rel=0["NetAppのビデオ: Scale on Your Terms: Expanding a SolidFire Cluster"^]

NetApp HCIアプライアンスにノードを追加できます。

.手順
. *クラスター* > *ノード*を選択します。
. 保留中のノードのリストを表示するには、「*保留中*」をクリックします。
+
ノードの追加プロセスが完了すると、アクティブ ノード リストに表示されます。それまでは、保留中のノードは「保留中のアクティブ」リストに表示されます。

+
SolidFire は、保留中のノードをクラスターに追加すると、そのクラスターの Element ソフトウェア バージョンを保留中のノードにインストールします。これには数分かかる場合があります。

. 次のいずれかを実行します。
+
** 個々のノードを追加するには、追加するノードの *アクション* アイコンをクリックします。
** 複数のノードを追加するには、追加するノードのチェックボックスをオンにして、[*一括操作*] を選択します。 *注:* 追加するノードに、クラスターで実行されているバージョンとは異なるバージョンの Element ソフトウェアがある場合、クラスターは、クラスター マスターで実行されている Element ソフトウェアのバージョンにノードを非同期的に更新します。ノードが更新されると、ノードは自動的にクラスターに追加されます。この非同期プロセス中、ノードは pendingActive 状態になります。


. *[追加]*をクリックします。
+
ノードがアクティブ ノードのリストに表示されます。





== 詳細情報の参照

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[ノードのバージョン管理と互換性]
