---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: クラスターの回復力を向上させるために、カスタム保護ドメインを構成できます。 
---
= カスタム保護ドメインを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2 つ以上のストレージ ノードを含む Element クラスターの場合、各ノードに対してカスタム保護ドメインを構成できます。カスタム保護ドメインを構成する場合は、クラスター内のすべてのノードをドメインに割り当てる必要があります。


TIP: 保護ドメインを割り当てると、ノード間のデータ同期が開始され、データ同期が完了するまで一部のクラスター操作は利用できなくなります。クラスターにカスタム保護ドメインを構成した後、新しいストレージ ノードを追加すると、そのノードに保護ドメインを割り当ててデータ同期が完了するまで、新しいノードにドライブを追加することはできません。訪問link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["保護ドメインのドキュメント"]保護ドメインについて詳しくは、こちらをご覧ください。


NOTE: カスタム保護ドメイン スキームをクラスターで有効にするには、各シャーシ内のすべてのストレージ ノードを同じカスタム保護ドメインに割り当てる必要があります。これを実現するには、必要な数のカスタム保護ドメインを作成する必要があります (可能な最小のカスタム保護ドメイン スキームは 3 つのドメインです)。ベスト プラクティスとして、ドメインごとに同数のノードを構成し、特定のドメインに割り当てられる各ノードが同じタイプであることを確認します。

.手順
. *クラスター* > *ノード*をクリックします。
. *保護ドメインの構成*をクリックします。
+
*カスタム保護ドメインの構成* ウィンドウでは、現在構成されている保護ドメイン (存在する場合) と、個々のノードに対する保護ドメインの割り当てを確認できます。

. 新しいカスタム保護ドメインの名前を入力し、「作成」をクリックします。
+
作成する必要があるすべての新しい保護ドメインに対してこの手順を繰り返します。

. *ノードの割り当て* リスト内の各ノードについて、*保護ドメイン* 列のドロップダウンをクリックし、そのノードに割り当てる保護ドメインを選択します。
+

CAUTION: 変更を適用する前に、ノードとシャーシのレイアウト、構成したカスタム保護ドメイン スキーム、およびそのスキームがデータ保護に与える影響を理解していることを確認してください。保護ドメイン スキームを適用し、すぐに変更を加える必要がある場合は、構成の適用後にデータの同期が行われるため、変更を加えるまでに時間がかかることがあります。

. *保護ドメインの構成*をクリックします。


.結果
クラスターのサイズによっては、ドメイン間のデータ同期に時間がかかる場合があります。データ同期が完了すると、*クラスター* > *ノード* ページでカスタム保護ドメインの割り当てを表示でき、Element Web UI ダッシュボードの *カスタム保護ドメインの健全性* ペインにクラスターの保護ステータスが表示されます。

.起こりうるエラー
カスタム保護ドメイン構成を適用した後に表示される可能性があるエラーを次に示します。

|===


| エラー | 説明 | 解決策 


| SetProtectionDomainLayout に失敗しました: ProtectionDomainLayout により NodeID {9} が使用できなくなります。デフォルト名とデフォルト以外の名前を両方併用することはできません。 | ノードに保護ドメインが割り当てられていません。 | ノードに保護ドメインを割り当てます。 


| SetProtectionDomainLayout に失敗しました: 保護ドメイン タイプ「カスタム」が保護ドメイン タイプ「シャーシ」を分割します。 | マルチノード シャーシ内のノードには、シャーシ内の他のノードとは異なる保護ドメインが割り当てられます。 | シャーシ内のすべてのノードに同じ保護ドメインが割り当てられていることを確認します。 
|===


== 詳細情報の参照

* link:../concepts/concept_solidfire_concepts_data_protection.html#custom_pd["カスタム保護ドメイン"^]
* link:../api/concept_element_api_about_the_api.html["Element APIでストレージを管理する"^]

