---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: NetApp Element UI を使用して、元のソース ボリュームを再同期し、フェイルバックすることができます。このセクションは、元のソース ボリュームが失われたが、元のクラスターがまだそのまま残っているシナリオに適用されます。新しいクラスターに復元する方法については、 NetAppサポート サイトのドキュメントを参照してください。 
---
= ソースボリュームが存在しなくなった場合にフェイルバックを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element UI を使用して、元のソース ボリュームを再同期し、フェイルバックすることができます。このセクションは、元のソース ボリュームが失われたが、元のクラスターがまだそのまま残っているシナリオに適用されます。新しいクラスターに復元する方法については、 NetAppサポート サイトのドキュメントを参照してください。

.要件
* Element ボリュームとONTAPボリューム間のレプリケーション関係が切断されています。
* エレメントボリュームは回復不能に失われました。
* 元のボリューム名は「見つかりません」と表示されます。


.手順
. Element UI で、フェイルオーバーを実行するために解除した関係を見つけます。
+
*ベスト プラクティス:* 元の切断された関係のSnapMirrorポリシーとスケジュールの詳細をメモします。この情報は、関係を再作成するときに必要になります。

. *アクション*アイコンをクリックし、*逆再同期*をクリックします。
. 操作を確定します。
+

NOTE: 逆再同期操作では、元のソース ボリュームと宛先ボリュームの役割が逆になった新しい関係が作成されます (元の関係は維持されるため、2 つの関係が作成されます)。元のボリュームは存在しなくなったため、システムは元のソース ボリュームと同じボリューム名とボリューム サイズを持つ新しい Element ボリュームを作成します。新しいボリュームには、sm-recovery と呼ばれるデフォルトの QoS ポリシーが割り当てられ、sm-recovery と呼ばれるデフォルトのアカウントに関連付けられます。破棄された元のソース ボリュームを置き換えるには、 SnapMirrorによって作成されたすべてのボリュームのアカウントと QoS ポリシーを手動で編集する必要があります。

+
逆再同期操作の一環として、最新のスナップショットのデータが新しいボリュームに転送されます。宛先側のアクティブ ボリュームへのアクセスとデータの書き込みは引き続き実行できますが、後の手順で元のプライマリ関係を復元する前に、アクティブ ボリュームへのすべてのホストを切断し、 SnapMirror更新を実行する必要があります。逆再同期を完了し、宛先側のボリュームに接続されたアクティブなセッションがないこと、および最新のデータが元のプライマリ ボリュームにあることを確認したら、次の手順に進んでフェイルバックを完了し、元のプライマリ ボリュームを再アクティブ化します。

. 逆再同期操作中に作成された逆関係の *アクション* アイコンをクリックし、*解除* をクリックします。
. ソースボリュームが存在しない元の関係の*アクション*アイコンをクリックし、*削除*をクリックします。
. 手順 4 で解除した逆関係の *アクション* アイコンをクリックし、*逆再同期* をクリックします。
. これにより、ソースと宛先が反転され、元の関係と同じボリューム ソースとボリューム宛先を持つ関係が作成されます。
. *アクション*アイコンと*編集*をクリックして、メモした元の QoS ポリシーとスケジュール設定とこの関係を更新します。
. これで、手順 6 で逆再同期した逆の関係を安全に削除できるようになりました。




== 詳細情報の参照

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirrorフェイルバックシナリオ]
