---
permalink: storage/task_snapmirror_transfer_or_one_time_migration_from_ontap_to_element.html 
sidebar: sidebar 
keywords: element, ui, transfer, perform, source, volume, snapmirror, dr, disaster, recovery, one-time, migration 
summary: 通常、 NetApp Elementソフトウェアを実行しているSolidFireストレージ クラスターからONTAPソフトウェアへの災害復旧にSnapMirror を使用する場合、Element がソースで、 ONTAP が宛先になります。ただし、場合によっては、 ONTAPストレージ システムがソースとして機能し、Element が宛先として機能することもあります。 
---
= ONTAPからElementへの転送または1回限りの移行を実行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通常、 NetApp Elementソフトウェアを実行しているSolidFireストレージ クラスターからONTAPソフトウェアへの災害復旧にSnapMirror を使用する場合、Element がソースで、 ONTAP が宛先になります。ただし、場合によっては、 ONTAPストレージ システムがソースとして機能し、Element が宛先として機能することもあります。

* 2 つのシナリオが存在します。
+
** 以前の災害復旧関係は存在しません。この手順のすべてのステップに従ってください。
** 以前の災害復旧関係は存在しますが、この軽減策に使用されているボリューム間には存在しません。この場合は、以下の手順 3 と 4 のみに従ってください。




.要件
* ONTAPからElementデスティネーション ノードにアクセスできるようにしておく必要があります。
* ElementボリュームのSnapMirrorレプリケーションを有効にしておく必要があります。


Element の宛先パスは、hostip:/lun/<id_number> の形式で指定する必要があります。ここで、lun は実際の文字列 "`lun`" であり、id_number は Element ボリュームの ID です。

.手順
. ONTAPを使用して、Element クラスタとの関係を作成します。
+
[listing]
----
snapmirror create -source-path SVM:volume|cluster://SVM/volume
-destination-path hostip:/lun/name -type XDP -schedule schedule -policy
    policy
----
+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst
-destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
. ONTAP snapmirror show コマンドを使用して、 SnapMirror関係が作成されたことを確認します。
+
レプリケーション関係の作成に関する情報は、 ONTAP のドキュメントを参照してください。完全なコマンド構文については、 ONTAP のマニュアル ページを参照してください。

. 使用して `ElementCreateVolume`API を使用して、ターゲット ボリュームを作成し、ターゲット ボリュームのアクセス モードをSnapMirrorに設定します。
+
Element APIを使用してElementボリュームを作成する

+
[listing]
----
{
   "method": "CreateVolume",
   "params": {
        "name": "SMTargetVolumeTest2",
        "accountID": 1,
        "totalSize": 100000000000,
        "enable512e": true,
        "attributes": {},
        "qosPolicyID": 1,
        "enableSnapMirrorReplication": true,
        "access": "snapMirrorTarget"
    },
    "id": 1
}
----
. ONTAPを使用してレプリケーション関係を初期化する `snapmirror initialize`指示：
+
[listing]
----
snapmirror initialize -source-path hostip:/lun/name
-destination-path SVM:volume|cluster://SVM/volume
----

