---
permalink: storage/task_replication_pair_volumes.html 
sidebar: sidebar 
keywords: volume pairings, replication, cluster, cluster pair 
summary: クラスター ペア内のクラスター間の接続を確立したら、ペア内の一方のクラスター上のボリュームをもう一方のクラスター上のボリュームとペアリングできます。ボリュームのペアリング関係が確立されたら、どのボリュームがレプリケーションのターゲットであるかを特定する必要があります。 
---
= ペアボリューム
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスター ペア内のクラスター間の接続を確立したら、ペア内の一方のクラスター上のボリュームをもう一方のクラスター上のボリュームとペアリングできます。ボリュームのペアリング関係が確立されたら、どのボリュームがレプリケーションのターゲットであるかを特定する必要があります。

接続されたクラスター ペア内の異なるストレージ クラスターに保存されている 2 つのボリュームを、リアルタイム レプリケーション用にペアリングできます。 2 つのクラスターをペアリングした後、1 つのクラスター上のアクティブ ボリュームを 2 番目のクラスターに継続的にレプリケートするように構成して、継続的なデータ保護 (CDP) を提供できます。いずれかのボリュームをレプリケーションのソースまたはターゲットとして割り当てることもできます。

ボリュームのペアリングは常に 1 対 1 です。ボリュームが別のクラスター上のボリュームとペアリングされた後は、他のボリュームと再度ペアリングすることはできません。

.要件
* クラスター ペア内のクラスター間の接続を確立しました。
* ペアリングされる 1 つまたは両方のクラスターに対するクラスター管理者権限を持っています。


.手順
. xref:task_replication_create_a_target_volume_with_read_write_access.adoc[読み取りまたは書き込みアクセスを持つターゲットボリュームを作成する]
. xref:task_replication_pair_volumes_using_volume_id_or_pairing_key.adoc[ボリュームIDまたはペアリングキーを使用してボリュームをペアリングする]
. xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアボリュームにレプリケーションソースとターゲットを割り当てる]

