---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: ボリュームのスナップショットが指定された間隔で自動的に実行されるようにスケジュールを設定できます。 
---
= スナップショットスケジュールを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームのスナップショットが指定された間隔で自動的に実行されるようにスケジュールを設定できます。

スナップショット スケジュールを構成するときに、曜日または日付に基づいて時間間隔を選択できます。定期的なスケジュールを作成し、次のスナップショットが発生するまでの日数、時間、分を指定することもできます。

5 分で割り切れない時間帯にスナップショットを実行するようにスケジュールした場合、スナップショットは 5 分で割り切れる次の時間帯に実行されます。たとえば、スナップショットを 12:42:00 UTC に実行するようにスケジュールした場合、スナップショットは 12:45:00 UTC に実行されます。スナップショットを 5 分未満の間隔で実行するようにスケジュールすることはできません。

Element 12.5 以降では、連続作成を有効にして、UI から先入れ先出し (FIFO) 方式でスナップショットを保持するように選択できます。

* *シリアル作成を有効にする* オプションは、一度に 1 つのスナップショットのみが複製されることを指定します。以前のスナップショットのレプリケーションがまだ進行中の場合、新しいスナップショットの作成は失敗します。チェックボックスが選択されていない場合、別のスナップショットレプリケーションが進行中の場合でもスナップショットの作成が許可されます。
* *FIFO* オプションは、最新のスナップショットを一定数保持する機能を追加します。チェックボックスをオンにすると、スナップショットは FIFO ベースで保持されます。  FIFO スナップショットのキューが最大深度に達すると、新しい FIFO スナップショットが挿入されるときに最も古い FIFO スナップショットが破棄されます。


.手順
. *データ保護* > *スケジュール*を選択します。
. *スケジュールの作成*を選択します。
. *ボリューム ID CSV* フィールドに、スナップショット操作に含める単一のボリューム ID またはボリューム ID のコンマ区切りリストを入力します。
. 新しいスケジュール名を入力します。
. スケジュール タイプを選択し、提供されたオプションからスケジュールを設定します。
. *オプション:* スナップショット スケジュールを無期限に繰り返すには、*定期的なスケジュール* を選択します。
. *オプション:* [新しいスナップショット名] フィールドに新しいスナップショットの名前を入力します。
+
フィールドを空白のままにすると、スナップショットの作成日時が名前として使用されます。

. *オプション:* 親ボリュームがペアリングされているときにスナップショットがレプリケーションでキャプチャされるようにするには、[ペアリング時にスナップショットをレプリケーションに含める] チェックボックスをオンにします。
. *オプション:* 一度に 1 つのスナップショットのみが複製されるようにするには、[連続作成を有効にする] チェックボックスをオンにします。
. スナップショットの保持期間を設定するには、次のオプションから選択します。
+
** *オプション:* 最新のスナップショットを一定数保持するには、*FIFO (先入れ先出し)* チェックボックスをオンにします。
** スナップショットをシステム上に無期限に保持するには、「永久に保持」を選択します。
** *保存期間の設定*を選択し、日付スピンボックスを使用してシステムがスナップショットを保持する期間を選択します。


. *スケジュールの作成*を選択します。

