---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: リモート クラスターのクラスター管理者の資格情報を持っている場合は、ボリュームをリモート クラスター上の別のボリュームとペアリングできます。 
---
= ボリュームIDを使用してボリュームをペアリングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームをペアにする両方のクラスターに対するクラスター管理者アクセス権を持っている場合は、ボリュームをリモート クラスター上の別のボリュームとペアにすることができます。このメソッドは、リモート クラスター上のボリュームのボリューム ID を使用して接続を開始します。

.要件
* ボリュームを含むクラスターがペアになっていることを確認します。
* リモート クラスターに新しいボリュームを作成します。
+

NOTE: ペアリング プロセスの後に、レプリケーション ソースとターゲットを割り当てることができます。レプリケーションのソースまたはターゲットは、ボリューム ペアのいずれかのボリュームにすることができます。データが含まれず、サイズ、ボリュームのブロック サイズ設定 (512e または 4k)、QoS 構成など、ソース ボリュームとまったく同じ特性を持つターゲット ボリュームを作成する必要があります。既存のボリュームをレプリケーション ターゲットとして割り当てると、そのボリューム上のデータは上書きされます。ターゲット ボリュームのサイズはソース ボリュームと同等かそれ以上にすることができますが、それより小さくすることはできません。

* ターゲットボリューム ID を把握します。


.手順
. *管理* > *ボリューム*を選択します。
. ペアリングするボリュームの*アクション*アイコンをクリックします。
. *ペア*をクリックします。
. *ボリュームのペアリング*ダイアログボックスで、*ペアリングの開始*を選択します。
. リモート クラスターへのアクセス権があることを示すには、[*I Do*] を選択します。
. リストから*レプリケーション モード*を選択します。
+
** *リアルタイム (非同期)*: 書き込みは、ソース クラスターでコミットされた後にクライアントに確認応答されます。
** *リアルタイム (同期)*: 書き込みは、ソース クラスターとターゲット クラスターの両方でコミットされた後にクライアントに確認応答されます。
** *スナップショットのみ*: ソース クラスターで作成されたスナップショットのみが複製されます。ソース ボリュームからのアクティブな書き込みは複製されません。


. リストからリモート クラスターを選択します。
. リモート ボリューム ID を選択します。
. *ペアリングを開始*をクリックします。
+
システムは、リモート クラスターの Element UI に接続する Web ブラウザー タブを開きます。クラスター管理者の資格情報を使用してリモート クラスターにログオンする必要がある場合があります。

. リモート クラスターの Element UI で、[ペアリングの完了] を選択します。
. *ボリュームペアリングの確認*で詳細を確認します。
. *ペアリングを完了*をクリックします。
+
ペアリングを確認すると、2 つのクラスターはペアリングのためにボリュームを接続するプロセスを開始します。ペアリング プロセス中は、[ボリューム ペア] ウィンドウの [ボリューム ステータス] 列にメッセージが表示されます。ボリュームペアの表示 `PausedMisconfigured`ボリューム ペアのソースとターゲットが割り当てられるまで。

+
ペアリングが正常に完了したら、ボリューム テーブルを更新して、ペアリングされたボリュームの *アクション* リストから *ペア* オプションを削除することをお勧めします。テーブルを更新しない場合は、*ペア* オプションは選択可能なままになります。もう一度「ペアリング」オプションを選択すると、新しいタブが開き、ボリュームがすでにペアリングされているため、システムは `StartVolumePairing Failed: xVolumeAlreadyPaired`Element UI ページの *Pair Volume* ウィンドウにエラー メッセージが表示されます。





== 詳細情報の参照

* xref:reference_replication_volume_pairing_messages.adoc[ボリュームペアリングメッセージ]
* xref:reference_replication_volume_pairing_warnings.adoc[ボリュームペアリングの警告]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアボリュームにレプリケーションソースとターゲットを割り当てる]

