---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: SolidFireシステムはボリュームを使用してストレージをプロビジョニングします。ボリュームは、iSCSI またはファイバー チャネル クライアントによってネットワーク経由でアクセスされるブロック デバイスです。 
---
= ボリュームを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFireシステムはボリュームを使用してストレージをプロビジョニングします。ボリュームは、iSCSI またはファイバー チャネル クライアントによってネットワーク経由でアクセスされるブロック デバイスです。

[管理] タブの [ボリューム] ページから、ノード上のボリュームを作成、変更、複製、および削除できます。



== ボリュームの作成

ボリュームを作成し、そのボリュームを特定のアカウントに関連付けることができます。すべてのボリュームはアカウントに関連付ける必要があります。この関連付けにより、アカウントは CHAP 資格情報を使用して iSCSI イニシエーター経由でボリュームにアクセスできるようになります。

ボリュームの作成時に QoS 設定を指定できます。

. *管理* > *ボリューム*を選択します。
. *ボリュームの作成*をクリックします。
. *新しいボリュームの作成* ダイアログボックスで、*ボリューム名* を入力します。
. ボリュームの合計サイズを入力します。
+

NOTE: デフォルトのボリューム サイズの選択は GB 単位です。  GB または GiB 単位で測定されたサイズを使用してボリュームを作成できます。

+
** 1GB = 1 000 000 000 バイト
** 1GiB = 1 073 741 824 バイト


. ボリュームの*ブロック サイズ*を選択します。
. *アカウント*ドロップダウンリストをクリックし、ボリュームへのアクセス権を持つアカウントを選択します。
+
アカウントが存在しない場合は、「*アカウントの作成*」リンクをクリックし、新しいアカウント名を入力して、「*作成*」をクリックします。アカウントが作成され、新しいボリュームに関連付けられます。

+

NOTE: アカウントが 50 を超える場合、リストは表示されません。入力を開始すると、オートコンプリート機能によって選択可能な値が表示されます。

. *サービス品質*を設定するには、次のいずれかを実行します。
+
.. *ポリシー* の下で、既存の QoS ポリシーを選択できます (使用可能な場合)。
.. *カスタム設定* で、IOPS のカスタマイズされた最小値、最大値、バースト値を設定するか、デフォルトの QoS 値を使用します。
+
最大 IOPS 値またはバースト IOPS 値が 20,000 IOPS を超えるボリュームでは、単一のボリュームでこのレベルの IOPS を達成するために、高いキュー深度または複数のセッションが必要になる場合があります。



. *ボリュームの作成*をクリックします。




== ボリュームの詳細を表示

. *管理* > *ボリューム*を選択します。
. 詳細を確認します。
+
** *ID*: ボリュームのシステム生成 ID。
** *名前*: ボリュームの作成時に付けられた名前。
** *アカウント*: ボリュームに割り当てられたアカウントの名前。
** *アクセス グループ*: ボリュームが属するボリューム アクセス グループの名前。
** *アクセス*: ボリュームの作成時に割り当てられたアクセスの種類。有効な値は次のとおりです。
+
*** 読み取り/書き込み: すべての読み取りと書き込みが受け入れられます。
*** 読み取り専用: すべての読み取りアクティビティが許可されますが、書き込みは許可されません。
*** ロック済み: 管理者アクセスのみ許可されます。
*** ReplicationTarget: 複製されたボリューム ペア内のターゲット ボリュームとして指定されます。


** *使用済み*: ボリューム内の使用済み領域の割合。
** *サイズ*: ボリュームの合計サイズ (GB 単位)。
** *プライマリ ノード ID*: このボリュームのプライマリ ノード。
** *セカンダリ ノード ID*: このボリュームのセカンダリ ノードのリスト。セカンダリ ノードの変更などの一時的な状態では複数の値を取ることができますが、通常は 1 つの値になります。
** *QoS スロットル*: プライマリ ストレージ ノードの負荷が高いためにボリュームがスロットルされているかどうかを識別します。
** *QoS ポリシー*: ユーザー定義の QoS ポリシーの名前とリンク。
** *最小 IOPS*: ボリュームに保証される IOPS の最小数。
** *最大 IOPS*: ボリュームに許可される IOPS の最大数。
** *バースト IOPS*: ボリュームに対して短時間に許可される IOPS の最大数。デフォルト = 15,000。
** *スナップショット*: ボリュームに作成されたスナップショットの数。
** *属性*: API メソッドを通じてキー/値のペアとしてボリュームに割り当てられた属性。
** *512e*: ボリューム上で 512e が有効になっているかどうかを示します。有効な値は次のとおりです。
+
*** はい
*** いいえ


** *作成日*: ボリュームが作成された日時。






== 個々のボリュームの詳細を表示する

個々のボリュームのパフォーマンス統計を表示できます。

. *レポート* > *ボリューム パフォーマンス* を選択します。
. ボリューム リストで、ボリュームの [アクション] アイコンをクリックします。
. *詳細を表示*をクリックします。
+
ボリュームに関する一般情報を含むトレイがページの下部に表示されます。

. ボリュームの詳細情報を表示するには、[詳細を表示] をクリックします。
+
システムはボリュームの詳細情報とパフォーマンス グラフを表示します。





== アクティブボリュームを編集する

QoS 値、ボリューム サイズ、バイト値を計算する測定単位などのボリューム属性を変更できます。レプリケーションの使用やボリュームへのアクセスを制限するために、アカウント アクセスを変更することもできます。

次の条件下では、クラスターに十分なスペースがある場合は、ボリュームのサイズを変更できます。

* 通常の動作条件。
* ボリューム エラーまたは障害が報告されています。
* ボリュームのクローンを作成中です。
* ボリュームを再同期中です。


.手順
. *管理* > *ボリューム*を選択します。
. *アクティブ* ウィンドウで、編集するボリュームの [アクション] アイコンをクリックします。
. *編集*をクリックします。
. *オプション:* ボリュームの合計サイズを変更します。
+
** ボリュームのサイズを大きくすることはできますが、小さくすることはできません。 1 回のサイズ変更操作でサイズ変更できるのは 1 つのボリュームのみです。ガベージ コレクション操作やソフトウェアのアップグレードによってサイズ変更操作が中断されることはありません。
** レプリケーションのボリューム サイズを調整する場合は、まずレプリケーション ターゲットとして割り当てられたボリュームのサイズを増やす必要があります。その後、ソースボリュームのサイズを変更できます。ターゲット ボリュームのサイズはソース ボリュームと同等かそれ以上にすることができますが、それより小さくすることはできません。


+
デフォルトのボリューム サイズの選択は GB 単位です。  GB または GiB 単位で測定されたサイズを使用してボリュームを作成できます。

+
** 1GB = 1 000 000 000 バイト
** 1GiB = 1 073 741 824 バイト


. *オプション:* 次のいずれかの異なるアカウント アクセス レベルを選択します。
+
** 読み取り専用
** 読み取り / 書き込み
** ロック
** レプリケーション ターゲット


. *オプション:* ボリュームへのアクセス権を持つアカウントを選択します。
+
アカウントが存在しない場合は、[*アカウントの作成*] リンクをクリックし、新しいアカウント名を入力して、[*作成*] をクリックします。アカウントが作成され、ボリュームに関連付けられます。

+

NOTE: アカウントが 50 を超える場合、リストは表示されません。入力を開始すると、オートコンプリート機能によって選択可能な値が表示されます。

. *オプション:* *サービス品質*の選択を変更するには、次のいずれかを実行します。
+
.. *ポリシー* の下で、既存の QoS ポリシーを選択できます (使用可能な場合)。
.. *カスタム設定* で、IOPS のカスタマイズされた最小値、最大値、バースト値を設定するか、デフォルトの QoS 値を使用します。
+

NOTE: ボリュームで QoS ポリシーを使用している場合は、カスタム QoS を設定して、ボリュームと QoS ポリシーの関連付けを削除できます。カスタム QoS は、ボリューム QoS 設定の QoS ポリシー値を上書きして調整します。

+

TIP: IOPS 値を変更する場合は、数十または数百単位で増加する必要があります。入力値には有効な整数が必要です。

+

TIP: 非常に高いバースト値でボリュームを構成します。これにより、システムはボリュームの持続的な IOPS を制限しながら、時折発生する大きなブロックのシーケンシャル ワークロードをより迅速に処理できるようになります。



. *変更を保存*をクリックします。




== ボリュームを削除する

Element ストレージ クラスターから 1 つ以上のボリュームを削除できます。

削除されたボリュームはすぐにはパージされず、約8時間は使用可能な状態です。この間にリストアしたボリュームはオンラインに戻り、iSCSI接続が再度確立されます。

スナップショットの作成に使用されたボリュームが削除されると、それに関連付けられたスナップショットは非アクティブになります。削除されたソース ボリュームが消去されると、関連付けられている非アクティブなスナップショットもシステムから削除されます。


IMPORTANT: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード中に作成され、新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、ボリュームまたはそれに関連付けられたアカウントを変更または削除しないでください。

.手順
. *管理* > *ボリューム*を選択します。
. 単一のボリュームを削除するには、次の手順を実行します。
+
.. 削除するボリュームのアクション アイコンをクリックします。
.. 表示されたメニューで、[削除] をクリックします。
.. 操作を確定します。


+
システムはボリュームを「ボリューム」ページの「削除済み」領域に移動します。

. 複数のボリュームを削除するには、次の手順を実行します。
+
.. ボリュームのリストで、削除するボリュームの横にあるチェックボックスをオンにします。
.. *一括操作*をクリックします。
.. 表示されたメニューで、[削除] をクリックします。
.. 操作を確定します。
+
システムはボリュームを「ボリューム」ページの「削除済み」領域に移動します。







== 削除されたボリュームを復元する

ボリュームが削除されたがまだ消去されていない場合は、システム内のボリュームを復元できます。ボリュームは、削除されてから約 8 時間後に自動的に消去されます。システムによってボリュームが消去された場合は、復元することはできません。

. *管理* > *ボリューム*を選択します。
. 削除されたボリュームのリストを表示するには、「*削除済み*」タブをクリックします。
. 復元するボリュームのアクション アイコンをクリックします。
. 表示されたメニューで、[復元] をクリックします。
. 操作を確定します。
+
ボリュームは「アクティブ」ボリューム リストに配置され、ボリュームへの iSCSI 接続が復元されます。





== ボリュームをパージする

ボリュームがパージされると、システムから永久に削除されます。ボリューム内のすべてのデータが失われます。

システムは削除後 8 時間で削除されたボリュームを自動的に消去します。ただし、スケジュールされた時間の前にボリュームを消去したい場合は、そうすることができます。

. *管理* > *ボリューム*を選択します。
. *削除済み*ボタンをクリックします。
. 単一のボリュームまたは複数のボリュームを消去する手順を実行します。
+
[cols="25,75"]
|===
| オプション | 手順 


 a| 
単一ボリュームをパージする
 a| 
.. 消去するボリュームのアクション アイコンをクリックします。
.. *パージ*をクリックします。
.. 操作を確定します。




 a| 
複数のボリュームを消去する
 a| 
.. 消去するボリュームを選択します。
.. *一括操作*をクリックします。
.. 表示されるメニューで、「*パージ*」を選択します。
.. 操作を確定します。


|===




== ボリュームをクローニングする

単一ボリュームまたは複数ボリュームのクローンを作成して、データのポイントインタイム コピーを作成できます。ボリュームのクローンを作成すると、システムはボリュームのスナップショットを作成し、スナップショットによって参照されるデータのコピーを作成します。これは非同期プロセスであり、プロセスに必要な時間は、複製するボリュームのサイズと現在のクラスターの負荷によって異なります。

クラスターは、ボリュームごとに一度に最大 2 つの実行中のクローン要求と、一度に最大 8 つのアクティブなボリューム クローン操作をサポートします。これらの制限を超えるリクエストは、後で処理するためにキューに入れられます。


NOTE: オペレーティング システムによって、クローン ボリュームの処理方法が異なります。 VMware ESXi は、クローン ボリュームをボリューム コピーまたはスナップショット ボリュームとして扱います。ボリュームは、新しいデータストアを作成するために使用できるデバイスになります。クローンボリュームのマウントとスナップショットLUNの取り扱いの詳細については、VMwareのドキュメントを参照してください。 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["VMFSデータストアのコピーをマウントする"]そして https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["重複したVMFSデータストアの管理"]。


IMPORTANT: クローン ボリュームを小さいサイズにクローンして切り捨てる前に、パーティションが小さいボリュームに収まるように準備されていることを確認してください。

.手順
. *管理* > *ボリューム*を選択します。
. 単一のボリュームを複製するには、次の手順を実行します。
+
.. *アクティブ* ページのボリュームのリストで、複製するボリュームの [アクション] アイコンをクリックします。
.. 表示されたメニューで、「*クローン*」をクリックします。
.. *クローンボリューム* ウィンドウで、新しくクローンされたボリュームのボリューム名を入力します。
.. *ボリューム サイズ* スピン ボックスとリストを使用して、ボリュームのサイズと測定値を選択します。
+

NOTE: デフォルトのボリューム サイズの選択は GB 単位です。  GB または GiB 単位で測定されたサイズを使用してボリュームを作成できます。

+
*** 1GB = 1 000 000 000 バイト
*** 1GiB = 1 073 741 824 バイト


.. 新しくクローンされたボリュームのアクセス タイプを選択します。
.. *アカウント* リストから、新しく複製されたボリュームに関連付けるアカウントを選択します。
+

NOTE: *アカウントの作成*リンクをクリックし、アカウント名を入力して*作成*をクリックすると、この手順でアカウントを作成できます。アカウントを作成すると、システムによってそのアカウントが *アカウント* リストに自動的に追加されます。



. 複数のボリュームのクローンを作成するには、次の手順を実行します。
+
.. *アクティブ* ページのボリュームのリストで、複製するボリュームの横にあるボックスをオンにします。
.. *一括操作*をクリックします。
.. 表示されたメニューで、「*クローン*」を選択します。
.. *複数のボリュームの複製* ダイアログボックスで、*新しいボリューム名のプレフィックス* フィールドに複製されたボリュームのプレフィックスを入力します。
.. *アカウント* リストから、クローン ボリュームに関連付けるアカウントを選択します。
.. クローンボリュームのアクセスの種類を選択します。


. *クローンの開始*をクリックします。
+

NOTE: クローンのボリューム サイズを増やすと、ボリュームの最後に空き領域が追加された新しいボリュームが作成されます。ボリュームの使用方法によっては、空き領域を活用するためにパーティションを拡張したり、新しいパーティションを作成したりする必要がある場合があります。





== 詳細情報

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

