---
permalink: storage/task_replication_pair_cluster_using_pairing_key.html 
sidebar: sidebar 
keywords: remote replication, pairing key, pairing clusters 
summary: ローカル クラスターへのクラスター管理者アクセス権はあるが、リモート クラスターへのアクセス権がない場合は、ペアリング キーを使用してクラスターをペアリングできます。ペアリング キーはローカル クラスターで生成され、リモート サイトのクラスター管理者に安全に送信され、接続を確立して、リアルタイム レプリケーションのためのクラスター ペアリングを完了します。 
---
= ペアリングキーを使用してクラスターをペアリングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ローカル クラスターへのクラスター管理者アクセス権はあるが、リモート クラスターへのアクセス権がない場合は、ペアリング キーを使用してクラスターをペアリングできます。ペアリング キーはローカル クラスターで生成され、リモート サイトのクラスター管理者に安全に送信され、接続を確立して、リアルタイム レプリケーションのためのクラスター ペアリングを完了します。

. ローカル クラスターで、[*データ保護*] > [*クラスター ペア*] を選択します。
. *クラスターのペア*をクリックします。
. *ペアリングを開始*をクリックし、*いいえ*をクリックして、リモート クラスターへのアクセス権がないことを示します。
. *キーの生成*をクリックします。
+

NOTE: このアクションは、ペアリング用のテキスト キーを生成し、ローカル クラスター上に未構成のクラスター ペアを作成します。手順を完了しない場合は、クラスター ペアを手動で削除する必要があります。

. クラスターペアリングキーをクリップボードにコピーします。
. リモート クラスタ サイトのクラスタ管理者がペアリング キーにアクセスできるようにします。
+

NOTE: クラスター ペアリング キーには、リモート レプリケーションのボリューム接続を許可するための MVIP、ユーザー名、パスワード、およびデータベース情報のバージョンが含まれています。このキーは安全な方法で扱う必要があり、ユーザー名やパスワードへの偶発的または安全でないアクセスを可能にするような方法で保存しないでください。

+

IMPORTANT: ペアリング キーの文字を変更しないでください。キーが変更されると無効になります。

. リモート クラスターで、[*データ保護*] > [*クラスター ペア*] を選択します。
. *クラスターのペア*をクリックします。
. *ペアリングの完了*をクリックし、*ペアリング キー* フィールドにペアリング キーを入力します (貼り付けが推奨される方法です)。
. *ペアリングを完了*をクリックします。




== 詳細情報の参照

* xref:task_replication_pair_cluster_using_mvip.adoc[MVIPを使用してクラスターをペアリングする]
* https://www.youtube.com/watch?v=1ljHAd1byC8&feature=youtu.be["クラスター ペアリング キーを使用したクラスターのペアリング (ビデオ)"]

