---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'ノードへのリモート IPMI アクセスが可能になったらすぐに、デフォルトの Intelligent Platform Management Interface (IPMI) 管理者パスワードを変更できます。インストールの更新があった場合は、これを実行することをお勧めします。' 
---
= ノードのデフォルトの IPMI パスワードを変更する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードへのリモート IPMI アクセスが可能になったらすぐに、デフォルトの Intelligent Platform Management Interface (IPMI) 管理者パスワードを変更できます。インストールの更新があった場合は、これを実行することをお勧めします。

ノードのIPMアクセスの設定の詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["各ノードのIPMIを構成する"^] 。

次のノードの IPM パスワードを変更できます。

* H410Sノード
* H610Sノード




== H410SノードのデフォルトのIPMIパスワードを変更する

IPMI ネットワーク ポートを構成したらすぐに、各ストレージ ノード上の IPMI 管理者アカウントのデフォルト パスワードを変更する必要があります。

.要件
各ストレージ ノードの IPMI IP アドレスを設定する必要があります。

.手順
. IPMI ネットワークにアクセスできるコンピューターで Web ブラウザーを開き、ノードの IPMI IP アドレスを参照します。
. ユーザー名を入力してください `ADMIN`パスワード `ADMIN`ログインプロンプトで。
. ログインしたら、[*構成*]タブをクリックします。
. *ユーザー*をクリックします。
. 選択してください `ADMIN`ユーザーを選択し、[ユーザーの変更] をクリックします。
. *パスワードの変更*チェックボックスを選択します。
. *パスワード*フィールドと*パスワードの確認*フィールドに新しいパスワードを入力します。
. [変更] をクリックし、[OK] をクリックします。
. デフォルトの IPMI パスワードを持つ他の H410S ノードに対してもこの手順を繰り返します。




== H610SノードのデフォルトのIPMIパスワードを変更する

IPMI ネットワーク ポートを構成したらすぐに、各ストレージ ノード上の IPMI 管理者アカウントのデフォルト パスワードを変更する必要があります。

.要件
各ストレージ ノードの IPMI IP アドレスを設定する必要があります。

.手順
. IPMI ネットワークにアクセスできるコンピューターで Web ブラウザーを開き、ノードの IPMI IP アドレスを参照します。
. ユーザー名を入力してください `root`パスワード `calvin`ログインプロンプトで。
. ログインしたら、ページの左上にあるメニュー ナビゲーション アイコンをクリックして、サイドバー ドロワーを開きます。
. *設定*をクリックします。
. *ユーザー管理*をクリックします。
. リストから*管理者*ユーザーを選択します。
. *パスワードの変更*チェックボックスを有効にします。
. *パスワード* フィールドと *パスワードの確認* フィールドに新しい強力なパスワードを入力します。
. ページの下部にある*保存*をクリックします。
. デフォルトの IPMI パスワードを持つ他の H610S ノードに対してもこの手順を繰り返します。




== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

