---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: 既存のボリューム アクセス グループに複数のイニシエーターを追加して、CHAP 認証の有無にかかわらず、ボリューム アクセス グループ内のボリュームにアクセスできるようにすることができます。 
---
= ボリューム アクセス グループに複数のイニシエーターを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のボリューム アクセス グループに複数のイニシエーターを追加して、CHAP 認証の有無にかかわらず、ボリューム アクセス グループ内のボリュームにアクセスできるようにすることができます。

ボリューム アクセス グループにイニシエーターを追加すると、イニシエーターはそのボリューム アクセス グループ内のすべてのボリュームにアクセスできるようになります。


TIP: 各ボリュームのイニシエーターを見つけるには、[アクション] アイコンをクリックし、アクティブ ボリューム リスト内のボリュームの [詳細の表示] をクリックします。

既存のボリューム アクセス グループに複数のイニシエーターを追加してボリュームへのアクセスを有効にし、そのボリューム アクセス グループ内の各イニシエーターに一意の CHAP 資格情報を割り当てることができます。これにより、既存のボリューム アクセス グループにこのオプションを適用できるようになります。

API 呼び出しを使用して、イニシエータベースの CHAP 属性を割り当てることができます。イニシエーターごとに CHAP アカウント名と資格情報を追加するには、ModifyInitiator API 呼び出しを使用して CHAP アクセスと属性を削除および追加する必要があります。

詳細については、link:../api/concept_element_api_about_the_api.html["Element APIでストレージを管理する"] 。

.手順
. *管理* > *イニシエーター*をクリックします。
. アクセス グループに追加するイニシエーターを選択します。
. *一括操作*ボタンをクリックします。
. *ボリューム アクセス グループに追加* をクリックします。
. [ボリューム アクセス グループに追加] ダイアログ ボックスで、[*ボリューム アクセス グループ*] リストからアクセス グループを選択します。
. *[追加]*をクリックします。

