---
permalink: storage/task_replication_plan_cluster_and_volume_pairing.html 
sidebar: sidebar 
keywords: cluster, volume pairing, plan for, real-time replication 
summary: リアルタイムのリモート レプリケーションでは、Element ソフトウェアを実行している 2 つのストレージ クラスターをペアリングし、各クラスターのボリュームをペアリングして、レプリケーションを検証する必要があります。レプリケーションが完了したら、ボリューム関係を削除する必要があります。 
---
= リアルタイムレプリケーションのためのクラスタとボリュームのペアリングを計画する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リアルタイムのリモート レプリケーションでは、Element ソフトウェアを実行している 2 つのストレージ クラスターをペアリングし、各クラスターのボリュームをペアリングして、レプリケーションを検証する必要があります。レプリケーションが完了したら、ボリューム関係を削除する必要があります。

.要件
* ペアリングする 1 つまたは両方のクラスターに対するクラスター管理者権限が必要です。
* ペアになったクラスターの管理ネットワークとストレージ ネットワークの両方にあるすべてのノード IP アドレスは、相互にルーティングされます。
* ペアになっているすべてのノードの MTU は同じであり、クラスター間でエンドツーエンドでサポートされている必要があります。
* 両方のストレージ クラスターには、一意のクラスター名、MVIP、SVIP、およびすべてのノード IP アドレスが必要です。
* クラスター上の Element ソフトウェア バージョン間の差は、メジャー バージョン 1 つ以内です。差が大きい場合は、データレプリケーションを実行するためにクラスターの 1 つをアップグレードする必要があります。



NOTE: データのレプリケーションにおけるWANアクセラレータ アプライアンスの使用は、NetAppで認定されていません。これらのアプライアンスは、データを複製している 2 つのクラスター間に展開された場合、圧縮と重複排除に干渉する可能性があります。  WAN Accelerator アプライアンスを実稼働環境に導入する前に、その効果を十分に評価してください。



== 詳細情報の参照

* xref:task_replication_pair_clusters.adoc[レプリケーション用のクラスタをペアリングする]
* xref:task_replication_pair_volumes.adoc[ペアボリューム]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアボリュームにレプリケーションソースとターゲットを割り当てる]

