---
permalink: storage/task_snapmirror_perform_failback_when_source_volume_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source volume, snapmirror 
summary: NetApp Element UI を使用して、元のソース ボリュームを再同期し、フェイルバックすることができます。この手順は、元のソース ボリュームがまだ存在するシナリオに適用されます。 
---
= ソースボリュームがまだ存在する場合にフェイルバックを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element UI を使用して、元のソース ボリュームを再同期し、フェイルバックすることができます。この手順は、元のソース ボリュームがまだ存在するシナリオに適用されます。

. Element UI で、フェイルオーバーを実行するために解除した関係を見つけます。
. [アクション] アイコンをクリックし、[逆再同期] をクリックします。
. 操作を確定します。
+

NOTE: 逆再同期操作では、元のソース ボリュームと宛先ボリュームの役割が逆になった新しい関係が作成されます (元の関係は維持されるため、2 つの関係が作成されます)。元の宛先ボリュームからの新しいデータは、逆再同期操作の一環として元のソース ボリュームに転送されます。宛先側のアクティブ ボリュームへのアクセスとデータの書き込みは継続できますが、元のプライマリにリダイレクトする前に、ソース ボリュームへのすべてのホストを切断し、 SnapMirror更新を実行する必要があります。

. 作成した逆関係のアクション アイコンをクリックし、[更新] をクリックします。
+
逆再同期が完了し、宛先側のボリュームに接続されたアクティブなセッションがないこと、および最新のデータが元のプライマリ ボリュームにあることが確認されたので、次の手順を実行してフェイルバックを完了し、元のプライマリ ボリュームを再アクティブ化できます。

. 逆関係のアクション アイコンをクリックし、[解除] をクリックします。
. 元の関係のアクションアイコンをクリックし、「再同期」をクリックします。
+

NOTE: 元のプライマリ ボリュームをマウントして、元のプライマリ ボリュームで実稼働ワークロードを再開できるようになりました。元のSnapMirrorレプリケーションは、関係に対して設定されたポリシーとスケジュールに基づいて再開されます。

. 元の関係のステータスが「`snapmirrored`」であることを確認した後、逆の関係のアクション アイコンをクリックし、*削除* をクリックします。




== 詳細情報の参照

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirrorフェイルバックシナリオ]
