---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: SolidFireストレージ システムでは、テナントはアカウントを使用して、クライアントがノード上のボリュームに接続できるようにすることができます。アカウントには、割り当てられたボリュームにアクセスするために必要な CHAP 認証が含まれています。ボリュームを作成すると、特定のアカウントに割り当てられます。 
---
= CHAP を使用してアカウントを操作する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFireストレージ システムでは、テナントはアカウントを使用して、クライアントがクラスター上のボリュームに接続できるようにすることができます。アカウントには、割り当てられたボリュームにアクセスするために必要なチャレンジ ハンドシェイク認証プロトコル (CHAP) 認証が含まれています。ボリュームを作成すると、特定のアカウントに割り当てられます。

1 つのアカウントには最大 2,000 個のボリュームを割り当てることができますが、1 つのボリュームは 1 つのアカウントにのみ属することができます。



== CHAPアルゴリズム

Element 12.7 以降では、安全な FIPS 準拠の CHAP アルゴリズム SHA1、SHA-256、および SHA3-256 がサポートされています。ホスト iSCSI イニシエーターが Element iSCSI ターゲットとの iSCSI セッションを作成するときに、使用する CHAP アルゴリズムのリストを要求します。  Element iSCSI ターゲットは、ホスト iSCSI イニシエーターによって要求されたリストから、サポートする最初のアルゴリズムを選択します。 Element iSCSI ターゲットが最も安全なアルゴリズムを選択することを確認するには、最も安全なもの (SHA3-256 など) から最も安全でないもの (SHA1 や MD5 など) の順に並べたアルゴリズムのリストを送信するようにホスト iSCSI イニシエーターを構成する必要があります。ホスト iSCSI イニシエーターによって SHA アルゴリズムが要求されない場合、Element iSCSI ターゲットは、ホストから提案されたアルゴリズム リストに MD5 が含まれていると想定して MD5 を選択します。安全なアルゴリズムのサポートを有効にするには、ホスト iSCSI イニシエーターの構成を更新する必要がある場合があります。

Element 12.7 以降のアップグレード中に、SHA アルゴリズムを含むリストを含むセッション要求を送信するようにホスト iSCSI イニシエーター構成をすでに更新している場合は、ストレージ ノードが再起動すると、新しい安全なアルゴリズムがアクティブ化され、最も安全なプロトコルを使用して新しい iSCSI セッションまたは再接続された iSCSI セッションが確立されます。アップグレード中に、既存のすべての iSCSI セッションが MD5 から SHA に移行します。 SHA を要求するようにホスト iSCSI イニシエーター構成を更新しない場合、既存の iSCSI セッションは引き続き MD5 を使用します。後日、ホスト iSCSI イニシエーターの CHAP アルゴリズムを更新した後、iSCSI セッションは、iSCSI セッションの再接続をもたらすメンテナンス アクティビティに基づいて、時間の経過とともに徐々に MD5 から SHA に移行します。

たとえば、Red Hat Enterprise Linux (RHEL) 8.3のデフォルトのホストiSCSIイニシエーターには、 `node.session.auth.chap_algs = SHA3-256,SHA256,SHA1,MD5`設定がコメントアウトされ、iSCSI イニシエーターは MD5 のみを使用するようになります。ホスト上でこの設定のコメントを解除し、iSCSI イニシエーターを再起動すると、そのホストからの iSCSI セッションが SHA3-256 を使用して開始されます。

必要に応じて、 https://docs.netapp.com/us-en/element-software/api/reference_element_api_listiscsisessions.html["ISCSIセッションのリスト"]各セッションで使用されている CHAP アルゴリズムを確認するための API メソッド。



== アカウントの作成

ボリュームへのアクセスを許可するアカウントを作成できます。

システム内の各アカウント名は一意である必要があります。

. *管理* > *アカウント*を選択します。
. *アカウントを作成*をクリックします。
. *ユーザー名*を入力してください。
. *CHAP 設定* セクションで、次の情報を入力します。
+

NOTE: いずれかのパスワードを自動生成するには、資格情報フィールドを空白のままにします。

+
** CHAP ノード セッション認証の *イニシエーター シークレット*。
** CHAP ノード セッション認証の *ターゲット シークレット*。


. *アカウントを作成*をクリックします。




== アカウントの詳細を表示

個々のアカウントのパフォーマンスアクティビティをグラフ形式で表示できます。

グラフ情報には、アカウントの I/O およびスループット情報が表示されます。平均およびピークのアクティビティ レベルは、10 秒のレポート期間の増分で表示されます。これらの統計には、アカウントに割り当てられたすべてのボリュームのアクティビティが含まれます。

. *管理* > *アカウント*を選択します。
. アカウントのアクション アイコンをクリックします。
. *詳細を表示*をクリックします。


詳細は次のとおりです:

* *ステータス*: アカウントのステータス。有効な値は次のとおりです。
+
** アクティブ: アクティブなアカウント。
** ロック済み: ロックされたアカウント。
** 削除済み: 削除され、消去されたアカウント。


* *アクティブボリューム*: アカウントに割り当てられたアクティブボリュームの数。
* *圧縮*: アカウントに割り当てられたボリュームの圧縮効率スコア。
* *重複排除*: アカウントに割り当てられたボリュームの重複排除効率スコア。
* *シン プロビジョニング*: アカウントに割り当てられたボリュームのシン プロビジョニング効率スコア。
* *全体的な効率*: アカウントに割り当てられたボリュームの全体的な効率スコア。




== アカウントを編集する

アカウントを編集して、ステータスを変更したり、CHAP シークレットを変更したり、アカウント名を変更したりできます。

アカウント内の CHAP 設定を変更したり、アクセス グループからイニシエーターまたはボリュームを削除したりすると、イニシエーターが予期せずボリュームにアクセスできなくなる可能性があります。ボリューム アクセスが予期せず失われないことを確認するには、アカウントまたはアクセス グループの変更によって影響を受ける iSCSI セッションを常にログアウトし、イニシエーター設定とクラスター設定の変更が完了した後にイニシエーターがボリュームに再接続できることを確認します。


IMPORTANT: 管理サービスに関連付けられている永続ボリュームは、インストールまたはアップグレード中に作成された新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、関連付けられているアカウントを変更または削除しないでください。

. *管理* > *アカウント*を選択します。
. アカウントのアクション アイコンをクリックします。
. 表示されたメニューで、[*編集*] を選択します。
. *オプション:* *ユーザー名*を編集します。
. *オプション:* [ステータス] ドロップダウン リストをクリックして、別のステータスを選択します。
+

IMPORTANT: ステータスを「ロック済み」に変更すると、アカウントへのすべての iSCSI 接続が終了し、アカウントにアクセスできなくなります。アカウントに関連付けられたボリュームは維持されますが、ボリュームは iSCSI で検出できません。

. *オプション:* *CHAP 設定* で、ノード セッション認証に使用される *イニシエーター シークレット* と *ターゲット シークレット* の資格情報を編集します。
+

NOTE: *CHAP 設定* の資格情報を変更しない場合は、同じままになります。資格情報フィールドを空白にすると、システムによって新しいパスワードが生成されます。

. *変更を保存*をクリックします。




== アカウントを削除する

不要になったアカウントは削除できます。

アカウントを削除する前に、アカウントに関連付けられているすべてのボリュームを削除して消去します。


IMPORTANT: 管理サービスに関連付けられている永続ボリュームは、インストールまたはアップグレード中に作成された新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、関連付けられているアカウントを変更または削除しないでください。

. *管理* > *アカウント*を選択します。
. 削除するアカウントのアクション アイコンをクリックします。
. 表示されるメニューで、[削除] を選択します。
. 操作を確定します。




== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

