---
permalink: storage/task-element-replication-create-relationship-element-destination.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, replication, snapmirror 
summary: ONTAP 9.4 以降では、 SnapMirror を使用して、 ONTAPソースで作成された LUN のスナップショット コピーを Element デスティネーションに複製することができます。これは、LUNを使用してONTAPからElementソフトウェアにデータを移行する場合に便利です。 
---
= ONTAPソースからElementデスティネーションへのレプリケーションの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4 以降では、 SnapMirror を使用して、 ONTAPソースで作成された LUN のスナップショット コピーを Element デスティネーションに複製することができます。これは、LUNを使用してONTAPからElementソフトウェアにデータを移行する場合に便利です。

.開始する前に
* ONTAPからElementデスティネーション ノードにアクセスできるようにしておく必要があります。
* ElementボリュームのSnapMirrorレプリケーションを有効にしておく必要があります。


.タスク概要
要素の宛先パスを次の形式で指定する必要があります `<hostip:>/lun/<name>`ここで「`lun`」は実際の文字列「`lun`」であり、 `name`要素ボリュームの名前です。

レプリケーション ルールは次のとおりです。

* レプリケーション関係には、タイプ「`async-mirror`」のポリシーが必要です。
+
デフォルト ポリシーまたはカスタム ポリシーを使用できます。

* iSCSI LUNのみがサポートされます。
* ONTAPボリュームからElementボリュームに複数のLUNをレプリケートすることはできません。
* ONTAPボリュームから複数のElementボリュームにLUNをレプリケートすることはできません。


.手順
. ONTAPソースからElementデスティネーションへのレプリケーション関係を作成します。
+
`snapmirror create -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -type XDP -schedule schedule -policy <policy>`

+
コマンド構文全体については、マニュアル ページを参照してください。

+
次の例では、デフォルトを使用してSnapMirror DR関係を作成します。 `MirrorLatest`ポリシー：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
次の例では、カスタムを使用してSnapMirror DR関係を作成します。 `my_mirror`ポリシー：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----


.終了後の操作
使用 `snapmirror show`SnapMirror関係が作成されたことを確認するコマンド。コマンド構文全体については、マニュアル ページを参照してください。
