---
permalink: storage/task_replication_pair_clusters.html 
sidebar: sidebar 
keywords: pair clusters, replication, connect clusters, data protection 
summary: 'リアルタイム レプリケーション機能を使用するための最初のステップとして、2 つのクラスターをペアリングする必要があります。  2 つのクラスターをペアにして接続すると、1 つのクラスター上のアクティブ ボリュームが 2 番目のクラスターに継続的にレプリケートされるように構成でき、継続的なデータ保護 (CDP) が実現します。' 
---
= レプリケーション用のクラスタをペアリングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リアルタイム レプリケーション機能を使用するための最初のステップとして、2 つのクラスターをペアリングする必要があります。  2 つのクラスターをペアリングして接続すると、1 つのクラスター上のアクティブ ボリュームを 2 番目のクラスターに継続的にレプリケートするように構成して、継続的なデータ保護 (CDP) を提供できます。

.要件
* ペアリングする 1 つまたは両方のクラスターに対するクラスター管理者権限が必要です。
* すべてのノード MIP と SIP は相互にルーティングされます。
* クラスター間の往復遅延は 2000 ミリ秒未満です。
* 両方のストレージ クラスターには、一意のクラスター名、MVIP、SVIP、およびすべてのノード IP アドレスが必要です。
* クラスター上の Element ソフトウェア バージョン間の差は、メジャー バージョン 1 つ以内です。差が大きい場合は、データレプリケーションを実行するためにクラスターの 1 つをアップグレードする必要があります。



NOTE: クラスターのペアリングには、管理ネットワーク上のノード間の完全な接続が必要です。レプリケーションには、ストレージ クラスター ネットワーク上の個々のノード間の接続が必要です。

ボリュームを複製するために、1 つのクラスターを最大 4 つの他のクラスターとペアリングできます。クラスター グループ内のクラスターを相互にペアリングすることもできます。



== MVIPまたはペアリングキーを使用してクラスターをペアリングする

両方のクラスターにクラスター管理者のアクセス権がある場合は、ターゲット クラスターの MVIP を使用して、ソース クラスターとターゲット クラスターをペアリングできます。クラスター管理者のアクセスがクラスター ペア内の 1 つのクラスターでのみ利用可能な場合は、ターゲット クラスターでペアリング キーを使用してクラスターのペアリングを完了できます。

. クラスターをペアリングするには、次のいずれかの方法を選択します。
+
** link:task_replication_pair_cluster_using_mvip.html["MVIPを使用してクラスターをペアリングする"]: 両方のクラスターにクラスター管理者のアクセス権がある場合は、この方法を使用します。この方法では、リモート クラスターの MVIP を使用して 2 つのクラスターをペアリングします。
** link:task_replication_pair_cluster_using_pairing_key.html["ペアリングキーを使用してクラスターをペアリングする"]: クラスター管理者がアクセスできるクラスターが 1 つだけの場合は、この方法を使用します。このメソッドは、ターゲット クラスターでクラスターのペアリングを完了するために使用できるペアリング キーを生成します。






== 詳細情報の参照

xref:reference_prereq_network_port_requirements.adoc[ネットワークポートの要件]
