---
permalink: storage/task_replication_pair_volumes_using_a_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, replication 
summary: リモート クラスターのクラスター管理者の資格情報がない場合は、ペアリング キーを使用して、ボリュームをリモート クラスター上の別のボリュームとペアリングできます。 
---
= ペアリングキーを使用してボリュームをペアリングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソース クラスターに対してのみクラスター管理者アクセス権がある場合 (リモート クラスターに対するクラスター管理者の資格情報を持っていない)、ペアリング キーを使用して、ボリュームをリモート クラスター上の別のボリュームとペアリングできます。

.要件
* ボリュームを含むクラスターがペアになっていることを確認します。
* ペアリングに使用するボリュームがリモート クラスター上に存在することを確認します。
+

NOTE: ペアリング プロセスの後に、レプリケーション ソースとターゲットを割り当てることができます。レプリケーションのソースまたはターゲットは、ボリューム ペアのいずれかのボリュームにすることができます。データが含まれず、サイズ、ボリュームのブロック サイズ設定 (512e または 4k)、QoS 構成など、ソース ボリュームとまったく同じ特性を持つターゲット ボリュームを作成する必要があります。既存のボリュームをレプリケーション ターゲットとして割り当てると、そのボリューム上のデータは上書きされます。ターゲット ボリュームのサイズはソース ボリュームと同等かそれ以上にすることができますが、それより小さくすることはできません。



.手順
. *管理* > *ボリューム*を選択します。
. ペアリングするボリュームの*アクション*アイコンをクリックします。
. *ペア*をクリックします。
. *ボリュームのペアリング*ダイアログボックスで、*ペアリングの開始*を選択します。
. リモート クラスターへのアクセス権がないことを指定するには、[*アクセス権がありません*] を選択します。
. リストから*レプリケーション モード*を選択します。
+
** *リアルタイム (非同期)*: 書き込みは、ソース クラスターでコミットされた後にクライアントに確認応答されます。
** *リアルタイム (同期)*: 書き込みは、ソース クラスターとターゲット クラスターの両方でコミットされた後にクライアントに確認応答されます。
** *スナップショットのみ*: ソース クラスターで作成されたスナップショットのみが複製されます。ソース ボリュームからのアクティブな書き込みは複製されません。


. *キーの生成*をクリックします。
+

NOTE: このアクションは、ペアリング用のテキスト キーを生成し、ローカル クラスター上に未構成のボリューム ペアを作成します。手順を完了しない場合は、ボリューム ペアを手動で削除する必要があります。

. ペアリング キーをコンピューターのクリップボードにコピーします。
. リモート クラスター サイトのクラスター管理者がペアリング キーにアクセスできるようにします。
+

NOTE: ボリューム ペアリング キーは安全な方法で扱う必要があり、偶発的または安全でないアクセスを許可するような方法で使用しないでください。

+

IMPORTANT: ペアリング キーの文字を変更しないでください。キーが変更されると無効になります。

. リモート クラスターの Element UI で、*管理* > *ボリューム* を選択します。
. ペアリングするボリュームのアクション アイコンをクリックします。
. *ペア*をクリックします。
. *ボリュームのペアリング*ダイアログボックスで、*ペアリングの完了*を選択します。
. 他のクラスターのペアリング キーを *ペアリング キー* ボックスに貼り付けます。
. *ペアリングを完了*をクリックします。
+
ペアリングを確認すると、2 つのクラスターはペアリングのためにボリュームを接続するプロセスを開始します。ペアリング プロセス中は、[ボリューム ペア] ウィンドウの [ボリューム ステータス] 列にメッセージが表示されます。ボリュームペアの表示 `PausedMisconfigured`ボリューム ペアのソースとターゲットが割り当てられるまで。

+
ペアリングが正常に完了したら、ボリューム テーブルを更新して、ペアリングされたボリュームの *アクション* リストから *ペア* オプションを削除することをお勧めします。テーブルを更新しない場合は、*ペア* オプションは選択可能なままになります。もう一度「ペアリング」オプションを選択すると、新しいタブが開き、ボリュームがすでにペアリングされているため、システムは `StartVolumePairing Failed: xVolumeAlreadyPaired`Element UI ページの *Pair Volume* ウィンドウにエラー メッセージが表示されます。





== 詳細情報の参照

* xref:reference_replication_volume_pairing_messages.adoc[ボリュームペアリングメッセージ]
* xref:reference_replication_volume_pairing_warnings.adoc[ボリュームペアリングの警告]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[ペアボリュームにレプリケーションソースとターゲットを割り当てる]

