---
permalink: storage/task_data_manage_vol_access_group_add_a_single_initiator.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add single initiator, create initiator 
summary: 既存のボリューム アクセス グループにイニシエーターを追加できます。 
---
= ボリューム アクセス グループに単一のイニシエーターを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のボリューム アクセス グループにイニシエーターを追加できます。

イニシエーターをボリューム アクセス グループに追加すると、イニシエーターはそのボリューム アクセス グループ内のすべてのボリュームにアクセスできるようになります。


TIP: 各ボリュームのイニシエーターを見つけるには、[アクション] アイコンをクリックし、アクティブ ボリューム リストでボリュームの [詳細の表示] を選択します。

イニシエーターベースの CHAP を使用する場合は、ボリューム アクセス グループ内の単一のイニシエーターに対して CHAP 資格情報を追加して、セキュリティを強化できます。これにより、既存のボリューム アクセス グループにこのオプションを適用できるようになります。

.手順
. *管理* > *アクセス グループ*をクリックします。
. 編集するアクセス グループの *アクション* アイコンをクリックします。
. *編集*をクリックします。
. ボリューム アクセス グループにファイバー チャネル イニシエーターを追加するには、次の手順を実行します。
+
.. [イニシエーターの追加] の下で、[*バインドされていないファイバー チャネル イニシエーター*] リストから既存のファイバー チャネル イニシエーターを選択します。
.. *FCイニシエーターの追加*をクリックします。
+

NOTE: この手順中にイニシエーターを作成するには、[*イニシエーターの作成*] リンクをクリックし、イニシエーター名を入力して [*作成*] をクリックします。イニシエーターを作成すると、システムによって自動的にそのイニシエーターが *イニシエーター* リストに追加されます。

+
形式のサンプルは次のとおりです。



+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
. ボリューム アクセス グループに iSCSI イニシエーターを追加するには、[イニシエーターの追加] で、[*イニシエーター*] リストから既存のイニシエーターを選択します。
+

NOTE: この手順中にイニシエーターを作成するには、[*イニシエーターの作成*] リンクをクリックし、イニシエーター名を入力して [*作成*] をクリックします。イニシエーターを作成すると、システムによって自動的にそのイニシエーターが *イニシエーター* リストに追加されます。

+
イニシエーター IQN の許容形式は次のとおりです: iqn.yyyy-mm (y と m は数字)、その後に数字、小文字の英字、ピリオド (.)、コロン (:)、またはダッシュ (-) のみを含むテキストが続きます。

+
形式のサンプルは次のとおりです。

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+

TIP: 各ボリュームのイニシエーター IQN は、[*管理*] > [*ボリューム*] の [アクティブ ボリューム] ページで [アクション] アイコンをクリックし、ボリュームの [*詳細の表示*] を選択すると確認できます。

. *変更を保存*をクリックします。

