---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: ノードをクラスターに追加する前に、個々のノードを構成する必要があります。ラック ユニットにノードを設置してケーブル配線し、電源をオンにした後、ノードごとの UI またはノード ターミナル ユーザー インターフェイスを使用してノードのネットワーク設定を構成できます。 
---
= ストレージノードを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノードをクラスターに追加する前に、個々のノードを構成する必要があります。ラック ユニットにノードを設置してケーブル配線し、電源をオンにした後、ノードごとの UI またはノード ターミナル ユーザー インターフェイス (TUI) を使用してノードのネットワーク設定を構成できます。続行する前に、ノードに必要なネットワーク構成情報があることを確認してください。

ストレージ ノードを構成するには、次の 2 つのオプションがあります。

* <<ノードごとのUIを使用してストレージノードを構成する,ノードごとのUI>>: ノードごとのUIを使用する (`https://<node_management_IP>:442`）を使用してノードのネットワーク設定を構成します。
* <<TUIを使用してストレージノードを構成する,TUI>>: ノード端末ユーザー インターフェイス (TUI) を使用してノードを構成します。


DHCP によって割り当てられた IP アドレスを持つノードをクラスターに追加することはできません。 DHCP IP アドレスを使用して、ノードごとの UI、TUI、または API でノードを初期構成できます。この初期構成中に、静的 IP アドレス情報を追加して、ノードをクラスターに追加することができます。

初期設定後、ノードの管理 IP アドレスを使用してノードにアクセスできるようになります。その後、ノードの設定を変更したり、ノードをクラスターに追加したり、ノードを使用してクラスターを作成したりできます。  Element ソフトウェア API メソッドを使用して新しいノードを構成することもできます。


NOTE: Element バージョン 11.0 以降では、管理ネットワークのノードに IPv4、IPv6、またはその両方のアドレスを構成できます。これは、IPv6 をサポートしない管理ノード 11.3 以降を除き、ストレージ ノードと管理ノードの両方に適用されます。クラスターを作成する場合、MVIP に使用できるのは 1 つの IPv4 または IPv6 アドレスのみであり、対応するアドレス タイプをすべてのノードで構成する必要があります。



== ノードごとのUIを使用してストレージノードを構成する

ノードごとのユーザー インターフェイスを使用してノードを構成できます。

.タスク概要
* ノードを IPv4 アドレスまたは IPv6 アドレスのいずれかを持つように構成できます。
* ノードにアクセスするには、TUI に表示される DHCP アドレスが必要です。  DHCP アドレスを使用してクラスターにノードを追加することはできません。
+

IMPORTANT: 管理 (Bond1G) インターフェイスとストレージ (Bond10G) インターフェイスを別々のサブネットに構成する必要があります。同じサブネットに設定された Bond1G および Bond10G インターフェイスでは、ストレージ トラフィックが Bond1G インターフェイス経由で送信されるときにルーティングの問題が発生します。管理トラフィックとストレージ トラフィックに同じサブネットを使用する必要がある場合は、Bond10G インターフェイスを使用するように管理トラフィックを手動で構成します。各ノードの UI の *クラスター設定* ページを使用して、各ノードに対してこれを実行できます。



.手順
. ブラウザ ウィンドウで、ノードの DHCP IP アドレスを入力します。
+
拡張機能を追加する必要があります `:442` ノードにアクセスするには、例えば、 `https://172.25.103.6:442`。

+
*ネットワーク設定*タブが開き、*Bond1G*セクションが表示されます。

. 1G 管理ネットワーク設定を入力します。
. *変更を適用*をクリックします。
. *Bond10G* をクリックすると、10G ストレージ ネットワーク設定が表示されます。
. 10G ストレージ ネットワーク設定を入力します。
. *変更を適用*をクリックします。
. *クラスター設定*をクリックします。
. 10G ネットワークのホスト名を入力します。
. クラスター名を入力します。
+

IMPORTANT: クラスターを作成する前に、この名前をすべてのノードの構成に追加する必要があります。クラスター内のすべてのノードは、同一のクラスター名を持つ必要があります。クラスター名では大文字と小文字が区別されます。

. *変更を適用*をクリックします。




== TUIを使用してストレージノードを構成する

ターミナル ユーザー インターフェイス (TUI) を使用して、新しいノードの初期構成を実行できます。

Bond1G (管理) インターフェースと Bond10G (ストレージ) インターフェースは別々のサブネットに設定する必要があります。同じサブネットに設定された Bond1G および Bond10G インターフェイスでは、ストレージ トラフィックが Bond1G インターフェイス経由で送信されるときにルーティングの問題が発生します。管理トラフィックとストレージ トラフィックに同じサブネットを使用する必要がある場合は、Bond10G インターフェイスを使用するように管理トラフィックを手動で構成します。  Element UI の *クラスター* > *ノード* ページを使用して、各ノードに対してこれを実行できます。

.手順
. ノードにキーボードとモニターを接続し、ノードの電源を入れます。
+
TUI のNetAppストレージ メイン メニューが tty1 端末に表示されます。

+

NOTE: ノードが構成サーバーに到達できない場合、TUI にエラー メッセージが表示されます。エラーを解決するには、構成サーバー接続またはネットワーク接続を確認してください。

. *ネットワーク* > *ネットワーク構成*を選択します。
+

TIP: メニュー内を移動するには、上矢印キーまたは下矢印キーを押します。別のボタンに移動したり、ボタンからフィールドに移動するには、*Tab* キーを押します。フィールド間を移動するには、上矢印キーまたは下矢印キーを使用します。

. *Bond1G (管理)* または *Bond10G (ストレージ)* を選択して、ノードの 1G および 10G ネットワーク設定を構成します。
. ボンド モードとステータス フィールドでは、*Tab* キーを押してヘルプ ボタンを選択し、使用可能なオプションを確認します。
+
クラスター内のすべてのノードは、同一のクラスター名を持つ必要があります。クラスター名では大文字と小文字が区別されます。使用可能な IP アドレスを持つネットワーク上で DHCP サーバーが実行中の場合、アドレス フィールドに 1GbE アドレスが表示されます。

. *Tab* キーを押して *OK* ボタンを選択し、変更を保存します。
+
ノードは保留状態になり、既存のクラスターまたは新しいクラスターに追加できます。





== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

