---
permalink: setup/concept_setup_fc_configure_a_fibre_channel_node.html 
sidebar: sidebar 
keywords:  
summary: 'ファイバー チャネル ノードを使用すると、クラスターをファイバー チャネル ネットワーク ファブリックに接続できます。ファイバー チャネル ノードはペアで追加され、アクティブ/アクティブ モードで動作します (すべてのノードがクラスターのトラフィックをアクティブに処理します)。  Element ソフトウェア バージョン 9.0 以降を実行するクラスターは最大 4 つのノードをサポートします。以前のバージョンを実行するクラスターは最大 2 つのノードをサポートします。' 
---
= ファイバーチャネルノードを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイバー チャネル ノードを使用すると、クラスターをファイバー チャネル ネットワーク ファブリックに接続できます。ファイバー チャネル ノードはペアで追加され、アクティブ/アクティブ モードで動作します (すべてのノードがクラスターのトラフィックをアクティブに処理します)。  Element ソフトウェア バージョン 9.0 以降を実行するクラスターは最大 4 つのノードをサポートします。以前のバージョンを実行するクラスターは最大 2 つのノードをサポートします。

ファイバー チャネル ノードを構成する前に、次の条件が満たされていることを確認する必要があります。

* 少なくとも 2 つのファイバー チャネル ノードがファイバー チャネル スイッチに接続されています。
* すべてのSolidFireファイバー チャネル ポートはファイバー チャネル ファブリックに接続する必要があります。 4 つのSolidFire Bond10G ネットワーク接続は、スイッチ レベルで 1 つの LACP ボンド グループに接続する必要があります。これにより、ファイバー チャネル システムの全体的なパフォーマンスが最大限に発揮されます。
* このNetAppナレッジベースの記事に含まれるファイバー チャネル クラスターのすべてのベスト プラクティスを確認し、検証します。
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/SolidFire_FC_cluster_best_practice["SolidFire FCクラスタのベストプラクティス"]



ネットワークとクラスターの構成手順は、ファイバー チャネル ノードとストレージ ノードで同じです。

ファイバー チャネル ノードとSolidFireストレージ ノードを使用して新しいクラスターを作成すると、ノードのワールドワイド ポート名 (WWPN) アドレスが Element UI で使用できるようになります。  WWPN アドレスを使用してファイバー チャネル スイッチをゾーン分けできます。

ノードを含む新しいクラスターを作成すると、WWPN がシステムに登録されます。  Element UI では、[クラスター] タブからアクセスする [FC ポート] タブの [WWPN] 列で WWPN アドレスを見つけることができます。



== 詳細情報の参照

xref:task_setup_fc_add_fibre_channel_nodes_to_a_cluster.adoc[ファイバーチャネルノードをクラスターに追加する]

xref:task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.adoc[ファイバーチャネルノードで新しいクラスターを作成する]
