---
permalink: setup/task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.html 
sidebar: sidebar 
keywords:  
summary: 個々のファイバー チャネル ノードを構成した後、新しいクラスターを作成できます。クラスターを作成すると、クラスター管理者のユーザー アカウントが自動的に作成されます。クラスター管理者には、すべてのクラスター属性を管理する権限があり、他のクラスター管理者アカウントを作成することもできます。 
---
= ファイバーチャネルノードで新しいクラスターを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
個々のファイバー チャネル ノードを構成した後、新しいクラスターを作成できます。クラスターを作成すると、クラスター管理者のユーザー アカウントが自動的に作成されます。クラスター管理者には、すべてのクラスター属性を管理する権限があり、他のクラスター管理者アカウントを作成することもできます。

新しいノードの構成中に、1G または 10G 管理 IP (MIP) アドレスが各ノードに割り当てられます。 「新しいクラスターの作成」ページを開くには、構成中に作成されたノード IP アドレスの 1 つを使用する必要があります。使用する IP アドレスは、クラスター管理用に選択したネットワークによって異なります。

.要件
個々のファイバー チャネル ノードを構成しました。

.手順
. ブラウザ ウィンドウで、ノードの MIP アドレスを入力します。
. 「新しいクラスターの作成」で、次の情報を入力します。
+
** 管理 VIP: ネットワーク管理タスク用の 1GbE または 10GbE ネットワーク上のルーティング可能な仮想 IP。
** iSCSI (ストレージ) VIP: ストレージおよび iSCSI 検出用の 10GbE ネットワーク上の仮想 IP。
+

NOTE: クラスターを作成した後は、SVIP を変更することはできません。

** ユーザー名: クラスターへの認証アクセスに使用するプライマリ クラスター管理者のユーザー名。将来の参照用にユーザー名を保存する必要があります。
+

NOTE: ユーザー名には、大文字、小文字、特殊文字、数字を使用できます。

** パスワード: クラスターへの認証アクセス用のパスワード。将来の参照用にユーザー名を保存する必要があります。双方向のデータ保護はデフォルトで有効になっています。この設定は変更できません。


. エンドユーザー使用許諾契約書を読み、「同意する」をクリックします。
. *オプション*: ノード リストで、クラスターに含めないノードのチェック ボックスが選択されていないことを確認します。
. *クラスターの作成*をクリックします。
+
クラスター内のノードの数によっては、クラスターの作成に数分かかる場合があります。適切に構成されたネットワークでは、5 つのノードからなる小規模なクラスターの実行には 1 分もかかりません。クラスターが作成されると、[新しいクラスターの作成] ウィンドウがクラスターの MVIP URL アドレスにリダイレクトされ、Web UI が表示されます。





== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

