---
permalink: setup/task_setup_create_a_storage_cluster.html 
sidebar: sidebar 
keywords:  
summary: 個々のノードをすべて構成した後、ストレージ クラスターを作成できます。クラスターを作成すると、クラスター管理者のユーザー アカウントが自動的に作成されます。クラスター管理者には、すべてのクラスター属性を管理する権限があり、他のクラスター管理者アカウントを作成することもできます。 
---
= ストレージ クラスタを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
個々のノードをすべて構成した後、ストレージ クラスターを作成できます。クラスターを作成すると、クラスター管理者のユーザー アカウントが自動的に作成されます。クラスター管理者には、すべてのクラスター属性を管理する権限があり、他のクラスター管理者アカウントを作成することもできます。

.要件
* 管理ノードをインストールしました。
* 個々のノードをすべて構成しました。


.タスク概要
新しいノードの構成中に、1G または 10G 管理 IP (MIP) アドレスが各ノードに割り当てられます。 「新しいクラスターの作成」ページを開くには、構成中に作成されたノード IP アドレスの 1 つを使用する必要があります。使用する IP アドレスは、クラスター管理用に選択したネットワークによって異なります。

[IMPORTANT]
====
クラスタ全体で有効にしたい場合はlink:../concepts/concept_solidfire_concepts_security.html#encryption-at-rest-software["保存時のソフトウェア暗号化"]SolidFireオールフラッシュ ストレージ クラスターの場合は、クラスターの作成時にこれを行う必要があります。  Element 12.5 以降では、クラスターの作成時に、クラスターの作成 UI で保存時のソフトウェア暗号化を有効にする必要があります。 Element 12.3.x以前の場合は、link:../api/reference_element_api_createcluster.html["CreateCluster"] APIメソッドのenableSoftwareEncryptionAtRestパラメータを次のように変更します。 `true` 。クラスター上で保存時のソフトウェア暗号化を有効にすると、無効にすることはできません。あなたはできるlink:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["有効化と無効化"]クラスター作成後の保存時のハードウェアベースの暗号化。

====
[NOTE]
====
新しいクラスターを作成するときは、次の点を考慮してください。

* 共有シャーシ内に存在するストレージ ノードを使用している場合は、保護ドメイン機能を使用してシャーシ レベルの障害保護を設計することを検討してください。
* 共有シャーシが使用されていない場合は、カスタム保護ドメイン レイアウトを定義できます。


====
.手順
. ブラウザウィンドウで、次のように入力します。 `\https://MIP:443`ここで、MIP は管理ノードの IP アドレスです。
. 「新しいクラスターの作成」で、次の情報を入力します。
+
** 管理 VIP: ネットワーク管理タスク用の 1GbE または 10GbE ネットワーク上のルーティング可能な仮想 IP。
+

NOTE: IPv4 または IPv6 アドレスを使用して新しいクラスターを作成できます。

** iSCSI (ストレージ) VIP: ストレージおよび iSCSI 検出用の 10GbE ネットワーク上の仮想 IP。
+

NOTE: クラスターを作成した後は、MVIP、SVIP、またはクラスター名を変更することはできません。

** ユーザー名: クラスターへの認証アクセスに使用するプライマリ クラスター管理者のユーザー名。将来の参照用にユーザー名を保存する必要があります。
+

NOTE: ユーザー名とパスワードには、大文字、小文字、特殊文字、数字を使用できます。

** パスワード: クラスターへの認証アクセス用のパスワード。将来の参照用にパスワードを保存する必要があります。双方向のデータ保護はデフォルトで有効になっています。この設定は変更できません。


. エンドユーザー使用許諾契約書を読み、「同意する」を選択します。
. *オプション*: ノード リストで、クラスターに含めないノードのチェック ボックスが選択されていないことを確認します。
. *クラスターの作成*を選択します。
+
クラスター内のノードの数によっては、クラスターの作成に数分かかる場合があります。適切に構成されたネットワークでは、5 つのノードからなる小規模なクラスターの実行には 1 分もかかりません。クラスターが作成されると、「新しいクラスターの作成」ウィンドウがクラスターの MVIP URL アドレスにリダイレクトされ、Element UI が表示されます。





== 詳細情報

* link:../api/concept_element_api_about_the_api.html["Element API によるストレージの管理"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

