---
permalink: setup/task_setup_fc_add_fibre_channel_nodes_to_a_cluster.html 
sidebar: sidebar 
keywords:  
summary: 追加のストレージが必要な場合やクラスターの作成中に、ファイバー チャネル ノードをクラスターに追加できます。ファイバー チャネル ノードは、初めて電源を入れるときに初期構成が必要です。ノードが設定されると、保留中のノードのリストに表示され、クラスターに追加できるようになります。 
---
= ファイバーチャネルノードをクラスターに追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
追加のストレージが必要な場合やクラスターの作成中に、ファイバー チャネル ノードをクラスターに追加できます。ファイバー チャネル ノードは、初めて電源を入れるときに初期構成が必要です。ノードが設定されると、保留中のノードのリストに表示され、クラスターに追加できるようになります。

クラスター内の各ファイバー チャネル ノードのソフトウェア バージョンは互換性がある必要があります。ファイバー チャネル ノードをクラスターに追加すると、クラスターは必要に応じて新しいノードに Element のクラスター バージョンをインストールします。

.手順
. *クラスター* > *ノード*を選択します。
. 保留中のノードのリストを表示するには、「*保留中*」をクリックします。
. 次のいずれかを実行します。
+
** 個々のノードを追加するには、追加するノードの *アクション* アイコンをクリックします。
** 複数のノードを追加するには、追加するノードのチェックボックスをオンにして、[*一括操作*] を選択します。
+

NOTE: 追加するノードに、クラスターで実行されているバージョンとは異なるバージョンの Element がある場合、クラスターは、そのノードをクラスター マスターで実行されている Element のバージョンに非同期的に更新します。ノードが更新されると、ノードは自動的にクラスターに追加されます。この非同期プロセス中、ノードは pendingActive 状態になります。



. *[追加]*をクリックします。
+
ノードがアクティブ ノードのリストに表示されます。





== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 用NetApp Elementプラグイン"^]

