---
permalink: api/concept_element_api_about_the_api.html 
sidebar: sidebar 
keywords: SolidFire,API,overview,about,Element 
summary: Element API は、HTTPS 経由の JSON-RPC プロトコルに基づいています。 JSON-RPC は、軽量の JSON データ交換形式に基づいたシンプルなテキストベースの RPC プロトコルです。すべての主要なプログラミング言語でクライアント ライブラリが利用可能です。 
---
= Element API を使用したストレージ管理について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element API は、HTTPS 経由の JSON-RPC プロトコルに基づいています。 JSON-RPC は、軽量の JSON データ交換形式に基づいたシンプルなテキストベースの RPC プロトコルです。すべての主要なプログラミング言語でクライアント ライブラリが利用可能です。

API エンドポイントへの HTTPS POST リクエストを介して API リクエストを行うことができます。  POST リクエストの本文は JSON-RPC リクエスト オブジェクトです。  API は現在、バッチ リクエスト (単一の POST 内の複数のリクエスト オブジェクト) をサポートしていません。  API リクエストを送信するときは、リクエストのコンテンツ タイプとして「application/json-rpc」を使用し、本文がフォーム エンコードされていないことを確認する必要があります。


NOTE: Element Web UI は、このドキュメントで説明されている API メソッドを利用します。 API ログを有効にすると、UI で API 操作を監視できます。これにより、システムに発行されているメソッドを確認できます。リクエストとレスポンスの両方を有効にして、発行されたメソッドに対してシステムがどのように応答するかを確認できます。

特に明記しない限り、API 応答内のすべての日付文字列は UTC+0 形式になります。


NOTE: ストレージ クラスターの負荷が高い場合、または、遅延なしで連続して多数の API 要求を送信する場合、メソッドが失敗し、エラー「xDBVersionMismatch」が返されることがあります。このような場合は、メソッド呼び出しを再試行してください。



== 一般的なオブジェクト

Element ソフトウェア API は、JSON オブジェクトを使用して整理されたデータ概念を表します。これらの API メソッドの多くは、データの入出力にこれらのオブジェクトを使用します。このセクションでは、これらのよく使用されるオブジェクトについて説明します。単一のメソッド内でのみ使用されるオブジェクトについては、このセクションではなく、そのメソッドで説明します。

link:../api/reference_element_api_account.html["一般的な物について学ぶ"]



== 一般的な方法

一般的なメソッドは、ストレージ クラスター、API 自体、または進行中の API 操作に関する情報を取得するために使用されるメソッドです。

link:../api/reference_element_api_getapi.html["一般的な方法について学ぶ"]



== アカウントAPIメソッド

アカウント メソッドを使用すると、アカウントおよびセキュリティ情報を追加、削除、表示、および変更できます。

link:../api/reference_element_api_addaccount.html["アカウントAPIメソッドについて学ぶ"]



== 管理者APIメソッド

管理者 API メソッドを使用して、ストレージ クラスター管理者を作成、変更、表示、削除したり、ストレージ クラスターへのアクセス権を持つ管理者にアクセス レベルと権限を割り当てたりすることができます。

link:../api/reference_element_api_addclusteradmin.html["管理者APIメソッドについて学ぶ"]



== クラスターAPIメソッド

Element ソフトウェア クラスター API メソッドを使用すると、ストレージ クラスターおよびストレージ クラスターに属するノードの構成とトポロジを管理できます。

一部のクラスター API メソッドは、クラスターの一部であるノード、またはクラスターに参加するように構成されているノードで動作します。新しいクラスターまたは既存のクラスターにノードを追加できます。クラスターに追加する準備ができているノードは「保留中」状態です。つまり、構成はされているものの、まだクラスターに追加されていないことを意味します。

link:../api/reference_element_api_addnodes.html["クラスターAPIメソッドについて学ぶ"]



== クラスター作成APIメソッド

これらの API メソッドを使用してストレージ クラスターを作成できます。これらのメソッドはすべて、単一のノード上の API エンドポイントに対して使用する必要があります。

link:../api/reference_element_api_checkproposedcluster.html["クラスター作成APIメソッドについて学ぶ"]



== ドライブAPIメソッド

ドライブ API メソッドを使用して、ストレージ クラスターで使用可能なドライブを追加および管理できます。ストレージ ノードをストレージ クラスターに追加したり、既存のストレージ ノードに新しいドライブをインストールしたりすると、ドライブをストレージ クラスターに追加できるようになります。

link:../api/reference_element_api_adddrives.html["ドライブAPIメソッドについて学ぶ"]



== ファイバーチャネルAPIメソッド

ファイバー チャネル API メソッドを使用して、ストレージ クラスターのファイバー チャネル ノード メンバーを追加、変更、または削除できます。

link:../api/reference_element_api_getvolumeaccessgrouplunassignments.html["ファイバーチャネルAPIメソッドについて学ぶ"]



== イニシエーターAPIメソッド

イニシエーター メソッドを使用すると、ストレージ システムと外部ストレージ クライアント間の通信を処理する iSCSI イニシエーター オブジェクトを追加、削除、表示、および変更できます。

link:../api/reference_element_api_createinitiators.html["イニシエーターAPIメソッドについて学ぶ"]



== LDAP APIメソッド

Lightweight Directory Access Protocol (LDAP) を使用して、Element ストレージへのアクセスを認証できます。このセクションで説明する LDAP API メソッドを使用すると、ストレージ クラスターへの LDAP アクセスを構成できます。

link:../api/reference_element_api_addldapclusteradmin.html["LDAP APIメソッドについて学ぶ"]



== 多要素認証APIメソッド

多要素認証 (MFA) を使用すると、セキュリティアサーションマークアップ言語 (SAML) を介してサードパーティの ID プロバイダー (IdP) を使用してユーザーセッションを管理できます。

link:../api/reference_element_api_addidpclusteradmin.html["多要素認証APIメソッドについて学ぶ"]



== セッション認証APIメソッド

セッションベースの認証を使用して、ユーザー セッションを管理できます。

link:../api/reference_element_api_listauthsessionbyclusteradmin.html["セッション認証APIメソッドについて学ぶ"]



== ノードAPIメソッド

ノード API メソッドを使用して個々のノードを構成できます。これらのメソッドは、構成する必要がある単一ノード、構成されているがまだクラスターに参加していない単一ノード、またはクラスターにアクティブに参加している単一ノードで動作します。ノード API メソッドを使用すると、個々のノードと、ノードとの通信に使用されるクラスター ネットワークの設定を表示および変更できます。これらのメソッドは個々のノードに対して実行する必要があります。クラスターのアドレスに対してノードごとの API メソッドを実行することはできません。

link:../api/reference_element_api_checkpingonvlan.html["ノードAPIメソッドについて学ぶ"]



== レプリケーションAPIメソッド

レプリケーション API メソッドを使用すると、継続的なデータ保護 (CDP) のために 2 つのクラスターを接続できます。 2 つのクラスターを接続すると、クラスター内のアクティブなボリュームを 2 番目のクラスターに継続的に複製して、データの回復を実現できます。レプリケーション用にボリュームをペアリングすることで、データにアクセスできなくなる可能性のあるイベントからデータを保護できます。

link:../api/reference_element_api_cluster_pairing_order_of_operations.html["レプリケーションAPIメソッドについて学ぶ"]



== セキュリティAPIメソッド

Element ソフトウェアを、外部キー管理サーバーなどの外部セキュリティ関連サービスと統合できます。これらのセキュリティ関連のメソッドを使用すると、保存時の暗号化の外部キー管理などの Element セキュリティ機能を構成できます。

link:../api/reference_element_api_addkeyservertoproviderkmip.html["セキュリティAPIメソッドについて学ぶ"]



== SnapMirror APIメソッド

SnapMirror API メソッドは、リモートONTAPシステムでミラーリングされたスナップショットを管理するために Element Web UI によって使用されます。これらのメソッドは、Element Web UI でのみ使用することを目的としています。  SnapMirror機能への API アクセスが必要な場合は、 ONTAP API を使用します。  SnapMirror API メソッドでは、要求と戻りの例は提供されません。

link:../api/reference_element_api_abortsnapmirrorrelationship.html["SnapMirror APIメソッドについて学ぶ"]



== システム構成APIメソッド

システム構成 API メソッドを使用すると、クラスター内のすべてのノードに適用される構成値を取得および設定できます。

link:../api/reference_element_api_disablebmccoldreset.html["システム構成APIメソッドについて学ぶ"]



== マルチテナントネットワークAPIメソッド

Element ストレージ クラスターのマルチテナント ネットワーキングにより、別々の論理ネットワーク上にある複数のクライアント間のトラフィックを、レイヤー 3 ルーティングなしで 1 つの Element ストレージ クラスターに接続できるようになります。

ストレージ クラスターへの接続は、VLAN タグ付けを使用してネットワーク スタック内で分離されます。



=== マルチテナント仮想ネットワークを設定するための前提条件

* ストレージ ノード上の仮想ネットワークに割り当てるクライアント ネットワーク IP アドレスのブロックを特定しておく必要があります。
* すべてのストレージ トラフィックのエンドポイントとして使用するクライアント ストレージ ネットワーク IP (SVIP) アドレスを特定する必要があります。




=== 仮想ネットワークの操作順序

. 入力した IP アドレスを一括プロビジョニングするには、AddVirtualNetwork メソッドを使用します。
+
仮想ネットワークを追加すると、クラスターは次の手順を自動的に実行します。

+
** 各ストレージ ノードは仮想ネットワーク インターフェイスを作成します。
** 各ストレージ ノードには、仮想 SVIP を使用してルーティングできる VLAN アドレスが割り当てられます。
** ノードを再起動しても、VLAN IP アドレスは各ノード上で保持されます。


. 仮想ネットワーク インターフェイスと VLAN アドレスが割り当てられたら、クライアント ネットワーク トラフィックを仮想 SVIP に割り当てることができます。


link:../api/concept_element_api_virtual_network_naming_conventions.html["マルチテナントネットワークAPIメソッドについて学ぶ"]



== ボリュームAPIメソッド

Element ソフトウェア ボリューム API メソッドを使用すると、ストレージ ノードに存在するボリュームを管理できます。これらの方法を使用して、ボリュームを作成、変更、複製、および削除できます。ボリューム API メソッドを使用して、ボリュームのデータ測定値を収集および表示することもできます。

link:../api/reference_element_api_cancelclone.html["ボリュームAPIメソッドについて学ぶ"]



== ボリュームアクセスグループAPIメソッド

ボリューム アクセス グループ メソッドを使用すると、iSCSI またはファイバー チャネル イニシエーターを使用してユーザーがアクセスできるボリュームのコレクションであるボリューム アクセス グループを追加、削除、表示、および変更できます。

link:../api/reference_element_api_addinitiatorstovolumeaccessgroup.html["ボリューム アクセス グループ API メソッドについて学習する"]



== ボリュームスナップショットAPIメソッド

Element ソフトウェア ボリューム スナップショット API メソッドを使用すると、ボリューム スナップショットを管理できます。ボリューム スナップショット API メソッドを使用して、ボリューム スナップショットを作成、変更、複製、および削除できます。

link:../api/concept_element_api_snapshots_overview.html["ボリュームスナップショットAPIメソッドについて学ぶ"]



== 仮想ボリュームAPIメソッド

Element ソフトウェア仮想ボリューム API メソッドを使用すると、仮想ボリューム (VVol) を管理できます。これらの API メソッドを使用して、既存の VVol を表示したり、仮想ボリューム ストレージ コンテナーを作成、変更、削除したりできます。これらのメソッドを使用して通常のボリュームを操作することはできませんが、通常のボリューム API メソッドを使用して VVol に関する情報を一覧表示することはできます。

link:../api/reference_element_api_createstoragecontainer.html["仮想ボリュームAPIメソッドについて学ぶ"]



== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFireおよび Element 製品の以前のバージョンのドキュメント"^]

