---
permalink: api/concept_element_api_asynchronous_methods.html 
sidebar: sidebar 
keywords: async,asynchronous,methods,API 
summary: 一部の API メソッドは非同期であるため、メソッドが返されたときに実行される操作が完了していない可能性があります。非同期メソッドは、操作のステータスを確認するために照会できるハンドルを返します。一部の操作のステータス情報には、完了率が含まれる場合があります。 
---
= 非同期メソッド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一部の API メソッドは非同期であるため、メソッドが返されたときに実行される操作が完了していない可能性があります。非同期メソッドは、操作のステータスを確認するために照会できるハンドルを返します。一部の操作のステータス情報には、完了率が含まれる場合があります。

非同期操作をクエリすると、その結果は次のいずれかの型になります。

* `DriveAdd`: システムはクラスターにドライブを追加しています。
* `BulkVolume`: システムは、バックアップや復元など、ボリューム間のコピー操作を実行しています。
* `Clone`: システムはボリュームの複製を行っています。
* `DriveRemoval`: システムは、クラスターからドライブを削除する準備として、ドライブからデータをコピーしています。
* `RtfiPendingNode`: システムは、ノードをクラスターに追加する前に、互換性のあるソフトウェアをノードにインストールしています。


非同期メソッドを使用する場合、または実行中の非同期操作のステータスを取得する場合は、次の点に注意してください。

* 非同期メソッドは、個々のメソッドのドキュメントに示されます。
* 非同期メソッドは、発行 API メソッドによって認識されるハンドルである「`asyncHandle`」を返します。ハンドルを使用して、非同期操作のステータスまたは結果をポーリングできます。
* GetAsyncResult メソッドを使用して、個々の非同期メソッドの結果を取得できます。  GetAsyncResult を使用して完了した操作を照会すると、システムは結果を返し、その結果をシステムから自動的に消去します。  GetAsyncResult を使用して不完全な操作を照会すると、システムは結果を返しますが、それを消去しません。
* ListAsyncResults メソッドを使用して、実行中または完了したすべての非同期メソッドの状態と結果を取得できます。この場合、システムは完了した操作の結果を削除しません。




== 詳細情報の参照

* https://docs.netapp.com/us-en/element-software/index.html["SolidFireおよびElementソフトウェアのドキュメント"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFireおよび Element 製品の以前のバージョンのドキュメント"^]

