---
permalink: api/reference_element_api_resyncsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,resync,resyncing,ResyncSnapMirrorRelationship 
summary: Element ソフトウェア Web UI は、ResyncSnapMirrorRelationship メソッドを使用して、ソース エンドポイントと宛先エンドポイント間のミラー関係を確立または再確立します。関係を再同期すると、システムは、共通スナップショット コピーよりも新しい宛先ボリューム上のスナップショットを削除し、共通スナップショット コピーをエクスポートされたスナップショット コピーとして使用して、宛先ボリュームをデータ保護ボリュームとしてマウントします。 
---
= スナップミラー関係の再同期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ElementソフトウェアのWeb UIは、 `ResyncSnapMirrorRelationship`ソースエンドポイントと宛先エンドポイント間のミラー関係を確立または再確立する方法。関係を再同期すると、システムは、共通スナップショット コピーよりも新しい宛先ボリューム上のスナップショットを削除し、共通スナップショット コピーをエクスポートされたスナップショット コピーとして使用して、宛先ボリュームをデータ保護ボリュームとしてマウントします。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
スナップミラーエンドポイントID
 a| 
Element ストレージ クラスタと通信するリモートONTAPストレージ システムのエンドポイント ID。
 a| 
integer
 a| 
なし
 a| 
はい



 a| 
宛先ボリューム
 a| 
SnapMirror関係の宛先ボリューム。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[スナップミラーボリューム情報]
 a| 
なし
 a| 
はい



 a| 
最大転送速度
 a| 
ボリューム間の最大データ転送速度をキロバイト/秒単位で指定します。デフォルト値 0 は無制限であり、 SnapMirror関係で利用可能なネットワーク帯域幅を完全に利用できるようになります。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
ソースボリューム
 a| 
SnapMirror関係のソース ボリューム。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[スナップミラーボリューム情報]
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
スナップミラー関係
 a| 
再同期されたSnapMirror関係に関する情報を含むオブジェクト。
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[スナップミラー関係]

|===


== バージョン以降の新機能

10.1
