---
permalink: api/reference_element_api_addclusteradmin.html 
sidebar: sidebar 
keywords: addclusteradmin,cluster,admin,administrator,adding,add 
summary: AddClusterAdmin メソッドを使用して、新しいクラスター管理者アカウントを追加できます。クラスター管理者は、API と管理ツールを使用してクラスターを管理できます。クラスター管理者は標準のテナント アカウントとは完全に別個であり、無関係です。 
---
= クラスタ管理者の追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `AddClusterAdmin`新しいクラスター管理者アカウントを追加する方法。クラスター管理者は、API と管理ツールを使用してクラスターを管理できます。クラスター管理者は標準のテナント アカウントとは完全に別個であり、無関係です。

各クラスター管理者は、API のサブセットに制限できます。異なるユーザーおよびアプリケーションには複数のクラスター管理者アカウントを使用する必要があります。ベストプラクティスとして、各クラスター管理者に必要な最小限の権限を付与します。これにより、資格情報の侵害による潜在的な影響が軽減されます。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
アクセス
 a| 
クラスター管理者が使用できる方法を制御します。
 a| 
文字列配列
 a| 
なし
 a| 
はい



 a| 
EULAを受け入れる
 a| 
エンド ユーザ ライセンス契約に同意します。クラスター管理者アカウントをシステムに追加するには、true に設定します。省略または false に設定された場合、メソッド呼び出しは失敗します。
 a| 
ブーリアン
 a| 
なし
 a| 
はい



 a| 
attributes
 a| 
JSON オブジェクト形式の名前/値のペアのリスト。
 a| 
JSONオブジェクト
 a| 
なし
 a| 
いいえ



 a| 
パスワード
 a| 
このクラスター管理者を認証するために使用されるパスワード。
 a| 
string
 a| 
なし
 a| 
はい



 a| 
ユーザ名
 a| 
このクラスター管理者の一意のユーザー名。長さは 1 ～ 1024 文字にする必要があります。
 a| 
string
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
クラスター管理者ID
 a| 
新しく作成されたクラスター管理者の ClusterAdminID。
 a| 
integer

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "AddClusterAdmin",
  "params": {
    "username": "joeadmin",
    "password": "68!5Aru268)$",
    "attributes": {},
    "acceptEula": true,
    "access": ["volumes", "reporting", "read"]
  },
  "id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id":1,
  "result" : {
    "clusterAdminID": 2
   }
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

xref:reference_element_api_app_b_access_control.adoc[アクセス制御]
