---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: ListDriveStats メソッドを使用すると、クラスター内の複数のドライブの高レベルのアクティビティ測定値を一覧表示できます。デフォルトでは、このメソッドはクラスター内のすべてのドライブの統計を返します。これらの測定値は、ドライブをクラスターに追加してから累積されます。このメソッドが返す値の中にはブロック ドライブに固有のものもあれば、メタデータ ドライブに固有のものもあります。 
---
= リストドライブ統計
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ListDriveStats`クラスター内の複数のドライブの高レベルのアクティビティ測定値を一覧表示するメソッド。デフォルトでは、このメソッドはクラスター内のすべてのドライブの統計を返します。これらの測定値は、ドライブをクラスターに追加してから累積されます。このメソッドが返す値の中にはブロック ドライブに固有のものもあれば、メタデータ ドライブに固有のものもあります。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
ドライブ
 a| 
ドライブ統計を返すドライブ ID (driveID) のリスト。このパラメータを省略すると、すべてのドライブの測定値が返されます。
 a| 
整数配列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
ドライブ統計
 a| 
各ドライブのドライブアクティビティ情報のリスト。
 a| 
xref:reference_element_api_drivestats.adoc[ドライブ統計]配列



 a| 
errors
 a| 
このリストには、ドライブ ID と関連するエラー メッセージが含まれています。常に存在し、エラーがない場合は空になります。
 a| 
JSONオブジェクト配列

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

xref:reference_element_api_getdrivestats.adoc[ドライブ統計を取得]
