---
permalink: api/reference_element_api_getvolumeefficiency.html 
sidebar: sidebar 
keywords: volume,volumes,get,getting,stats,measurements,efficiency,GetVolumeEfficiency 
summary: GetVolumeEfficiency メソッドを使用してボリュームに関する情報を取得できます。この API メソッドでパラメータとして指定したボリュームのみが容量の計算に使用されます。 
---
= ボリューム効率の取得
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `GetVolumeEfficiency`ボリュームに関する情報を取得するメソッド。この API メソッドでパラメータとして指定したボリュームのみが容量の計算に使用されます。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
volumeID
 a| 
容量を計算するボリュームを指定します。
 a| 
integer
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
圧縮
 a| 
単一ボリューム上のデータを圧縮することで節約されるスペースの量。比率で表され、1 はデータが圧縮されずに保存されていることを意味します。
 a| 
float



 a| 
重複排除
 a| 
データを重複させないことで単一ボリューム上で節約されるスペースの量。比率で表します。
 a| 
float



 a| 
不足しているボリューム
 a| 
効率データのクエリができなかったボリューム。ボリュームの欠落は、ガベージ コレクション (GC) が 1 時間未満であること、一時的なネットワーク損失、または GC サイクル以降のサービスの再起動によって発生する可能性があります。
 a| 
整数配列



 a| 
シンプロビジョニング
 a| 
データの保存に割り当てられたスペースの量に対する使用済みスペースの比率。比率で表します。
 a| 
float



 a| 
タイムスタンプ
 a| 
GC 後に効率データが最後に収集されたとき。
 a| 
ISO 8601データ文字列

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "GetVolumeEfficiency",
   "params": {
      "volumeID": 606
   },
   "id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.001591240821456,
       "deduplication": 1,
       "missingVolumes": [],
       "thinProvisioning": 1.009861932938856,
       "timestamp": "2014-03-10T16:06:33Z"
   }
}
----


== バージョン以降の新機能

9.6
