---
permalink: api/reference_element_api_removeinitiatorsfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: initiators,initiator,volume,access,group,remove,removing,removeinitiatorsfromvolumeaccessgroup 
summary: RemoveInitiatorsFromVolumeAccessGroup メソッドを使用して、指定したボリューム アクセス グループからイニシエーターを削除できます。 
---
= ボリュームアクセスグループからイニシエーターを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `RemoveInitiatorsFromVolumeAccessGroup`指定されたボリューム アクセス グループからイニシエーターを削除する方法。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
ボリュームアクセスグループID
 a| 
イニシエーターが削除されるボリューム アクセス グループの ID。
 a| 
integer
 a| 
なし
 a| 
はい



 a| 
イニシエータ
 a| 
ボリューム アクセス グループに含めるイニシエーター ID または名前 (IQN および WWPN) のリスト。イニシエーター名のリストを渡すと、イニシエーターがまだ存在しない場合は作成されます。イニシエーター ID のリストを渡す場合、いずれかのイニシエーターがまだ存在しないと、メソッドはエラーを返します。イニシエーター名を渡すことは非推奨です。可能な場合はイニシエーター ID を使用する必要があります。
 a| 
整数配列（推奨）または文字列配列（非推奨）
 a| 
なし
 a| 
いいえ



 a| 
孤立イニシエーターの削除
 a| 
イニシエーター オブジェクトをボリューム アクセス グループから削除した後に削除するかどうかを指定します。有効な値は次のとおりです。

* true: ボリューム アクセス グループから削除された後、イニシエーター オブジェクトを削除します。
* false: ボリューム アクセス グループから削除された後、イニシエーター オブジェクトを削除しません。これがデフォルトです。

 a| 
ブーリアン
 a| 
false
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| Name | 説明 | タイプ 


 a| 
ボリュームアクセスグループ
 a| 
新しく変更されたボリューム アクセス グループに関する情報を含むオブジェクト。
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[ボリュームアクセスグループ]

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "id": 13171,
  "method": "RemoveInitiatorsFromVolumeAccessGroup",
  "params": {
    "initiators": [114,115],
    "volumeAccessGroupID": 96
  }
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 13171,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [],
      "initiators": [],
      "name": "test",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== バージョン以降の新機能

9.6
