---
permalink: api/reference_element_api_snapshot.html 
sidebar: sidebar 
keywords: object,objects,snapshot 
summary: スナップショット オブジェクトには、ボリュームに対して作成されたスナップショットに関する情報が含まれています。 ListSnapshots API メソッドを使用して、ボリュームまたはすべてのボリュームのスナップショット情報のリストを取得できます。オブジェクトには、アクティブなスナップショットと、ボリュームに対して作成された各スナップショットに関する情報が含まれます。 
---
= Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スナップショット オブジェクトには、ボリュームに対して作成されたスナップショットに関する情報が含まれています。使用することができます `ListSnapshots`ボリュームまたはすべてのボリュームのスナップショット情報のリストを取得するための API メソッド。オブジェクトには、アクティブなスナップショットと、ボリュームに対して作成された各スナップショットに関する情報が含まれます。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSONオブジェクト



 a| 
checksum
 a| 
保存されたスナップショット内のデータの小さな文字列表現。このチェックサムは、後で他のスナップショットと比較してデータ内のエラーを検出するために使用できます。
 a| 
string



 a| 
作成時間
 a| 
スナップショットが作成された UTC+0 形式の時刻。
 a| 
ISO 8601日付文字列



 a| 
リモートレプリケーションを有効にする
 a| 
リモート レプリケーションのスナップショットが有効になっているかどうかを識別します。
 a| 
ブーリアン



 a| 
有効期限
 a| 
スナップショットの有効期限がどのように設定されているかを示します。有効な値は次のとおりです。

* Api: 有効期限は API を使用して設定されます。
* なし: 有効期限は設定されていません。
* テスト: テスト用に有効期限が設定されます。
* fifo: 有効期限は先入先出方式で発生します。

 a| 
string



 a| 
有効期限
 a| 
このスナップショットが期限切れになり、クラスターから削除される時刻。
 a| 
ISO 8601日付文字列



 a| 
groupID
 a| 
スナップショットがグループ スナップショットのメンバーである場合のグループ ID。
 a| 
integer



 a| 
グループスナップショットUUID
 a| 
グループ内の各スナップショットに関する情報が含まれます。これらの各メンバーには、スナップショットの UUID 用の UUID パラメーターがあります。
 a| 
string



 a| 
インスタンス作成時間
 a| 
ローカル クラスターでスナップショットが作成された時刻。
 a| 
ISO 8601日付文字列



 a| 
インスタンススナップショットUUID
 a| 
ローカル クラスター上のスナップショットのユニバーサルに一意の ID。この ID は他のクラスターに複製されません。
 a| 
string



 a| 
名前
 a| 
スナップショットに割り当てられた一意の名前。名前が指定されていない場合、名前はスナップショットが作成された時点の UTC+0 形式のタイムスタンプになります。
 a| 
string



 a| 
リモートステータス
 a| 
ソース クラスターから見たターゲット クラスター上の各リモート スナップショットのユニバーサル識別子とレプリケーション ステータスを含む配列。
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[リモートクラスタスナップショットステータス]配列



 a| 
スナップミラーラベル
 a| 
SnapMirrorエンドポイントのスナップショット保持ポリシーを指定するためにSnapMirrorソフトウェアによって使用されるラベル。設定されていない場合、この値は null になります。
 a| 
string



 a| 
スナップショットID
 a| 
既存のスナップショットの一意の ID。
 a| 
string



 a| 
スナップショットUUID
 a| 
既存のスナップショットのユニバーサルに一意の ID。スナップショットがクラスター間で複製されると、この ID も一緒に複製され、クラスター間でスナップショットを識別するために使用されます。
 a| 
string



 a| 
ステータス
 a| 
スナップショットの現在のステータス。有効な値は次のとおりです。

* 不明: スナップショットのステータスの取得中にエラーが発生しました。
* 準備中: このスナップショットは使用準備中であり、まだ書き込み可能ではありません。
* RemoteSyncing: このスナップショットはリモート クラスターから複製されています。
* 完了: このスナップショットは準備またはレプリケーションが完了し、使用可能になりました。
* アクティブ: このスナップショットはアクティブ ブランチです。
* クローン作成: このスナップショットは CopyVolume 操作に関係しています。

 a| 
string



 a| 
合計サイズ
 a| 
スナップショットの合計サイズ（バイト単位）。
 a| 
integer



 a| 
仮想ボリュームID
 a| 
このスナップショットに関連付けられている仮想ボリュームの ID。
 a| 
UUID



 a| 
volumeID
 a| 
スナップショットが作成されたボリュームの ID。
 a| 
integer



 a| 
volumeName
 a| 
スナップショットが作成された時点のボリュームの名前。
 a| 
string

|===


== 詳細情報の参照

xref:reference_element_api_listsnapshots.adoc[リストスナップショット]
