---
permalink: api/reference_element_api_listvirtualnetworks.html 
sidebar: sidebar 
keywords: virtual,network,networks,listing,list,listvirtualnetworks 
summary: ListVirtualNetworks メソッドを使用して、クラスターに構成されているすべての仮想ネットワークを一覧表示できます。 
---
= ListVirtualNetworks
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ListVirtualNetworks`クラスターに構成されているすべての仮想ネットワークを一覧表示するメソッド。

この方法を使用して、クラスター内の仮想ネットワーク設定を確認できます。このメソッドには必須のパラメータはありません。ただし、結果をフィルタリングするには、1 つ以上の virtualNetworkID または virtualNetworkTag 値を渡すことができます。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
仮想ネットワークID
 a| 
単一の仮想ネットワークのリストをフィルターするためのネットワーク ID。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
仮想ネットワークタグ
 a| 
単一の仮想ネットワークのリストをフィルターするためのネットワーク タグ。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
仮想ネットワークID
 a| 
リストに含めるネットワーク ID。
 a| 
整数配列
 a| 
なし
 a| 
いいえ



 a| 
仮想ネットワークタグ
 a| 
リストに含めるネットワーク タグ。
 a| 
整数配列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
仮想ネットワーク
 a| 
仮想ネットワーク IP アドレスを含むオブジェクト。
 a| 
xref:reference_element_api_virtualnetwork.adoc[仮想ネットワーク]

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "ListVirtualNetworks",
  "params": {
     "virtualNetworkIDs": [5,6]
   },
"id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "virtualNetworks": [
   {
    "addressBlocks": [
   {
    "available": "11000000",
    "size": 8,
    "start": "10.26.250.207"
   }
 ],
    "attributes": null,
    "gateway": "10.26.250.254",
    "name": "2250",
    "namespace": false,
    "netmask": "255.255.255.0",
    "svip": "10.26.250.200",
    "virtualNetworkID": 2250
   },
   {
     "addressBlocks": [
   {
     "available": "11000000",
     "size": 8,
     "start": "10.26.241.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.241.254",
     "name": "2241",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.241.200",
     "virtualNetworkID": 2241
   },
  {
     "addressBlocks": [
  {
     "available": "11000000",
     "size": 8,
     "start": "10.26.240.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.240.254",
     "name": "2240",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.240.200",
     "virtualNetworkID": 2240
    },
   {
  }
 ]
}
----


== バージョン以降の新機能

9.6
