---
permalink: api/reference_element_api_node.html 
sidebar: sidebar 
keywords: object,objects,node 
summary: ノード オブジェクトには、クラスター内の各ノードに関する情報が含まれています。この情報は、ListActiveNodes メソッドと ListAllNodes メソッドを使用して取得できます。 
---
= ノード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノード オブジェクトには、クラスター内の各ノードに関する情報が含まれています。この情報は、 `ListActiveNodes`そして `ListAllNodes`方法。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
関連FサービスID
 a| 
ノードのファイバー チャネル サービス ID。ノードがファイバー チャネル ノードでない場合は「0」。
 a| 
integer



 a| 
関連マスターサービスID
 a| 
ノードのマスター サービス ID。
 a| 
integer



 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSONオブジェクト



 a| 
シャーシ名
 a| 
シャーシを一意に識別します。単一シャーシ内のすべてのノードで同一です。
 a| 
string



 a| 
シップ
 a| 
ノードに割り当てられたクラスター IP アドレス。
 a| 
string



 a| 
シピ
 a| 
クラスター通信に使用されるネットワーク インターフェイス。
 a| 
string



 a| 
カスタム保護ドメイン名
 a| 
カスタム保護ドメインを一意に識別します。この名前は、特定のカスタム保護ドメイン内のすべてのシャーシ内のすべてのストレージ ノードで同一です。
 a| 
string



 a| 
ファイバーチャネルターゲットポートグループ
 a| 
このノードに関連付けられたターゲット グループ。ノードがファイバー チャネル ノードでない場合は "null" になります。
 a| 
integer



 a| 
メンテナンスモード
 a| 
ノードがメンテナンスのためにどのモードになっているかを示します。
 a| 
N/A



 a| 
ミップ
 a| 
ノード管理に使用される IP アドレス。
 a| 
string



 a| 
ミピ
 a| 
ノード管理に使用されるネットワーク インターフェイス。
 a| 
string



 a| 
名前
 a| 
ノードのホスト名。
 a| 
string



 a| 
nodeID
 a| 
このノードのノードID。
 a| 
integer



 a| 
ノードスロット
 a| 
HCI プラットフォームの場合、このノードが存在するシャーシ スロットに対応する文字 (「A」、「B」、「C」、または「D」)。ストレージ プラットフォームの場合、この値は null です。
 a| 
string



 a| 
プラットフォーム情報
 a| 
ノードのハードウェア情報。メンバー:

* chassisType: ノードのハードウェア プラットフォーム。
* cpuModel: ハードウェア プラットフォームの CPU モデル。
* nodeMemoryGB: 物理プラットフォームにインストールされているメモリの量 (GB)。
* nodeType: ノード モデル名。
* platformConfigVersion: このノード ハードウェア用に構成されたソフトウェアのバージョン。

 a| 
JSONオブジェクト



 a| 
ロール
 a| 
クラスター内のノードの役割。有効な値は次のとおりです。

* 管理
* ストレージ
* コンピューティング
* 監視

 a| 



 a| 
一口飲む
 a| 
ノードに割り当てられたストレージ IP アドレス。
 a| 
string



 a| 
シピ
 a| 
ストレージ トラフィックに使用されるネットワーク インターフェイス。
 a| 
string



 a| 
ソフトウェアバージョン
 a| 
ノード上で実行されている Element ソフトウェアの現在のバージョンを返します。
 a| 
string



 a| 
uuid
 a| 
このノードに関連付けられたユニバーサル一意識別子。
 a| 
string



 a| 
仮想ネットワーク
 a| 
仮想ネットワークの IP アドレスと ID を含むオブジェクト。
 a| 
xref:reference_element_api_virtualnetwork.adoc[仮想ネットワーク]配列

|===


== 詳細情報の参照

* xref:reference_element_api_listactivenodes.adoc[ListActiveNodes]
* xref:reference_element_api_listallnodes.adoc[すべてのノードをリスト]

