---
permalink: api/reference_element_api_clusterstats.html 
sidebar: sidebar 
keywords: objects,clusterStats 
summary: clusterStats オブジェクトには、クラスターの統計データが含まれています。オブジェクトに含まれるボリューム関連の統計の多くは、クラスター内のすべてのボリュームについて平均化されます。  GetClusterStats メソッドを使用して、クラスターのこの情報を取得できます。 
---
= クラスター統計
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clusterStats オブジェクトには、クラスターの統計データが含まれています。オブジェクトに含まれるボリューム関連の統計の多くは、クラスター内のすべてのボリュームについて平均化されます。  GetClusterStats メソッドを使用して、クラスターのこの情報を取得できます。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | 計算式 | タイプ 


 a| 
実際のIOPS
 a| 
過去 500 ミリ秒間のクラスター全体の現在の実際の IOPS。
 a| 
ポイントインタイム
 a| 
integer



 a| 
平均IOPサイズ
 a| 
過去 500 ミリ秒間のクラスターへの最近の I/O の平均サイズ (バイト単位)。
 a| 
ポイントインタイム
 a| 
integer



 a| 
クライアントキュー深度
 a| 
クラスターへの未処理の読み取りおよび書き込み操作の数。
 a| 
該当なし
 a| 
integer



 a| 
クラスター使用率
 a| 
現在使用されているクラスターの最大 IOPS の割合。これは、clusterUtilization = normalizedIOPS / maxIOPS (GetClusterCapacity から) として計算されます。
 a| 
該当なし
 a| 
float



 a| 
レイテンシUSec
 a| 
過去 500 ミリ秒間にクラスターへの操作を完了するのにかかった平均時間 (マイクロ秒単位)。
 a| 
ポイントインタイム
 a| 
integer



 a| 
正規化されたIOPS
 a| 
過去 500 ミリ秒間のクラスター全体の IOPS の平均数。
 a| 
ポイントインタイム
 a| 
integer



 a| 
readBytes
 a| 
クラスターの作成以降にクラスターから読み取られた合計累積バイト数。
 a| 
単調増加
 a| 
integer



 a| 
最終サンプルバイト読み取り
 a| 
最後のサンプル期間中にクラスターから読み取られたバイトの合計数。
 a| 
ポイントインタイム
 a| 
integer



 a| 
読み取りレイテンシUSec
 a| 
過去 500 ミリ秒間にクラスターへの読み取り操作を完了するのにかかった平均時間 (マイクロ秒単位)。
 a| 
ポイントインタイム
 a| 
integer



 a| 
読み取りレイテンシUSec合計
 a| 
クラスターの作成以降に読み取り操作を実行するのに費やされた合計時間。
 a| 
単調増加
 a| 
integer



 a| 
readOps
 a| 
クラスターの作成以降のクラスターへの累積読み取り操作の合計。
 a| 
単調増加
 a| 
integer



 a| 
読み取り操作最終サンプル
 a| 
最後のサンプル期間中の読み取り操作の合計数。
 a| 
ポイントインタイム
 a| 
integer



 a| 
サンプル期間ミリ秒
 a| 
サンプル期間の長さ（ミリ秒単位）。
 a| 
該当なし
 a| 
integer



 a| 
サービス数
 a| 
クラスター上で実行されているサービスの数。  servicesTotal と等しい場合、すべてのノードから有効な統計が収集されたことを示します。
 a| 
ポイントインタイム
 a| 
integer



 a| 
サービス合計
 a| 
クラスター上で実行されると予想されるサービスの合計数。
 a| 
該当なし
 a| 
integer



 a| 
タイムスタンプ
 a| 
UTC+0 形式の現在の時刻。
 a| 
該当なし
 a| 
ISO 8601日付文字列



 a| 
非整列読み取り
 a| 
クラスターの作成以降のクラスターに対する累積非整列読み取り操作の合計。
 a| 
単調増加
 a| 
integer



 a| 
非整列書き込み
 a| 
クラスターの作成以降にクラスターに対して行われた、アラインメントされていない書き込み操作の累計数。
 a| 
単調増加
 a| 
integer



 a| 
writeBytes
 a| 
クラスターの作成以降にクラスターに書き込まれた合計累積バイト数。
 a| 
単調増加
 a| 
integer



 a| 
書き込みバイト最終サンプル
 a| 
最後のサンプル期間中にクラスターに書き込まれたバイトの合計数。
 a| 
単調増加
 a| 
integer



 a| 
書き込みレイテンシUSec
 a| 
過去 500 ミリ秒間にクラスターへの書き込み操作を完了するのにかかった平均時間 (マイクロ秒単位)。
 a| 
ポイントインタイム
 a| 
integer



 a| 
書き込みレイテンシUSec合計
 a| 
クラスターの作成以降に書き込み操作を実行するのに費やされた合計時間。
 a| 
単調増加
 a| 
integer



 a| 
writeOps
 a| 
クラスターの作成以降のクラスターへの累積書き込み操作の合計。
 a| 
単調増加
 a| 
integer



 a| 
書き込み操作最終サンプル
 a| 
最後のサンプル期間中の書き込み操作の合計数。
 a| 
ポイントインタイム
 a| 
integer

|===


== 詳細情報の参照

xref:reference_element_api_getclusterstats.adoc[クラスター統計情報を取得する]
