---
permalink: api/reference_element_api_getclustercapacity.html 
sidebar: sidebar 
keywords: cluster,capacity,getting,get,measurements,measure,deduplication,GetClusterCapacity 
summary: GetClusterCapacity を使用すると、ストレージ クラスター全体の高レベルの容量測定値を返すことができます。このメソッドは、Element Web UI に表示される効率率を計算するために使用できるフィールドを返します。スクリプト内の効率計算を使用して、シン プロビジョニング、重複排除、圧縮、および全体的な効率の効率率を返すことができます。 
---
= クラスタ容量の取得
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `GetClusterCapacity`ストレージ クラスター全体の高レベルの容量測定値を返します。このメソッドは、Element Web UI に表示される効率率を計算するために使用できるフィールドを返します。スクリプト内の効率計算を使用して、シン プロビジョニング、重複排除、圧縮、および全体的な効率の効率率を返すことができます。



== 効率計算

シン プロビジョニング、重複排除、および圧縮を計算するには、次の式を使用します。これらの式は要素 8.2 以降に適用されます。

* thinProvisioningFactor = (非ゼロブロック数 + ゼロブロック数) / 非ゼロブロック数
* deDuplicationFactor = (nonZeroBlocks + snapshotNonZeroBlocks) / uniqueBlocks
* 圧縮係数 = (ユニークブロック * 4096) / (ユニークブロック使用スペース * 0.93)




== 総合効率計算

シン プロビジョニング、重複排除、および圧縮の効率計算の結果を使用して、次の式を使用してクラスター全体の効率を計算します。

* 効率係数 = シンプロビジョニング係数 * 重複排除係数 * 圧縮係数




== パラメータ

このメソッドには入力パラメータはありません。



== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| Name | 説明 | タイプ 


 a| 
クラスター容量
 a| 
ストレージ クラスターの容量測定。
 a| 
xref:reference_element_api_clustercapacity.adoc[クラスター容量]

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "GetClusterCapacity",
   "params": {},
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "clusterCapacity": {
      "activeBlockSpace": 236015557096,
      "activeSessions": 20,
      "averageIOPS": 0,
      "clusterRecentIOSize": 0,
      "currentIOPS": 0,
      "maxIOPS": 150000,
      "maxOverProvisionableSpace": 259189767127040,
      "maxProvisionedSpace": 51837953425408,
      "maxUsedMetadataSpace": 404984011161,
      "maxUsedSpace": 12002762096640,
      "nonZeroBlocks": 310080350,
      "peakActiveSessions": 20,
      "peakIOPS": 0,
      "provisionedSpace": 1357931085824,
      "snapshotNonZeroBlocks": 0,
      "timestamp": "2016-10-17T21:24:36Z",
      "totalOps": 1027407650,
      "uniqueBlocks": 108180156,
      "uniqueBlocksUsedSpace": 244572686901,
      "usedMetadataSpace": 8745762816,
      "usedMetadataSpaceInSnapshots": 8745762816,
      "usedSpace": 244572686901,
      "zeroBlocks": 352971938
    }
  }
}
----


== バージョン以降の新機能

9.6
