---
permalink: api/reference_element_api_createsupportbundle.html 
sidebar: sidebar 
keywords: create,creating,support,bundle,CreateSupportBundle 
summary: CreateSupportBundle を使用して、ノードのディレクトリの下にサポート バンドル ファイルを作成できます。作成後、バンドルは tar.gz ファイルとしてノードに保存されます。 
---
= サポートバンドルの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用できます `CreateSupportBundle`ノードのディレクトリの下にサポート バンドル ファイルを作成します。作成後、バンドルは tar ファイルとしてノードに保存されます (gz 圧縮オプションは extraArgs パラメータ経由で使用できます)。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
バンドル名
 a| 
サポート バンドルの一意の名前。名前が指定されていない場合は、「supportbundle」とノード名がファイル名として使用されます。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
追加引数
 a| 
サポート バンドルを tar.gz ファイルとして作成するには、「--compress gz」を使用します。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
タイムアウト秒
 a| 
サポート バンドル スクリプトが実行される秒数。
 a| 
integer
 a| 
1500
 a| 
いいえ

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
詳細
 a| 
サポート バンドルの詳細。有効な値は次のとおりです。

* bundleName: CreateSupportBundleAPI メソッドで指定された名前。名前が指定されていない場合は、「supportbundle」が使用されます。
* extraArgs: このメソッドで渡される引数。
* files: システムによって作成されたサポート バンドル ファイルのリスト。
* 出力: サポート バンドルを作成したスクリプトからのコマンド ライン出力。
* timeoutSec: サポート バンドル スクリプトが停止するまでの実行秒数。
* url: 作成されたサポート バンドルの URL。

 a| 
JSONオブジェクト



 a| 
duration
 a| 
サポート バンドルの作成に使用された時間 (形式: HH:MM:SS.ssssss)。
 a| 
string



 a| 
結果
 a| 
サポート バンドル操作の成功または失敗。
 a| 
string

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
 "method": "CreateSupportBundle",
"params": {
  "extraArgs": "--compress gz"
 },
"id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
"id": 1,
"result": {
  "details": {
    "bundleName": "supportbundle",
    "extraArgs": "--compress gz",
    "files": [
         "supportbundle.nodehostname.tar.gz"
     ],
     "output": "timeout -s KILL 1500s /sf/scripts/sfsupportbundle --quiet --compress gz /tmp/solidfire-dtemp.1L6bdX/supportbundle<br><br>Moved '/tmp/solidfire-dtemp.1L6bdX/supportbundle.nodehostname.tar.gz' to /tmp/supportbundles",
      "timeoutSec": 1500,
      "url": [
          "https://nodeIP:442/config/supportbundles/supportbundle.nodehostname.tar.gz"
      ]
    },
    "duration": "00:00:43.101627",
    "result": "Passed"
  }
}
----


== バージョン以降の新機能

9.6
