---
permalink: api/reference_element_api_modifyvolumepair.html 
sidebar: sidebar 
keywords: volume,pair,pairs,modify,modifying,edit,editing,changing,change,modifyvolumepair,paired 
summary: 'ModifyVolumePair メソッドを使用して、ボリュームのペア間のレプリケーションを一時停止または再開できます。このメソッドは、ソース ボリューム (読み取り/書き込みアクセス権を持つボリューム) に設定されます。' 
---
= ボリュームペアの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ModifyVolumePair`ボリュームのペア間のレプリケーションを一時停止または再開する方法。このメソッドは、ソース ボリューム (読み取り/書き込みアクセス権を持つボリューム) に設定されます。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===


| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
volumeID
 a| 
変更するボリュームの識別番号。
 a| 
integer
 a| 
なし
 a| 
はい



 a| 
一時停止手動
 a| 
リモート レプリケーションは、ソース (読み取り/書き込み) ボリュームで一時停止または再開できます。有効な値は次のとおりです。

* true: ボリュームのレプリケーションを一時停止します。
* false: ボリュームのレプリケーションを再起動します。


値を指定しない場合は、レプリケーションの変更は実行されません。
 a| 
ブーリアン
 a| 
なし
 a| 
いいえ



 a| 
モード
 a| 
ボリュームレプリケーションモード。有効な値は次のとおりです。

* 非同期: 書き込みはローカルで完了すると確認されます。クラスターは、書き込みがターゲット クラスターに複製されるまで待機しません。
* 同期: データがローカルおよびリモート クラスターに保存されると、ソースは書き込みを確認します。
* SnapshotsOnly: ソース クラスターで作成されたスナップショットのみがレプリケートされます。ソース ボリュームからのアクティブな書き込みは複製されません。

 a| 
string
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには戻り値はありません。



== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "ModifyVolumePair",
  "params": {
    "pausedManual": false,
    "volumeID": 5,
    "mode": "sync"
   },
  "id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id" : 1,
   "result" : {}
}
----


== バージョン以降の新機能

9.6
