---
permalink: api/reference_element_api_signsshkeys.html 
sidebar: sidebar 
keywords: ssh, sign key 
summary: ノードまたはクラスターで ssh が有効になったら、SignSshKeys メソッドを使用して、sfadmin または sfreadonly としてノード上のシェルにアクセスできます。sfreadonly は、Element 12.5 以降の新しいユーザー アカウントであり、ノードでの初期トラブルシューティングを可能にしますが、昇格されたコマンドを実行する権限がありません。 
---
= 署名Sshキー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSHをクラスタ上で有効にした後、link:../api/reference_element_api_enablessh.html["EnableSSHメソッド"] 、あなたは `SignSshKeys`ノード上のシェルにアクセスする方法。

要素12.5から、 `sfreadonly`新しいシステム アカウントにより、ノード上の基本的なトラブルシューティングが可能になります。このAPIは、 `sfreadonly`クラスター内のすべてのノードにわたるシステム アカウント。


WARNING: NetAppサポートからのアドバイスがない限り、システムへの変更はサポートされず、サポート契約が無効になり、データが不安定になったり、アクセスできなくなる可能性があります。

この方法を使用した後、応答からキーチェーンをコピーし、SSH 接続を開始するシステムに保存して、次のコマンドを実行する必要があります。

[listing]
----
ssh -i <identity_file> sfreadonly@<node_ip>
----
 `identity_file`公開鍵認証のためのID（秘密鍵）が読み取られるファイルであり、 `node_ip`ノードの IP アドレスです。詳細については `identity_file`については、SSH のマニュアル ページを参照してください。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
duration
 a| 
署名されたキーの有効時間数を表す 1 から 24 までの整数。期間が指定されていない場合は、デフォルトが使用されます。
 a| 
integer
 a| 
1
 a| 
いいえ



 a| 
公開鍵
 a| 
指定されている場合、このパラメータは、ユーザーに対して完全なキーチェーンを作成するのではなく、signed_public_key のみを返します。


NOTE: ブラウザのURLバーを使用して送信された公開鍵 `+`スペースとブレークサインとして解釈されます。
 a| 
string
 a| 
Null
 a| 
いいえ



 a| 
sfadmin
 a| 
supportAdmin クラスター アクセスを使用して API 呼び出しを行うとき、またはノードがクラスター内にない場合に、sfadmin シェル アカウントへのアクセスを許可します。
 a| 
ブーリアン
 a| 
間違い
 a| 
いいえ

|===


== 戻り値

このメソッドには次の戻り値があります。

|===
| Name | 説明 | タイプ 


 a| 
キー生成ステータス
 a| 
署名されたキーの ID、許可されたプリンシパル、およびキーの有効な開始日と終了日が含まれます。
 a| 
string



 a| 
秘密鍵
 a| 
秘密 SSH キー値は、API がエンドユーザー用の完全なキーチェーンを生成する場合にのみ返されます。


NOTE: 値は Base64 でエンコードされているため、有効な秘密キーとして読み取られることを確認するために、ファイルに書き込むときに値をデコードする必要があります。
 a| 
string



 a| 
公開鍵
 a| 
公開 SSH キー値は、API がエンドユーザー用の完全なキーチェーンを生成している場合にのみ返されます。


NOTE: APIメソッドにpublic_keyパラメータを渡すと、 `signed_public_key`応答で値が返されます。
 a| 
string



 a| 
署名済み公開鍵
 a| 
公開キーの署名から得られる SSH 公開キー。ユーザーが提供したものでも、API によって生成されたものでもかまいません。
 a| 
string

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
    "method": "SignSshKeys",
    "params": {
        "duration": 2,
        "publicKey":<string>
    },
    "id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": null,
  "result": {
    "signedKeys": {
      "keygen_status": <keygen_status>,
      "signed_public_key": <signed_public_key>
    }
  }
}
----
この例では、一定期間（1 ～ 24 時間）有効な公開キーが署名され、返されます。



== バージョン以降の新機能

12.5
