---
permalink: api/reference_element_api_setconfig.html 
sidebar: sidebar 
keywords: config,configuration,set,setting,node,setconfig,network,cluster 
summary: SetConfig メソッドを使用して、ノードのネットワークおよびクラスター情報を設定できます。このメソッドには、SetClusterConfig メソッドと SetNetworkConfig メソッドの両方で使用できる同じ設定が単一の API メソッドに含まれています。このメソッドでは、変更するフィールドのみを含める必要があります。 
---
= 設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `SetConfig`ノードのネットワークとクラスター情報を設定するメソッド。このメソッドは、両方のAPIメソッドで使用できる同じ設定を単一のAPIメソッドに含めます。 `SetClusterConfig`そして `SetNetworkConfig`方法。このメソッドでは、変更するフィールドのみを含める必要があります。



== パラメータ

警告：

ノードのボンド モードを変更すると、ネットワーク接続が一時的に失われる可能性があります。

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
cluster
 a| 
ストレージ ノードが関連付けられているストレージ クラスターと通信する方法を識別するクラスター情報。
 a| 
xref:reference_element_api_cluster.adoc[cluster]
 a| 
なし
 a| 
いいえ



 a| 
network
 a| 
ノードの各ネットワーク インターフェイスのネットワーク接続タイプと現在の設定。
 a| 
xref:reference_element_api_network_all_interfaces.adoc[ネットワーク（すべてのインターフェース）]
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| Name | 説明 | タイプ 


 a| 
設定
 a| 
ノードの新しい現在の構成。このオブジェクトには次のものが含まれます。

* xref:reference_element_api_cluster.adoc[cluster]: ストレージ ノードが関連付けられているストレージ クラスターと通信する方法を識別するクラスター情報。
* xref:reference_element_api_network_all_interfaces.adoc[ネットワーク（すべてのインターフェース）]: ノードの各ネットワーク インターフェイスのネットワーク接続タイプと現在の設定。

 a| 
JSONオブジェクト

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
	"method": "SetConfig",
	"params": {
		"cluster": {
			"name": "MyHostname"
		},
		"network": {
			"Bond10G": {
				"bond-mode": "ALB"
			}
		}
	}
}
----


== 応答例

このメソッドからの応答は、GetConfig メソッドの戻り値と同じです。  SetConfig を使用すると、オブジェクトのすべてのフィールドが表示され、更新された値が表示されます。



== バージョン以降の新機能

9.6



== 詳細情報の参照

* xref:reference_element_api_setclusterconfig.adoc[クラスタ構成の設定]
* xref:reference_element_api_setnetworkconfig.adoc[ネットワーク設定の設定]
* xref:reference_element_api_response_example_getconfig.adoc[ゲットコンフィグ]

