---
permalink: api/reference_element_api_drive.html 
sidebar: sidebar 
keywords: objects,object,drive 
summary: ドライブ オブジェクトには、クラスターのアクティブ ノード内の個々のドライブに関する情報が含まれています。このオブジェクトには、ボリューム メタデータまたはブロック ドライブとして追加されたドライブと、まだ追加されていない使用可能なドライブの詳細が含まれます。この情報は、ListDrives API メソッドを使用して取得できます。 
---
= ドライブ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブ オブジェクトには、クラスターのアクティブ ノード内の個々のドライブに関する情報が含まれています。このオブジェクトには、ボリューム メタデータまたはブロック ドライブとして追加されたドライブと、まだ追加されていない使用可能なドライブの詳細が含まれます。この情報は、 `ListDrives` API メソッド。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。このオブジェクトは常に null であり、変更できません。
 a| 
JSONオブジェクト



 a| 
capacity
 a| 
ドライブの合計容量（バイト単位）。
 a| 
integer



 a| 
シャーシスロット
 a| 
HCI プラットフォームの場合、この値は、このドライブが配置されているサーバー シャーシ内のノード文字とスロット番号です。ストレージ プラットフォームの場合、スロット番号は「スロット」整数の文字列表現です。
 a| 
string



 a| 
ドライブ障害の詳細
 a| 
ドライブのステータスが「失敗」の場合、このフィールドには、ドライブが失敗としてマークされた理由の詳細が表示されます。
 a| 
string



 a| 
ドライブID
 a| 
このドライブの ID。
 a| 
integer



 a| 
ドライブセキュリティ障害の理由
 a| 
ドライブ セキュリティの有効化または無効化に失敗した場合は、失敗した理由。値が「none」の場合、失敗はありませんでした。
 a| 
string



 a| 
キーID
 a| 
このドライブのロックを解除するための認証キーを取得するためにキープロバイダーが使用するキー ID。
 a| 
UUID



 a| 
キープロバイダーID
 a| 
このドライブのロックを解除するための認証キーのプロバイダーを識別します。
 a| 
integer



 a| 
nodeID
 a| 
このドライブを含むノードの ID。
 a| 
integer



 a| 
セグメントファイルサイズ
 a| 
ドライブのセグメント ファイル サイズ (バイト単位)。
 a| 
integer



 a| 
シリアル
 a| 
ドライブのシリアル番号。
 a| 
string



 a| 
slot
 a| 
このドライブが配置されているサーバー シャーシ内のスロット番号。内部メタデータ ドライブに SATADimm デバイスが使用されている場合は -1 です。
 a| 
integer



 a| 
ステータス
 a| 
ドライブのステータス。有効な値は次のとおりです。

* available: 使用可能なドライブ。
* アクティブ: アクティブなドライブ。
* 消去中: ドライブは安全に消去中です。そのドライブ上のすべてのデータは永久に削除されます。
* 失敗: 故障したドライブ。以前ドライブ上にあったデータはすべてクラスター内の他のドライブに移行されています。
* 削除中: ドライブを削除中です。以前ドライブ上にあったデータは、クラスター内の他のドライブに移行されています。

 a| 
string



 a| 
type
 a| 
ドライブの種類。有効な値は次のとおりです。

* volume: ボリュームのメタデータを保存します。
* block: ブロックデータを格納します。
* 不明: ドライブ タイプはまだアクティブではなく、まだ決定されていません。

 a| 
string



 a| 
使用可能容量
 a| 
ドライブの使用可能な容量（バイト単位）。
 a| 
integer

|===


== 詳細情報の参照

xref:reference_element_api_listdrives.adoc[リストドライブ]
