---
permalink: api/reference_element_api_deletevolumes.html 
sidebar: sidebar 
keywords: volumes,volume,delete,deleting,multiple,DeleteVolumes 
summary: 'DeleteVolumes メソッドを使用すると、複数の (最大 500 個) アクティブ ボリュームを削除対象としてマークできます。マークを付けると、クリーンアップ間隔が経過した後にボリュームがパージ（完全に削除）されます。' 
---
= ボリュームの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `DeleteVolumes`複数 (最大 500 個) のアクティブ ボリュームを削除対象としてマークする方法。マークを付けると、クリーンアップ間隔が経過した後にボリュームがパージ (完全に削除) されます。

ボリュームの削除を要求すると、ボリュームへのアクティブな iSCSI 接続は直ちに終了され、ボリュームがこの状態にある間はそれ以上の接続は許可されません。マークされたボリュームは、ターゲット検出要求では返されません。

削除対象としてマークされたボリュームのスナップショットは影響を受けません。スナップショットは、ボリュームがシステムから削除されるまで保持されます。ボリュームが削除対象としてマークされており、一括ボリューム読み取りまたは一括ボリューム書き込み操作が進行中の場合、一括ボリューム読み取りまたは書き込み操作は停止されます。

削除するボリュームがボリュームとペアになっている場合、ペアになっているボリューム間のレプリケーションは中断され、削除された状態の間はそれらのボリュームとの間でデータの転送は行われません。削除されたボリュームとペアになっていたリモート ボリュームは PausedMisconfigured 状態になり、それらのボリュームや削除されたボリュームからのデータは送信されなくなります。削除されたボリュームがパージされるまでは、ボリュームをリストアしてデータ転送を再開できます。削除されたボリュームがシステムから消去されると、そのボリュームとペアになっていたボリュームは StoppedMisconfigured 状態になり、ボリュームのペアリング ステータスは削除されます。パージされたボリュームは完全に使用できなくなります。



== パラメータ

このメソッドには次の入力パラメータがあります。


NOTE: 次のパラメータのうち少なくとも 1 つは必須であり、そのうち 1 つのパラメータのみを使用する必要があります (すべてのパラメータは相互に排他的です)。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
ボリュームID
 a| 
システムから削除するボリュームの ID のリスト。
 a| 
整数配列
 a| 
なし
 a| 
注記を参照してください。



 a| 
ボリュームアクセスグループID
 a| 
ボリューム アクセス グループ ID のリスト。このリストで指定したすべてのボリューム アクセス グループのすべてのボリュームがシステムから削除されます。
 a| 
整数配列
 a| 
なし
 a| 
注記を参照してください。



 a| 
アカウントID
 a| 
アカウント ID のリスト。これらのアカウントのすべてのボリュームはシステムから削除されます。
 a| 
整数配列
 a| 
なし
 a| 
注記を参照してください。

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
ボリューム
 a| 
新しく削除されたボリュームに関する情報。
 a| 
xref:reference_element_api_volume.adoc[音量]



 a| 
曲線
 a| 
曲線はキーと値のペアのセットです。キーはバイト単位の I/O サイズです。値は、特定の I/O サイズで IOP を実行するコストを表します。曲線は、100 IOPS に設定された 4096 バイトの操作を基準として計算されます。
 a| 
JSONオブジェクト

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "DeleteVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----

{
  "id" : 1,
  "result": {
    "volumes" : [ {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {},
      "blockSize": 4096,
      "createTime": "2015-03-06T18:50:56Z",
      "deleteTime": "",
      "enable512e": False,
      "iqn": "iqn.2010-01.com.solidfire:pzsr.vclient-030-v00001.1",
      "name": "vclient-030-v00001",
      "qos": {
        "burstIOPS": 15000,
        "burstTime": 60,
        "curve": {},
        "maxIOPS": 15000,
        "minIOPS": 100
      },
      "purgeTime": "",
      "sliceCount": 1,
      "scsiEUIDeviceID": "707a737200000001f47acc0100000000",
      "scsiNAADeviceID": "6f47acc100000000707a737200000001",
      "status": "active",
      "totalSize": 10000003072,
      "virtualVolumeID": 5,
      "volumeAccessGroups": [],
      "volumePairs": [],
      "volumeID": 1
    } ]
  }
}
----


== バージョン以降の新機能

9.6
