---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: SetSnmpInfo メソッドを使用して、クラスター ノードで SNMP バージョン 2 およびバージョン 3 を構成できます。このインターフェイスで設定した値はクラスター内のすべてのノードに適用され、渡された値は SetSnmpInfo への以前の呼び出しで設定されたすべての値を置き換えます。 
---
= SnmpInfo の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `SetSnmpInfo`クラスター ノードで SNMP バージョン 2 およびバージョン 3 を構成する方法。このインターフェースで設定した値はクラスタ内のすべてのノードに適用され、渡された値は以前の呼び出しで設定されたすべての値を置き換えます。 `SetSnmpInfo` 。



== パラメータ


NOTE: SetSnmpInfo は、Element バージョン 6.0 以降では非推奨です。使用xref:reference_element_api_enablesnmp.adoc[Snmpを有効にする]そしてxref:reference_element_api_setsnmpacl.adoc[SnmpACLの設定]代わりにメソッドを使用します。

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
ネットワーク
 a| 
クラスター ノードで実行されている SNMP サーバーに対するネットワークとアクセスの種類のリスト。 SNMPを参照してくださいxref:reference_element_api_network_snmp.adoc[network]可能な値のオブジェクト。このパラメータは SNMP v2 のみに必要です。
 a| 
xref:reference_element_api_network_snmp.adoc[network]配列
 a| 
なし
 a| 
いいえ



 a| 
有効
 a| 
true に設定すると、クラスター内の各ノードで SNMP が有効になります。
 a| 
ブーリアン
 a| 
false
 a| 
いいえ



 a| 
snmpV3有効
 a| 
true に設定すると、クラスター内の各ノードで SNMP v3 が有効になります。
 a| 
ブーリアン
 a| 
false
 a| 
いいえ



 a| 
usmユーザー
 a| 
SNMP v3 が有効になっている場合は、ネットワーク パラメータの代わりにこの値を渡す必要があります。このパラメータは SNMP v3 のみに必要です。
 a| 
xref:reference_element_api_usmuser.adoc[usmユーザー]
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには戻り値はありません。



== SNMP v3 を有効にしたリクエストの例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== SNMP v2 を有効にしたリクエストの例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== バージョン以降の新機能

9.6
