---
permalink: api/reference_element_api_volumestats.html 
sidebar: sidebar 
keywords: object,objects,volumeStats 
summary: volumeStats オブジェクトには、個々のボリュームの統計データが含まれています。 
---
= ボリューム統計
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
volumeStats オブジェクトには、個々のボリュームの統計データが含まれています。



== オブジェクトメンバー

一部またはすべてのボリュームの volumeStats オブジェクトを取得するには、次のメソッドを使用できます。

* xref:reference_element_api_getvolumestats.adoc[ボリューム統計情報を取得する]
* xref:reference_element_api_listvolumestatsbyaccount.adoc[アカウント別ボリューム統計リスト]
* xref:reference_element_api_listvolumestatsbyvolume.adoc[ボリューム別リストボリューム統計]
* xref:reference_element_api_listvolumestatsbyvolumeaccessgroup.adoc[ボリュームアクセスグループごとのボリューム統計のリスト]


このオブジェクトには次のメンバーが含まれます。

[cols="20,50,15,15"]
|===
| Name | 説明 | 計算式 | タイプ 


 a| 
accountID
 a| 
ボリューム所有者のアカウントの ID。
 a| 
該当なし
 a| 
integer



 a| 
実際のIOPS
 a| 
過去 500 ミリ秒間のボリュームに対する現在の実際の IOPS。
 a| 
ポイントインタイム
 a| 
integer



 a| 
非同期遅延
 a| 
ボリュームがリモート クラスターと最後に同期されてからの経過時間。ボリュームがペアリングされていない場合は null になります。 *注:* アクティブなレプリケーション状態にあるターゲット ボリュームの asyncDelay は常に 0 (ゼロ) になります。ターゲット ボリュームはレプリケーション中にシステムを認識し、asyncDelay が常に正確であると想定します。
 a| 
該当なし
 a| 
ISO 8601 期間文字列または null



 a| 
平均IOPサイズ
 a| 
過去 500 ミリ秒間のボリュームへの最近の I/O の平均サイズ (バイト単位)。
 a| 
ポイントインタイム
 a| 
integer



 a| 
バーストIOPSクレジット
 a| 
ユーザーが利用できる IOP クレジットの合計数。ボリュームが設定された maxIOPS まで使用されていない場合、クレジットが蓄積されます。
 a| 
該当なし
 a| 
integer



 a| 
クライアントキュー深度
 a| 
ボリュームに対する未処理の読み取りおよび書き込み操作の数。
 a| 
該当なし
 a| 
integer



 a| 
必要なメタデータホスト
 a| 
ボリューム メタデータがメタデータ サービス間で移行されている場合、移行先のメタデータ (スライス) サービス。  「null」値はボリュームが移行されていないことを意味します。
 a| 
該当なし
 a| 
JSONオブジェクト



 a| 
レイテンシUSec
 a| 
過去 500 ミリ秒間にボリュームに対する操作を完了するのにかかった平均時間 (マイクロ秒単位)。  「0」(ゼロ) 値は、ボリュームへの I/O がないことを意味します。
 a| 
ポイントインタイム
 a| 
integer



 a| 
メタデータホスト
 a| 
ボリューム メタデータが存在するメタデータ (スライス) サービス。有効な値は次のとおりです。

* primary: ボリュームをホストするプライマリ メタデータ サービス。
* liveSecondaries: 現在「ライブ」状態にあるセカンダリ メタデータ サービス。
* deadSecondaries: デッド状態にあるセカンダリ メタデータ サービス。

 a| 
該当なし
 a| 
JSONオブジェクト



 a| 
正規化されたIOPS
 a| 
過去 500 ミリ秒間のクラスター全体の IOPS の平均数。
 a| 
ポイントインタイム
 a| 
integer



 a| 
非ゼロブロック
 a| 
最後のガベージ コレクション操作が完了した後にデータが含まれている 4KiB ブロックの合計数。
 a| 
該当なし
 a| 
integer



 a| 
readBytes
 a| 
ボリュームの作成以降にボリュームから読み取られた合計累積バイト数。
 a| 
単調増加
 a| 
integer



 a| 
最終サンプルバイト読み取り
 a| 
最後のサンプル期間中にボリュームから読み取られたバイトの合計数。
 a| 
ポイントインタイム
 a| 
integer



 a| 
読み取りレイテンシUSec
 a| 
過去 500 ミリ秒間にボリュームへの読み取り操作を完了するのにかかった平均時間 (マイクロ秒単位)。
 a| 
ポイントインタイム
 a| 
integer



 a| 
読み取りレイテンシUSec合計
 a| 
ボリュームからの読み取り操作の実行に費やされた合計時間。
 a| 
単調増加
 a| 
integer



 a| 
readOps
 a| 
ボリュームの作成以降のボリュームに対する読み取り操作の合計。
 a| 
単調増加
 a| 
integer



 a| 
読み取り操作最終サンプル
 a| 
最後のサンプル期間中の読み取り操作の合計数。
 a| 
ポイントインタイム
 a| 
integer



 a| 
サンプル期間ミリ秒
 a| 
サンプル期間の長さ（ミリ秒単位）。
 a| 
該当なし
 a| 
integer



 a| 
スライスIops統計
 a| 
ボリュームの I/O 使用状況統計。  Element 12.8 以降で使用可能です。  sliceIopsStats の可能な値:

* largeStatistics: 通常は過去 24 時間など、より長い期間にわたって測定されたボリュームの I/O 統計。
* smallStatistics: 通常は過去 1 時間など、より短い期間にわたって測定されたボリュームの I/O 統計。


largeStatistics と smallStatistics に可能な値:

* averageReadIops: ボリュームの平均読み取り IOPS。
* averageTotalIops: ボリュームの平均合計 (読み取り + 書き込み) IOPS。
* averageWriteIops: ボリュームの平均書き込み IOPS。
* nSamples: 統計計算に含まれるサンプルの数。
* peakReadIops: 統計間隔中に観測された最大読み取り IOPS。
* peakTotalIops: 統計間隔中に観測された最大合計 IOPS。
* peakWriteIops: 統計間隔中に観測された最大書き込み IOPS。
* sliceID: ボリュームIDまたはスライスID

 a| 
ポイントインタイム
 a| 
JSONオブジェクト



 a| 
スロットル
 a| 
データの再レプリケーション、一時的なエラー、およびスナップショットの取得により、システムがクライアントを maxIOPS 未満に制限している程度を表す 0 から 1 までの浮動小数点値。
 a| 
該当なし
 a| 
float



 a| 
タイムスタンプ
 a| 
UTC+0 形式の現在の時刻。
 a| 
該当なし
 a| 
ISO 8601日付文字列



 a| 
非整列読み取り
 a| 
ボリュームの作成以降のボリュームに対する累積非整列読み取り操作の合計。
 a| 
単調増加
 a| 
integer



 a| 
非整列書き込み
 a| 
ボリュームの作成以降にボリュームに対して行われた、アラインメントされていない書き込み操作の合計累積数。
 a| 
単調増加
 a| 
integer



 a| 
ボリュームアクセスグループ
 a| 
ボリュームが属するボリューム アクセス グループの ID のリスト。
 a| 
該当なし
 a| 
整数配列



 a| 
volumeID
 a| 
ボリュームのID。
 a| 
該当なし
 a| 
integer



 a| 
ボリュームサイズ
 a| 
プロビジョニングされた合計容量（バイト単位）。
 a| 
該当なし
 a| 
integer



 a| 
ボリューム使用率
 a| 
ボリュームの maxIOPS QoS 設定と比較して、クライアントがボリュームの入出力機能をどの程度使用しているかを示す浮動小数点値。有効な値は次のとおりです。

* 0: クライアントはボリュームを使用していません。
* 0.01 ～ 0.99: クライアントはボリュームの IOPS 機能を十分に活用していません。
* 1.00: クライアントは、maxIOPS 設定で設定された IOPS 制限までボリュームを完全に使用しています。
* > 1.00: クライアントは maxIOPS で設定された制限を超えて使用しています。これは、burstIOPS QoS 設定が maxIOPS よりも高く設定されている場合に可能です。たとえば、maxIOPSが1000に設定され、burstIOPSが2000に設定されている場合、 `volumeUtilization`クライアントがボリュームを完全に使用している場合、値は 2.00 になります。

 a| 
該当なし
 a| 
float



 a| 
writeBytes
 a| 
ボリュームの作成以降にボリュームに書き込まれた合計累積バイト数。
 a| 
単調増加
 a| 
integer



 a| 
書き込みバイト最終サンプル
 a| 
最後のサンプル期間中にボリュームに書き込まれたバイトの合計数。
 a| 
単調増加
 a| 
integer



 a| 
書き込みレイテンシUSec
 a| 
過去 500 ミリ秒間にボリュームへの書き込み操作を完了するのにかかった平均時間 (マイクロ秒単位)。
 a| 
ポイントインタイム
 a| 
integer



 a| 
書き込みレイテンシUSec合計
 a| 
ボリュームへの書き込み操作の実行に費やされた合計時間。
 a| 
単調増加
 a| 
integer



 a| 
writeOps
 a| 
ボリュームの作成以降のボリュームへの累積書き込み操作の合計。
 a| 
単調増加
 a| 
integer



 a| 
書き込み操作最終サンプル
 a| 
最後のサンプル期間中の書き込み操作の合計数。
 a| 
ポイントインタイム
 a| 
integer



 a| 
ゼロブロック
 a| 
最後のガベージ コレクション操作が完了した後の、データのない空の 4KiB ブロックの合計数。
 a| 
ポイントインタイム
 a| 
integer

|===