---
permalink: api/reference_element_api_removenodes.html 
sidebar: sidebar 
keywords: node,nodes,cluster,remove,removing,removenodes 
summary: RemoveNodes を使用すると、クラスターに参加しなくなった 1 つ以上のノードを削除できます。 
---
= RemoveNodes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用できます `RemoveNodes`クラスターに参加しなくなった 1 つ以上のノードを削除します。

ノードを削除する前に、ノードに含まれるすべてのドライブを削除する必要があります。 `RemoveDrives`方法。ノードを削除するには、 `RemoveDrives`プロセスが完了し、すべてのデータがノードから移行されました。ノードを削除すると、そのノードは保留中のノードとして登録されます。ノードを再度追加するか、シャットダウンすることができます (ノードをシャットダウンすると、保留中のノード リストから削除されます)。



== クラスターマスターノードの削除

使用する場合 `RemoveNodes`クラスター マスター ノードを削除する場合、メソッドは応答を返す前にタイムアウトする可能性があります。メソッド呼び出しでノードの削除に失敗した場合は、メソッド呼び出しを再度実行します。クラスター マスター ノードを他のノードと一緒に削除する場合は、クラスター マスター ノードのみを削除するには別の呼び出しを使用する必要があることに注意してください。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
アンサンブル許容値の変更を無視
 a| 
ノードを削除するときに、アンサンブルのノード障害許容度の変更を無視します。

ストレージ クラスターが複数のノード障害を許容するデータ保護スキームを使用しており、ノードを削除するとアンサンブルのノード障害許容度が低下する場合、通常、ノードの削除はエラーで失敗します。このパラメータを true に設定すると、アンサンブル許容値チェックが無効になり、ノードの削除が成功します。
 a| 
ブーリアン
 a| 
false
 a| 
いいえ



 a| 
ノード
 a| 
削除するノードの NodeID のリスト。
 a| 
整数配列
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドには戻り値はありません。



== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "RemoveNodes",
   "params": {
     "nodes"  : [3,4,5]
   },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id" : 1
  "result" : {},
}
----


== バージョン以降の新機能

9.6
