---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: TestPing メソッドを使用すると、ICMP パケットを使用して 1G および 10G インターフェースの両方でクラスター内のすべてのノードへのネットワーク接続をテストできます。テストでは、ネットワーク構成の MTU 設定に基づいて、各パケットに適切な MTU サイズが使用されます。  TestPing は一時的な VLAN インターフェイスを作成しません。 
---
= テストピング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `TestPing`ICMP パケットを使用して、1G および 10G インターフェースの両方でクラスター内のすべてのノードへのネットワーク接続をテストする方法。テストでは、ネットワーク構成の MTU 設定に基づいて、各パケットに適切な MTU サイズが使用されます。 `TestPing`一時的な VLAN インターフェイスを作成しません。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
試み
 a| 
システムがテスト ping を繰り返す回数を指定します。
 a| 
integer
 a| 
5
 a| 
いいえ



 a| 
ホスト
 a| 
ping するデバイスのアドレスまたはホスト名をコンマで区切ったリストを指定します。ホストが指定されていない場合、このメソッドはストレージ クラスター内のホストに ping を実行します。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
インタフェース
 a| 
ping を送信する既存の (ベース) インターフェイス。有効な値は次のとおりです。

* `Bond10G`: Bond10G インターフェースから ping を送信します。
* `Bond1G`: Bond1G インターフェースから ping を送信します。

 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
パケットサイズ
 a| 
各 IP に送信される ICMP パケットで送信するバイト数を指定します。バイト数は、ネットワーク構成で指定された最大 MTU 未満である必要があります。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
pingタイムアウトミリ秒
 a| 
個々の ping 応答を待機するミリ秒数を指定します。
 a| 
integer
 a| 
500ミリ秒
 a| 
いいえ



 a| 
断片化を禁止する
 a| 
ICMP パケットの DF (Do not Fragment) フラグを有効にします。
 a| 
ブーリアン
 a| 
false
 a| 
いいえ



 a| 
ソースアドレスV4
 a| 
ICMP ping パケットで使用する送信元 IPv4 アドレス。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
ソースアドレスV6
 a| 
ICMP ping パケットで使用する送信元 IPv6 アドレス。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
合計タイムアウト秒
 a| 
次の ping 試行を発行するかプロセスを終了する前に、ping がシステム応答を待機する時間を秒単位で指定します。
 a| 
integer
 a| 
5
 a| 
いいえ



 a| 
仮想ネットワークタグ
 a| 
ping パケットを送信するときに使用する VLAN ID。
 a| 
integer
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
詳細
 a| 
ノードが通信できた各 IP のリストと ping 応答統計。
 a| 
JSONオブジェクト

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== バージョン以降の新機能

5.0
