---
permalink: api/reference_element_api_breaksnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,volume,volumes,break,breaking,relationship,ONTAP 
summary: Element Web UI は、BreakSnapMirrorRelationship メソッドを使用してSnapMirror関係を解除します。  SnapMirror関係が解除されると、宛先ボリュームは読み取り/書き込み可能かつ独立し、ソースから分岐できるようになります。 ResyncSnapMirrorRelationship API メソッドを使用して関係を再確立できます。この方法では、 ONTAPクラスタが使用可能である必要があります。 
---
= スナップミラー関係を解除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ElementウェブUIは `BreakSnapMirrorRelationship`SnapMirror関係を解除する方法。 SnapMirror関係が解除されると、宛先ボリュームは読み取り/書き込み可能かつ独立し、ソースから分岐できるようになります。関係を再構築することができます `ResyncSnapMirrorRelationship`API メソッド。この方法では、 ONTAPクラスタが使用可能である必要があります。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
スナップミラーエンドポイントID
 a| 
Element ストレージ クラスタと通信するリモートONTAPストレージ システムのエンドポイント ID。
 a| 
integer
 a| 
なし
 a| 
はい



 a| 
宛先ボリューム
 a| 
SnapMirror関係の宛先ボリューム。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[スナップミラーボリューム情報]
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
スナップミラー関係
 a| 
破損したSnapMirror関係に関する情報を含むオブジェクト。
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[スナップミラー関係]

|===


== バージョン以降の新機能

10.1



== 詳細情報の参照

xref:reference_element_api_breaksnapmirrorvolume.adoc[ブレークスナップミラーボリューム]
