---
permalink: api/reference_element_api_createpublicprivatekeypair.html 
sidebar: sidebar 
keywords: SSL keys,public and private keys,certificate signing request,creating key pair 
summary: CreatePublicPrivateKeyPair メソッドを使用して、公開 SSL キーと秘密 SSL キーを作成できます。これらのキーを使用して証明書署名要求を生成できます。各ストレージ クラスターで使用できるキー ペアは 1 つだけです。この方法を使用して既存のキーを置き換える前に、そのキーがどのプロバイダーでも使用されていないことを確認してください。 
---
= 公開鍵ペアの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `CreatePublicPrivateKeyPair`公開 SSL キーと秘密 SSL キーを作成する方法。これらのキーを使用して証明書署名要求を生成できます。各ストレージ クラスターで使用できるキー ペアは 1 つだけです。この方法を使用して既存のキーを置き換える前に、そのキーがどのプロバイダーでも使用されていないことを確認してください。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
共通名
 a| 
X.509 識別名 *Common Name* フィールド (CN)。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
国
 a| 
X.509 識別名 *Country* フィールド (C)。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
電子メールアドレス
 a| 
X.509 識別名 *電子メール アドレス* フィールド (MAIL)。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
地域
 a| 
X.509 識別名 *Locality Name* フィールド (L)。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
組織
 a| 
X.509 識別名 *組織名* フィールド (O)。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
組織単位
 a| 
X.509 識別名 *組織単位名* フィールド (OU)。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
状態
 a| 
X.509 識別名 *State* または *Province Name* フィールド (ST またはSPまたは S)。
 a| 
string
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには戻り値はありません。エラーがなければ、キーの作成は成功したとみなされます。



== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "CreatePublicPrivateKeyPair",
  "params": {
    "commonName": "Name",
    "country": "US",
    "emailAddress" : "email@domain.com"
   },
"id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


== バージョン以降の新機能

11.7
