---
permalink: api/reference_element_api_keyproviderkmip.html 
sidebar: sidebar 
keywords: key provider,KMIP,keys 
summary: 'keyProviderKmip オブジェクトは、キー管理相互運用性プロトコル (KMIP) キー プロバイダーを記述します。キー プロバイダーは、Encryption at Rest などのクラスター機能で使用する認証キーを取得するためのメカニズムであり、場所でもあります。' 
---
= キープロバイダーKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
keyProviderKmip オブジェクトは、キー管理相互運用性プロトコル (KMIP) キー プロバイダーを記述します。キー プロバイダーは、Encryption at Rest などのクラスター機能で使用する認証キーを取得するためのメカニズムであり、場所でもあります。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
キープロバイダーID
 a| 
KMIP キープロバイダーの ID。これは、キープロバイダーの作成時にクラスターによって割り当てられる一意の値であり、変更できません。
 a| 
integer



 a| 
キープロバイダーがアクティブ
 a| 
KMIP キー プロバイダーがアクティブな場合は True です。作成されたがまだ削除されておらず、まだ使用中であると考えられる未処理のキーがある場合、プロバイダーはアクティブであると見なされます。
 a| 
ブーリアン



 a| 
キープロバイダー名
 a| 
KMIP キープロバイダーの名前。
 a| 
string



 a| 
キーサーバーID
 a| 
このプロバイダーに関連付けられているキー サーバー ID。このプロバイダーをアクティブにするには、サーバーを追加する必要があります。このプロバイダーがアクティブな間はサーバーを削除できません。各プロバイダーに対してサポートされるサーバー ID は 1 つだけです。
 a| 
整数配列



 a| 
kmip機能
 a| 
この KMIP キー プロバイダーの機能には、基盤となるライブラリ、FIPS 準拠、SSL プロバイダーなどの詳細が含まれます。
 a| 
string

|===