---
permalink: api/reference_element_api_addvirtualnetwork.html 
sidebar: sidebar 
keywords: addvirtualnetwork,cluster,add,adding,virtual,network 
summary: AddVirtualNetwork メソッドを使用して、クラスター構成に新しい仮想ネットワークを追加できます。 
---
= 仮想ネットワークの追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `AddVirtualNetwork`クラスター構成に新しい仮想ネットワークを追加する方法。

仮想ネットワークを追加すると、各ノードのインターフェイスが作成され、各インターフェイスには仮想ネットワーク IP アドレスが必要になります。この API メソッドのパラメータとして指定する IP アドレスの数は、クラスター内のノードの数以上である必要があります。システムは仮想ネットワーク アドレスを一括プロビジョニングし、個々のノードに自動的に割り当てます。仮想ネットワーク アドレスをノードに手動で割り当てる必要はありません。


NOTE: AddVirtualNetwork メソッドは、新しい仮想ネットワークを作成するためにのみ使用されます。既存の仮想ネットワークに変更を加える場合は、xref:reference_element_api_modifyvirtualnetwork.adoc[仮想ネットワークの変更]方法。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
アドレスブロック
 a| 
仮想ネットワークに含める IP アドレスの一意の範囲。オブジェクトに必要なメンバー:

* start: IP アドレス範囲の開始。  （弦）
* size: ブロックに含める IP アドレスの数。  （整数）

 a| 
JSONオブジェクト配列
 a| 
なし
 a| 
はい



 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSONオブジェクト
 a| 
なし
 a| 
いいえ



 a| 
ゲートウェイ
 a| 
仮想ネットワークのゲートウェイの IP アドレス。このパラメータは、名前空間パラメータが true に設定されている場合にのみ有効です。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
名前
 a| 
新しい仮想ネットワークのユーザー定義名。
 a| 
string
 a| 
なし
 a| 
はい



 a| 
namespace
 a| 
true に設定すると、名前空間とそれに含まれる仮想ネットワークを作成および構成することで、ルーティング可能なストレージ VLAN 機能が有効になります。
 a| 
ブーリアン
 a| 
なし
 a| 
いいえ



 a| 
netmask
 a| 
作成する仮想ネットワークの一意のネットワーク マスク。
 a| 
string
 a| 
なし
 a| 
はい



 a| 
svip
 a| 
作成する仮想ネットワークの一意のストレージ IP アドレス。
 a| 
string
 a| 
なし
 a| 
はい



 a| 
仮想ネットワークタグ
 a| 
一意の仮想ネットワーク (VLAN) タグ。サポートされる値は 1 ～ 4094 です。
 a| 
integer
 a| 
なし
 a| 
はい

|===
*注:* 名前空間を false に設定する場合、仮想ネットワーク パラメータは各仮想ネットワークに対して一意である必要があります。



== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
仮想ネットワークID
 a| 
新しい仮想ネットワークの仮想ネットワーク ID。
 a| 
integer

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "AddVirtualNetwork",
  "params": {
    "virtualNetworkTag": 2010,
    "name": "network1",
    "addressBlocks" : [
        { "start": "192.86.5.1", "size": 10 },
        { "start": "192.86.5.50", "size": 20 }
    ],
    "netmask" : "255.255.192.0",
    "gateway" : "10.0.1.254",
    "svip" : "192.86.5.200",
    "attributes" : {}
    "namespace" : true
  },
"id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id": 1,
   "result":
      {
        "virtualNetworkID": 5
   }
}
----


== バージョン以降の新機能

9.6
