---
permalink: api/reference_element_api_getaccountefficiency.html 
sidebar: sidebar 
keywords: accounts,account,efficiency,get,getting,GetAccountEfficiency 
summary: GetAccountEfficiency を使用すると、ボリューム アカウントに関する効率統計を取得できます。このメソッドは、パラメータとして指定したアカウントの効率情報のみを返します。 
---
= アカウント効率化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用できます `GetAccountEfficiency`ボリューム アカウントに関する効率統計を取得します。このメソッドは、パラメータとして指定したアカウントの効率情報のみを返します。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
accountID
 a| 
効率統計が返されるボリューム アカウントを指定します。
 a| 
integer
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| Name | 説明 | タイプ 


 a| 
圧縮
 a| 
アカウント内のすべてのボリュームのデータ圧縮によって節約されたスペースの量。比率として表され、値「1」はデータが圧縮されずに保存されていることを意味します。
 a| 
float



 a| 
重複排除
 a| 
アカウント内のすべてのボリュームのデータを重複させないことで節約されるスペースの量。比率で表します。
 a| 
float



 a| 
不足しているボリューム
 a| 
効率データのクエリができなかったボリューム。ボリュームの欠落は、ガベージ コレクション (GC) サイクルが 1 時間未満であること、ネットワーク接続が一時的に失われていること、または GC サイクル以降にサービスが再起動されたことが原因で発生することがあります。
 a| 
整数配列



 a| 
シンプロビジョニング
 a| 
データの保存に割り当てられたスペースの量に対する使用済みスペースの比率。比率で表します。
 a| 
float



 a| 
タイムスタンプ
 a| 
ガベージ コレクション (GC) 後に効率データが最後に収集された時刻 (UTC+0 形式)。
 a| 
ISO 8601日付文字列

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "GetAccountEfficiency",
   "params": {
     "accountID": 3
   },
   "id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.020468042933262,
       "deduplication": 2.042488619119879,
       "missingVolumes": [],
       "thinProvisioning": 1.010087163391013,
       "timestamp": "2014-03-10T14:06:02Z"
   }
}
----


== バージョン以降の新機能

9.6
