---
permalink: api/reference_element_api_volume_pairing_order_of_operations.html 
sidebar: sidebar 
keywords: volume,pairing,order,operations,volumes,pairing,pair,pairs 
summary: ボリュームをペアリングする前に、対応する 2 つのクラスター間にクラスター ペアを作成する必要があります。 
---
= ボリュームペアリングの操作順序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームをペアリングする前に、対応する 2 つのクラスター間にクラスター ペアを作成する必要があります。

クラスター接続を確立するには、次の API メソッド セットを使用します。

* xref:reference_element_api_startvolumepairing.adoc[ボリュームペアリングの開始]:
+
この API メソッドは、ボリューム ペアの作成に使用されるボリューム ペアリング キーを作成して返します。キーには、ボリューム間の通信を確立するために使用される情報が含まれています。

* xref:reference_element_api_completevolumepairing.adoc[完全な音量ペアリング]:
+
この方法では、xref:reference_element_api_startvolumepairing.adoc[ボリュームペアリングの開始]ボリューム ペアを作成する API メソッド。発行するxref:reference_element_api_completevolumepairing.adoc[完全な音量ペアリング]volumeID および volumePairingKey パラメータを使用して宛先ボリュームに渡す API メソッド。



ペアになっているボリュームのうち 1 つだけをレプリケーション ターゲット ボリュームとして識別できます。使用xref:reference_element_api_modifyvolumepair.adoc[ボリュームペアの変更]どのボリュームがターゲットであるかを識別して、ボリュームのデータ複製の方向を確立する API メソッド。データはソース ボリュームからターゲット ボリュームに複製されます。



== 詳細情報の参照

* xref:reference_element_api_startvolumepairing.adoc[ボリュームペアリングの開始]
* xref:reference_element_api_completevolumepairing.adoc[完全な音量ペアリング]
* xref:reference_element_api_modifyvolumepair.adoc[ボリュームペアの変更]

