---
permalink: api/reference_element_api_volume.html 
sidebar: sidebar 
keywords: object,objects,volume 
summary: ボリューム オブジェクトには、ペアリングされていないボリュームまたはペアリングされたボリュームに関する構成情報が含まれています。実行時間や使用状況の情報は含まれず、仮想ボリュームに関する情報も含まれません。 
---
= 音量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリューム オブジェクトには、ペアリングされていないボリュームまたはペアリングされたボリュームに関する構成情報が含まれています。実行時間や使用状況の情報は含まれず、仮想ボリュームに関する情報も含まれません。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
アクセス
 a| 
ボリュームに許可されるアクセスの種類。有効な値は次のとおりです。

* `readOnly`: 読み取り操作のみが許可されます。
* `readWrite`: 読み取りと書き込みが許可されます。
* `locked`: 読み取りも書き込みも許可されません。
* `replicationTarget`: 複製されたボリューム ペアのターゲット ボリュームとして指定されます。

 a| 
string



 a| 
accountID
 a| 
ボリュームを含むアカウントのアカウントID。
 a| 
integer



 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSONオブジェクト



 a| 
ブロックサイズ
 a| 
ボリューム上のブロックのサイズ。
 a| 
integer



 a| 
作成時間
 a| 
ボリュームが作成された UTC+0 形式の時刻。
 a| 
ISO 8601文字列



 a| 
現在の保護スキーム
 a| 
このボリュームに使用されている保護スキーム。ボリュームが 1 つの保護スキームから別の保護スキームに変換されている場合、このメンバーはボリュームが変換する保護スキームを反映します。
 a| 
string



 a| 
削除時間
 a| 
ボリュームが削除された UTC+0 形式の時刻。
 a| 
ISO 8601文字列



 a| 
enable512e
 a| 
true に設定すると、ボリュームは 512 バイト セクター エミュレーションを提供します。
 a| 
ブーリアン



 a| 
SnapMirrorReplication を有効にする
 a| 
ボリュームをSnapMirrorエンドポイントによるレプリケーションに使用できるかどうか。
 a| 
ブーリアン



| fifoサイズ | 先入れ先出し (FIFO) スナップショット保持モードを使用する場合に、同時に維持されるボリュームのスナップショットの最大数を指定します。 | integer 


 a| 
iqn
 a| 
ボリュームの iSCSI 修飾名。
 a| 
string



 a| 
最終アクセス時間
 a| 
ボリュームへのアクセス (I/O を含む) が最後に発生した時刻 (UTC+0 としてフォーマットされます)。最終アクセス時間が不明な場合、この値は null になります。
 a| 
ISO 8601文字列



 a| 
最終アクセス時間IO
 a| 
ボリュームへの I/O が最後に発生した時刻 (UTC+0 としてフォーマットされます)。最終アクセス時間が不明な場合、この値は null になります。
 a| 
ISO 8601文字列



| 最小Fifoサイズ | 先入れ先出し (FIFO) スナップショット保持モードを使用する場合、ボリュームによって同時に予約される先入れ先出し (FIFO) スナップショット スロットの最小数を指定します。 | integer 


 a| 
名前
 a| 
作成時に指定されたボリュームの名前。
 a| 
string



 a| 
以前の保護スキーム
 a| 
ボリュームが 1 つの保護スキームから別の保護スキームに変換されている場合、このメンバーはボリュームが変換される保護スキームを反映します。このメンバーは変換が開始されるまで変更されません。ボリュームが一度も変換されていない場合、このメンバーは null になります。
 a| 
string



 a| 
パージ時間
 a| 
ボリュームがシステムから消去された UTC+0 形式の時刻。
 a| 
ISO 8601文字列



 a| 
qos
 a| 
このボリュームのサービス品質設定。
 a| 
xref:reference_element_api_qos.adoc[QoS]



 a| 
qosポリシーID
 a| 
ボリュームに関連付けられた QoS ポリシー ID。ボリュームがポリシーに関連付けられていない場合、値は null になります。
 a| 
integer



 a| 
scsiEUIデバイスID
 a| 
EUI-64 ベースの 16 バイト形式で表された、ボリュームのグローバルに一意の SCSI デバイス識別子。
 a| 
string



 a| 
scsiNAAデバイスID
 a| 
NAA IEEE 登録拡張形式のボリュームのグローバルに一意の SCSI デバイス識別子。
 a| 
string



 a| 
スライス数
 a| 
ボリューム上のスライスの数。この値は常に「1」です。
 a| 
integer



 a| 
ステータス
 a| 
ボリュームの現在のステータス。有効な値は次のとおりです。

* init: 初期化中であり、接続の準備ができていないボリューム。
* アクティブ: 接続の準備ができているアクティブなボリューム。
* 削除済み: 削除対象としてマークされているが、まだ削除されていないボリューム。

 a| 
string



 a| 
合計サイズ
 a| 
プロビジョニングされた容量の合計バイト数。
 a| 
integer



 a| 
仮想ボリュームID
 a| 
ボリュームに関連付けられている一意の仮想ボリューム ID (存在する場合)。
 a| 
UUID



 a| 
ボリュームアクセスグループ
 a| 
ボリュームが属するボリューム アクセス グループの ID のリスト。ボリュームがどのボリューム アクセス グループにも属していない場合、この値は空のリストになります。
 a| 
整数配列



 a| 
ボリューム整合性グループUUID
 a| 
ボリュームがメンバーとなっているボリューム整合性グループのユニバーサルに一意の ID。
 a| 
UUID



 a| 
volumeID
 a| 
ボリュームの一意のボリュームID。
 a| 
integer



 a| 
ボリュームペア
 a| 
ペアボリュームに関する情報。ボリュームがペアになっている場合にのみ表示されます。ボリュームがペアリングされていない場合、この値は空のリストになります。
 a| 
xref:reference_element_api_volumepair.adoc[ボリュームペア]配列



 a| 
ボリュームUUID
 a| 
ボリュームのユニバーサルに一意の ID。
 a| 
UUID

|===


== 詳細情報の参照

* xref:reference_element_api_listactivevolumes.adoc[アクティブボリュームの一覧]
* xref:reference_element_api_listdeletedvolumes.adoc[削除されたボリュームの一覧]
* xref:reference_element_api_listvolumes.adoc[リストボリューム]
* xref:reference_element_api_listvolumesforaccount.adoc[アカウントのボリューム一覧]
* xref:reference_element_api_qos.adoc[QoS]

