---
permalink: api/reference_element_api_modifygroupsnapshot.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,group,snapshot,modifygroupsnapshot 
summary: 'ModifyGroupSnapshot を使用して、スナップショットのグループの属性を変更できます。この方法を使用すると、読み取り/書き込み \(ソース\) ボリューム上に作成されたスナップショットをターゲット ストレージ システムにリモートで複製することもできます。' 
---
= グループスナップショットの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用できます `ModifyGroupSnapshot`スナップショットのグループの属性を変更します。この方法を使用すると、読み取り/書き込み (ソース) ボリューム上に作成されたスナップショットをターゲット ストレージ システムにリモートで複製することもできます。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===


| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
リモートレプリケーションを有効にする
 a| 
作成されたスナップショットをリモート クラスターに複製できるようにするには、これを使用します。有効な値は次のとおりです。

* `true`: スナップショットはリモート ストレージに複製されます。
* `false`: スナップショットはリモート ストレージに複製されません。

 a| 
ブーリアン
 a| 
false
 a| 
いいえ



 a| 
有効期限
 a| 
スナップショットを削除できるまでの時間を指定します。保持と併用することはできません。元のスナップショットの有効期限または保持期間が指定されていない場合、スナップショットは期限切れになりません。時間の形式は、時間に基づいて有効期限を設定するための ISO 8601 日付文字列です。それ以外の場合は、有効期限は切れません。の値は `null`スナップショットが永続的に保持されます。  fifo の値を指定すると、ボリューム上の他の FIFO スナップショットと比較して、スナップショットは先入れ先出し (FIFO) ベースで保存されます。  FIFO スペースが利用できない場合、API は失敗します。
 a| 
ISO 8601日付文字列
 a| 
なし
 a| 
いいえ



 a| 
名前
 a| 
グループ スナップショットの名前。名前を入力しない場合は、グループスナップショットが作成された日時が使用されます。許可される名前の最大長は 255 文字です。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
グループスナップショットID
 a| 
スナップショットのグループの ID。
 a| 
string
 a| 
なし
 a| 
はい



 a| 
スナップミラーラベル
 a| 
SnapMirrorエンドポイントのスナップショット保持ポリシーを指定するためにSnapMirrorソフトウェアによって使用されるラベル。
 a| 
string
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
グループスナップショット
 a| 
新しく変更されたグループ スナップショットに関する情報を含むオブジェクト。
 a| 
xref:reference_element_api_groupsnapshot.adoc[グループスナップショット]

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "id": 695,
  "method": "ModifyGroupSnapshot",
  "params": {
    "groupSnapshotID": 3,
    "enableRemoteReplication": true,
    "expirationTime": "2016-04-08T22:46:25Z"
  }
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 695,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-06T17:31:41Z",
      "groupSnapshotID": 3,
      "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-06T17:31:41Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2016-04-08T22:46:25Z",
          "groupID": 3,
          "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
          "name": "grpsnap1-2",
          "snapshotID": 2,
          "snapshotUUID": "719b162c-e170-4d80-b4c7-1282ed88f4e1",
          "status": "done",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "grpsnap1",
      "status": "done"
    }
  }
}
----


== バージョン以降の新機能

9.6
