---
permalink: api/reference_element_api_clustercapacity.html 
sidebar: sidebar 
keywords: objects,object,clusterCapacity 
summary: clusterCapacity オブジェクトには、クラスターの高レベルの容量測定値が含まれています。 GetClusterCapacity API メソッドを使用してクラスター容量情報を取得できます。オブジェクト メンバー内のスペース測定はバイト単位で計算されます。 
---
= クラスター容量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clusterCapacity オブジェクトには、クラスターの高レベルの容量測定値が含まれています。 GetClusterCapacity API メソッドを使用してクラスター容量情報を取得できます。オブジェクト メンバー内のスペース測定はバイト単位で計算されます。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
アクティブブロックスペース
 a| 
ブロック ドライブ上のスペースの量。これには、メタデータ エントリやクリーンアップ可能なスペースなどの追加情報が含まれます。
 a| 
integer



 a| 
アクティブセッション
 a| 
クラスターと通信しているアクティブな iSCSI セッションの数。
 a| 
integer



 a| 
平均IOPS
 a| 
協定世界時 (UTC) の午前 0 時以降のクラスターの平均 IOPS。
 a| 
integer



 a| 
クラスターの最近のIOサイズ
 a| 
クラスター内のすべてのボリュームに対する IOPS の平均サイズ。
 a| 
integer



 a| 
現在のIOPS
 a| 
過去 5 秒間のクラスター内のすべてのボリュームの平均 IOPS。
 a| 
integer



 a| 
最大IOPS
 a| 
現在のクラスターの推定最大 IOPS 機能。
 a| 
integer



 a| 
プロビジョニング可能なスペースの最大値
 a| 
プロビジョニング可能なスペースの最大量。これは計算された値です。現在プロビジョニングされているスペースと新しいボリュームのサイズの合計がこの数を超える場合は、新しいボリュームを作成することはできません。値は次のように計算されます。 `maxOverProvisionableSpace = maxProvisionedSpace * maxMetadataOverProvisionFactor`
 a| 
integer



 a| 
最大プロビジョニングスペース
 a| 
すべてのボリュームが 100% 埋まっている場合のプロビジョニング可能なスペースの合計量 (シン プロビジョニングされたメタデータなし)。
 a| 
integer



 a| 
最大使用メタデータスペース
 a| 
メタデータを保存するために使用されるボリューム ドライブ上のバイト数。
 a| 
integer



 a| 
最大使用スペース
 a| 
すべてのアクティブなブロック ドライブ上のスペースの合計量。
 a| 
integer



 a| 
非ゼロブロック
 a| 
最後のガベージ コレクション操作が完了した後にデータが含まれている 4KiB ブロックの合計数。
 a| 
integer



 a| 
ピークアクティブセッション
 a| 
UTC の深夜以降の iSCSI 接続のピーク数。
 a| 
integer



 a| 
ピークIOPS
 a| 
UTC の深夜以降の currentIOPS の最高値。
 a| 
integer



 a| 
プロビジョニングされたスペース
 a| 
クラスター上のすべてのボリュームにプロビジョニングされたスペースの合計量。
 a| 
integer



 a| 
タイムスタンプ
 a| 
このクラスター容量サンプルが取得された日時 (UTC+0 形式)。
 a| 
ISO 8601文字列



 a| 
トータルオペレーション
 a| 
クラスターの存続期間中に実行された I/O 操作の合計数。
 a| 
integer



 a| 
ユニークブロック
 a| 
ブロック ドライブに保存されているブロックの合計数。値には複製されたブロックが含まれます。
 a| 
integer



 a| 
ユニークブロック使用スペース
 a| 
ブロック ドライブ上で uniqueBlocks が占めるデータの合計量。この数値が uniqueBlocks 値とどのように関連しているかについては、GetclusterCapacity メソッドを参照してください。
 a| 
integer



 a| 
使用メタデータスペース
 a| 
メタデータを保存するために使用されるボリューム ドライブ上のバイトの合計数。
 a| 
integer



 a| 
スナップショットで使用されたメタデータスペース
 a| 
スナップショット内の一意のデータを保存するために使用されるボリューム ドライブ上のバイト数。この数値は、システム上のすべてのスナップショットを削除することで回復されるメタデータ領域の量の見積もりを示します。
 a| 
integer



 a| 
使用スペース
 a| 
システム内のすべてのブロック ドライブによって使用されているスペースの合計量。
 a| 
integer



 a| 
ゼロブロック
 a| 
最後のガベージ コレクション操作が完了した後の、データのない空の 4KiB ブロックの合計数。
 a| 
integer

|===


== 詳細情報の参照

xref:reference_element_api_getclustercapacity.adoc[クラスタ容量の取得]
