---
permalink: api/reference_element_api_schedule.html 
sidebar: sidebar 
keywords: object,objects,schedule 
summary: スケジュール オブジェクトには、ボリュームのスナップショットを自動的に作成するために作成されたスケジュールに関する情報が含まれています。  ListSchedules API メソッドを使用して、すべてのスケジュールのスケジュール情報を取得できます。 
---
= スケジュール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スケジュール オブジェクトには、ボリュームのスナップショットを自動的に作成するために作成されたスケジュールに関する情報が含まれています。すべてのスケジュールのスケジュール情報を取得するには、 `ListSchedules` API メソッド。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
attributes
 a| 
スケジュールの発生頻度を示します。有効な値は次のとおりです。

* 曜日
* 月日
* 間隔

 a| 
JSONオブジェクト



 a| 
エラーあり
 a| 
スケジュールにエラーがあるかどうかを示します。有効な値は次のとおりです。

* true
* false

 a| 
ブーリアン



 a| 
hours
 a| 
次のスナップショットが作成されるまでの経過時間を表示します。可能な値は 0 ～ 24 です。
 a| 
integer



 a| 
最終実行ステータス
 a| 
最後にスケジュールされたスナップショットのステータスを示します。有効な値は次のとおりです。

* 成功
* 失敗

 a| 
string



 a| 
最後の実行時間開始
 a| 
スケジュールが最後に開始された時刻を示します。
 a| 
ISO 8601日付文字列



 a| 
minutes
 a| 
次のスナップショットが作成されるまでに経過する分数を表示します。可能な値は 0 ～ 59 です。
 a| 
integer



 a| 
月日
 a| 
スナップショットが作成される月の日を示します。
 a| 
配列



 a| 
一時停止
 a| 
スケジュールが一時停止されているかどうかを示します。有効な値は次のとおりです。

* true
* false

 a| 
ブーリアン



 a| 
定期的な
 a| 
スケジュールが定期的に実行されるかどうかを示します。有効な値は次のとおりです。

* true
* false

 a| 
ブーリアン



 a| 
実行次の間隔
 a| 
スケジューラが次回アクティブになったときにスケジュールが実行されるかどうかを示します。 true の場合、スケジュールはスケジューラが次にアクティブになったときに実行され、その後この値は false に戻されます。有効な値は次のとおりです。

* true
* false

 a| 
ブーリアン



 a| 
スケジュールID
 a| 
スケジュールの一意の ID。
 a| 
integer



 a| 
scheduleInfo
 a| 
スケジュールに付けられた一意の名前、作成されたスナップショットの保持期間、スナップショットが作成されたボリュームのボリューム ID が含まれます。有効な値は次のとおりです。

* `enableRemoteReplication`: スナップショットをリモート レプリケーションに含めるかどうかを示します。  （ブール値）
* `ensureSerialCreation`: 以前のスナップショットのレプリケーションが進行中の場合に、新しいスナップショットの作成を許可するかどうかを指定します。  （ブール値）
* `name`: 使用するスナップショット名。  （弦）
* `retention`: スナップショットが保持される時間の長さ。時間に応じて、次のいずれかの形式で表示されます。
+
** `fifo`: スナップショットは先入れ先出し (FIFO) 方式で保持されます。空の場合、スナップショットは永久に保持されます。  （弦）
** 時:分:秒


* `volumeID`: スナップショットに含めるボリュームの ID。  （整数）
* `volumes`: グループ スナップショットに含めるボリューム ID のリスト。  （整数配列）

 a| 
JSONオブジェクト



 a| 
スケジュール名
 a| 
スケジュールに割り当てられた一意の名前。
 a| 
string



 a| 
スケジュールタイプ
 a| 
現時点では、スケジュール タイプのスナップショットのみがサポートされています。
 a| 
string



 a| 
スナップミラーラベル
 a| 
作成されたスナップショットまたはグループ スナップショットに適用される snapMirrorLabel (scheduleInfo に含まれます)。設定されていない場合、この値は null になります。
 a| 
string



 a| 
開始日
 a| 
スケジュールが最初に開始された、または開始される日付を示します。UTC 時間形式で表示されます。
 a| 
ISO 8601日付文字列



 a| 
削除予定
 a| 
スケジュールが削除対象としてマークされているかどうかを示します。有効な値は次のとおりです。

* true
* false

 a| 
ブーリアン



 a| 
weekdays
 a| 
スナップショットが作成される曜日を示します。
 a| 
配列

|===


== 詳細情報の参照

xref:reference_element_api_listschedules.adoc[リストスケジュール]
