---
permalink: api/reference_element_api_removedrives.html 
sidebar: sidebar 
keywords: cluster,drive,drives,remove,removing,removedrives 
summary: RemoveDrives メソッドを使用すると、クラスターの一部であるドライブを事前に削除できます。この方法は、クラスターの容量を削減する場合や、耐用年数が近づいているドライブを交換する準備をする場合などに使用できます。ドライブがクラスターから削除される前に、ドライブ上のすべてのデータが削除され、クラスター内の他のドライブに移行されます。 
---
= RemoveDrives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `RemoveDrives`クラスターの一部であるドライブを事前に削除する方法。この方法は、クラスターの容量を削減する場合や、耐用年数が近づいているドライブを交換する準備をする場合などに使用できます。 `RemoveDrives`クラスター内の他のノードにブロック データの 3 番目のコピーを作成し、同期が完了するまで待ってから、ドライブを「使用可能」リストに移動します。  「使用可能」リスト内のドライブはシステムから完全に削除されており、実行中のサービスやアクティブなデータは存在しません。

`RemoveDrives`非同期メソッドです。取り外すドライブの合計容量によっては、すべてのデータを移行するのに数分かかる場合があります。

複数のドライブを取り外す場合は、単一の `RemoveDrives`それぞれ 1 つのドライブを持つ複数の個別のメソッドではなく、メソッド呼び出しです。これにより、クラスター上のストレージ負荷を均等に安定させるために必要なデータバランス調整の量が削減されます。

「故障」ステータスのドライブを削除するには、 `RemoveDrives` 。 「障害」ステータスのドライブを削除しても、ドライブは「使用可能」または「アクティブ」ステータスに戻りません。ドライブはクラスター内で使用できません。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
ドライブ
 a| 
クラスターから削除するドライブ ID のリスト。
 a| 
整数配列
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| Name | 説明 | タイプ 


 a| 
非同期ハンドル
 a| 
操作結果を取得するために使用されるハンドル値。
 a| 
integer

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "RemoveDrives",
   "params": {
      "drives"  : [3, 4, 5]
   },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id": 1,
   "result" : {
     "asyncHandle": 1
   }
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

* xref:reference_element_api_getasyncresult.adoc[非同期結果を取得する]
* xref:reference_element_api_listdrives.adoc[リストドライブ]

