---
permalink: api/reference_element_api_task_virtual_volumes.html 
sidebar: sidebar 
keywords: object,objects,task 
summary: タスク オブジェクトには、システムで現在実行中または完了した仮想ボリューム タスクに関する情報が含まれます。  ListVirtualVolumeTasks メソッドを使用して、すべての仮想ボリューム タスクに関するこの情報を取得できます。 
---
= タスク（仮想ボリューム）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
タスク オブジェクトには、システムで現在実行中または完了した仮想ボリューム タスクに関する情報が含まれます。使用することができます `ListVirtualVolumeTasks`すべての仮想ボリューム タスクについてこの情報を取得する方法。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
キャンセル
 a| 
タスクがキャンセルされたかどうかを示します。有効な値は次のとおりです。

* true
* false

 a| 
ブーリアン



 a| 
クローン仮想ボリュームID
 a| 
クローンされる仮想ボリュームの一意の仮想ボリューム ID (クローン タスクの場合)。
 a| 
UUID



 a| 
親メタデータ
 a| 
仮想ボリュームの複製またはスナップショットを作成するタスクの親のメタデータを含むオブジェクト。
 a| 
JSONオブジェクト



 a| 
親の合計サイズ
 a| 
クローンまたはスナップショット タスクに親で使用可能な合計スペース (バイト単位)。
 a| 
integer



 a| 
親の使用サイズ
 a| 
クローンまたはスナップショット タスクの親の使用済み領域 (バイト単位)。
 a| 
integer



 a| 
operation
 a| 
タスクが実行している操作の種類。有効な値は次のとおりです。

* 不明: タスク操作は不明です。
* 準備: タスクは仮想ボリュームを準備しています。
* スナップショット: タスクは仮想ボリュームのスナップショットを作成しています。
* ロールバック: タスクは仮想ボリュームをスナップショットにロールバックしています。
* クローン: タスクは仮想ボリュームのクローンを作成しています。
* fastClone: タスクは仮想ボリュームの高速クローンを作成しています。
* copyDiffs: タスクは異なるブロックを仮想ボリュームにコピーしています。

 a| 
string



 a| 
ステータス
 a| 
仮想ボリューム タスクの現在のステータス。有効な値は次のとおりです。

* エラー: タスクが失敗し、エラーが返されました。
* キューに追加済み: タスクは実行を待機中です。
* 実行中: タスクは現在実行中です。
* 成功: タスクは正常に完了しました。

 a| 
string



 a| 
仮想ボリュームホストID
 a| 
タスクを開始したホストの一意の ID。
 a| 
UUID



 a| 
仮想ボリュームID
 a| 
新しい一意の仮想ボリューム ID (新しい仮想ボリュームを作成するタスクの場合)。
 a| 
UUID



 a| 
仮想ボリュームタスクID
 a| 
タスクの一意の ID。
 a| 
UUID

|===


== 詳細情報の参照

xref:reference_element_api_listvirtualvolumetasks.adoc[仮想ボリュームタスクの一覧]
