---
permalink: api/reference_element_api_deletevolume.html 
sidebar: sidebar 
keywords: volume,volumes,delete,deleting,DeleteVolume 
summary: DeleteVolume メソッドを使用して、アクティブなボリュームを削除対象としてマークできます。マークを付けると、クリーンアップ間隔が経過した後にボリュームがパージ（完全に削除）されます。 
---
= ボリュームの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `DeleteVolume`アクティブなボリュームを削除対象としてマークする方法。マークを付けると、クリーンアップ間隔が経過した後にボリュームがパージ (完全に削除) されます。

ボリュームの削除を要求すると、ボリュームへのアクティブな iSCSI 接続は直ちに終了され、ボリュームがこの状態にある間はそれ以上の接続は許可されません。マークされたボリュームは、ターゲット検出要求では返されません。

削除対象としてマークされたボリュームのスナップショットは影響を受けません。スナップショットは、ボリュームがシステムから削除されるまで保持されます。ボリュームが削除対象としてマークされており、一括ボリューム読み取りまたは一括ボリューム書き込み操作が進行中の場合、一括ボリューム読み取りまたは書き込み操作は停止されます。

削除するボリュームがボリュームとペアになっている場合、ペアになっているボリューム間のレプリケーションは中断され、削除された状態の間は、そのボリュームとの間でデータの転送は行われません。削除されたボリュームとペアになっていたリモート ボリュームは PausedMisconfigured 状態になり、そのボリュームまたは削除されたボリュームからのデータは送信されなくなります。削除されたボリュームが消去されるまで、ボリュームを復元してデータ転送を再開できます。削除されたボリュームがシステムから消去されると、そのボリュームとペアになっていたボリュームは StoppedMisconfigured 状態になり、ボリュームのペアリング ステータスは削除されます。パージされたボリュームは永久に使用できなくなります。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
volumeID
 a| 
削除するボリュームの ID。
 a| 
integer
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
音量
 a| 
削除されたボリュームに関する情報を含むオブジェクト。
 a| 
xref:reference_element_api_volume.adoc[音量]



 a| 
volumeID
 a| 
削除されたボリュームのボリュームID。
 a| 
integer



 a| 
曲線
 a| 
曲線はキーと値のペアのセットです。キーはバイト単位の I/O サイズです。値は、特定の I/O サイズで IOP を実行するコストを表します。曲線は、100 IOPS に設定された 4096 バイトの操作を基準として計算されます。
 a| 
JSONオブジェクト

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "DeleteVolume",
   "params": {
      "volumeID"  : 5
   },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "volume": {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
      },
      "blockSize": 4096,
      "createTime": "2016-03-28T16:16:13Z",
      "deleteTime": "2016-03-31T22:59:42Z",
      "enable512e": true,
      "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
      "name": "1459181777648",
      "purgeTime": "2016-04-01T06:59:42Z",
      "qos": {
        "burstIOPS": 150,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 100,
        "minIOPS": 60
      },
      "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
      "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
      "sliceCount": 1,
      "status": "deleted",
      "totalSize": 1000341504,
      "virtualVolumeID": null,
      "volumeAccessGroups": [
        1
      ],
      "volumeID": 5,
      "volumePairs": []
    }
  }
}
----


== バージョン以降の新機能

9.6
