---
permalink: api/reference_element_api_initiator.html 
sidebar: sidebar 
keywords: object,objects,initiator 
summary: イニシエーター オブジェクトには、iSCSI またはファイバー チャネル イニシエーターに関する情報が含まれています。イニシエーター オブジェクトには、IQN または WWPN 識別子を含めることができます。 ListInitiators メソッドを使用すると、システム上で既知のすべてのイニシエーターのリストを取得できます。イニシエーター オブジェクトを使用して、ボリューム アクセス グループを通じてボリューム セットへの SCSI イニシエーター アクセスを構成します。イニシエーターは、一度に 1 つのボリューム アクセス グループのメンバーにのみなることができます。 CreateInitiators メソッドと ModifyInitiators メソッドを使用して 1 つ以上の virtualNetworkID を指定することにより、イニシエーターのアクセスを 1 つ以上の VLAN に制限できます。仮想ネットワークを指定しない場合は、イニシエーターはすべてのネットワークにアクセスできます。 
---
= イニシエータ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イニシエーター オブジェクトには、iSCSI またはファイバー チャネル イニシエーターに関する情報が含まれています。イニシエーター オブジェクトには、IQN または WWPN 識別子を含めることができます。使用することができます `ListInitiators`システム上で既知のすべてのイニシエーターのリストを取得するメソッド。イニシエーター オブジェクトを使用して、ボリューム アクセス グループを通じてボリューム セットへの SCSI イニシエーター アクセスを構成します。イニシエーターは、一度に 1 つのボリューム アクセス グループのメンバーにのみなることができます。 1つ以上の仮想ネットワークIDを指定して、イニシエータのアクセスを1つ以上のVLANに制限することができます。 `CreateInitiators`そして `ModifyInitiators`方法。仮想ネットワークを指定しない場合は、イニシエーターはすべてのネットワークにアクセスできます。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
エイリアス
 a| 
イニシエーターに割り当てられているフレンドリ名（ある場合）。
 a| 
string



 a| 
attributes
 a| 
このイニシエーターに割り当てられた JSON 属性のセット。属性が割り当てられていない場合は空になります。
 a| 
JSONオブジェクト



 a| 
chapユーザー名
 a| 
このイニシエーターの一意の CHAP ユーザー名。
 a| 
string



 a| 
イニシエーターID
 a| 
イニシエーターの数値識別子。
 a| 
integer



 a| 
イニシエーター名
 a| 
IQN または WWPN 形式のイニシエーター名。
 a| 
string



 a| 
イニシエーターシークレット
 a| 
イニシエーターの認証に使用される CHAP シークレット。
 a| 
string



 a| 
必要なChap
 a| 
このイニシエーターに CHAP が必要な場合は True になります。
 a| 
ブーリアン



 a| 
ターゲットシークレット
 a| 
ターゲットを認証するために使用される CHAP シークレット (相互 CHAP 認証を使用する場合)。
 a| 
string



 a| 
仮想ネットワークID
 a| 
このイニシエーターに関連付けられている仮想ネットワーク識別子のリスト。 1 つ以上定義されている場合、このイニシエーターは指定された仮想ネットワークにのみログインできます。仮想ネットワークが定義されていない場合、このイニシエーターはすべてのネットワークにログインできます。
 a| 
integer



 a| 
ボリュームアクセスグループ
 a| 
このイニシエーターが属するボリューム アクセス グループ ID のリスト。
 a| 
整数配列

|===


== 詳細情報の参照

xref:reference_element_api_listinitiators.adoc[リストイニシエーター]
