---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: ListVolumes メソッドを使用して、クラスター内にあるボリュームのリストを取得できます。利用可能なパラメータを使用して、リストに返すボリュームを指定できます。 
---
= リストボリューム
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ListVolumes`クラスター内にあるボリュームのリストを取得するメソッド。利用可能なパラメータを使用して、リストに返すボリュームを指定できます。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
アカウント
 a| 
ここで指定したアカウントが所有するボリュームのみが返されます。  volumeIDs パラメータとは排他的です。
 a| 
整数配列
 a| 
なし
 a| 
いいえ



 a| 
仮想ボリュームを含める
 a| 
仮想ボリュームはデフォルトで応答に含まれます。仮想ボリュームを除外するには、false に設定します。
 a| 
ブーリアン
 a| 
true
 a| 
いいえ



 a| 
ペアリング済み
 a| 
ペアになっているボリュームとペアになっていないボリュームを返します。有効な値は次のとおりです。

* true: ペアになっているすべてのボリュームを返します。
* false: ペアリングされていないすべてのボリュームを返します。

 a| 
ブーリアン
 a| 
なし
 a| 
いいえ



 a| 
limit
 a| 
返されるボリューム結果の最大数を設定できます。  volumeIDs パラメータとは排他的です。
 a| 
integer
 a| 
10000
 a| 
いいえ



 a| 
開始ボリュームID
 a| 
この値以上の ID を持つボリュームのみが返されます。  volumeIDs パラメータとは排他的です。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
ボリュームID
 a| 
ボリューム ID のリスト。このパラメータを指定すると、他のパラメータはこのボリューム セットに対してのみ動作します。  accounts、startVolumeID、limit パラメータとは相互に排他的です。
 a| 
整数配列
 a| 
いいえ
 a| 
いいえ



 a| 
volumeName
 a| 
ボリューム名に一致するボリューム オブジェクト情報のみが返されます。
 a| 
string
 a| 
いいえ
 a| 
いいえ



 a| 
ボリュームステータス
 a| 
ステータス値と等しいステータスを持つボリュームのみが返されます。有効な値は次のとおりです。

* 作成
* スナップショット
* active
* 削除済み

 a| 
string
 a| 
いいえ
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
ボリューム
 a| 
巻の一覧。
 a| 
xref:reference_element_api_volume.adoc[音量]配列

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== バージョン以降の新機能

9.6
