---
permalink: api/reference_element_api_clonevolume.html 
sidebar: sidebar 
keywords: volumes,volume,cloning,clone,CloneVolume 
summary: CloneVolume メソッドを使用してボリュームのコピーを作成できます。このメソッドは非同期であり、完了するまでにさまざまな時間がかかる可能性があります。 
---
= CloneVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `CloneVolume`ボリュームのコピーを作成する方法。このメソッドは非同期であり、完了するまでにさまざまな時間がかかる可能性があります。

クローン作成プロセスは、 `CloneVolume`リクエストであり、API メソッドが発行されたときのボリュームの状態を表します。使用することができますxref:reference_element_api_getasyncresult.adoc[非同期結果を取得する]クローン作成プロセスが完了し、新しいボリュームが接続可能になったかどうかを判定する方法。使用できますxref:reference_element_api_listsyncjobs.adoc[リスト同期ジョブ]クローンの作成の進行状況を確認します。ボリュームの初期属性とサービス品質設定は、複製されるボリュームから継承されます。これらの設定は、xref:reference_element_api_modifyvolume.adoc[ボリュームの変更] 。


NOTE: クローンボリュームは、ソースボリュームからボリューム アクセス グループのメンバーシップを継承しません。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
アクセス
 a| 
新しいボリュームへのアクセスが許可されました。値が指定されていない場合、アクセス値は変更されません。有効な値は次のとおりです。

* `readOnly`: (オプション) 読み取り操作のみが許可されます。
* `readWrite`: (オプション) 読み取りと書き込みが許可されます。
* `locked`: (オプション) 読み取りまたは書き込みは許可されません。指定しない場合は、複製されるボリュームのアクセス値が使用されます。
* `replicationTarget`: (オプション) ボリュームのペア セットのターゲット ボリュームとしてボリュームを識別します。ボリュームがペアリングされていない場合、アクセス状態はロックされます。

 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSONオブジェクト
 a| 
なし
 a| 
いいえ



 a| 
enable512e
 a| 
新しいボリュームで 512 バイト セクター エミュレーションを使用するかどうかを指定します。指定しない場合は、クローンされるボリュームの設定が使用されます。
 a| 
ブーリアン
 a| 
オリジナル音量の設定
 a| 
いいえ



 a| 
SnapMirrorReplication を有効にする
 a| 
ボリュームをSnapMirrorエンドポイントでのレプリケーションに使用できるかどうかを決定します。有効な値は次のとおりです。

* true
* false

 a| 
ブーリアン
 a| 
false
 a| 
いいえ



 a| 
名前
 a| 
新しいクローンボリュームの名前。長さは 1 ～ 64 文字にする必要があります。
 a| 
string
 a| 
なし
 a| 
はい



 a| 
新しいアカウントID
 a| 
新しいボリュームの所有者のアカウント ID。指定しない場合は、複製されるボリュームの所有者のアカウント ID が使用されます。
 a| 
integer
 a| 
元のボリュームの所有者のアカウントID
 a| 
いいえ



 a| 
新しいサイズ
 a| 
ボリュームの新しいサイズ（バイト単位）。クローンされるボリュームのサイズよりも大きくなったり小さくなったりする可能性があります。指定しない場合はボリューム サイズは変更されません。サイズは 1MB 単位に切り上げられます。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
スナップショットID
 a| 
クローンのソースとして使用されるスナップショットの ID。  ID が指定されていない場合は、現在アクティブなボリュームが使用されます。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
volumeID
 a| 
クローンするボリュームのボリュームID。
 a| 
integer
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
非同期ハンドル
 a| 
操作結果を取得するために使用されるハンドル値。
 a| 
integer



 a| 
クローンID
 a| 
新しくクローンされたボリュームのクローン ID。
 a| 
integer



 a| 
曲線
 a| 
クローンに対して適用される QoS 曲線の値。
 a| 
JSONオブジェクト



 a| 
音量
 a| 
新しく複製されたボリュームに関する情報を含むオブジェクト。
 a| 
xref:reference_element_api_volume.adoc[音量]



 a| 
volumeID
 a| 
新しく複製されたボリュームのボリューム ID。
 a| 
integer

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "CloneVolume",
   "params": {
      "volumeID" : 5,
      "name"  : "mysqldata-snapshot1",
      "access" : "readOnly"
   },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
      "asyncHandle": 42,
      "cloneID": 37,
      "volume": {
          "access": "readOnly",
          "accountID": 1,
          "attributes": {},
          "blockSize": 4096,
          "createTime": "2016-03-31T22:26:03Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.mysqldata-snapshot1.680",
          "name": "mysqldata-snapshot1",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 100,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 50
          },
          "scsiEUIDeviceID": "6a796179000002a8f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a796179000002a8",
          "sliceCount": 0,
          "status": "init",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [],
          "volumeID": 680,
          "volumePairs": []
      },
      "volumeID": 680
  }
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

* xref:reference_element_api_getasyncresult.adoc[非同期結果を取得する]
* xref:reference_element_api_listsyncjobs.adoc[リスト同期ジョブ]
* xref:reference_element_api_modifyvolume.adoc[ボリュームの変更]

