---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: StartVolumePairing メソッドを使用すると、別のボリュームとペアリングするために使用されるボリュームからエンコードされたキーを作成できます。このメソッドによって作成されるキーは、CompleteVolumePairing メソッドでボリュームのペアリングを確立するために使用されます。 
---
= ボリュームペアリングの開始
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `StartVolumePairing`別のボリュームとペアリングするために使用されるボリュームからエンコードされたキーを作成する方法。このメソッドで作成されるキーは、 `CompleteVolumePairing`ボリュームのペアリングを確立する方法。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
モード
 a| 
ペアリング プロセスを開始するボリュームのモード。モードは、ボリュームがソース ボリュームである場合にのみ設定できます。有効な値は次のとおりです。

* `Async`: 書き込みはローカルで完了すると確認応答されます。クラスターは、書き込みがターゲット クラスターに複製されるまで待機しません。  (モード パラメータが指定されていない場合はデフォルトです。)
* `Sync`: データがローカルおよびリモート クラスターに保存されるときに、ソースは書き込みを確認します。
* `SnapshotsOnly`: ソース クラスターで作成されたスナップショットのみが複製されます。ソース ボリュームからのアクティブな書き込みは複製されません。

 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
volumeID
 a| 
ペアリング プロセスを開始するボリュームの ID。
 a| 
integer
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| Name | 説明 | タイプ 


 a| 
ボリュームペアリングキー
 a| 
使用される文字列xref:reference_element_api_completevolumepairing.adoc[完全な音量ペアリング]API メソッド。
 a| 
string

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

xref:reference_element_api_completevolumepairing.adoc[完全な音量ペアリング]
