---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: ModifyVirtualNetwork メソッドを使用して、既存の仮想ネットワークの属性を変更できます。 
---
= 仮想ネットワークの変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ModifyVirtualNetwork`既存の仮想ネットワークの属性を変更する方法。

この方法を使用すると、アドレス ブロックを追加または削除したり、ネットマスクを変更したり、仮想ネットワークの名前や説明を変更したりできます。また、これを使用して、名前空間を有効化または無効化したり、仮想ネットワーク上で名前空間が有効になっている場合はゲートウェイを追加または削除したりすることもできます。


NOTE: このメソッドでは、パラメーターとして virtualNetworkID または virtualNetworkTag のいずれかが必要ですが、両方は必要ありません。

警告：

名前空間パラメータを変更して既存の仮想ネットワークのルーティング可能なストレージ VLAN 機能を有効または無効にすると、仮想ネットワークによって処理されるトラフィックが中断されます。名前空間パラメータの変更は、スケジュールされたメンテナンス ウィンドウ中に行うのが最適です。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===


| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
仮想ネットワークID
 a| 
変更する仮想ネットワークの一意の識別子。これはクラスターによって割り当てられた仮想ネットワーク ID です。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
仮想ネットワークタグ
 a| 
変更する仮想ネットワークを識別するネットワーク タグ。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
アドレスブロック
 a| 
この仮想ネットワークに設定する新しいアドレス ブロック。これには、既存のオブジェクトに追加する新しいアドレス ブロックや、削除する必要がある未使用のアドレス ブロックを省略することが含まれる場合があります。あるいは、既存のアドレス ブロックのサイズを拡張または縮小することもできます。仮想ネットワーク オブジェクトの開始アドレス ブロックのサイズを増やすことしかできず、減らすことはできません。このオブジェクトに必要なメンバー:

* start: IP アドレス範囲の開始。  （弦）
* size: ブロックに含める IP アドレスの数。  （整数）

 a| 
JSONオブジェクト
 a| 
なし
 a| 
いいえ



 a| 
ゲートウェイ
 a| 
仮想ネットワークのゲートウェイの IP アドレス。このパラメータは、名前空間パラメータが true に設定されている場合にのみ有効です。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSONオブジェクト
 a| 
なし
 a| 
いいえ



 a| 
名前
 a| 
仮想ネットワークの新しい名前。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
namespace
 a| 
true に設定すると、仮想ネットワークを再作成し、それを含める名前空間を構成することで、ルーティング可能なストレージ VLAN 機能が有効になります。 false に設定すると、仮想ネットワークの VRF 機能が無効になります。この値を変更すると、この仮想ネットワークを通過するトラフィックが中断されます。
 a| 
ブーリアン
 a| 
なし
 a| 
いいえ



 a| 
netmask
 a| 
この仮想ネットワークの新しいネットワーク マスク。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
svip
 a| 
この仮想ネットワークのストレージ仮想 IP アドレス。仮想ネットワークの SVIP は変更できません。別の SVIP アドレスを使用するには、新しい仮想ネットワークを作成する必要があります。
 a| 
string
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには戻り値はありません。



== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== バージョン以降の新機能

9.6
