---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: ListAuthSessionsByUsername メソッドを使用して、指定したユーザーのすべての認証セッションを一覧表示できます。  AccessGroup ClusterAdmins / 管理者権限を持たない発信者は、自分のセッションのみをリストできます。  ClusterAdmins / Administrator 権限を持つ呼び出し元は、任意のユーザーに属するセッションを一覧表示できます。 
---
= ユーザー名による認証セッションの一覧
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ListAuthSessionsByUsername`指定されたユーザーのすべての認証セッションを一覧表示するメソッド。  AccessGroup ClusterAdmins / 管理者権限を持たない発信者は、自分のセッションのみをリストできます。  ClusterAdmins / Administrator 権限を持つ呼び出し元は、任意のユーザーに属するセッションを一覧表示できます。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
認証方法
 a| 
一覧表示するユーザー セッションの認証方法。 ClusterAdmins/Administrator AccessGroup 内の呼び出し元のみがこのパラメータを提供できます。有効な値は次のとおりです。

* *authMethod=Cluster* は ClusterAdmin ユーザー名を指定します。
* *authMethod=Ldap* はユーザーの LDAP DN を指定します。
* *authMethod=Idp* は、ユーザーの IdP UUID または NameID のいずれかを指定します。  IdP がどちらのオプションも返すように設定されていない場合は、セッションの作成時に発行されたランダム UUID を指定します。

 a| 
認証方法
 a| 
なし
 a| 
はい



 a| 
ユーザ名
 a| 
ユーザーの一意の識別子。
 a| 
string
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
セッション
 a| 
認証セッションのセッション情報のリスト。
 a| 
link:reference_element_api_authsessioninfo.html["認証セッション情報"]

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== バージョン以降の新機能

12.0
