---
permalink: api/reference_element_api_purgedeletedvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,purge,purging,multiple,deleted,purgedeletedvolumes 
summary: PurgeDeletedVolumes メソッドを使用すると、削除されたボリュームを即時かつ永続的に消去できます。このメソッドを使用すると、一度に最大 500 個のボリュームを消去できます。 
---
= 削除されたボリュームの消去
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `PurgeDeletedVolumes`削除されたボリュームを即時かつ永続的に消去する方法。この方法を使用すると、一度に最大 500 個のボリュームを消去できます。

ボリュームを削除するには、 `DeleteVolumes`削除される前に。ボリュームは一定期間後に自動的に消去されるため、通常はこの方法を使用する必要はありません。


NOTE: 一度に多数のボリュームを消去する場合、または消去する各ボリュームに多数の関連付けられたスナップショットがある場合、メソッドは失敗し、エラー「xDBConnectionLoss」が返される可能性があります。このような場合は、ボリューム数を減らしてメソッド呼び出しを再試行してください。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


| ボリュームID | システムから削除するボリュームのボリューム ID のリスト。 | 整数配列 | いいえ | いいえ 


| アカウントID | アカウントIDのリスト。指定されたすべてのアカウントのすべてのボリュームがシステムから削除されます。 | 整数配列 | いいえ | いいえ 


| ボリュームアクセスグループID | volumeAccessGroupID のリスト。指定されたすべてのボリューム アクセス グループのすべてのボリュームがシステムから削除されます。 | 整数配列 | いいえ | いいえ 
|===
*注:* メソッド呼び出しごとに上記のパラメータを 1 つだけ指定できます。複数指定する場合、またはまったく指定しない場合は、エラーが発生します。



== 戻り値

このメソッドには戻り値はありません。



== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "PurgeDeletedVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id" : 1,
  "result": {}
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

xref:reference_element_api_deletevolumes.adoc[ボリュームの削除]
