---
permalink: api/reference_element_api_listsnapmirrorvolumes.html 
sidebar: sidebar 
keywords: snapmirror,volume,list,listing,volumes,listsnapmirrorvolumes,ontap 
summary: Element ソフトウェア Web UI は、ListSnapMirrorVolumes メソッドを使用して、リモートONTAPシステムで使用可能なすべてのSnapMirrorボリュームを一覧表示します。 
---
= スナップミラーボリュームのリスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ElementソフトウェアのWeb UIは、 `ListSnapMirrorVolumes`リモートONTAPシステムで使用可能なすべてのSnapMirrorボリュームを一覧表示する方法。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
スナップミラーエンドポイントID
 a| 
指定されたエンドポイント ID に関連付けられているボリュームのみを一覧表示します。エンドポイント ID が指定されていない場合、システムは既知のすべてのSnapMirrorエンドポイントのボリュームを一覧表示します。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
SVM
 a| 
指定された Vserver でホストされているボリュームを一覧表示します。  Vserver は「データ」タイプである必要があります。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
名前
 a| 
指定された名前のONTAPボリュームのみを一覧表示します。
 a| 
string
 a| 
なし
 a| 
いいえ



 a| 
type
 a| 
指定されたタイプのONTAPボリュームのみを一覧表示します。有効な値は次のとおりです。

* rw: 読み書きボリューム
* ls: 負荷分散ボリューム
* dp: データ保護ボリューム

 a| 
string
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
スナップミラーボリューム
 a| 
ONTAPストレージ システムで使用可能なSnapMirrorボリュームのリスト。
 a| 
xref:reference_element_api_snapmirrorvolume.adoc[スナップミラーボリューム]配列

|===


== バージョン以降の新機能

10.1
