---
permalink: api/reference_element_api_session_iscsi.html 
sidebar: sidebar 
keywords: object,objects,session 
summary: 'セッション \(iSCSI\) オブジェクトには、各ボリュームの iSCSI セッションに関する詳細情報が含まれています。  ListISCSISessions API メソッドを使用して iSCSI セッション情報を取得できます。' 
---
= セッション（iSCSI）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
セッション (iSCSI) オブジェクトには、各ボリュームの iSCSI セッションに関する詳細情報が含まれています。  iSCSIセッション情報を取得するには、 `ListISCSISessions` API メソッド。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
accountID
 a| 
CHAP 認証に使用されるアカウントのアカウント ID（存在する場合）。
 a| 
integer



 a| 
accountName
 a| 
CHAP 認証に使用されるアカウントの名前（存在する場合）。
 a| 
string



 a| 
認証
 a| 
この iSCSI セッションの認証情報。
 a| 
xref:reference_element_api_iscsiauthentication.adoc[iSCSI認証]



 a| 
作成時間
 a| 
iSCSI セッションの作成時刻（UTC+0 形式）。
 a| 
ISO 8601日付文字列



 a| 
ドライブID
 a| 
セッションをホストするトランスポート サービスに関連付けられたドライブ ID。
 a| 
integer



 a| 
ドライブID
 a| 
障害を報告しているドライブのドライブ ID のリスト。該当しない場合は空のリスト。
 a| 
整数配列



 a| 
イニシエータ
 a| 
この iSCSI セッションのサーバー イニシエーターに関する情報。メンバー:

* エイリアス: イニシエーターに割り当てられたフレンドリ名。
* 属性: このイニシエーターの属性。
* イニシエーターID: このイニシエーターの ID。
* イニシエーター名: このイニシエーターの名前。
* volumeAccessGroups: このイニシエーターに関連付けられているボリューム アクセス グループのリスト。

 a| 
JSONオブジェクト



 a| 
イニシエーターIP
 a| 
iSCSI サーバー イニシエーターの IP アドレスとポート番号。
 a| 
string



 a| 
イニシエーター名
 a| 
iSCSI サーバー イニシエーターの iSCSI 修飾名 (IQN)。
 a| 
string



 a| 
イニシエーターポート名
 a| 
イニシエーター名とイニシエーターセッションIDの組み合わせにより、イニシエーター ポートが識別されます。
 a| 
string



 a| 
イニシエーターセッションID
 a| 
イニシエーターによって提供される 48 ビットの ID で、iSCSI セッションがそのイニシエーターに属することを識別します。
 a| 
integer



 a| 
前回のIscsiPDUからの経過時間
 a| 
このセッションで最後の iSCSI PDU が受信されてからの経過時間 (ミリ秒)。
 a| 
integer



 a| 
前回のScsiコマンドからの経過時間
 a| 
このセッションで最後の SCSI コマンドが受信されてからの経過時間 (ミリ秒)。
 a| 
integer



 a| 
nodeID
 a| 
セッションをホストするトランスポート サービスに関連付けられたノード ID。
 a| 
integer



 a| 
サービスID
 a| 
セッションをホストするトランスポート サービスのサービス ID。
 a| 
integer



 a| 
sessionID
 a| 
iSCSI セッション ID。
 a| 
integer



 a| 
ターゲットIP
 a| 
iSCSI ストレージ ターゲットの IP アドレスとポート番号。
 a| 
string



 a| 
ターゲット名
 a| 
iSCSI ターゲットの IQN。
 a| 
string



 a| 
ターゲットポート名
 a| 
ターゲット ポータル グループ タグと組み合わせた targetName は、ターゲット ポートを識別します。
 a| 
string



 a| 
仮想ネットワークID
 a| 
セッションに関連付けられた仮想ネットワーク ID。
 a| 
integer



 a| 
volumeID
 a| 
セッションに関連付けられているボリュームのボリューム ID（存在する場合）。
 a| 
integer



 a| 
ボリュームインスタンス
 a| 
iSCSI セッションに関連付けられているボリューム オブジェクトを識別します (存在する場合)。
 a| 
integer

|===


== 詳細情報の参照

xref:reference_element_api_listiscsisessions.adoc[ISCSIセッションのリスト]
