---
permalink: api/reference_element_api_modifyclusterfullthreshold.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,cluster,full,fullness,threshold,modifyclusterfullthreshold 
summary: ModifyClusterFullThreshold メソッドを使用すると、ストレージ クラスターが特定の容量使用率に近づいたときにシステムがイベントを生成するレベルを変更できます。しきい値設定を使用すると、システムが警告を生成する前に許容されるブロック ストレージの使用量を示すことができます。 
---
= クラスタフルしきい値の変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ModifyClusterFullThreshold`ストレージ クラスターが特定の容量使用率に近づいたときにシステムがイベントを生成するレベルを変更する方法。しきい値設定を使用すると、システムが警告を生成する前に許容されるブロック ストレージの使用量を示すことができます。

たとえば、システムのブロック ストレージ使用率が「エラー」レベルの 3% を下回ったときに警告を受け取るようにするには、stage3BlockThresholdPercent パラメータに「3」の値を入力します。このレベルに達すると、システムはクラスタ管理コンソールのイベント ログにアラートを送信します。



== パラメータ

このメソッドには次の入力パラメータがあります。


NOTE: 少なくとも 1 つのパラメータを選択する必要があります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
最大メタデータオーバープロビジョニング係数
 a| 
使用可能なスペースの量に対してメタデータ スペースを過剰にプロビジョニングできる回数を表す値。たとえば、100 TiB のボリュームを保存するのに十分なメタデータ領域があり、この数値が 5 に設定されている場合、500 TiB 相当のボリュームを作成できます。
 a| 
integer
 a| 
5
 a| 
いいえ



 a| 
ステージ2認識しきい値
 a| 
システムが容量通知をトリガーする前にクラスター内に残っている容量のノードの数。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
ステージ3ブロックしきい値パーセント
 a| 
システムがクラスターの「警告」アラートをトリガーする「エラー」しきい値を下回るブロック ストレージ使用率のパーセンテージ。
 a| 
integer
 a| 
なし
 a| 
いいえ



 a| 
ステージ3メタデータしきい値パーセント
 a| 
システムがクラスターの「警告」アラートをトリガーする「エラー」しきい値を下回るメタデータ ストレージ使用率のパーセンテージ。
 a| 
integer
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドには次の戻り値があります。

|===


| Name | 説明 | タイプ 


 a| 
ブロックの満ち欠け
 a| 
クラスターのブロック占有率の現在の計算レベル。

* stage1Happy: アラートやエラー状態はありません。  Web UI の *正常* 状態に対応します。
* stage2Aware: アラートやエラー状態はありません。  Web UI の *正常* 状態に対応します。
* stage3Low: システムは、同時ではない 2 つのノード障害からの冗長データ保護を提供できません。 Web UI の *警告* 状態に対応します。このレベルは Web UI で設定できます (デフォルトでは、システムはエラー状態より 3% 低い容量でこのアラートをトリガーします)。
* stage4Critical: システムは、単一ノード障害からの冗長データ保護を提供できません。新しいボリュームやクローンを作成できません。要素 UI の *エラー* 状態に対応します。
* stage5CompletelyConsumed: 完全に消費されました。クラスターは読み取り専用であり、iSCSI 接続は維持されますが、すべての書き込みは中断されます。要素 UI の *Critical* 状態に対応します。

 a| 
string



 a| 
満腹感
 a| 
「blockFullness」と「metadataFullness」の間の最も高いレベルの完全性を反映します。
 a| 
string



 a| 
最大メタデータオーバープロビジョニング係数
 a| 
使用可能なスペースの量に対してメタデータ スペースを過剰にプロビジョニングできる回数を表す値。たとえば、100 TiB のボリュームを保存するのに十分なメタデータ領域があり、この数値が 5 に設定されている場合、500 TiB 相当のボリュームを作成できます。
 a| 
integer



 a| 
メタデータの完全性
 a| 
クラスターのメタデータの完全性の現在の計算レベル。

* stage1Happy: アラートやエラー状態はありません。  Web UI の *正常* 状態に対応します。
* stage2Aware: アラートやエラー状態はありません。  Web UI の *正常* 状態に対応します。
* stage3Low: システムは、同時ではない 2 つのノード障害からの冗長データ保護を提供できません。 Web UI の *警告* 状態に対応します。このレベルは Web UI で設定できます (デフォルトでは、システムはエラー状態より 3% 低い容量でこのアラートをトリガーします)。
* stage4Critical: システムは、単一ノード障害からの冗長データ保護を提供できません。新しいボリュームやクローンを作成できません。要素 UI の *エラー* 状態に対応します。
* stage5CompletelyConsumed: 完全に消費されました。クラスターは読み取り専用であり、iSCSI 接続は維持されますが、すべての書き込みは中断されます。要素 UI の *Critical* 状態に対応します。

 a| 
string



 a| 
スライス予約使用しきい値パーセント
 a| 
エラー状態。予約されたスライスの使用率が返された sliceReserveUsedThresholdPct 値より大きい場合、システム アラートがトリガーされます。
 a| 
integer



 a| 
ステージ2認識しきい値
 a| 
認識状態。  「ステージ 2」のクラスターしきい値レベルに設定されている値。
 a| 
integer



 a| 
ステージ2ブロックしきい値バイト
 a| 
ステージ 2 の満杯状態が発生するクラスターによって使用されているバイト数。
 a| 
integer



 a| 
ステージ2メタデータしきい値バイト
 a| 
ステージ 2 の満杯状態が存在するクラスターによって使用されているメタデータ バイト数。
 a| 



 a| 
ステージ3ブロックしきい値バイト
 a| 
ステージ 3 の満杯状態が発生するクラスターによって使用されているストレージ バイト数。
 a| 
integer



 a| 
ステージ3ブロックしきい値パーセント
 a| 
ステージ 3 に設定されたパーセント値。この割合に達すると、アラート ログに警告が記録されます。
 a| 
integer



 a| 
ステージ3低閾値
 a| 
エラー状態。クラスターの容量不足によりシステムアラートが作成されるしきい値。
 a| 
integer



 a| 
ステージ3メタデータしきい値バイト
 a| 
ステージ 3 の満杯状態が存在するクラスターによって使用されるメタデータ バイト数。
 a| 



 a| 
ステージ4ブロックしきい値バイト
 a| 
ステージ 4 の満杯状態が発生するクラスターによって使用されているストレージ バイト数。
 a| 
integer



 a| 
ステージ4クリティカルしきい値
 a| 
エラー状態。クラスターの容量が極端に低下していることを警告するシステムアラートが作成されるしきい値。
 a| 
integer



 a| 
ステージ4メタデータしきい値バイト
 a| 
ステージ 4 の満杯状態が存在するクラスターによって使用されるメタデータ バイト数。
 a| 



 a| 
ステージ5ブロックしきい値バイト
 a| 
ステージ 5 の満杯状態が発生するクラスターで使用されるストレージ バイト数。
 a| 
integer



 a| 
ステージ5メタデータしきい値バイト
 a| 
ステージ 5 の満杯状態が存在するクラスターによって使用されるメタデータ バイト数。
 a| 



 a| 
合計クラスターバイト数
 a| 
クラスターの物理容量（バイト単位で測定）。
 a| 
integer



 a| 
合計メタデータクラスターバイト数
 a| 
メタデータを保存するために使用できるスペースの合計量。
 a| 
integer



 a| 
合計使用済みクラスターバイト
 a| 
クラスターで使用されるストレージ バイト数。
 a| 
integer



 a| 
使用されたメタデータクラスターバイトの合計
 a| 
メタデータを保存するためにボリューム ドライブ上で使用されるスペースの量。
 a| 
integer

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method" : "ModifyClusterFullThreshold",
   "params" : {
              "stage3BlockThresholdPercent" : 3
              },
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "blockFullness": "stage1Happy",
    "fullness": "stage3Low",
    "maxMetadataOverProvisionFactor": 5,
    "metadataFullness": "stage3Low",
    "sliceReserveUsedThresholdPct": 5,
    "stage2AwareThreshold": 3,
    "stage2BlockThresholdBytes": 2640607661261,
    "stage3BlockThresholdBytes": 8281905846682,
    "stage3BlockThresholdPercent": 3,
    "stage3LowThreshold": 2,
    "stage4BlockThresholdBytes": 8641988709581,
    "stage4CriticalThreshold": 1,
    "stage5BlockThresholdBytes": 12002762096640,
    "sumTotalClusterBytes": 12002762096640,
    "sumTotalMetadataClusterBytes": 404849531289,
    "sumUsedClusterBytes": 45553617581,
    "sumUsedMetadataClusterBytes": 31703113728
  }
}
----


== バージョン以降の新機能

9.6
