---
permalink: api/reference_element_api_listinitiators.html 
sidebar: sidebar 
keywords: initiators,initiator,list,listing,listinitiators,iqn,wwpn,iqns,wwpns 
summary: 'ListInitiators メソッドを使用して、イニシエーター IQN またはワールド ワイド ポート名 (WWPN) のリストを取得できます。' 
---
= リストイニシエーター
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ListInitiators`イニシエーター IQN またはワールド ワイド ポート名 (WWPN) のリストを取得する方法。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
イニシエータ
 a| 
取得するイニシエーター ID のリスト。このパラメータまたは startInitiatorID パラメータのいずれかを指定できますが、両方を指定することはできません。
 a| 
整数配列
 a| 
なし
 a| 
いいえ



 a| 
開始イニシエーターID
 a| 
リストを開始するイニシエーター ID。このパラメータまたはイニシエーターパラメータのいずれかを指定できますが、両方を指定することはできません。
 a| 
integer
 a| 
0
 a| 
いいえ



 a| 
limit
 a| 
返されるイニシエーター オブジェクトの最大数。
 a| 
integer
 a| 
（無制限）
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
イニシエータ
 a| 
イニシエーター情報のリスト。
 a| 
xref:reference_element_api_initiator.adoc[イニシエータ]配列

|===


== 例外

このメソッドには次の例外が発生する可能性があります。

|===


| Name | 説明 


 a| 
x無効なパラメータ
 a| 
同じメソッド呼び出しに startInitiatorID とイニシエーター パラメータの両方を含めるとスローされます。

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "ListInitiators",
   "params": {},
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "initiators": [
      {
        "alias": "",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:c84ffd71216",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== バージョン以降の新機能

9.6
