---
permalink: api/reference_element_api_deleteauthsessionsbyusername.html 
sidebar: sidebar 
keywords: auth sessions,username,delete,authentication sessions 
summary: DeleteAuthSessionsByUsername メソッドを使用して、特定のユーザーのすべての認証セッションを削除できます。  AccessGroup ClusterAdmins/Administrator に属していない発信者は、自分のセッションのみを削除できます。 ClusterAdmins/Administrator 権限を持つ呼び出し元は、任意のユーザーに属するセッションを削除できます。削除できるセッションのリストを表示するには、同じパラメータを使用して ListAuthSessionsByUsername を使用します。削除の可能性があるセッションのリストを表示するには、同じパラメータを持つ ListAuthSessionsByUsername メソッドを使用します。 
---
= ユーザー名による認証セッションの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `DeleteAuthSessionsByUsername`特定のユーザーのすべての認証セッションを削除するメソッド。  AccessGroup ClusterAdmins/Administrator に属していない発信者は、自分のセッションのみを削除できます。 ClusterAdmins/Administrator 権限を持つ呼び出し元は、任意のユーザーに属するセッションを削除できます。削除できるセッションのリストを表示するには、 `ListAuthSessionsByUsername`同じパラメータで。削除可能なセッションのリストを表示するには、 `ListAuthSessionsByUsername`同じパラメータを持つメソッド。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
認証方法
 a| 
削除するユーザー セッションの認証方法。 ClusterAdmins/Administrator AccessGroup 内の呼び出し元のみがこのパラメータを提供できます。有効な値は次のとおりです。

* *authMethod=Cluster* は ClusterAdmin ユーザー名を指定します。
* *authMethod=Ldap* はユーザーの LDAP DN を指定します。
* *authMethod=Idp* は、ユーザーの IdP UUID または NameID のいずれかを指定します。  IdP がどちらのオプションも返すように設定されていない場合は、セッションの作成時に発行されたランダム UUID を指定します。

 a| 
認証方法
 a| 
なし
 a| 
いいえ



 a| 
ユーザ名
 a| 
ユーザーの一意の識別子。
 a| 
string
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===


| Name | 説明 | タイプ 


 a| 
セッション
 a| 
削除された認証セッションのセッション情報。
 a| 
link:reference_element_api_authsessioninfo.html["認証セッション情報"]

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "DeleteAuthSessionsByUsername",
  "params": {
    "authMethod": "Cluster",
    "username": "admin"
  }
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== バージョン以降の新機能

12.0
