---
permalink: api/reference_element_api_listvolumestatsbyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,access,group,listvolumestatsbyvolumeaccessgroup,activity 
summary: ListVolumeStatsByVolumeAccessGroup メソッドを使用すると、指定されたボリューム アクセス グループのメンバーであるすべてのボリュームの合計アクティビティ測定値を一覧表示できます。 
---
= ボリュームアクセスグループごとのボリューム統計のリスト
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `ListVolumeStatsByVolumeAccessGroup`指定されたボリューム アクセス グループのメンバーであるすべてのボリュームの合計アクティビティ測定値を一覧表示するメソッド。



== パラメータ

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
仮想ボリュームを含める
 a| 
仮想ボリュームはデフォルトで応答に含まれます。仮想ボリュームを除外するには、false に設定します。
 a| 
ブーリアン
 a| 
true
 a| 
いいえ



 a| 
ボリュームアクセスグループ
 a| 
ボリューム アクティビティが返される VolumeAccessGroupID の配列。省略した場合、すべてのボリューム アクセス グループの統計が返されます。
 a| 
整数配列
 a| 
なし
 a| 
いいえ

|===


== 戻り値

このメソッドの戻り値は次のとおりです。

|===
| Name | 説明 | タイプ 


 a| 
ボリューム統計
 a| 
指定されたボリューム アクセス グループ内のすべてのボリュームのボリューム アクティビティ情報のリスト。*注:* 値はアカウントが所有するすべてのボリュームの合計を表すため、各エントリの volumeID メンバーは 0 になります。
 a| 
xref:reference_element_api_volumestats.adoc[ボリューム統計]

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "ListVolumeStatsByVolumeAccessGroup",
    "params": {"volumeAccessGroups": [1]},
    "id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 0,
        "nonZeroBlocks": 149366393,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T21:04:10.712370Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 0,
        "volumeSize": 1073741824000,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 112777607
      }
    ]
  }
}
----


== バージョン以降の新機能

9.6
