---
permalink: api/reference_element_api_addldapclusteradmin.html 
sidebar: sidebar 
keywords: LDAP,cluster,admin,add,adding,addldapclusteradmin 
summary: AddLdapClusterAdmin を使用して、新しい LDAP クラスター管理者ユーザーを追加できます。  LDAP クラスター管理者は、API と管理ツールを使用してクラスターを管理できます。  LDAP クラスター管理者アカウントは標準のテナント アカウントとは完全に別個であり、無関係です。 
---
= LdapClusterAdmin の追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `AddLdapClusterAdmin`新しい LDAP クラスタ管理者ユーザーを追加します。  LDAP クラスター管理者は、API と管理ツールを使用してクラスターを管理できます。  LDAP クラスター管理者アカウントは標準のテナント アカウントとは完全に別個であり、無関係です。



== パラメータ

この方法を使用して、Active Directory® で定義されている LDAP グループを追加することもできます。グループに付与されたアクセス レベルは、LDAP グループ内の個々のユーザーに渡されます。

このメソッドには次の入力パラメータがあります。

|===
| Name | 説明 | タイプ | デフォルト値 | 必須 


 a| 
アクセス
 a| 
このクラスター管理者が使用できる方法を制御します。
 a| 
文字列配列
 a| 
なし
 a| 
はい



 a| 
EULAを受け入れる
 a| 
エンド ユーザ ライセンス契約に同意します。クラスター管理者アカウントをシステムに追加するには、true に設定します。省略または false に設定された場合、メソッド呼び出しは失敗します。
 a| 
ブーリアン
 a| 
なし
 a| 
はい



 a| 
attributes
 a| 
JSON オブジェクト形式の名前と値のペアのリスト。
 a| 
JSONオブジェクト
 a| 
なし
 a| 
いいえ



 a| 
ユーザ名
 a| 
新しい LDAP クラスター管理者の識別ユーザー名。
 a| 
string
 a| 
なし
 a| 
はい

|===


== 戻り値

このメソッドには戻り値はありません。



== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
  "method": "AddLdapClusterAdmin",
  "params": {"username":"cn=mike jones,ou=ptusers,dc=prodtest,dc=solidfire,dc=net",
    "access": ["administrator", "read"
    ]
  },
"id": 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
 "id": 1,
 "result": {}
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

xref:reference_element_api_app_b_access_control.adoc[アクセス制御]
