---
permalink: api/reference_element_api_syncjob.html 
sidebar: sidebar 
keywords: object,objects,syncjob 
summary: syncJob オブジェクトには、クラスター上で実行されているクローン、リモート レプリケーション、またはスライス同期ジョブに関する情報が含まれています。 
---
= 同期ジョブ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syncJob オブジェクトには、クラスター上で実行されているクローン、リモート レプリケーション、またはスライス同期ジョブに関する情報が含まれています。

同期情報を取得するには、 `ListSyncJobs` API メソッド。



== オブジェクトメンバー

このオブジェクトには次のメンバーが含まれます。

|===
| Name | 説明 | タイプ 


 a| 
ブロック/秒
 a| 
ソース クラスターからターゲット クラスターに 1 秒あたりに転送されるデータ ブロックの数。タイプ メンバーがリモートに設定されている場合にのみ存在します。
 a| 
integer



 a| 
ブランチタイプ
 a| 
リモート レプリケーション同期ジョブに対してのみ返されます。有効な値は次のとおりです。

* Snapshot
* 音量

 a| 
string



 a| 
バイト/秒
 a| 
クローンが 1 秒あたりに処理しているバイト数。タイプ メンバーが clone または slice に設定されている場合にのみ存在します。
 a| 
float



 a| 
クローンID
 a| 
進行中のクローン操作の識別子。タイプ メンバーが clone に設定されている場合にのみ存在します。
 a| 
integer



 a| 
現在のバイト数
 a| 
クローンによってソース ボリューム内で処理されたバイト数。タイプ メンバーが clone または slice に設定されている場合にのみ存在します。
 a| 
integer



 a| 
dstサービスID
 a| 
ボリュームのプライマリレプリカをホストするサービス識別子。タイプ メンバーがリモートに設定されている場合にのみ存在します。
 a| 
integer



 a| 
dstボリュームID
 a| 
宛先ボリューム ID。タイプ メンバーが clone または remote に設定されている場合にのみ存在します。
 a| 
integer



 a| 
経過時間
 a| 
同期ジョブが開始されてから経過した時間（秒）。
 a| 
同期操作の種類に応じて浮動小数点または整数



 a| 
グループクローンID
 a| 
進行中のグループ複製操作の ID。
 a| 
integer



 a| 
nodeID
 a| 
クローンが実行されるノードを指定します。タイプ メンバーが clone に設定されている場合にのみ存在します。
 a| 
integer



 a| 
完了率
 a| 
同期ジョブの完了率。
 a| 
同期操作の種類に応じて浮動小数点または整数



 a| 
残り時間
 a| 
操作を完了するまでの推定時間（秒単位）。
 a| 
float



 a| 
スライスID
 a| 
同期されているスライス ドライブの ID。
 a| 
integer



 a| 
ステージ
 a| 
タイプ メンバーがリモートまたはクローンとして設定されている場合にのみ存在します。有効な値は次のとおりです。

* メタデータ: レプリケーションは、リモート クラスターに転送する必要があるデータを決定するプロセス中です。レプリケーション プロセスのこの段階ではステータスは報告されません。
* データ: レプリケーションは、大量のデータをリモート クラスターに転送中です。
* 全体: スライス同期ジョブのスライスの下位互換性を示します。

 a| 
string



 a| 
スナップショットID
 a| 
クローンの作成元となったスナップショットの ID。タイプ メンバーが clone に設定されている場合にのみ存在します。
 a| 
integer



 a| 
ソースサービスID
 a| 
ソース サービス ID。
 a| 
integer



 a| 
ソースボリュームID
 a| 
ソースボリューム ID。
 a| 
integer



 a| 
合計バイト数
 a| 
クローンの合計バイト数。タイプ メンバーが clone または slice に設定されている場合にのみ存在します。
 a| 
integer



 a| 
type
 a| 
同期操作の種類。有効な値は次のとおりです。

* クローン
* スライス
* ブロック
* リモート

 a| 
string

|===


== 詳細情報の参照

xref:reference_element_api_listsyncjobs.adoc[リスト同期ジョブ]
