---
permalink: api/reference_element_api_getbootstrapconfig.html 
sidebar: sidebar 
keywords: cluster,getting,bootstrap,information,node,GetBootstrapConfig 
summary: GetBootstrapConfig メソッドを使用して、ブートストラップ構成ファイルからクラスターとノードの情報を取得できます。この API メソッドは、ノードがクラスターに結合される前に、個々のノードで使用します。このメソッドが返す情報は、クラスターを作成するときにクラスター構成インターフェイスで使用されます。 
---
= ブートストラップ設定の取得
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用することができます `GetBootstrapConfig`ブートストラップ構成ファイルからクラスターとノードの情報を取得する方法。この API メソッドは、ノードがクラスターに結合される前に、個々のノードで使用します。このメソッドが返す情報は、クラスターを作成するときにクラスター構成インターフェイスで使用されます。



== パラメータ

このメソッドには入力パラメータはありません。



== 戻り値

このメソッドには次の戻り値があります。

|===
| Name | 説明 | タイプ 


 a| 
クラスター名
 a| 
クラスタの名前。
 a| 
string



 a| 
mvip
 a| 
クラスター MVIP アドレス。ノードがクラスターの一部でない場合は空になります。
 a| 
string



 a| 
nodeName
 a| 
ノードの名前。
 a| 
string



 a| 
ノード
 a| 
クラスターへの参加をアクティブに待機している各ノードに関する情報のリスト。有効な値は次のとおりです。

* chassisType: (文字列) ノードのハードウェア プラットフォーム。
* cip: (文字列) ノードのクラスター IP アドレス。
* compatible: (boolean) ノードが API 呼び出しが実行されたノードと互換性があるかどうかを示します。
* hostname: (文字列) ノードのホスト名。
* mip: (文字列) ノードの IPv4 管理 IP アドレス。
* mipV6: (文字列) ノードの IPv6 管理 IP アドレス。
* nodeType: (文字列) ノードのモデル名。
* version: (文字列) ノードに現在インストールされているソフトウェアのバージョン。

 a| 
JSONオブジェクト配列



 a| 
svip
 a| 
クラスター SVIP アドレス。ノードがクラスターの一部でない場合は null になります。
 a| 
string



 a| 
version
 a| 
この API メソッドによって呼び出されたノードに現在インストールされている Element ソフトウェアのバージョン。
 a| 
string

|===


== リクエスト例

このメソッドのリクエストは次の例のようになります。

[listing]
----
{
   "method": "GetBootstrapConfig",
   "params": {},
   "id" : 1
}
----


== 応答例

このメソッドは、次の例のような応答を返します。

[listing]
----
{
	"id":1,
	"result":{
		"clusterName":"testname",
		"nodeName":"testnode",
		"svip": "10.117.1.5",
		"mvip": "10.117.1.6",
		"nodes":[
			{
				"chassisType":"R630",
				"cip":"10.117.115.16",
				"compatible":true,
				"hostname":"NLABP1132",
				"mip":"10.117.114.16",
				"mipV6":"fd20:8b1e:b256:45a::16",
				"nodeType":"SF2405",
				"role":"Storage",
				"version":"11.0"
			},
			{
				"chassisType":"R630",
				"cip":"10.117.115.17",
				"compatible":true,
				"hostname":"NLABP1133",
				"mip":"10.117.114.17",
				"mipV6":"fd20:8b1e:b256:45a::17",
				"nodeType":"SF2405",
				"role":"Storage",
				"version":"11.0"
			},
			{
				"chassisType":"R630",
				"cip":"10.117.115.18",
				"compatible":true,
				"hostname":"NLABP1134",
				"mip":"10.117.114.18",
				"mipV6":"fd20:8b1e:b256:45a::18",
				"nodeType":"SF2405",
				"role":"Storage",
				"version":"11.0"
			}
		],
		"version":"11.0"
	}
}
----


== バージョン以降の新機能

9.6



== 詳細情報の参照

xref:reference_element_api_createcluster.adoc[CreateCluster]
